/* Everyday letters for the Briefe tab, in the style of the B1 writing task.
   Each: title, task with its points, the letter as parts [kind, German,
   English] – kind m = sender/date line, b = subject, a = greeting,
   p = paragraph, g = closing – and key phrases [German, English].
   [Klammern] are placeholders to fill in. tools/check-alltag.mjs checks it. */
window.BR = [
{id:"schule", de:"Schule: Befreiung wegen Arzttermin", en:"School: excusing your daughter for a doctor's appointment", formal:true,
 task:"Ihre Tochter hat am Donnerstag einen wichtigen Termin beim Facharzt. Schreiben Sie an die Klassenlehrerin.",
 taskEn:"Your daughter has an important specialist appointment on Thursday. Write to her class teacher.",
 points:["Grund des Schreibens","Wann und wie lange fehlt Ihre Tochter?","Hausaufgaben / Unterrichtsstoff","Dank und Kontakt"],
 parts:[
  ["m","[Ihr Name] · [Straße, Hausnummer] · [PLZ Ort] — [Ort], den [Datum]","[Your name] · [street, number] · [postcode, town] — [town], [date]"],
  ["b","Befreiung vom Unterricht am Donnerstag, [Datum] – [Name der Tochter], Klasse 4b","Excusal from lessons on Thursday, [date] – [daughter's name], class 4b"],
  ["a","Sehr geehrte Frau Hoffmann,","Dear Ms Hoffmann,"],
  ["p","meine Tochter [Name der Tochter] hat am Donnerstag, den [Datum], um 10:00 Uhr einen Termin bei einer Fachärztin für Augenheilkunde. Den Termin haben wir schon vor drei Monaten bekommen, und leider war kein anderer Termin am Nachmittag möglich.","My daughter [daughter's name] has an appointment with an eye specialist on Thursday, [date], at 10 am. We got the appointment three months ago, and unfortunately no other afternoon appointment was possible."],
  ["p","Deshalb bitte ich Sie, meine Tochter an diesem Tag von der ersten bis zur vierten Stunde vom Unterricht zu befreien. Nach dem Arzttermin bringe ich sie direkt in die Schule, sodass sie ab der fünften Stunde wieder am Unterricht teilnehmen kann.","I therefore ask you to excuse my daughter from lessons from the first to the fourth period on that day. After the appointment I will bring her straight to school so that she can take part in lessons again from the fifth period."],
  ["p","Könnten Sie mir bitte mitteilen, welche Aufgaben sie nachholen soll? Sie kann die Hausaufgaben auch gern von einer Mitschülerin bekommen.","Could you please let me know which work she should catch up on? She can also get the homework from a classmate."],
  ["p","Vielen Dank für Ihr Verständnis. Bei Fragen erreichen Sie mich unter [Telefonnummer].","Thank you for your understanding. If you have any questions, you can reach me on [phone number]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Deshalb bitte ich Sie, meine Tochter … vom Unterricht zu befreien.","I therefore ask you to excuse my daughter from lessons."],["Könnten Sie mir bitte mitteilen, …?","Could you please let me know …?"],["Vielen Dank für Ihr Verständnis.","Thank you for your understanding."],["Bei Fragen erreichen Sie mich unter …","If you have questions, you can reach me on …"]]},

{id:"kindergeld", de:"Familienkasse: Kindergeld nicht erhalten", en:"Family benefits office: child benefit not received", formal:true,
 task:"Seit zwei Monaten bekommen Sie kein Kindergeld mehr, obwohl sich nichts geändert hat. Schreiben Sie an die Familienkasse.",
 taskEn:"You haven't received child benefit for two months, although nothing has changed. Write to the family benefits office.",
 points:["Kindergeldnummer und Kind nennen","Problem: seit wann keine Zahlung","Situation hat sich nicht geändert","Bitte: prüfen und wieder auszahlen"],
 parts:[
  ["m","[Ihr Name] · [Adresse] — [Ort], den [Datum]","[Your name] · [address] — [town], [date]"],
  ["b","Kindergeld für [Name des Kindes], geb. [Geburtsdatum] – Kindergeldnummer [Nummer] – keine Zahlung seit [Monat]","Child benefit for [child's name], born [date of birth] – child benefit number [number] – no payment since [month]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","ich beziehe seit [Jahr] Kindergeld für meine Tochter [Name des Kindes]. Seit [Monat] ist das Kindergeld leider nicht mehr auf meinem Konto eingegangen. Ich habe keinen Bescheid und keinen Brief von Ihnen bekommen.","I have been receiving child benefit for my daughter [child's name] since [year]. Unfortunately, since [month] the child benefit has no longer arrived in my account. I have not received any notice or letter from you."],
  ["p","An unserer Situation hat sich nichts geändert: Meine Tochter lebt weiterhin in meinem Haushalt, und auch meine Adresse und meine Bankverbindung sind gleich geblieben. Meine IBAN lautet [IBAN].","Nothing has changed in our situation: my daughter still lives in my household, and my address and bank details have also stayed the same. My IBAN is [IBAN]."],
  ["p","Ich bitte Sie daher, meinen Fall zu prüfen und die Zahlung wieder zu aktivieren. Bitte zahlen Sie mir auch die fehlenden Beträge für [Monat] und [Monat] nach.","I therefore ask you to check my case and to reactivate the payment. Please also pay me the missing amounts for [month] and [month]."],
  ["p","Falls Sie weitere Unterlagen von mir brauchen, teilen Sie mir das bitte mit. Eine Kopie der Geburtsurkunde und meiner Meldebescheinigung lege ich diesem Brief bei.","If you need any further documents from me, please let me know. I enclose a copy of the birth certificate and my registration certificate with this letter."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlagen: Geburtsurkunde (Kopie), Meldebescheinigung (Kopie)","Kind regards\n[your name]\nEnclosures: birth certificate (copy), registration certificate (copy)"]],
 tips:[["Seit [Monat] ist das Kindergeld nicht mehr eingegangen.","Since [month] the child benefit hasn't arrived."],["An unserer Situation hat sich nichts geändert.","Nothing has changed in our situation."],["Ich bitte Sie, meinen Fall zu prüfen.","I ask you to check my case."],["Eine Kopie … lege ich diesem Brief bei.","I enclose a copy of … with this letter."]]},

{id:"heizung", de:"Vermieter: Heizung kaputt", en:"Landlord: heating broken", formal:true,
 task:"Die Heizung in Ihrer Wohnung funktioniert seit einer Woche nicht. Sie haben schon angerufen, aber nichts ist passiert. Schreiben Sie an Ihren Vermieter.",
 taskEn:"The heating in your flat hasn't worked for a week. You've already phoned, but nothing has happened. Write to your landlord.",
 points:["Problem beschreiben","Was haben Sie schon gemacht?","Folgen für Ihre Familie","Frist und Bitte"],
 parts:[
  ["m","[Ihr Name] · [Adresse, Wohnung 2. OG links] — [Ort], den [Datum]","[Your name] · [address, flat 2nd floor left] — [town], [date]"],
  ["b","Defekte Heizung in meiner Wohnung – Bitte um Reparatur","Broken heating in my flat – request for repair"],
  ["a","Sehr geehrter Herr Keller,","Dear Mr Keller,"],
  ["p","seit dem [Datum] funktioniert die Heizung in meiner Wohnung nicht mehr. Alle Heizkörper bleiben kalt, und das warme Wasser ist nur lauwarm.","Since [date] the heating in my flat has not been working. All the radiators stay cold and the hot water is only lukewarm."],
  ["p","Ich habe Sie bereits am [Datum] telefonisch informiert. Sie haben mir gesagt, dass ein Techniker kommt, aber bis heute ist niemand gekommen.","I already informed you by phone on [date]. You told me that a technician would come, but so far nobody has come."],
  ["p","Draußen ist es nachts unter null Grad. In der Wohnung sind es nur noch 15 Grad, und meine kleine Tochter ist deshalb schon erkältet.","Outside it's below zero at night. It's only 15 degrees in the flat, and my little daughter has already caught a cold because of it."],
  ["p","Ich bitte Sie dringend, die Heizung bis spätestens [Datum] reparieren zu lassen. Sollte das nicht möglich sein, behalte ich mir vor, die Miete zu mindern. Ich bin werktags ab 16 Uhr zu Hause, für einen Termin können Sie mich unter [Telefonnummer] erreichen.","I urgently ask you to have the heating repaired by [date] at the latest. Should this not be possible, I reserve the right to reduce the rent. I'm at home on weekdays from 4 pm; you can reach me on [phone number] to arrange an appointment."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Seit dem … funktioniert die Heizung nicht mehr.","The heating hasn't worked since …"],["Ich habe Sie bereits am … telefonisch informiert.","I already informed you by phone on …"],["Ich bitte Sie dringend, … bis spätestens … zu …","I urgently ask you to … by … at the latest."],["Ich behalte mir vor, die Miete zu mindern.","I reserve the right to reduce the rent."]]},

{id:"kuendigung", de:"Fitnessstudio: Vertrag kündigen", en:"Gym: cancelling a contract", formal:true,
 task:"Sie ziehen in eine andere Stadt und möchten Ihren Vertrag beim Fitnessstudio kündigen.",
 taskEn:"You're moving to another city and want to cancel your gym contract.",
 points:["Kündigung mit Mitgliedsnummer","Zu welchem Datum?","Grund: Umzug","Bitte um Bestätigung"],
 parts:[
  ["m","[Ihr Name] · [Adresse] — [Ort], den [Datum]","[Your name] · [address] — [town], [date]"],
  ["b","Kündigung meiner Mitgliedschaft – Mitgliedsnummer [Nummer]","Cancellation of my membership – membership number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","hiermit kündige ich meine Mitgliedschaft in Ihrem Fitnessstudio fristgerecht zum [Datum].","I hereby give notice of cancellation of my membership at your gym, in accordance with the notice period, effective [date]."],
  ["p","Der Grund für meine Kündigung ist ein Umzug: Ab dem [Datum] wohne ich in Hamburg, wo es keine Filiale Ihres Studios gibt. Eine Kopie meiner neuen Meldebescheinigung lege ich bei.","The reason for my cancellation is a move: from [date] I will live in Hamburg, where there is no branch of your gym. I enclose a copy of my new registration certificate."],
  ["p","Bitte buchen Sie nach dem Vertragsende keine Beiträge mehr von meinem Konto ab.","Please do not debit any more fees from my account after the contract ends."],
  ["p","Ich bitte Sie, mir die Kündigung und das Datum des Vertragsendes schriftlich zu bestätigen. Vielen Dank für die schöne Zeit in Ihrem Studio!","Please confirm the cancellation and the end date of the contract in writing. Thank you for the great time at your gym!"],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Hiermit kündige ich … fristgerecht zum …","I hereby give notice … effective …"],["Der Grund für meine Kündigung ist …","The reason for my cancellation is …"],["Bitte buchen Sie keine Beiträge mehr ab.","Please don't debit any more fees."],["Ich bitte Sie, mir die Kündigung schriftlich zu bestätigen.","Please confirm the cancellation in writing."]]},

{id:"urlaub", de:"Chef: Urlaubsantrag", en:"Boss: request for leave", formal:true,
 task:"Sie möchten im August drei Wochen Urlaub nehmen, um Ihre Familie in Ihrer Heimat zu besuchen. Schreiben Sie eine E-Mail an Ihre Chefin.",
 taskEn:"You want to take three weeks' leave in August to visit your family back home. Write an email to your boss.",
 points:["Zeitraum des Urlaubs","Grund","Vertretung / offene Aufgaben","Bitte um Genehmigung"],
 parts:[
  ["b","Betreff: Urlaubsantrag vom 4. bis 22. August","Subject: Leave request from 4 to 22 August"],
  ["a","Liebe Frau Brandt,","Dear Ms Brandt,"],
  ["p","ich möchte gern vom 4. bis zum 22. August Urlaub nehmen. Das sind 15 Arbeitstage, und ich habe noch 22 Urlaubstage für dieses Jahr.","I would like to take leave from 4 to 22 August. That is 15 working days, and I still have 22 days of leave for this year."],
  ["p","In dieser Zeit möchte ich meine Eltern in [Land] besuchen. Ich habe sie seit zwei Jahren nicht gesehen, und meine Mutter feiert im August ihren 70. Geburtstag.","During this time I would like to visit my parents in [country]. I haven't seen them for two years, and my mother is celebrating her 70th birthday in August."],
  ["p","Ich habe schon mit meinem Kollegen Herrn Özdemir gesprochen. Er kann mich in dieser Zeit vertreten. Das Projekt für die Firma Maier schließe ich vor meinem Urlaub ab.","I have already spoken to my colleague Mr Özdemir. He can cover for me during this time. I will complete the project for Maier before my leave."],
  ["p","Ich würde mich freuen, wenn Sie meinen Antrag genehmigen könnten, damit ich die Flüge bald buchen kann.","I would be pleased if you could approve my request so that I can book the flights soon."],
  ["g","Viele Grüße\n[Ihr Name]","Best regards\n[your name]"]],
 tips:[["Ich möchte gern vom … bis zum … Urlaub nehmen.","I'd like to take leave from … to …"],["Er kann mich in dieser Zeit vertreten.","He can cover for me during this time."],["… schließe ich vor meinem Urlaub ab.","I will finish … before my leave."],["Ich würde mich freuen, wenn Sie … genehmigen könnten.","I'd be pleased if you could approve …"]]},

{id:"krankmeldung", de:"Arbeitgeber: Krankmeldung", en:"Employer: calling in sick", formal:true,
 task:"Sie sind heute Morgen krank aufgewacht und können nicht arbeiten. Schreiben Sie eine kurze E-Mail an Ihren Teamleiter.",
 taskEn:"You woke up ill this morning and can't work. Write a short email to your team leader.",
 points:["Sie sind krank","Wie lange ungefähr?","Krankschreibung vom Arzt","Wichtige Termine / Übergabe"],
 parts:[
  ["b","Betreff: Krankmeldung – [Ihr Name]","Subject: Sick notification – [your name]"],
  ["a","Hallo Herr Schmidt,","Hello Mr Schmidt,"],
  ["p","leider muss ich mich heute krankmelden. Ich habe seit heute Nacht hohes Fieber und starke Kopfschmerzen.","Unfortunately I have to call in sick today. Since last night I've had a high fever and a bad headache."],
  ["p","Ich gehe heute Vormittag zum Arzt. Die Arbeitsunfähigkeitsbescheinigung bekommen Sie wie immer elektronisch von meiner Krankenkasse. Ich denke, dass ich bis mindestens Mittwoch ausfalle.","I'm going to the doctor this morning. As usual, you'll receive the certificate of incapacity for work electronically from my health insurer. I think I'll be off until at least Wednesday."],
  ["p","Heute um 14 Uhr habe ich ein Meeting mit einem Kunden. Könnte Frau Weber den Termin übernehmen? Alle Unterlagen liegen im Projektordner.","I have a meeting with a client today at 2 pm. Could Ms Weber take over the appointment? All the documents are in the project folder."],
  ["p","Ich melde mich, sobald ich mehr weiß.","I'll get in touch as soon as I know more."],
  ["g","Viele Grüße\n[Ihr Name]","Best regards\n[your name]"]],
 tips:[["Leider muss ich mich heute krankmelden.","Unfortunately I have to call in sick today."],["Ich falle bis mindestens … aus.","I'll be off until at least …"],["Könnte … den Termin übernehmen?","Could … take over the appointment?"],["Ich melde mich, sobald ich mehr weiß.","I'll be in touch as soon as I know more."]]},

{id:"internetbeschwerde", de:"Internetanbieter: Beschwerde und Gutschrift", en:"Internet provider: complaint and credit", formal:true,
 task:"Ihr Internet hat zwei Wochen nicht funktioniert. Sie haben mehrmals angerufen. Schreiben Sie eine Beschwerde an den Anbieter.",
 taskEn:"Your internet didn't work for two weeks. You phoned several times. Write a complaint to the provider.",
 points:["Problem und Zeitraum","Was ist passiert, als Sie angerufen haben?","Folgen für Sie","Forderung: Gutschrift"],
 parts:[
  ["m","[Ihr Name] · [Adresse] · Kundennummer [Nummer] — [Ort], den [Datum]","[Your name] · [address] · customer number [number] — [town], [date]"],
  ["b","Beschwerde über den Ausfall meines Internetanschlusses vom [Datum] bis [Datum]","Complaint about the failure of my internet connection from [date] to [date]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","vom [Datum] bis zum [Datum] hat mein Internetanschluss nicht funktioniert – insgesamt vierzehn Tage.","From [date] to [date] my internet connection did not work – fourteen days in total."],
  ["p","Ich habe in dieser Zeit dreimal bei Ihrer Hotline angerufen. Jedes Mal wurde mir versprochen, dass ein Techniker kommt, aber erst beim dritten Anruf wurde wirklich ein Termin vereinbart.","During this time I called your hotline three times. Each time I was promised that a technician would come, but only on the third call was an appointment actually arranged."],
  ["p","Da ich im Homeoffice arbeite, musste ich an mehreren Tagen ins Büro fahren und hatte dadurch zusätzliche Fahrtkosten. Das war für mich sehr ärgerlich.","As I work from home, I had to travel to the office on several days and had extra travel costs as a result. That was very annoying for me."],
  ["p","Ich erwarte, dass Sie mir die Grundgebühr für diesen Zeitraum gutschreiben. Bitte bestätigen Sie mir die Gutschrift bis zum [Datum] schriftlich.","I expect you to credit me the basic fee for this period. Please confirm the credit to me in writing by [date]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Ich möchte mich über … beschweren.","I'd like to complain about …"],["Jedes Mal wurde mir versprochen, dass …","Each time I was promised that …"],["Das war für mich sehr ärgerlich.","That was very annoying for me."],["Ich erwarte, dass Sie mir … gutschreiben.","I expect you to credit me …"]]},

{id:"aufenthalt", de:"Ausländerbehörde: Termin für Verlängerung", en:"Immigration office: appointment for extension", formal:true,
 task:"Ihr Aufenthaltstitel läuft in acht Wochen ab. Online gibt es keine freien Termine. Schreiben Sie an die Ausländerbehörde.",
 taskEn:"Your residence permit expires in eight weeks. There are no free appointments online. Write to the immigration office.",
 points:["Wer sind Sie? (Name, Geburtsdatum, Aktenzeichen)","Wann läuft der Titel ab?","Problem mit der Online-Terminvergabe","Bitte um Termin / Fiktionsbescheinigung"],
 parts:[
  ["m","[Ihr Name] · geb. am [Datum] · Staatsangehörigkeit [Land] · [Adresse] — [Ort], den [Datum]","[Your name] · born on [date] · nationality [country] · [address] — [town], [date]"],
  ["b","Antrag auf Verlängerung meines Aufenthaltstitels – Bitte um einen Termin","Application to extend my residence permit – request for an appointment"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","mein Aufenthaltstitel ist noch bis zum [Datum] gültig. Ich möchte ihn rechtzeitig verlängern lassen.","My residence permit is valid until [date]. I would like to have it extended in good time."],
  ["p","Leider habe ich in den letzten drei Wochen auf Ihrer Internetseite keinen freien Termin gefunden. Auch telefonisch konnte ich Sie nicht erreichen.","Unfortunately I haven't found a free appointment on your website in the last three weeks. I also couldn't reach you by phone."],
  ["p","Ich arbeite seit zwei Jahren unbefristet als Softwareentwickler bei der Firma [Firma] in Frankfurt. Eine Kopie meines Passes, meines Arbeitsvertrags und meiner letzten drei Gehaltsabrechnungen lege ich bei.","I have been working on a permanent contract as a software developer at [company] in Frankfurt for two years. I enclose a copy of my passport, my employment contract and my last three pay slips."],
  ["p","Ich bitte Sie, mir einen Termin zu geben. Falls das vor dem Ablauf meines Titels nicht möglich ist, bitte ich um eine Fiktionsbescheinigung, damit ich weiter arbeiten und reisen kann.","I ask you to give me an appointment. If that isn't possible before my permit expires, I request a fictional certificate so that I can continue to work and travel."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlagen: Pass, Arbeitsvertrag, Gehaltsabrechnungen (Kopien)","Kind regards\n[your name]\nEnclosures: passport, employment contract, pay slips (copies)"]],
 tips:[["Mein Aufenthaltstitel ist noch bis zum … gültig.","My residence permit is valid until …"],["Ich möchte ihn rechtzeitig verlängern lassen.","I'd like to have it extended in good time."],["Ich bitte Sie, mir einen Termin zu geben.","I ask you to give me an appointment."],["Anlagen: …","Enclosures: …"]]},

{id:"kita", de:"Kita: Anmeldung für einen Platz", en:"Nursery: registering for a place", formal:true,
 task:"Sie suchen ab August einen Kitaplatz für Ihren Sohn (2 Jahre). Schreiben Sie an eine Kita in Ihrer Nähe.",
 taskEn:"You're looking for a nursery place for your son (2 years old) from August. Write to a nursery near you.",
 points:["Ihr Kind vorstellen","Ab wann und wie viele Stunden?","Warum diese Kita?","Fragen: Kosten, Besichtigung"],
 parts:[
  ["b","Betreff: Anfrage Kitaplatz ab August für [Name des Kindes], geb. [Datum]","Subject: Enquiry about a nursery place from August for [child's name], born [date]"],
  ["a","Sehr geehrte Frau Neumann,","Dear Ms Neumann,"],
  ["p","wir suchen für unseren Sohn [Name des Kindes] ab dem 1. August einen Platz in einer Kita. Er ist zwei Jahre alt, sehr aktiv und spielt gern mit anderen Kindern.","We are looking for a nursery place for our son [child's name] from 1 August. He is two years old, very active and likes playing with other children."],
  ["p","Da wir beide Vollzeit arbeiten, brauchen wir einen Ganztagsplatz von 8 bis 16 Uhr.","As we both work full-time, we need a full-day place from 8 am to 4 pm."],
  ["p","Ihre Kita liegt nur fünf Minuten von unserer Wohnung entfernt, und wir haben von anderen Eltern viel Gutes über Ihr Konzept gehört, besonders über die Zeit im Garten.","Your nursery is only five minutes from our flat, and we have heard a lot of good things about your approach from other parents, especially about the time in the garden."],
  ["p","Könnten Sie mir bitte sagen, ob noch Plätze frei sind und wie hoch die Kosten für das Mittagessen sind? Wir würden die Kita auch gern einmal besichtigen.","Could you please tell me whether there are still places available and how much lunch costs? We would also like to visit the nursery."],
  ["p","Über eine Antwort freuen wir uns sehr.","We look forward to your reply."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Wir suchen für unseren Sohn ab … einen Kitaplatz.","We're looking for a nursery place for our son from …"],["Da wir beide Vollzeit arbeiten, …","As we both work full-time, …"],["Könnten Sie mir bitte sagen, ob …?","Could you please tell me whether …?"],["Über eine Antwort freuen wir uns sehr.","We look forward to your reply."]]},

{id:"krankenkasse", de:"Krankenkasse: neue Karte (verloren)", en:"Health insurer: new card (lost)", formal:true,
 task:"Sie haben Ihre Versichertenkarte verloren und haben nächste Woche einen Arzttermin. Schreiben Sie an Ihre Krankenkasse.",
 taskEn:"You've lost your health insurance card and have a doctor's appointment next week. Write to your health insurer.",
 points:["Versichertennummer","Was ist passiert?","Bitte um neue Karte","Was tun beim Arzttermin?"],
 parts:[
  ["b","Betreff: Verlust meiner Versichertenkarte – Versichertennummer [Nummer]","Subject: Loss of my health insurance card – insurance number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","leider habe ich am [Datum] meine Geldbörse mit meiner Versichertenkarte verloren. Den Verlust habe ich bereits bei der Polizei gemeldet.","Unfortunately on [date] I lost my wallet with my health insurance card. I have already reported the loss to the police."],
  ["p","Ich bitte Sie, die alte Karte zu sperren und mir so schnell wie möglich eine neue Karte zu schicken. Ein aktuelles Foto habe ich in Ihrer App hochgeladen.","I ask you to block the old card and send me a new card as quickly as possible. I have uploaded a current photo in your app."],
  ["p","Nächsten Dienstag habe ich einen Termin beim Hausarzt. Können Sie mir bis dahin eine Ersatzbescheinigung schicken, zum Beispiel per E-Mail?","I have an appointment with my GP next Tuesday. Could you send me a replacement certificate by then, for example by email?"],
  ["p","Vielen Dank im Voraus für Ihre Hilfe.","Thank you in advance for your help."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Leider habe ich … verloren.","Unfortunately I've lost …"],["Ich bitte Sie, die alte Karte zu sperren.","Please block the old card."],["so schnell wie möglich","as quickly as possible"],["Vielen Dank im Voraus für Ihre Hilfe.","Thank you in advance for your help."]]},

{id:"adresse", de:"Bank / Versicherung: neue Adresse", en:"Bank / insurance: change of address", formal:true,
 task:"Sie sind umgezogen. Teilen Sie Ihrer Versicherung Ihre neue Adresse und Ihre neue Bankverbindung mit.",
 taskEn:"You've moved. Tell your insurance company your new address and your new bank details.",
 points:["Vertrags- / Versicherungsnummer","Neue Adresse ab wann","Neue Bankverbindung","Bitte um Bestätigung"],
 parts:[
  ["b","Betreff: Änderung meiner Adresse und Bankverbindung – Vertragsnummer [Nummer]","Subject: Change of my address and bank details – contract number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","ich bin umgezogen und möchte Ihnen meine neue Adresse mitteilen. Ab dem [Datum] wohne ich in: [Straße, Hausnummer, PLZ Ort].","I have moved and would like to inform you of my new address. From [date] I live at: [street, number, postcode, town]."],
  ["p","Außerdem habe ich ein neues Konto. Bitte buchen Sie die Beiträge ab dem nächsten Monat von folgendem Konto ab: IBAN [IBAN], [Name der Bank]. Das neue SEPA-Lastschriftmandat habe ich unterschrieben und lege es bei.","I also have a new account. From next month please debit the contributions from the following account: IBAN [IBAN], [bank name]. I have signed the new SEPA direct debit mandate and enclose it."],
  ["p","Bitte bestätigen Sie mir die Änderungen kurz schriftlich oder per E-Mail.","Please briefly confirm the changes to me in writing or by email."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlage: SEPA-Lastschriftmandat","Kind regards\n[your name]\nEnclosure: SEPA direct debit mandate"]],
 tips:[["Ich möchte Ihnen meine neue Adresse mitteilen.","I'd like to inform you of my new address."],["Ab dem … wohne ich in …","From … I live at …"],["Bitte buchen Sie die Beiträge von folgendem Konto ab.","Please debit the contributions from the following account."],["Bitte bestätigen Sie mir die Änderungen.","Please confirm the changes."]]},

{id:"freundin", de:"Freundin: Absage und neuer Vorschlag", en:"Friend: declining and suggesting another date", formal:false,
 task:"Ihre Freundin Anna hat Sie zu ihrer Geburtstagsfeier am Samstag eingeladen. Sie können leider nicht kommen. Schreiben Sie ihr.",
 taskEn:"Your friend Anna has invited you to her birthday party on Saturday. Unfortunately you can't come. Write to her.",
 points:["Dank für die Einladung","Warum Sie nicht kommen können","Geschenk / Glückwunsch","Vorschlag für ein Treffen"],
 parts:[
  ["a","Liebe Anna,","Dear Anna,"],
  ["p","vielen Dank für deine Einladung zu deiner Geburtstagsfeier! Ich habe mich sehr darüber gefreut.","Thank you so much for inviting me to your birthday party! I was really pleased."],
  ["p","Leider kann ich am Samstag nicht kommen, weil meine Schwiegereltern uns an diesem Wochenende besuchen. Sie kommen aus [Land] und bleiben nur drei Tage. Das tut mir wirklich leid!","Unfortunately I can't come on Saturday because my parents-in-law are visiting us that weekend. They're coming from [country] and are only staying three days. I'm really sorry!"],
  ["p","Ich wünsche dir schon jetzt alles Gute zum Geburtstag und eine tolle Party. Mein Geschenk bekommst du, wenn wir uns sehen – ich verrate nur so viel: Es hat etwas mit Kochen zu tun.","I already wish you a very happy birthday and a great party. You'll get my present when we see each other – I'll only tell you this much: it has something to do with cooking."],
  ["p","Hast du vielleicht nächste Woche Zeit? Wir könnten am Mittwochabend zusammen essen gehen und ein bisschen nachfeiern. Was meinst du?","Do you perhaps have time next week? We could go out for dinner on Wednesday evening and celebrate a bit belatedly. What do you think?"],
  ["g","Liebe Grüße\n[Ihr Name]","Love\n[your name]"]],
 tips:[["Vielen Dank für deine Einladung!","Thanks for your invitation!"],["Leider kann ich nicht kommen, weil …","Unfortunately I can't come because …"],["Alles Gute zum Geburtstag!","Happy birthday!"],["Wir könnten … – Was meinst du?","We could … – What do you think?"]]},

{id:"anschreiben", de:"Bewerbung: kurzes Anschreiben", en:"Job application: short cover letter", formal:true,
 task:"Sie haben eine Anzeige gelesen: Ein Supermarkt sucht eine Aushilfe an der Kasse (20 Stunden pro Woche). Schreiben Sie eine kurze Bewerbung.",
 taskEn:"You've read an advert: a supermarket is looking for a part-time cashier (20 hours a week). Write a short application.",
 points:["Wo haben Sie die Anzeige gesehen?","Ihre Erfahrung","Warum passen Sie?","Wann können Sie anfangen?"],
 parts:[
  ["m","[Ihr Name] · [Adresse] · [Telefon] · [E-Mail] — [Ort], den [Datum]","[Your name] · [address] · [phone] · [email] — [town], [date]"],
  ["b","Bewerbung als Aushilfe an der Kasse (20 Std./Woche)","Application as a part-time cashier (20 hrs/week)"],
  ["a","Sehr geehrte Frau Krüger,","Dear Ms Krüger,"],
  ["p","mit großem Interesse habe ich Ihre Anzeige auf Ihrer Internetseite gelesen. Hiermit bewerbe ich mich um die Stelle als Aushilfe an der Kasse.","I read your advert on your website with great interest. I hereby apply for the position as a part-time cashier."],
  ["p","In meiner Heimat habe ich zwei Jahre in einem Lebensmittelgeschäft gearbeitet. Dort war ich an der Kasse und im Lager tätig und hatte täglich Kontakt mit Kunden.","In my home country I worked in a grocery shop for two years. There I worked at the checkout and in the stockroom and had contact with customers every day."],
  ["p","Ich bin zuverlässig, freundlich und arbeite gern im Team. Da meine Kinder vormittags in der Schule sind, kann ich besonders gut von 8 bis 13 Uhr arbeiten. Meine Deutschkenntnisse entsprechen dem Niveau B1.","I am reliable, friendly and enjoy working in a team. As my children are at school in the mornings, I can work particularly well from 8 am to 1 pm. My German is at B1 level."],
  ["p","Ich könnte ab dem 1. [Monat] anfangen. Über eine Einladung zu einem persönlichen Gespräch freue ich mich sehr.","I could start from 1 [month]. I would be very pleased to be invited to a personal interview."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlagen: Lebenslauf, Zeugnisse","Kind regards\n[your name]\nEnclosures: CV, references"]],
 tips:[["Mit großem Interesse habe ich Ihre Anzeige gelesen.","I read your advert with great interest."],["Hiermit bewerbe ich mich um die Stelle als …","I hereby apply for the position as …"],["Ich bin zuverlässig und arbeite gern im Team.","I'm reliable and enjoy working in a team."],["Über eine Einladung zu einem Gespräch freue ich mich sehr.","I'd be very pleased to be invited to an interview."]]},

{id:"laerm", de:"Nachbar: höfliche Beschwerde über Lärm", en:"Neighbour: polite noise complaint", formal:false,
 task:"Ihre Nachbarn hören oft spät abends laute Musik. Schreiben Sie ihnen einen freundlichen Brief und legen Sie ihn in den Briefkasten.",
 taskEn:"Your neighbours often play loud music late at night. Write them a friendly letter and put it in their letterbox.",
 points:["Wer sind Sie?","Was ist das Problem?","Warum ist es für Sie schwierig?","Vorschlag"],
 parts:[
  ["a","Liebe Familie Schneider,","Dear Schneider family,"],
  ["p","wir sind Ihre Nachbarn aus dem ersten Stock und wohnen direkt unter Ihnen. Wir hoffen, es geht Ihnen gut!","We're your neighbours from the first floor and live directly below you. We hope you're well!"],
  ["p","Leider müssen wir Ihnen etwas sagen, das nicht so angenehm ist: In den letzten Wochen war abends oft laute Musik zu hören, manchmal bis nach Mitternacht.","Unfortunately we have to tell you something that isn't so pleasant: in the last few weeks loud music has often been audible in the evenings, sometimes until after midnight."],
  ["p","Für uns ist das schwierig, weil mein Mann sehr früh aufstehen muss und unsere kleine Tochter oft davon aufwacht.","This is difficult for us because my husband has to get up very early and our little daughter often wakes up because of it."],
  ["p","Wir möchten Ihnen den Spaß natürlich nicht verderben. Wäre es möglich, dass Sie die Musik ab 22 Uhr etwas leiser machen? Am Wochenende ist es für uns auch mal später in Ordnung.","Of course we don't want to spoil your fun. Would it be possible for you to turn the music down a little from 10 pm? At the weekend a bit later is fine for us too."],
  ["p","Wenn Sie möchten, klingeln Sie gern bei uns, dann können wir auch persönlich darüber sprechen.","If you like, feel free to ring our bell and we can talk about it in person."],
  ["g","Viele freundliche Grüße\nIhre Nachbarn [Name]","Best wishes\nYour neighbours [name]"]],
 tips:[["Leider müssen wir Ihnen etwas sagen, …","Unfortunately we have to tell you something …"],["Für uns ist das schwierig, weil …","That's difficult for us because …"],["Wäre es möglich, dass …?","Would it be possible for …?"],["Wir können auch persönlich darüber sprechen.","We can also talk about it in person."]]},

{id:"schimmel", de:"Hausverwaltung: Schimmel in der Wohnung", en:"Property management: mould in the flat", formal:true,
 task:"Im Schlafzimmer Ihrer Wohnung ist an der Wand Schimmel. Schreiben Sie an die Hausverwaltung.",
 taskEn:"There's mould on the wall in the bedroom of your flat. Write to the property management.",
 points:["Problem beschreiben (wo, seit wann)","Was haben Sie getan?","Gesundheit / Folgen","Bitte um Besichtigung und Beseitigung"],
 parts:[
  ["m","[Ihr Name] · [Adresse, Wohnung] — [Ort], den [Datum]","[Your name] · [address, flat] — [town], [date]"],
  ["b","Schimmel im Schlafzimmer – Bitte um Überprüfung","Mould in the bedroom – request for inspection"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","seit etwa vier Wochen bildet sich im Schlafzimmer meiner Wohnung Schimmel an der Außenwand, vor allem in der Ecke hinter dem Schrank. Der Fleck ist inzwischen ungefähr 50 mal 30 Zentimeter groß.","For about four weeks mould has been forming on the outside wall of the bedroom in my flat, especially in the corner behind the wardrobe. The patch is now about 50 by 30 centimetres."],
  ["p","Wir lüften drei- bis viermal am Tag und heizen regelmäßig. Trotzdem wird der Schimmel immer größer. Fotos habe ich diesem Schreiben beigefügt.","We air the flat three to four times a day and heat regularly. Nevertheless the mould keeps getting bigger. I have attached photos to this letter."],
  ["p","Ich mache mir Sorgen um unsere Gesundheit, da mein Sohn Asthma hat und in diesem Zimmer schläft.","I'm worried about our health, as my son has asthma and sleeps in this room."],
  ["p","Ich bitte Sie, die Wohnung so bald wie möglich besichtigen zu lassen und die Ursache zu beseitigen. Bitte teilen Sie mir bis zum [Datum] einen Termin mit.","I ask you to have the flat inspected as soon as possible and to remove the cause. Please let me know an appointment by [date]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlage: Fotos","Kind regards\n[your name]\nEnclosure: photos"]],
 tips:[["Seit etwa vier Wochen bildet sich Schimmel …","Mould has been forming for about four weeks …"],["Fotos habe ich beigefügt.","I have attached photos."],["Ich mache mir Sorgen um …","I'm worried about …"],["Bitte teilen Sie mir einen Termin mit.","Please let me know an appointment."]]},

{id:"sprachschule", de:"Sprachschule: Anfrage für einen Kurs", en:"Language school: course enquiry", formal:true,
 task:"Sie möchten einen Vorbereitungskurs für die B1-Prüfung machen. Schreiben Sie an eine Sprachschule.",
 taskEn:"You want to take a preparation course for the B1 exam. Write to a language school.",
 points:["Warum schreiben Sie?","Ihr Niveau und Ihre Zeit","Fragen zu Kosten und Prüfung","Bitte um Informationen"],
 parts:[
  ["b","Betreff: Anfrage zum Vorbereitungskurs B1","Subject: Enquiry about the B1 preparation course"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","ich interessiere mich für einen Vorbereitungskurs für die Prüfung Deutsch-Test für Zuwanderer (B1) und möchte gern mehr über Ihr Angebot erfahren.","I'm interested in a preparation course for the German test for immigrants (B1) and would like to find out more about what you offer."],
  ["p","Ich habe den A2-Kurs vor drei Monaten abgeschlossen und lerne seitdem allein weiter. Da ich tagsüber arbeite, suche ich einen Abendkurs oder einen Kurs am Samstag.","I completed the A2 course three months ago and have been continuing to learn on my own since then. As I work during the day, I'm looking for an evening course or a Saturday course."],
  ["p","Könnten Sie mir bitte mitteilen, wann der nächste Kurs beginnt, wie viel er kostet und ob die Prüfungsgebühr schon im Preis enthalten ist? Außerdem möchte ich wissen, ob man vorher einen Einstufungstest machen muss.","Could you please let me know when the next course starts, how much it costs and whether the exam fee is already included in the price? I'd also like to know whether you have to take a placement test beforehand."],
  ["p","Ich freue mich auf Ihre Antwort.","I look forward to your reply."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Ich möchte gern mehr über Ihr Angebot erfahren.","I'd like to find out more about your offer."],["Da ich tagsüber arbeite, …","As I work during the day, …"],["Könnten Sie mir bitte mitteilen, …?","Could you please let me know …?"],["Außerdem möchte ich wissen, ob …","I'd also like to know whether …"]]},

{id:"reklamation", de:"Online-Shop: defekte Ware", en:"Online shop: faulty goods", formal:true,
 task:"Sie haben online einen Wasserkocher bestellt. Er funktioniert nicht. Schreiben Sie an den Kundenservice.",
 taskEn:"You ordered a kettle online. It doesn't work. Write to customer service.",
 points:["Bestellung (Nummer, Datum)","Was ist kaputt?","Was möchten Sie? (Ersatz / Geld zurück)","Frage zur Rücksendung"],
 parts:[
  ["b","Betreff: Reklamation – Bestellnummer [Nummer] vom [Datum]","Subject: Complaint – order number [number] of [date]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","am [Datum] habe ich in Ihrem Online-Shop einen Wasserkocher der Marke [Marke] bestellt. Das Gerät wurde am [Datum] geliefert.","On [date] I ordered a [brand] kettle from your online shop. The appliance was delivered on [date]."],
  ["p","Leider funktioniert der Wasserkocher nicht: Wenn ich ihn einschalte, leuchtet die Lampe, aber das Wasser wird nicht warm. Außerdem ist der Deckel beschädigt.","Unfortunately the kettle doesn't work: when I switch it on, the light comes on but the water doesn't get hot. The lid is also damaged."],
  ["p","Ich möchte das Gerät zurückschicken und bitte Sie, mir einen neuen Wasserkocher zu senden. Falls das nicht möglich ist, möchte ich mein Geld zurück.","I would like to send the appliance back and ask you to send me a new kettle. If that isn't possible, I would like my money back."],
  ["p","Bitte schicken Sie mir ein kostenloses Rücksendeetikett. Vielen Dank für Ihre schnelle Bearbeitung.","Please send me a free return label. Thank you for dealing with this quickly."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Am … habe ich … bestellt.","On … I ordered …"],["Leider funktioniert … nicht.","Unfortunately … doesn't work."],["Ich möchte das Gerät zurückschicken.","I'd like to send the appliance back."],["ein kostenloses Rücksendeetikett","a free return label"]]},

{id:"hotelbeschwerde", de:"Hotel: Beschwerde nach dem Urlaub", en:"Hotel: complaint after the holiday", formal:true,
 task:"Sie waren eine Woche in einem Hotel. Vieles war nicht wie im Prospekt. Schreiben Sie an das Hotel.",
 taskEn:"You spent a week in a hotel. A lot wasn't as in the brochure. Write to the hotel.",
 points:["Wann waren Sie dort?","Was war nicht in Ordnung?","Wie hat das Hotel reagiert?","Was erwarten Sie?"],
 parts:[
  ["b","Betreff: Beschwerde über meinen Aufenthalt vom [Datum] bis [Datum], Buchungsnummer [Nummer]","Subject: Complaint about my stay from [date] to [date], booking number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","vom [Datum] bis zum [Datum] habe ich mit meiner Familie in Ihrem Hotel Urlaub gemacht. Leider war ich mit meinem Aufenthalt sehr unzufrieden.","From [date] to [date] I spent a holiday with my family at your hotel. Unfortunately I was very dissatisfied with my stay."],
  ["p","Im Prospekt steht, dass alle Zimmer Meerblick haben. Unser Zimmer lag jedoch zum Parkplatz. Außerdem war der Pool drei Tage lang geschlossen, und das Frühstück war jeden Tag gleich.","The brochure says that all rooms have a sea view. However, our room faced the car park. The pool was also closed for three days, and breakfast was the same every day."],
  ["p","Ich habe mich schon am zweiten Tag an der Rezeption beschwert, aber man hat mir kein anderes Zimmer angeboten.","I already complained at reception on the second day, but I wasn't offered another room."],
  ["p","Ich erwarte daher, dass Sie mir einen Teil des Preises, mindestens 20 Prozent, zurückerstatten. Ich freue mich auf Ihre Antwort bis zum [Datum].","I therefore expect you to refund part of the price, at least 20 per cent. I look forward to your reply by [date]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Leider war ich mit … sehr unzufrieden.","Unfortunately I was very dissatisfied with …"],["Im Prospekt steht, dass … Jedoch …","The brochure says that … However …"],["Ich habe mich schon … beschwert.","I already complained …"],["Ich erwarte, dass Sie mir … zurückerstatten.","I expect you to refund me …"]]},

{id:"entschuldigung", de:"Schule: Kind war krank", en:"School: your child was ill", formal:true,
 task:"Ihr Sohn war zwei Tage krank und konnte nicht zur Schule gehen. Schreiben Sie eine Entschuldigung an den Klassenlehrer.",
 taskEn:"Your son was ill for two days and couldn't go to school. Write a note to excuse him to his class teacher.",
 points:["Wer fehlte und wann?","Grund","Arztbesuch / Attest","Bitte um Hausaufgaben"],
 parts:[
  ["m","[Ort], den [Datum]","[town], [date]"],
  ["b","Entschuldigung für [Name des Kindes], Klasse 6a","Excuse note for [child's name], class 6a"],
  ["a","Sehr geehrter Herr Braun,","Dear Mr Braun,"],
  ["p","mein Sohn [Name des Kindes] konnte am Montag, den [Datum], und am Dienstag, den [Datum], leider nicht am Unterricht teilnehmen, weil er eine Magen-Darm-Grippe hatte.","Unfortunately my son [child's name] couldn't attend lessons on Monday, [date], and Tuesday, [date], because he had gastroenteritis."],
  ["p","Wir waren am Montag beim Kinderarzt. Das Attest lege ich diesem Brief bei.","We went to the paediatrician on Monday. I enclose the doctor's note with this letter."],
  ["p","Heute geht es ihm wieder gut. Bitte sagen Sie ihm, welche Aufgaben er nachholen muss, besonders für die Mathearbeit am Freitag.","He's feeling well again today. Please tell him which work he needs to catch up on, especially for the maths test on Friday."],
  ["p","Vielen Dank!","Thank you!"],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["… konnte leider nicht am Unterricht teilnehmen, weil …","… unfortunately couldn't attend lessons because …"],["Das Attest lege ich bei.","I enclose the doctor's note."],["Heute geht es ihm wieder gut.","He's feeling better again today."],["welche Aufgaben er nachholen muss","which work he has to catch up on"]]},

{id:"finanzamt", de:"Finanzamt: Frist verlängern", en:"Tax office: extending a deadline", formal:true,
 task:"Sie müssen Ihre Steuererklärung bis zum 31. Juli abgeben, aber es fehlen noch Unterlagen. Schreiben Sie an das Finanzamt.",
 taskEn:"You have to submit your tax return by 31 July, but some documents are still missing. Write to the tax office.",
 points:["Steuernummer und Jahr","Warum brauchen Sie mehr Zeit?","Bis wann?","Bitte um Bestätigung"],
 parts:[
  ["m","[Ihr Name] · [Adresse] · Steuernummer [Nummer] — [Ort], den [Datum]","[Your name] · [address] · tax number [number] — [town], [date]"],
  ["b","Antrag auf Fristverlängerung für die Einkommensteuererklärung [Jahr]","Application to extend the deadline for the income tax return [year]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","hiermit beantrage ich eine Verlängerung der Frist für meine Einkommensteuererklärung [Jahr] bis zum 30. September.","I hereby apply for an extension of the deadline for my income tax return [year] until 30 September."],
  ["p","Der Grund ist, dass mir noch wichtige Unterlagen fehlen: Die Bescheinigung meines früheren Arbeitgebers habe ich trotz mehrmaliger Nachfrage noch nicht bekommen.","The reason is that important documents are still missing: despite asking several times, I haven't yet received the certificate from my former employer."],
  ["p","Sobald ich die Bescheinigung erhalte, werde ich die Steuererklärung sofort über ELSTER abgeben.","As soon as I receive the certificate, I will submit the tax return straight away via ELSTER."],
  ["p","Ich bitte Sie, mir die Fristverlängerung kurz schriftlich zu bestätigen.","Please briefly confirm the extension in writing."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Hiermit beantrage ich eine Verlängerung der Frist.","I hereby apply for an extension of the deadline."],["Der Grund ist, dass …","The reason is that …"],["trotz mehrmaliger Nachfrage","despite asking several times"],["Sobald ich … erhalte, werde ich …","As soon as I receive …, I will …"]]},

{id:"kaution", de:"Vermieter: Kaution zurück", en:"Landlord: deposit refund", formal:true,
 task:"Sie sind vor drei Monaten ausgezogen und haben Ihre Kaution noch nicht zurückbekommen. Schreiben Sie an Ihren ehemaligen Vermieter.",
 taskEn:"You moved out three months ago and haven't got your deposit back yet. Write to your former landlord.",
 points:["Wann sind Sie ausgezogen?","Zustand der Wohnung bei der Übergabe","Bitte um Rückzahlung (Konto)","Frist"],
 parts:[
  ["b","Betreff: Rückzahlung meiner Mietkaution – Wohnung [Adresse]","Subject: Refund of my rental deposit – flat [address]"],
  ["a","Sehr geehrter Herr Lorenz,","Dear Mr Lorenz,"],
  ["p","am [Datum] bin ich aus der Wohnung in der [Straße] ausgezogen. Bei der Übergabe haben wir die Wohnung gemeinsam besichtigt, und im Protokoll wurden keine Schäden festgestellt.","On [date] I moved out of the flat on [street]. At the handover we viewed the flat together, and no damage was recorded in the report."],
  ["p","Bis heute habe ich meine Kaution in Höhe von [Betrag] Euro leider noch nicht zurückbekommen.","Unfortunately I still haven't got back my deposit of [amount] euros."],
  ["p","Ich bitte Sie, die Kaution einschließlich Zinsen bis zum [Datum] auf folgendes Konto zu überweisen: IBAN [IBAN], [Bank]. Falls Sie noch auf die Nebenkostenabrechnung warten, zahlen Sie mir bitte zumindest einen Teil der Kaution schon jetzt zurück.","I ask you to transfer the deposit including interest to the following account by [date]: IBAN [IBAN], [bank]. If you are still waiting for the service charge statement, please at least refund part of the deposit now."],
  ["p","Vielen Dank im Voraus.","Thank you in advance."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\n[neue Adresse]","Kind regards\n[your name]\n[new address]"]],
 tips:[["Im Protokoll wurden keine Schäden festgestellt.","No damage was recorded in the report."],["die Kaution in Höhe von … Euro","the deposit of … euros"],["einschließlich Zinsen überweisen","to transfer including interest"],["zumindest einen Teil","at least part of it"]]},

{id:"einladung", de:"Kollegen: Einladung zur Abschiedsfeier", en:"Colleagues: invitation to a leaving party", formal:false,
 task:"Ihre Kollegin Frau Weber geht in Rente. Schreiben Sie eine E-Mail an alle Kollegen und laden Sie zur Feier ein.",
 taskEn:"Your colleague Ms Weber is retiring. Write an email to all colleagues and invite them to the party.",
 points:["Anlass","Wann und wo?","Essen / Beitrag","Geschenk und Anmeldung"],
 parts:[
  ["b","Betreff: Abschiedsfeier für Frau Weber – Donnerstag, 15 Uhr","Subject: Leaving party for Ms Weber – Thursday, 3 pm"],
  ["a","Liebe Kolleginnen und Kollegen,","Dear colleagues,"],
  ["p","wie viele von euch wissen, geht unsere liebe Kollegin Frau Weber Ende des Monats nach 30 Jahren in der Firma in Rente. Das möchten wir natürlich mit ihr feiern!","As many of you know, our dear colleague Ms Weber is retiring at the end of the month after 30 years with the company. Of course we want to celebrate that with her!"],
  ["p","Die Feier findet am Donnerstag, den [Datum], um 15 Uhr im Konferenzraum im zweiten Stock statt.","The party will take place on Thursday, [date], at 3 pm in the conference room on the second floor."],
  ["p","Wir machen ein Buffet – es wäre schön, wenn jeder eine Kleinigkeit mitbringt, zum Beispiel einen Salat oder Kuchen. Getränke organisieren wir.","We're having a buffet – it would be nice if everyone brought something small, for example a salad or a cake. We'll organise the drinks."],
  ["p","Als Geschenk wollen wir ihr einen Gutschein für eine Städtereise schenken. Tom sammelt bis Mittwoch das Geld, jeder gibt, so viel er möchte. Bitte sagt mir bis Dienstag Bescheid, ob ihr kommt.","As a present we want to give her a voucher for a city trip. Tom is collecting the money until Wednesday; everyone gives as much as they like. Please let me know by Tuesday whether you're coming."],
  ["g","Viele Grüße\n[Ihr Name]","Best wishes\n[your name]"]],
 tips:[["Die Feier findet am … um … statt.","The party takes place on … at …"],["Es wäre schön, wenn jeder … mitbringt.","It would be nice if everyone brought …"],["Bitte sagt mir bis … Bescheid.","Please let me know by …"],["jeder gibt, so viel er möchte","everyone gives as much as they like"]]},

{id:"terminabsage", de:"Arztpraxis: Termin absagen per E-Mail", en:"Doctor's practice: cancelling by email", formal:true,
 task:"Sie haben morgen einen Termin beim Hautarzt, können aber wegen einer wichtigen Besprechung nicht kommen. Schreiben Sie eine E-Mail an die Praxis.",
 taskEn:"You have an appointment with the dermatologist tomorrow but can't come because of an important meeting. Write an email to the practice.",
 points:["Termin (Datum, Uhrzeit)","Grund","Entschuldigung","Neuer Termin: Vorschläge"],
 parts:[
  ["b","Betreff: Absage meines Termins am [Datum] um 9:30 Uhr – [Ihr Name], geb. [Datum]","Subject: Cancellation of my appointment on [date] at 9:30 – [your name], born [date]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","leider muss ich meinen Termin am [Datum] um 9:30 Uhr absagen, da ich zu dieser Zeit an einer wichtigen Besprechung teilnehmen muss, die kurzfristig angesetzt wurde.","Unfortunately I have to cancel my appointment on [date] at 9:30, as I have to attend an important meeting at that time which was scheduled at short notice."],
  ["p","Es tut mir leid, dass ich so spät absage.","I'm sorry for cancelling so late."],
  ["p","Ich würde gern einen neuen Termin vereinbaren. Am besten passt es mir montags oder mittwochs ab 16 Uhr. Bitte rufen Sie mich unter [Telefonnummer] an oder antworten Sie auf diese E-Mail.","I would like to make a new appointment. Mondays or Wednesdays from 4 pm suit me best. Please call me on [phone number] or reply to this email."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Leider muss ich meinen Termin absagen, da …","Unfortunately I have to cancel my appointment, as …"],["kurzfristig","at short notice"],["Ich würde gern einen neuen Termin vereinbaren.","I'd like to make a new appointment."],["Am besten passt es mir …","… suits me best."]]},

{id:"besuch", de:"Freund: Tipps für den Besuch", en:"Friend: tips for a visit", formal:false,
 task:"Ihr Freund Carlos kommt im Mai zum ersten Mal nach Frankfurt und möchte ein Wochenende bei Ihnen bleiben. Schreiben Sie ihm.",
 taskEn:"Your friend Carlos is coming to Frankfurt for the first time in May and wants to stay with you for a weekend. Write to him.",
 points:["Freude über den Besuch","Wie kommt er zu Ihnen?","Programm für das Wochenende","Was soll er mitbringen?"],
 parts:[
  ["a","Lieber Carlos,","Dear Carlos,"],
  ["p","ich freue mich riesig, dass du im Mai nach Frankfurt kommst! Natürlich kannst du bei uns wohnen – das Gästezimmer ist schon bereit.","I'm really happy that you're coming to Frankfurt in May! Of course you can stay with us – the guest room is already ready."],
  ["p","Vom Flughafen nimmst du am besten die S-Bahn S8 bis Hauptbahnhof und dann die U4 bis Bornheim Mitte. Das dauert ungefähr 30 Minuten. Ich hole dich an der Haltestelle ab.","From the airport it's best to take the S8 to the main station and then the U4 to Bornheim Mitte. That takes about 30 minutes. I'll pick you up at the stop."],
  ["p","Am Samstag zeige ich dir die Altstadt und den Römer, und abends gehen wir in Sachsenhausen Apfelwein trinken. Am Sonntag könnten wir mit dem Fahrrad am Main entlangfahren, wenn das Wetter gut ist.","On Saturday I'll show you the old town and the Römer, and in the evening we'll go to Sachsenhausen for apple wine. On Sunday we could cycle along the Main if the weather is good."],
  ["p","Bring auf jeden Fall bequeme Schuhe und eine Regenjacke mit – im Mai weiß man nie! Schreib mir, wann dein Flug ankommt.","Definitely bring comfortable shoes and a rain jacket – in May you never know! Let me know when your flight arrives."],
  ["g","Bis bald und viele Grüße\n[Ihr Name]","See you soon, best wishes\n[your name]"]],
 tips:[["Ich freue mich riesig, dass …","I'm really happy that …"],["Du nimmst am besten …","It's best to take …"],["Ich hole dich ab.","I'll pick you up."],["Bring auf jeden Fall … mit.","Definitely bring …"]]}
];
