/* Everyday letters for the Briefe tab, in the style of the B1 writing task.
   Each: title, task with its points, the letter as parts [kind, German,
   English] – kind m = sender/date line, b = subject, a = greeting,
   p = paragraph, g = closing – and key phrases [German, English].
   [Klammern] are placeholders to fill in. tools/check-alltag.mjs checks it. */
window.BR = [
{id:"schule", de:"Schule: Befreiung wegen Arzttermin", en:"School: excusing your daughter for a doctor's appointment", formal:true,
 task:"Ihre Tochter hat am Donnerstag einen wichtigen Termin beim Facharzt. Schreiben Sie an die Klassenlehrerin.",
 taskEn:"Your daughter has an important specialist appointment on Thursday. Write to her class teacher.",
 points:["Grund des Schreibens","Wann und wie lange fehlt Ihre Tochter?","Hausaufgaben / Unterrichtsstoff","Dank und Kontakt"],
 parts:[
  ["m","[Ihr Name] · [Straße, Hausnummer] · [PLZ Ort] — [Ort], den [Datum]","[Your name] · [street, number] · [postcode, town] — [town], [date]"],
  ["b","Befreiung vom Unterricht am Donnerstag, [Datum] – [Name der Tochter], Klasse 4b","Excusal from lessons on Thursday, [date] – [daughter's name], class 4b"],
  ["a","Sehr geehrte Frau Hoffmann,","Dear Ms Hoffmann,"],
  ["p","meine Tochter [Name der Tochter] hat am Donnerstag, den [Datum], um 10:00 Uhr einen Termin bei einer Fachärztin für Augenheilkunde. Den Termin haben wir schon vor drei Monaten bekommen, und leider war kein anderer Termin am Nachmittag möglich.","My daughter [daughter's name] has an appointment with an eye specialist on Thursday, [date], at 10 am. We got the appointment three months ago, and unfortunately no other afternoon appointment was possible."],
  ["p","Deshalb bitte ich Sie, meine Tochter an diesem Tag von der ersten bis zur vierten Stunde vom Unterricht zu befreien. Nach dem Arzttermin bringe ich sie direkt in die Schule, sodass sie ab der fünften Stunde wieder am Unterricht teilnehmen kann.","I therefore ask you to excuse my daughter from lessons from the first to the fourth period on that day. After the appointment I will bring her straight to school so that she can take part in lessons again from the fifth period."],
  ["p","Könnten Sie mir bitte mitteilen, welche Aufgaben sie nachholen soll? Sie kann die Hausaufgaben auch gern von einer Mitschülerin bekommen.","Could you please let me know which work she should catch up on? She can also get the homework from a classmate."],
  ["p","Vielen Dank für Ihr Verständnis. Bei Fragen erreichen Sie mich unter [Telefonnummer].","Thank you for your understanding. If you have any questions, you can reach me on [phone number]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Deshalb bitte ich Sie, meine Tochter … vom Unterricht zu befreien.","I therefore ask you to excuse my daughter from lessons."],["Könnten Sie mir bitte mitteilen, …?","Could you please let me know …?"],["Vielen Dank für Ihr Verständnis.","Thank you for your understanding."],["Bei Fragen erreichen Sie mich unter …","If you have questions, you can reach me on …"]]},

{id:"kindergeld", de:"Familienkasse: Kindergeld nicht erhalten", en:"Family benefits office: child benefit not received", formal:true,
 task:"Seit zwei Monaten bekommen Sie kein Kindergeld mehr, obwohl sich nichts geändert hat. Schreiben Sie an die Familienkasse.",
 taskEn:"You haven't received child benefit for two months, although nothing has changed. Write to the family benefits office.",
 points:["Kindergeldnummer und Kind nennen","Problem: seit wann keine Zahlung","Situation hat sich nicht geändert","Bitte: prüfen und wieder auszahlen"],
 parts:[
  ["m","[Ihr Name] · [Adresse] — [Ort], den [Datum]","[Your name] · [address] — [town], [date]"],
  ["b","Kindergeld für [Name des Kindes], geb. [Geburtsdatum] – Kindergeldnummer [Nummer] – keine Zahlung seit [Monat]","Child benefit for [child's name], born [date of birth] – child benefit number [number] – no payment since [month]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","ich beziehe seit [Jahr] Kindergeld für meine Tochter [Name des Kindes]. Seit [Monat] ist das Kindergeld leider nicht mehr auf meinem Konto eingegangen. Ich habe keinen Bescheid und keinen Brief von Ihnen bekommen.","I have been receiving child benefit for my daughter [child's name] since [year]. Unfortunately, since [month] the child benefit has no longer arrived in my account. I have not received any notice or letter from you."],
  ["p","An unserer Situation hat sich nichts geändert: Meine Tochter lebt weiterhin in meinem Haushalt, und auch meine Adresse und meine Bankverbindung sind gleich geblieben. Meine IBAN lautet [IBAN].","Nothing has changed in our situation: my daughter still lives in my household, and my address and bank details have also stayed the same. My IBAN is [IBAN]."],
  ["p","Ich bitte Sie daher, meinen Fall zu prüfen und die Zahlung wieder zu aktivieren. Bitte zahlen Sie mir auch die fehlenden Beträge für [Monat] und [Monat] nach.","I therefore ask you to check my case and to reactivate the payment. Please also pay me the missing amounts for [month] and [month]."],
  ["p","Falls Sie weitere Unterlagen von mir brauchen, teilen Sie mir das bitte mit. Eine Kopie der Geburtsurkunde und meiner Meldebescheinigung lege ich diesem Brief bei.","If you need any further documents from me, please let me know. I enclose a copy of the birth certificate and my registration certificate with this letter."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlagen: Geburtsurkunde (Kopie), Meldebescheinigung (Kopie)","Kind regards\n[your name]\nEnclosures: birth certificate (copy), registration certificate (copy)"]],
 tips:[["Seit [Monat] ist das Kindergeld nicht mehr eingegangen.","Since [month] the child benefit hasn't arrived."],["An unserer Situation hat sich nichts geändert.","Nothing has changed in our situation."],["Ich bitte Sie, meinen Fall zu prüfen.","I ask you to check my case."],["Eine Kopie … lege ich diesem Brief bei.","I enclose a copy of … with this letter."]]},

{id:"heizung", de:"Vermieter: Heizung kaputt", en:"Landlord: heating broken", formal:true,
 task:"Die Heizung in Ihrer Wohnung funktioniert seit einer Woche nicht. Sie haben schon angerufen, aber nichts ist passiert. Schreiben Sie an Ihren Vermieter.",
 taskEn:"The heating in your flat hasn't worked for a week. You've already phoned, but nothing has happened. Write to your landlord.",
 points:["Problem beschreiben","Was haben Sie schon gemacht?","Folgen für Ihre Familie","Frist und Bitte"],
 parts:[
  ["m","[Ihr Name] · [Adresse, Wohnung 2. OG links] — [Ort], den [Datum]","[Your name] · [address, flat 2nd floor left] — [town], [date]"],
  ["b","Defekte Heizung in meiner Wohnung – Bitte um Reparatur","Broken heating in my flat – request for repair"],
  ["a","Sehr geehrter Herr Keller,","Dear Mr Keller,"],
  ["p","seit dem [Datum] funktioniert die Heizung in meiner Wohnung nicht mehr. Alle Heizkörper bleiben kalt, und das warme Wasser ist nur lauwarm.","Since [date] the heating in my flat has not been working. All the radiators stay cold and the hot water is only lukewarm."],
  ["p","Ich habe Sie bereits am [Datum] telefonisch informiert. Sie haben mir gesagt, dass ein Techniker kommt, aber bis heute ist niemand gekommen.","I already informed you by phone on [date]. You told me that a technician would come, but so far nobody has come."],
  ["p","Draußen ist es nachts unter null Grad. In der Wohnung sind es nur noch 15 Grad, und meine kleine Tochter ist deshalb schon erkältet.","Outside it's below zero at night. It's only 15 degrees in the flat, and my little daughter has already caught a cold because of it."],
  ["p","Ich bitte Sie dringend, die Heizung bis spätestens [Datum] reparieren zu lassen. Sollte das nicht möglich sein, behalte ich mir vor, die Miete zu mindern. Ich bin werktags ab 16 Uhr zu Hause, für einen Termin können Sie mich unter [Telefonnummer] erreichen.","I urgently ask you to have the heating repaired by [date] at the latest. Should this not be possible, I reserve the right to reduce the rent. I'm at home on weekdays from 4 pm; you can reach me on [phone number] to arrange an appointment."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Seit dem … funktioniert die Heizung nicht mehr.","The heating hasn't worked since …"],["Ich habe Sie bereits am … telefonisch informiert.","I already informed you by phone on …"],["Ich bitte Sie dringend, … bis spätestens … zu …","I urgently ask you to … by … at the latest."],["Ich behalte mir vor, die Miete zu mindern.","I reserve the right to reduce the rent."]]},

{id:"kuendigung", de:"Fitnessstudio: Vertrag kündigen", en:"Gym: cancelling a contract", formal:true,
 task:"Sie ziehen in eine andere Stadt und möchten Ihren Vertrag beim Fitnessstudio kündigen.",
 taskEn:"You're moving to another city and want to cancel your gym contract.",
 points:["Kündigung mit Mitgliedsnummer","Zu welchem Datum?","Grund: Umzug","Bitte um Bestätigung"],
 parts:[
  ["m","[Ihr Name] · [Adresse] — [Ort], den [Datum]","[Your name] · [address] — [town], [date]"],
  ["b","Kündigung meiner Mitgliedschaft – Mitgliedsnummer [Nummer]","Cancellation of my membership – membership number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","hiermit kündige ich meine Mitgliedschaft in Ihrem Fitnessstudio fristgerecht zum [Datum].","I hereby give notice of cancellation of my membership at your gym, in accordance with the notice period, effective [date]."],
  ["p","Der Grund für meine Kündigung ist ein Umzug: Ab dem [Datum] wohne ich in Hamburg, wo es keine Filiale Ihres Studios gibt. Eine Kopie meiner neuen Meldebescheinigung lege ich bei.","The reason for my cancellation is a move: from [date] I will live in Hamburg, where there is no branch of your gym. I enclose a copy of my new registration certificate."],
  ["p","Bitte buchen Sie nach dem Vertragsende keine Beiträge mehr von meinem Konto ab.","Please do not debit any more fees from my account after the contract ends."],
  ["p","Ich bitte Sie, mir die Kündigung und das Datum des Vertragsendes schriftlich zu bestätigen. Vielen Dank für die schöne Zeit in Ihrem Studio!","Please confirm the cancellation and the end date of the contract in writing. Thank you for the great time at your gym!"],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Hiermit kündige ich … fristgerecht zum …","I hereby give notice … effective …"],["Der Grund für meine Kündigung ist …","The reason for my cancellation is …"],["Bitte buchen Sie keine Beiträge mehr ab.","Please don't debit any more fees."],["Ich bitte Sie, mir die Kündigung schriftlich zu bestätigen.","Please confirm the cancellation in writing."]]},

{id:"urlaub", de:"Chef: Urlaubsantrag", en:"Boss: request for leave", formal:true,
 task:"Sie möchten im August drei Wochen Urlaub nehmen, um Ihre Familie in Ihrer Heimat zu besuchen. Schreiben Sie eine E-Mail an Ihre Chefin.",
 taskEn:"You want to take three weeks' leave in August to visit your family back home. Write an email to your boss.",
 points:["Zeitraum des Urlaubs","Grund","Vertretung / offene Aufgaben","Bitte um Genehmigung"],
 parts:[
  ["b","Betreff: Urlaubsantrag vom 4. bis 22. August","Subject: Leave request from 4 to 22 August"],
  ["a","Liebe Frau Brandt,","Dear Ms Brandt,"],
  ["p","ich möchte gern vom 4. bis zum 22. August Urlaub nehmen. Das sind 15 Arbeitstage, und ich habe noch 22 Urlaubstage für dieses Jahr.","I would like to take leave from 4 to 22 August. That is 15 working days, and I still have 22 days of leave for this year."],
  ["p","In dieser Zeit möchte ich meine Eltern in [Land] besuchen. Ich habe sie seit zwei Jahren nicht gesehen, und meine Mutter feiert im August ihren 70. Geburtstag.","During this time I would like to visit my parents in [country]. I haven't seen them for two years, and my mother is celebrating her 70th birthday in August."],
  ["p","Ich habe schon mit meinem Kollegen Herrn Özdemir gesprochen. Er kann mich in dieser Zeit vertreten. Das Projekt für die Firma Maier schließe ich vor meinem Urlaub ab.","I have already spoken to my colleague Mr Özdemir. He can cover for me during this time. I will complete the project for Maier before my leave."],
  ["p","Ich würde mich freuen, wenn Sie meinen Antrag genehmigen könnten, damit ich die Flüge bald buchen kann.","I would be pleased if you could approve my request so that I can book the flights soon."],
  ["g","Viele Grüße\n[Ihr Name]","Best regards\n[your name]"]],
 tips:[["Ich möchte gern vom … bis zum … Urlaub nehmen.","I'd like to take leave from … to …"],["Er kann mich in dieser Zeit vertreten.","He can cover for me during this time."],["… schließe ich vor meinem Urlaub ab.","I will finish … before my leave."],["Ich würde mich freuen, wenn Sie … genehmigen könnten.","I'd be pleased if you could approve …"]]},

{id:"krankmeldung", de:"Arbeitgeber: Krankmeldung", en:"Employer: calling in sick", formal:true,
 task:"Sie sind heute Morgen krank aufgewacht und können nicht arbeiten. Schreiben Sie eine kurze E-Mail an Ihren Teamleiter.",
 taskEn:"You woke up ill this morning and can't work. Write a short email to your team leader.",
 points:["Sie sind krank","Wie lange ungefähr?","Krankschreibung vom Arzt","Wichtige Termine / Übergabe"],
 parts:[
  ["b","Betreff: Krankmeldung – [Ihr Name]","Subject: Sick notification – [your name]"],
  ["a","Hallo Herr Schmidt,","Hello Mr Schmidt,"],
  ["p","leider muss ich mich heute krankmelden. Ich habe seit heute Nacht hohes Fieber und starke Kopfschmerzen.","Unfortunately I have to call in sick today. Since last night I've had a high fever and a bad headache."],
  ["p","Ich gehe heute Vormittag zum Arzt. Die Arbeitsunfähigkeitsbescheinigung bekommen Sie wie immer elektronisch von meiner Krankenkasse. Ich denke, dass ich bis mindestens Mittwoch ausfalle.","I'm going to the doctor this morning. As usual, you'll receive the certificate of incapacity for work electronically from my health insurer. I think I'll be off until at least Wednesday."],
  ["p","Heute um 14 Uhr habe ich ein Meeting mit einem Kunden. Könnte Frau Weber den Termin übernehmen? Alle Unterlagen liegen im Projektordner.","I have a meeting with a client today at 2 pm. Could Ms Weber take over the appointment? All the documents are in the project folder."],
  ["p","Ich melde mich, sobald ich mehr weiß.","I'll get in touch as soon as I know more."],
  ["g","Viele Grüße\n[Ihr Name]","Best regards\n[your name]"]],
 tips:[["Leider muss ich mich heute krankmelden.","Unfortunately I have to call in sick today."],["Ich falle bis mindestens … aus.","I'll be off until at least …"],["Könnte … den Termin übernehmen?","Could … take over the appointment?"],["Ich melde mich, sobald ich mehr weiß.","I'll be in touch as soon as I know more."]]},

{id:"internetbeschwerde", de:"Internetanbieter: Beschwerde und Gutschrift", en:"Internet provider: complaint and credit", formal:true,
 task:"Ihr Internet hat zwei Wochen nicht funktioniert. Sie haben mehrmals angerufen. Schreiben Sie eine Beschwerde an den Anbieter.",
 taskEn:"Your internet didn't work for two weeks. You phoned several times. Write a complaint to the provider.",
 points:["Problem und Zeitraum","Was ist passiert, als Sie angerufen haben?","Folgen für Sie","Forderung: Gutschrift"],
 parts:[
  ["m","[Ihr Name] · [Adresse] · Kundennummer [Nummer] — [Ort], den [Datum]","[Your name] · [address] · customer number [number] — [town], [date]"],
  ["b","Beschwerde über den Ausfall meines Internetanschlusses vom [Datum] bis [Datum]","Complaint about the failure of my internet connection from [date] to [date]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","vom [Datum] bis zum [Datum] hat mein Internetanschluss nicht funktioniert – insgesamt vierzehn Tage.","From [date] to [date] my internet connection did not work – fourteen days in total."],
  ["p","Ich habe in dieser Zeit dreimal bei Ihrer Hotline angerufen. Jedes Mal wurde mir versprochen, dass ein Techniker kommt, aber erst beim dritten Anruf wurde wirklich ein Termin vereinbart.","During this time I called your hotline three times. Each time I was promised that a technician would come, but only on the third call was an appointment actually arranged."],
  ["p","Da ich im Homeoffice arbeite, musste ich an mehreren Tagen ins Büro fahren und hatte dadurch zusätzliche Fahrtkosten. Das war für mich sehr ärgerlich.","As I work from home, I had to travel to the office on several days and had extra travel costs as a result. That was very annoying for me."],
  ["p","Ich erwarte, dass Sie mir die Grundgebühr für diesen Zeitraum gutschreiben. Bitte bestätigen Sie mir die Gutschrift bis zum [Datum] schriftlich.","I expect you to credit me the basic fee for this period. Please confirm the credit to me in writing by [date]."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Ich möchte mich über … beschweren.","I'd like to complain about …"],["Jedes Mal wurde mir versprochen, dass …","Each time I was promised that …"],["Das war für mich sehr ärgerlich.","That was very annoying for me."],["Ich erwarte, dass Sie mir … gutschreiben.","I expect you to credit me …"]]},

{id:"aufenthalt", de:"Ausländerbehörde: Termin für Verlängerung", en:"Immigration office: appointment for extension", formal:true,
 task:"Ihr Aufenthaltstitel läuft in acht Wochen ab. Online gibt es keine freien Termine. Schreiben Sie an die Ausländerbehörde.",
 taskEn:"Your residence permit expires in eight weeks. There are no free appointments online. Write to the immigration office.",
 points:["Wer sind Sie? (Name, Geburtsdatum, Aktenzeichen)","Wann läuft der Titel ab?","Problem mit der Online-Terminvergabe","Bitte um Termin / Fiktionsbescheinigung"],
 parts:[
  ["m","[Ihr Name] · geb. am [Datum] · Staatsangehörigkeit [Land] · [Adresse] — [Ort], den [Datum]","[Your name] · born on [date] · nationality [country] · [address] — [town], [date]"],
  ["b","Antrag auf Verlängerung meines Aufenthaltstitels – Bitte um einen Termin","Application to extend my residence permit – request for an appointment"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","mein Aufenthaltstitel ist noch bis zum [Datum] gültig. Ich möchte ihn rechtzeitig verlängern lassen.","My residence permit is valid until [date]. I would like to have it extended in good time."],
  ["p","Leider habe ich in den letzten drei Wochen auf Ihrer Internetseite keinen freien Termin gefunden. Auch telefonisch konnte ich Sie nicht erreichen.","Unfortunately I haven't found a free appointment on your website in the last three weeks. I also couldn't reach you by phone."],
  ["p","Ich arbeite seit zwei Jahren unbefristet als Softwareentwickler bei der Firma [Firma] in Frankfurt. Eine Kopie meines Passes, meines Arbeitsvertrags und meiner letzten drei Gehaltsabrechnungen lege ich bei.","I have been working on a permanent contract as a software developer at [company] in Frankfurt for two years. I enclose a copy of my passport, my employment contract and my last three pay slips."],
  ["p","Ich bitte Sie, mir einen Termin zu geben. Falls das vor dem Ablauf meines Titels nicht möglich ist, bitte ich um eine Fiktionsbescheinigung, damit ich weiter arbeiten und reisen kann.","I ask you to give me an appointment. If that isn't possible before my permit expires, I request a fictional certificate so that I can continue to work and travel."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlagen: Pass, Arbeitsvertrag, Gehaltsabrechnungen (Kopien)","Kind regards\n[your name]\nEnclosures: passport, employment contract, pay slips (copies)"]],
 tips:[["Mein Aufenthaltstitel ist noch bis zum … gültig.","My residence permit is valid until …"],["Ich möchte ihn rechtzeitig verlängern lassen.","I'd like to have it extended in good time."],["Ich bitte Sie, mir einen Termin zu geben.","I ask you to give me an appointment."],["Anlagen: …","Enclosures: …"]]},

{id:"kita", de:"Kita: Anmeldung für einen Platz", en:"Nursery: registering for a place", formal:true,
 task:"Sie suchen ab August einen Kitaplatz für Ihren Sohn (2 Jahre). Schreiben Sie an eine Kita in Ihrer Nähe.",
 taskEn:"You're looking for a nursery place for your son (2 years old) from August. Write to a nursery near you.",
 points:["Ihr Kind vorstellen","Ab wann und wie viele Stunden?","Warum diese Kita?","Fragen: Kosten, Besichtigung"],
 parts:[
  ["b","Betreff: Anfrage Kitaplatz ab August für [Name des Kindes], geb. [Datum]","Subject: Enquiry about a nursery place from August for [child's name], born [date]"],
  ["a","Sehr geehrte Frau Neumann,","Dear Ms Neumann,"],
  ["p","wir suchen für unseren Sohn [Name des Kindes] ab dem 1. August einen Platz in einer Kita. Er ist zwei Jahre alt, sehr aktiv und spielt gern mit anderen Kindern.","We are looking for a nursery place for our son [child's name] from 1 August. He is two years old, very active and likes playing with other children."],
  ["p","Da wir beide Vollzeit arbeiten, brauchen wir einen Ganztagsplatz von 8 bis 16 Uhr.","As we both work full-time, we need a full-day place from 8 am to 4 pm."],
  ["p","Ihre Kita liegt nur fünf Minuten von unserer Wohnung entfernt, und wir haben von anderen Eltern viel Gutes über Ihr Konzept gehört, besonders über die Zeit im Garten.","Your nursery is only five minutes from our flat, and we have heard a lot of good things about your approach from other parents, especially about the time in the garden."],
  ["p","Könnten Sie mir bitte sagen, ob noch Plätze frei sind und wie hoch die Kosten für das Mittagessen sind? Wir würden die Kita auch gern einmal besichtigen.","Could you please tell me whether there are still places available and how much lunch costs? We would also like to visit the nursery."],
  ["p","Über eine Antwort freuen wir uns sehr.","We look forward to your reply."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Wir suchen für unseren Sohn ab … einen Kitaplatz.","We're looking for a nursery place for our son from …"],["Da wir beide Vollzeit arbeiten, …","As we both work full-time, …"],["Könnten Sie mir bitte sagen, ob …?","Could you please tell me whether …?"],["Über eine Antwort freuen wir uns sehr.","We look forward to your reply."]]},

{id:"krankenkasse", de:"Krankenkasse: neue Karte (verloren)", en:"Health insurer: new card (lost)", formal:true,
 task:"Sie haben Ihre Versichertenkarte verloren und haben nächste Woche einen Arzttermin. Schreiben Sie an Ihre Krankenkasse.",
 taskEn:"You've lost your health insurance card and have a doctor's appointment next week. Write to your health insurer.",
 points:["Versichertennummer","Was ist passiert?","Bitte um neue Karte","Was tun beim Arzttermin?"],
 parts:[
  ["b","Betreff: Verlust meiner Versichertenkarte – Versichertennummer [Nummer]","Subject: Loss of my health insurance card – insurance number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","leider habe ich am [Datum] meine Geldbörse mit meiner Versichertenkarte verloren. Den Verlust habe ich bereits bei der Polizei gemeldet.","Unfortunately on [date] I lost my wallet with my health insurance card. I have already reported the loss to the police."],
  ["p","Ich bitte Sie, die alte Karte zu sperren und mir so schnell wie möglich eine neue Karte zu schicken. Ein aktuelles Foto habe ich in Ihrer App hochgeladen.","I ask you to block the old card and send me a new card as quickly as possible. I have uploaded a current photo in your app."],
  ["p","Nächsten Dienstag habe ich einen Termin beim Hausarzt. Können Sie mir bis dahin eine Ersatzbescheinigung schicken, zum Beispiel per E-Mail?","I have an appointment with my GP next Tuesday. Could you send me a replacement certificate by then, for example by email?"],
  ["p","Vielen Dank im Voraus für Ihre Hilfe.","Thank you in advance for your help."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]","Kind regards\n[your name]"]],
 tips:[["Leider habe ich … verloren.","Unfortunately I've lost …"],["Ich bitte Sie, die alte Karte zu sperren.","Please block the old card."],["so schnell wie möglich","as quickly as possible"],["Vielen Dank im Voraus für Ihre Hilfe.","Thank you in advance for your help."]]},

{id:"adresse", de:"Bank / Versicherung: neue Adresse", en:"Bank / insurance: change of address", formal:true,
 task:"Sie sind umgezogen. Teilen Sie Ihrer Versicherung Ihre neue Adresse und Ihre neue Bankverbindung mit.",
 taskEn:"You've moved. Tell your insurance company your new address and your new bank details.",
 points:["Vertrags- / Versicherungsnummer","Neue Adresse ab wann","Neue Bankverbindung","Bitte um Bestätigung"],
 parts:[
  ["b","Betreff: Änderung meiner Adresse und Bankverbindung – Vertragsnummer [Nummer]","Subject: Change of my address and bank details – contract number [number]"],
  ["a","Sehr geehrte Damen und Herren,","Dear Sir or Madam,"],
  ["p","ich bin umgezogen und möchte Ihnen meine neue Adresse mitteilen. Ab dem [Datum] wohne ich in: [Straße, Hausnummer, PLZ Ort].","I have moved and would like to inform you of my new address. From [date] I live at: [street, number, postcode, town]."],
  ["p","Außerdem habe ich ein neues Konto. Bitte buchen Sie die Beiträge ab dem nächsten Monat von folgendem Konto ab: IBAN [IBAN], [Name der Bank]. Das neue SEPA-Lastschriftmandat habe ich unterschrieben und lege es bei.","I also have a new account. From next month please debit the contributions from the following account: IBAN [IBAN], [bank name]. I have signed the new SEPA direct debit mandate and enclose it."],
  ["p","Bitte bestätigen Sie mir die Änderungen kurz schriftlich oder per E-Mail.","Please briefly confirm the changes to me in writing or by email."],
  ["g","Mit freundlichen Grüßen\n[Ihr Name]\nAnlage: SEPA-Lastschriftmandat","Kind regards\n[your name]\nEnclosure: SEPA direct debit mandate"]],
 tips:[["Ich möchte Ihnen meine neue Adresse mitteilen.","I'd like to inform you of my new address."],["Ab dem … wohne ich in …","From … I live at …"],["Bitte buchen Sie die Beiträge von folgendem Konto ab.","Please debit the contributions from the following account."],["Bitte bestätigen Sie mir die Änderungen.","Please confirm the changes."]]},

{id:"freundin", de:"Freundin: Absage und neuer Vorschlag", en:"Friend: declining and suggesting another date", formal:false,
 task:"Ihre Freundin Anna hat Sie zu ihrer Geburtstagsfeier am Samstag eingeladen. Sie können leider nicht kommen. Schreiben Sie ihr.",
 taskEn:"Your friend Anna has invited you to her birthday party on Saturday. Unfortunately you can't come. Write to her.",
 points:["Dank für die Einladung","Warum Sie nicht kommen können","Geschenk / Glückwunsch","Vorschlag für ein Treffen"],
 parts:[
  ["a","Liebe Anna,","Dear Anna,"],
  ["p","vielen Dank für deine Einladung zu deiner Geburtstagsfeier! Ich habe mich sehr darüber gefreut.","Thank you so much for inviting me to your birthday party! I was really pleased."],
  ["p","Leider kann ich am Samstag nicht kommen, weil meine Schwiegereltern uns an diesem Wochenende besuchen. Sie kommen aus [Land] und bleiben nur drei Tage. Das tut mir wirklich leid!","Unfortunately I can't come on Saturday because my parents-in-law are visiting us that weekend. They're coming from [country] and are only staying three days. I'm really sorry!"],
  ["p","Ich wünsche dir schon jetzt alles Gute zum Geburtstag und eine tolle Party. Mein Geschenk bekommst du, wenn wir uns sehen – ich verrate nur so viel: Es hat etwas mit Kochen zu tun.","I already wish you a very happy birthday and a great party. You'll get my present when we see each other – I'll only tell you this much: it has something to do with cooking."],
  ["p","Hast du vielleicht nächste Woche Zeit? Wir könnten am Mittwochabend zusammen essen gehen und ein bisschen nachfeiern. Was meinst du?","Do you perhaps have time next week? We could go out for dinner on Wednesday evening and celebrate a bit belatedly. What do you think?"],
  ["g","Liebe Grüße\n[Ihr Name]","Love\n[your name]"]],
 tips:[["Vielen Dank für deine Einladung!","Thanks for your invitation!"],["Leider kann ich nicht kommen, weil …","Unfortunately I can't come because …"],["Alles Gute zum Geburtstag!","Happy birthday!"],["Wir könnten … – Was meinst du?","We could … – What do you think?"]]}
];
