/* Everyday conversations for the Gespräche tab.
   Each: title, situation, the two roles, lines [role, German, English] and
   key phrases [German, English]. [Klammern] are placeholders to fill in.
   tools/check-alltag.mjs checks the shape. */
window.GS = [
{id:"kinderarzt", de:"Kinderarzt: Termin für die Tochter", en:"Paediatrician: appointment for your daughter",
 sit:"Ihre Tochter hat seit gestern Fieber und Husten. Sie rufen in der Kinderarztpraxis an.",
 sitEn:"Your daughter has had a fever and a cough since yesterday. You call the paediatric practice.",
 who:{A:"Praxis", B:"Sie"},
 lines:[
  ["A","Kinderarztpraxis Dr. Becker, Sie sprechen mit Frau Lang. Was kann ich für Sie tun?","Dr Becker's paediatric practice, you're speaking to Ms Lang. What can I do for you?"],
  ["B","Guten Morgen, mein Name ist [Ihr Name]. Ich möchte gern einen Termin für meine Tochter machen.","Good morning, my name is [your name]. I'd like to make an appointment for my daughter."],
  ["A","Wie alt ist Ihre Tochter, und was fehlt ihr denn?","How old is your daughter, and what's wrong with her?"],
  ["B","Sie ist sechs Jahre alt. Sie hat seit gestern Abend Fieber, fast 39 Grad, und einen starken Husten.","She's six. She has had a fever since last night, almost 39 degrees, and a bad cough."],
  ["A","Isst und trinkt sie noch normal?","Is she still eating and drinking normally?"],
  ["B","Sie trinkt genug, aber sie hat kaum Appetit und ist sehr müde.","She's drinking enough, but she has hardly any appetite and is very tired."],
  ["A","Gut. Waren Sie schon einmal bei uns in der Praxis?","All right. Have you been to our practice before?"],
  ["B","Ja, meine Tochter ist hier Patientin. Sie heißt [Name der Tochter].","Yes, my daughter is a patient here. Her name is [daughter's name]."],
  ["A","Einen Moment, ich schaue nach … Ja, ich habe sie gefunden. Können Sie heute um 11:30 Uhr kommen?","One moment, I'll check … Yes, I've found her. Can you come today at 11:30?"],
  ["B","Ja, das passt. Muss ich etwas mitbringen?","Yes, that works. Do I need to bring anything?"],
  ["A","Bitte bringen Sie die Versichertenkarte und das gelbe Untersuchungsheft mit.","Please bring the insurance card and the yellow check-up booklet."],
  ["B","Alles klar. Und was soll ich tun, wenn das Fieber bis dahin steigt?","All right. And what should I do if the fever goes up before then?"],
  ["A","Geben Sie ihr ein Fiebermittel für Kinder. Wenn es ihr sehr schlecht geht, rufen Sie den Notdienst unter 116 117 an.","Give her a fever medicine for children. If she gets very unwell, call the out-of-hours service on 116 117."],
  ["B","Vielen Dank für Ihre Hilfe. Bis später!","Thank you for your help. See you later!"],
  ["A","Gern geschehen. Gute Besserung für Ihre Tochter!","You're welcome. I hope your daughter gets well soon!"]],
 tips:[["Ich möchte gern einen Termin für meine Tochter machen.","I'd like to make an appointment for my daughter."],["Sie hat seit gestern Fieber.","She has had a fever since yesterday."],["Muss ich etwas mitbringen?","Do I need to bring anything?"],["Gute Besserung!","Get well soon!"]]},

{id:"kardiologe", de:"Facharzt: Brustschmerzen", en:"Specialist: chest pain",
 sit:"Sie haben seit einigen Tagen immer wieder leichte Schmerzen in der Brust. Ihr Hausarzt hat Ihnen eine Überweisung zum Kardiologen gegeben.",
 sitEn:"For a few days you've had recurring mild chest pain. Your GP has given you a referral to a cardiologist.",
 who:{A:"Praxis", B:"Sie"},
 lines:[
  ["A","Kardiologische Praxis am Markt, guten Tag.","Cardiology practice am Markt, good afternoon."],
  ["B","Guten Tag, ich habe eine Überweisung von meinem Hausarzt und brauche einen Termin.","Hello, I have a referral from my GP and need an appointment."],
  ["A","Worum geht es denn genau?","What exactly is it about?"],
  ["B","Ich habe seit ungefähr einer Woche immer wieder Schmerzen in der Brust, vor allem beim Treppensteigen.","For about a week I've had recurring pain in my chest, especially when climbing stairs."],
  ["A","Haben Sie die Schmerzen im Moment auch?","Do you have the pain right now as well?"],
  ["B","Nein, im Moment nicht. Sie kommen und gehen.","No, not at the moment. They come and go."],
  ["A","Wichtig: Wenn Sie starke Schmerzen, Atemnot oder Schmerzen im linken Arm haben, rufen Sie sofort den Notruf 112 an.","Important: if you have severe pain, shortness of breath or pain in your left arm, call the emergency number 112 immediately."],
  ["B","Verstanden, das mache ich.","Understood, I'll do that."],
  ["A","Da Sie eine Überweisung haben, kann ich Ihnen einen dringenden Termin geben. Passt Ihnen Donnerstag um 8:15 Uhr?","As you have a referral, I can give you an urgent appointment. Does Thursday at 8:15 suit you?"],
  ["B","Ja, am Donnerstag kann ich. Muss ich nüchtern kommen?","Yes, I can on Thursday. Do I need to come with an empty stomach?"],
  ["A","Nein, das ist nicht nötig. Wir machen ein EKG und einen Ultraschall. Bringen Sie bitte die Überweisung und Ihre Medikamentenliste mit.","No, that's not necessary. We'll do an ECG and an ultrasound. Please bring the referral and your list of medicines."],
  ["B","In Ordnung. Wie lange dauert die Untersuchung ungefähr?","OK. Roughly how long does the examination take?"],
  ["A","Planen Sie etwa eine Stunde ein. Wie ist Ihr Name, bitte?","Allow about an hour. What's your name, please?"],
  ["B","[Ihr Name], ich buchstabiere: [Buchstaben].","[your name], I'll spell it: [letters]."],
  ["A","Danke, der Termin ist eingetragen. Bis Donnerstag!","Thank you, the appointment is booked. See you on Thursday!"]],
 tips:[["Ich habe eine Überweisung von meinem Hausarzt.","I have a referral from my GP."],["Die Schmerzen kommen und gehen.","The pain comes and goes."],["Muss ich nüchtern kommen?","Do I have to come with an empty stomach?"],["Bei starken Schmerzen: Notruf 112.","With severe pain: call 112."]]},

{id:"internet", de:"Internetanbieter: Beschwerde", en:"Internet provider: complaint",
 sit:"Ihr Internet funktioniert seit drei Tagen nicht. Sie arbeiten im Homeoffice und rufen beim Kundenservice an.",
 sitEn:"Your internet hasn't worked for three days. You work from home and call customer service.",
 who:{A:"Kundenservice", B:"Sie"},
 lines:[
  ["A","Willkommen beim Kundenservice von NetFix. Mein Name ist Herr Wolf. Wie kann ich Ihnen helfen?","Welcome to NetFix customer service. My name is Mr Wolf. How can I help you?"],
  ["B","Guten Tag. Mein Internet funktioniert seit drei Tagen überhaupt nicht mehr.","Hello. My internet hasn't worked at all for three days."],
  ["A","Das tut mir leid. Nennen Sie mir bitte Ihre Kundennummer.","I'm sorry to hear that. Please give me your customer number."],
  ["B","Meine Kundennummer ist [Nummer].","My customer number is [number]."],
  ["A","Danke. Haben Sie den Router schon einmal neu gestartet?","Thank you. Have you already restarted the router?"],
  ["B","Ja, mehrmals. Die Lampe für das Internet blinkt die ganze Zeit rot.","Yes, several times. The internet light keeps flashing red."],
  ["A","Ich sehe hier, dass es in Ihrer Straße eine Störung gibt. Ein Techniker ist schon informiert.","I can see there's a fault in your street. A technician has already been informed."],
  ["B","Und wann ist das Problem gelöst? Ich arbeite von zu Hause und brauche das Internet dringend.","And when will the problem be fixed? I work from home and urgently need the internet."],
  ["A","Wir rechnen damit, dass die Störung bis morgen Abend behoben ist.","We expect the fault to be fixed by tomorrow evening."],
  ["B","Das ist ärgerlich. Ich bezahle jeden Monat, aber jetzt habe ich vier Tage kein Internet.","That's annoying. I pay every month, but now I'll have no internet for four days."],
  ["A","Das verstehe ich. Sie bekommen für die Tage ohne Internet eine Gutschrift auf Ihrer nächsten Rechnung.","I understand. You'll get a credit on your next bill for the days without internet."],
  ["B","Gut. Können Sie mir das bitte auch schriftlich per E-Mail bestätigen?","Good. Could you also confirm that in writing by email, please?"],
  ["A","Natürlich, Sie bekommen heute noch eine E-Mail. Kann ich sonst noch etwas für Sie tun?","Of course, you'll get an email today. Is there anything else I can do for you?"],
  ["B","Nein, danke. Auf Wiederhören.","No, thank you. Goodbye."]],
 tips:[["Mein Internet funktioniert seit drei Tagen nicht.","My internet hasn't worked for three days."],["Die Lampe blinkt rot.","The light is flashing red."],["Wann ist das Problem gelöst?","When will the problem be fixed?"],["Können Sie mir das schriftlich bestätigen?","Can you confirm that in writing?"]]},

{id:"supermarkt", de:"Im Supermarkt", en:"At the supermarket",
 sit:"Sie suchen im Supermarkt ein Produkt und möchten außerdem etwas umtauschen.",
 sitEn:"You're looking for a product in the supermarket and also want to exchange something.",
 who:{A:"Verkäufer", B:"Sie"},
 lines:[
  ["B","Entschuldigung, können Sie mir helfen? Ich finde die glutenfreien Nudeln nicht.","Excuse me, can you help me? I can't find the gluten-free pasta."],
  ["A","Die finden Sie in Gang vier, ganz unten im Regal neben dem Reis.","You'll find them in aisle four, on the bottom shelf next to the rice."],
  ["B","Danke. Und haben Sie auch frisches Brot ohne Weizen?","Thank you. And do you also have fresh bread without wheat?"],
  ["A","Leider nicht. Das bekommen Sie aber in der Bäckerei am Eingang.","Unfortunately not. But you can get it at the bakery by the entrance."],
  ["B","Noch eine Frage: Ich habe gestern diesen Käse gekauft, aber er ist schon abgelaufen.","One more question: I bought this cheese yesterday, but it has already expired."],
  ["A","Oh, das tut mir leid. Haben Sie den Kassenbon dabei?","Oh, I'm sorry. Do you have the receipt with you?"],
  ["B","Ja, hier ist er.","Yes, here it is."],
  ["A","Möchten Sie das Geld zurück oder lieber einen neuen Käse?","Would you like your money back or a new cheese instead?"],
  ["B","Einen neuen, bitte. Aber diesmal mit einem längeren Haltbarkeitsdatum.","A new one, please. But this time with a longer best-before date."],
  ["A","Selbstverständlich. Ich hole Ihnen einen aus dem Lager.","Of course. I'll get you one from the storeroom."],
  ["B","Vielen Dank. Sind die Erdbeeren heute im Angebot?","Thank you very much. Are the strawberries on offer today?"],
  ["A","Ja, 500 Gramm kosten heute nur 1,99 Euro.","Yes, 500 grams only cost 1.99 euros today."],
  ["B","Super, dann nehme ich zwei Schalen. Kann ich an der Kasse auch mit Karte bezahlen?","Great, then I'll take two punnets. Can I also pay by card at the checkout?"],
  ["A","Ja, mit Karte oder mit dem Handy, wie Sie möchten.","Yes, by card or with your phone, as you like."]],
 tips:[["Entschuldigung, wo finde ich …?","Excuse me, where can I find …?"],["Der Käse ist schon abgelaufen.","The cheese has already expired."],["Haben Sie den Kassenbon dabei?","Do you have the receipt with you?"],["Kann ich mit Karte bezahlen?","Can I pay by card?"]]},

{id:"arzt", de:"Beim Arzt: Rückenschmerzen und Verletzung", en:"At the doctor's: back pain and an injury",
 sit:"Sie sind beim Hausarzt. Sie haben starke Rückenschmerzen und haben sich beim Sport den Fuß verletzt.",
 sitEn:"You're at your GP's. You have bad back pain and hurt your foot doing sport.",
 who:{A:"Ärztin", B:"Sie"},
 lines:[
  ["A","Guten Tag, nehmen Sie bitte Platz. Was führt Sie zu mir?","Hello, please take a seat. What brings you to me?"],
  ["B","Ich habe seit einer Woche starke Rückenschmerzen, vor allem morgens nach dem Aufstehen.","I've had bad back pain for a week, especially in the morning after getting up."],
  ["A","Wo genau tut es weh? Zeigen Sie es mir bitte.","Where exactly does it hurt? Please show me."],
  ["B","Hier unten, im unteren Rücken. Manchmal zieht der Schmerz bis ins Bein.","Down here, in the lower back. Sometimes the pain goes down into my leg."],
  ["A","Sitzen Sie bei der Arbeit viel?","Do you sit a lot at work?"],
  ["B","Ja, acht Stunden am Tag vor dem Computer.","Yes, eight hours a day at the computer."],
  ["A","Das ist oft der Grund. Haben Sie noch andere Beschwerden?","That's often the reason. Do you have any other complaints?"],
  ["B","Ja, ich bin am Samstag beim Fußball umgeknickt. Mein Knöchel ist geschwollen.","Yes, I twisted my ankle playing football on Saturday. My ankle is swollen."],
  ["A","Lassen Sie mich mal sehen … Können Sie den Fuß bewegen?","Let me have a look … Can you move your foot?"],
  ["B","Ja, aber es tut beim Gehen weh.","Yes, but it hurts when I walk."],
  ["A","Ich glaube, er ist nur verstaucht, nicht gebrochen. Zur Sicherheit machen wir aber ein Röntgenbild.","I think it's only sprained, not broken. But to be safe we'll do an X-ray."],
  ["B","Und was kann ich gegen die Rückenschmerzen tun?","And what can I do about the back pain?"],
  ["A","Ich verschreibe Ihnen Physiotherapie und eine Salbe. Bewegen Sie sich regelmäßig und machen Sie Pausen bei der Arbeit.","I'll prescribe physiotherapy and an ointment. Move regularly and take breaks at work."],
  ["B","Brauche ich eine Krankschreibung?","Do I need a sick note?"],
  ["A","Ja, ich schreibe Sie für drei Tage krank. Die Bescheinigung bekommt Ihr Arbeitgeber elektronisch.","Yes, I'll sign you off sick for three days. Your employer gets the certificate electronically."],
  ["B","Vielen Dank, Frau Doktor.","Thank you very much, doctor."]],
 tips:[["Wo genau tut es weh?","Where exactly does it hurt?"],["Ich bin umgeknickt.","I twisted my ankle."],["Der Knöchel ist geschwollen.","The ankle is swollen."],["Brauche ich eine Krankschreibung?","Do I need a sick note?"]]},

{id:"restaurant", de:"Im Restaurant bestellen", en:"Ordering in a restaurant",
 sit:"Sie sind mit einer Freundin im Restaurant. Sie bestellen, haben eine Frage zum Essen und bezahlen.",
 sitEn:"You're in a restaurant with a friend. You order, ask about the food and pay.",
 who:{A:"Kellner", B:"Sie"},
 lines:[
  ["A","Guten Abend! Haben Sie reserviert?","Good evening! Do you have a reservation?"],
  ["B","Ja, auf den Namen [Ihr Name], ein Tisch für zwei Personen um 19 Uhr.","Yes, under the name [your name], a table for two at 7 pm."],
  ["A","Sehr schön, folgen Sie mir bitte. Hier ist die Speisekarte. Was möchten Sie trinken?","Very good, please follow me. Here's the menu. What would you like to drink?"],
  ["B","Wir nehmen eine große Flasche Wasser und zwei Apfelschorlen, bitte.","We'll have a large bottle of water and two apple spritzers, please."],
  ["A","Haben Sie schon gewählt?","Have you already decided?"],
  ["B","Fast. Ist in der Gemüsesuppe Fleisch oder Fleischbrühe?","Almost. Is there meat or meat stock in the vegetable soup?"],
  ["A","Nein, die Suppe ist vegetarisch.","No, the soup is vegetarian."],
  ["B","Gut, dann hätte ich gern die Suppe als Vorspeise und danach das Hähnchen mit Reis.","Good, then I'd like the soup as a starter and then the chicken with rice."],
  ["A","Und für Sie?","And for you?"],
  ["B","Meine Freundin nimmt die Pasta mit Tomatensoße, aber bitte ohne Käse.","My friend will have the pasta with tomato sauce, but without cheese, please."],
  ["A","Kein Problem.","No problem."],
  ["B","Entschuldigung, das Hähnchen ist leider nicht richtig warm.","Excuse me, unfortunately the chicken isn't properly hot."],
  ["A","Oh, das tut mir leid. Ich bringe es sofort zurück in die Küche.","Oh, I'm sorry. I'll take it straight back to the kitchen."],
  ["B","Wir möchten bitte zahlen. Getrennt, bitte.","We'd like to pay, please. Separately, please."],
  ["A","Gern. Das macht bei Ihnen 24,50 Euro.","Certainly. That's 24.50 euros for you."],
  ["B","26, bitte. Stimmt so.","26, please. Keep the change."]],
 tips:[["Ein Tisch für zwei Personen, bitte.","A table for two, please."],["Ich hätte gern …","I'd like …"],["Ohne Käse, bitte.","Without cheese, please."],["Wir möchten zahlen. – Getrennt oder zusammen?","We'd like to pay. – Separately or together?"],["Stimmt so.","Keep the change."]]},

{id:"bank", de:"Bei der Bank: Konto eröffnen", en:"At the bank: opening an account",
 sit:"Sie sind neu in Deutschland und möchten ein Girokonto eröffnen.",
 sitEn:"You're new in Germany and want to open a current account.",
 who:{A:"Bankberaterin", B:"Sie"},
 lines:[
  ["A","Guten Tag, was kann ich für Sie tun?","Hello, what can I do for you?"],
  ["B","Guten Tag, ich möchte ein Girokonto eröffnen. Ich habe vor zwei Monaten eine Stelle hier angefangen.","Hello, I'd like to open a current account. I started a job here two months ago."],
  ["A","Gern. Haben Sie Ihren Pass und Ihre Meldebescheinigung dabei?","Certainly. Do you have your passport and your registration certificate with you?"],
  ["B","Ja, hier sind beide. Brauchen Sie auch meinen Aufenthaltstitel?","Yes, here are both. Do you also need my residence permit?"],
  ["A","Ja, bitte, und Ihre Steuer-Identifikationsnummer.","Yes, please, and your tax ID number."],
  ["B","Die habe ich auf diesem Brief vom Finanzamt.","I have it on this letter from the tax office."],
  ["A","Sehr gut. Wir haben zwei Kontomodelle. Das Online-Konto ist kostenlos, beim Konto mit Filialservice zahlen Sie fünf Euro im Monat.","Very good. We have two account types. The online account is free; with the branch-service account you pay five euros a month."],
  ["B","Ich nehme das Online-Konto. Bekomme ich auch eine Karte?","I'll take the online account. Do I get a card too?"],
  ["A","Ja, Sie bekommen eine Debitkarte. Die Karte und die PIN kommen in zwei getrennten Briefen.","Yes, you'll get a debit card. The card and the PIN come in two separate letters."],
  ["B","Wie lange dauert das ungefähr?","Roughly how long does that take?"],
  ["A","Etwa eine Woche. Ihre IBAN bekommen Sie aber heute schon, dann können Sie sie Ihrem Arbeitgeber geben.","About a week. But you'll get your IBAN today, so you can give it to your employer."],
  ["B","Perfekt. Kann ich auch die Miete per Dauerauftrag bezahlen?","Perfect. Can I also pay the rent by standing order?"],
  ["A","Natürlich, das können Sie im Online-Banking selbst einrichten.","Of course, you can set that up yourself in online banking."],
  ["B","Vielen Dank für die Beratung.","Thank you for the advice."]],
 tips:[["Ich möchte ein Girokonto eröffnen.","I'd like to open a current account."],["Meldebescheinigung, Aufenthaltstitel, Steuer-ID","registration certificate, residence permit, tax ID"],["Die Karte und die PIN kommen getrennt.","The card and PIN come separately."],["Kann ich einen Dauerauftrag einrichten?","Can I set up a standing order?"]]},

{id:"bahn", de:"Am DB-Schalter: Fahrkarte kaufen", en:"At the DB counter: buying a ticket",
 sit:"Sie möchten am Freitag mit dem Zug von Frankfurt nach Hamburg fahren und am Sonntag zurück.",
 sitEn:"You want to travel by train from Frankfurt to Hamburg on Friday and back on Sunday.",
 who:{A:"Bahnmitarbeiter", B:"Sie"},
 lines:[
  ["A","Guten Tag, wohin möchten Sie fahren?","Hello, where would you like to go?"],
  ["B","Ich möchte eine Fahrkarte nach Hamburg, hin und zurück, bitte.","I'd like a return ticket to Hamburg, please."],
  ["A","Wann möchten Sie fahren?","When would you like to travel?"],
  ["B","Am Freitag, am liebsten am Nachmittag, und am Sonntagabend zurück.","On Friday, preferably in the afternoon, and back on Sunday evening."],
  ["A","Es gibt einen ICE um 14:52 Uhr. Er fährt direkt, Sie sind um 18:36 Uhr in Hamburg.","There's an ICE at 14:52. It's direct; you'll be in Hamburg at 18:36."],
  ["B","Das passt gut. Und zurück?","That works well. And back?"],
  ["A","Am Sonntag um 17:05 Uhr ab Hamburg Hauptbahnhof, mit einmal Umsteigen in Hannover.","On Sunday at 17:05 from Hamburg main station, with one change in Hanover."],
  ["B","Gibt es auch eine direkte Verbindung?","Is there a direct connection too?"],
  ["A","Ja, um 18:01 Uhr, dann sind Sie um 21:40 Uhr in Frankfurt.","Yes, at 18:01, then you'll be in Frankfurt at 21:40."],
  ["B","Die nehme ich. Was kostet das?","I'll take that one. How much is it?"],
  ["A","Mit dem Sparpreis 79,80 Euro für beide Fahrten. Haben Sie eine BahnCard?","With the saver fare 79.80 euros for both journeys. Do you have a BahnCard?"],
  ["B","Nein. Kann ich den Sparpreis stornieren, wenn ich nicht fahren kann?","No. Can I cancel the saver fare if I can't travel?"],
  ["A","Ja, bis einen Tag vorher, aber es kostet eine Gebühr von zehn Euro.","Yes, up to one day before, but there's a fee of ten euros."],
  ["B","In Ordnung. Ich möchte auch einen Sitzplatz reservieren, am Fenster, bitte.","OK. I'd also like to reserve a seat, by the window, please."],
  ["A","Gern. Wagen 7, Platz 45 hin und Wagen 5, Platz 12 zurück. Hier ist Ihre Fahrkarte.","Certainly. Coach 7, seat 45 there and coach 5, seat 12 back. Here's your ticket."]],
 tips:[["Eine Fahrkarte nach …, hin und zurück, bitte.","A return ticket to …, please."],["Muss ich umsteigen? – Gibt es eine direkte Verbindung?","Do I have to change? – Is there a direct connection?"],["Ich möchte einen Sitzplatz reservieren.","I'd like to reserve a seat."],["Kann ich die Fahrkarte stornieren?","Can I cancel the ticket?"]]},

{id:"auslaenderbehoerde", de:"Ausländerbehörde: Termin absagen", en:"Immigration office: cancelling an appointment",
 sit:"Sie haben einen Termin bei der Ausländerbehörde, können aber nicht kommen, weil Ihr Kind krank ist. Sie rufen an.",
 sitEn:"You have an appointment at the immigration office but can't come because your child is ill. You call.",
 who:{A:"Behörde", B:"Sie"},
 lines:[
  ["A","Ausländerbehörde Frankfurt, Frau Schulz. Guten Morgen.","Frankfurt immigration office, Ms Schulz. Good morning."],
  ["B","Guten Morgen. Ich habe morgen um 9 Uhr einen Termin, aber leider kann ich nicht kommen.","Good morning. I have an appointment tomorrow at 9, but unfortunately I can't come."],
  ["A","Wie ist Ihr Name und Ihr Geburtsdatum?","What's your name and date of birth?"],
  ["B","[Ihr Name], geboren am [Datum].","[your name], born on [date]."],
  ["A","Danke. Worum geht es bei dem Termin?","Thank you. What is the appointment about?"],
  ["B","Um die Verlängerung meines Aufenthaltstitels. Mein Titel ist noch bis Ende nächsten Monats gültig.","About extending my residence permit. My permit is valid until the end of next month."],
  ["A","Darf ich fragen, warum Sie nicht kommen können?","May I ask why you can't come?"],
  ["B","Mein Sohn ist krank und ich muss zu Hause bleiben. Das tut mir sehr leid.","My son is ill and I have to stay at home. I'm very sorry."],
  ["A","Kein Problem, gut, dass Sie anrufen. Ich sage den Termin ab. Möchten Sie gleich einen neuen?","No problem, it's good that you called. I'll cancel the appointment. Would you like a new one straight away?"],
  ["B","Ja, bitte. Ist es wichtig, dass der neue Termin vor dem Ablauf meines Titels ist?","Yes, please. Is it important that the new appointment is before my permit expires?"],
  ["A","Ja. Ich gebe Ihnen einen Termin in zwei Wochen, am Dienstag, den 14., um 10:30 Uhr.","Yes. I'll give you an appointment in two weeks, on Tuesday the 14th, at 10:30."],
  ["B","Das passt. Muss ich die Unterlagen noch einmal schicken?","That works. Do I have to send the documents again?"],
  ["A","Nein, bringen Sie einfach alles zum Termin mit: Pass, biometrisches Foto, Arbeitsvertrag und Mietvertrag.","No, just bring everything to the appointment: passport, biometric photo, employment contract and rental contract."],
  ["B","Bekomme ich eine Bestätigung?","Will I get a confirmation?"],
  ["A","Ja, per E-Mail. Gute Besserung für Ihren Sohn!","Yes, by email. I hope your son gets better soon!"]],
 tips:[["Ich kann leider nicht zum Termin kommen.","Unfortunately I can't come to the appointment."],["Ich möchte den Termin absagen / verschieben.","I'd like to cancel / postpone the appointment."],["die Verlängerung meines Aufenthaltstitels","the extension of my residence permit"],["Bekomme ich eine Bestätigung?","Will I get a confirmation?"]]},

{id:"aktien", de:"Zwei Freunde: Aktien und Sparen", en:"Two friends: shares and saving",
 sit:"Zwei Freunde sprechen in der Mittagspause über Geld, Sparen und die Börse.",
 sitEn:"Two friends talk about money, saving and the stock market during their lunch break.",
 who:{A:"Daniel", B:"Sie"},
 lines:[
  ["A","Sag mal, legst du eigentlich Geld an, oder liegt alles auf dem Sparkonto?","Tell me, do you actually invest money, or is it all in a savings account?"],
  ["B","Ich habe vor einem Jahr angefangen, jeden Monat etwas in einen ETF zu investieren.","A year ago I started investing something in an ETF every month."],
  ["A","Ein ETF? Was ist das genau?","An ETF? What exactly is that?"],
  ["B","Das ist ein Fonds, der viele Aktien auf einmal enthält, zum Beispiel von Firmen aus der ganzen Welt.","It's a fund that contains lots of shares at once, for example from companies all over the world."],
  ["A","Und ist das nicht riskant? Letzte Woche sind die Kurse ziemlich stark gefallen.","And isn't that risky? Last week prices fell quite sharply."],
  ["B","Kurzfristig schon, die Kurse steigen und fallen. Aber ich will das Geld erst in zwanzig Jahren benutzen.","In the short term, yes, prices go up and down. But I don't want to use the money for another twenty years."],
  ["A","Ich habe mal einzelne Aktien gekauft und viel verloren. Seitdem bin ich vorsichtig.","I once bought individual shares and lost a lot. Since then I've been careful."],
  ["B","Das verstehe ich. Deshalb kaufe ich keine einzelnen Aktien, sondern verteile das Risiko.","I understand. That's why I don't buy individual shares but spread the risk."],
  ["A","Wie viel legst du denn jeden Monat an, wenn ich fragen darf?","How much do you invest each month, if I may ask?"],
  ["B","Nur einen kleinen Betrag. Wichtig ist, dass man immer ein Notfallpolster auf dem Konto hat.","Only a small amount. The important thing is to always keep an emergency cushion in your account."],
  ["A","Stimmt. Und wo hast du dein Depot eröffnet?","True. And where did you open your securities account?"],
  ["B","Bei einer Online-Bank. Aber ich bin kein Experte – lass dich am besten neutral beraten.","At an online bank. But I'm no expert – it's best to get neutral advice."],
  ["A","Gute Idee. Vielleicht gehe ich mal zur Verbraucherzentrale.","Good idea. Maybe I'll go to the consumer advice centre."],
  ["B","Mach das. Und jetzt lass uns lieber essen, bevor die Pause vorbei ist!","Do that. And now let's eat before the break is over!"]],
 tips:[["Geld anlegen / investieren","to invest money"],["Die Kurse steigen / fallen.","Prices are rising / falling."],["das Risiko verteilen","to spread the risk"],["Lass dich neutral beraten.","Get neutral advice."]]},

{id:"vermieter", de:"Vermieter anrufen: Heizung kaputt", en:"Calling the landlord: heating broken",
 sit:"Es ist Januar und Ihre Heizung funktioniert nicht. Sie rufen Ihren Vermieter an.",
 sitEn:"It's January and your heating isn't working. You call your landlord.",
 who:{A:"Vermieter", B:"Sie"},
 lines:[
  ["A","Hausverwaltung Keller, guten Tag.","Keller property management, good afternoon."],
  ["B","Guten Tag, hier ist [Ihr Name] aus der Goethestraße 12, zweiter Stock. Meine Heizung ist kaputt.","Hello, this is [your name] from Goethestraße 12, second floor. My heating is broken."],
  ["A","Seit wann funktioniert sie nicht?","Since when hasn't it been working?"],
  ["B","Seit gestern Abend. Die Heizkörper bleiben kalt, und auch das Wasser ist nur lauwarm.","Since last night. The radiators stay cold, and the water is only lukewarm too."],
  ["A","Haben Sie schon nachgesehen, ob das Ventil aufgedreht ist?","Have you checked whether the valve is turned on?"],
  ["B","Ja, alles ist auf Stufe fünf. Meine Nachbarn haben das gleiche Problem.","Yes, everything is on level five. My neighbours have the same problem."],
  ["A","Dann liegt es wahrscheinlich an der Heizungsanlage im Keller. Ich schicke heute noch einen Techniker.","Then it's probably the heating system in the basement. I'll send a technician today."],
  ["B","Wann ungefähr kommt er? Ich muss um 15 Uhr meine Kinder abholen.","Roughly when will he come? I have to pick up my children at 3 pm."],
  ["A","Er kommt zwischen 12 und 14 Uhr. Wenn Sie nicht da sind, kann er auch zuerst in den Keller gehen.","He'll come between 12 and 2. If you're not there, he can go to the basement first."],
  ["B","Gut. Und was mache ich, wenn es heute Abend immer noch nicht funktioniert?","Good. And what do I do if it still isn't working this evening?"],
  ["A","Dann rufen Sie bitte den Notdienst an, die Nummer hängt im Treppenhaus.","Then please call the emergency service; the number is on the wall in the stairwell."],
  ["B","Könnten Sie mir bitte auch ein kleines Heizgerät leihen? Meine Tochter ist erst zwei.","Could you also lend me a small heater? My daughter is only two."],
  ["A","Natürlich, der Techniker bringt eins mit.","Of course, the technician will bring one."],
  ["B","Vielen Dank für die schnelle Hilfe.","Thank you for the quick help."]],
 tips:[["Meine Heizung ist kaputt.","My heating is broken."],["Die Heizkörper bleiben kalt.","The radiators stay cold."],["Wann kommt der Techniker?","When will the technician come?"],["Die Nummer vom Notdienst","the number of the emergency service"]]},

{id:"apotheke", de:"In der Apotheke", en:"At the pharmacy",
 sit:"Sie sind erkältet und gehen in die Apotheke. Sie haben auch ein Rezept für Ihren Mann.",
 sitEn:"You have a cold and go to the pharmacy. You also have a prescription for your husband.",
 who:{A:"Apothekerin", B:"Sie"},
 lines:[
  ["A","Guten Tag, was darf es sein?","Hello, what can I get you?"],
  ["B","Guten Tag, ich habe eine starke Erkältung. Haben Sie etwas gegen Halsschmerzen und Schnupfen?","Hello, I have a bad cold. Do you have something for a sore throat and a runny nose?"],
  ["A","Haben Sie auch Fieber?","Do you have a fever too?"],
  ["B","Nein, nur Halsschmerzen, Schnupfen und ein bisschen Husten.","No, just a sore throat, a runny nose and a bit of a cough."],
  ["A","Dann empfehle ich Ihnen diese Lutschtabletten und ein Nasenspray. Nehmen Sie das Spray aber höchstens eine Woche.","Then I recommend these lozenges and a nasal spray. But don't use the spray for more than a week."],
  ["B","Wie oft soll ich die Tabletten nehmen?","How often should I take the tablets?"],
  ["A","Alle drei bis vier Stunden eine, maximal sechs am Tag.","One every three to four hours, a maximum of six a day."],
  ["B","Darf ich die Tabletten auch nehmen, wenn ich stille?","May I take the tablets if I'm breastfeeding?"],
  ["A","Gut, dass Sie fragen. Dann nehmen Sie lieber diesen Tee und dieses Spray, die sind unbedenklich.","Good that you ask. Then better take this tea and this spray; they're safe."],
  ["B","Danke. Ich habe außerdem ein Rezept für meinen Mann.","Thank you. I also have a prescription for my husband."],
  ["A","Das Medikament haben wir leider nicht da. Wir können es bis heute Nachmittag bestellen.","Unfortunately we don't have that medicine in stock. We can order it for this afternoon."],
  ["B","Das ist in Ordnung. Muss ich etwas zuzahlen?","That's fine. Do I have to pay anything towards it?"],
  ["A","Ja, fünf Euro Zuzahlung. Sie können es ab 16 Uhr abholen.","Yes, a five-euro co-payment. You can collect it from 4 pm."],
  ["B","Super. Dann komme ich nach der Arbeit vorbei.","Great. Then I'll come by after work."]],
 tips:[["Haben Sie etwas gegen …?","Do you have something for …?"],["Wie oft soll ich das nehmen?","How often should I take it?"],["Ich habe ein Rezept.","I have a prescription."],["Muss ich etwas zuzahlen?","Do I have to pay a co-payment?"]]}
];
