/* Everyday conversations for the Gespräche tab.
   Each: title, situation, the two roles and their genders (g: m / f, or
   "me" = the learner's own voice setting), lines [role, German, English]
   and key phrases [German, English]. [Klammern] are placeholders to fill in.
   tools/check-alltag.mjs checks the shape. */
window.GS = [
{id:"kinderarzt", de:"Kinderarzt: Termin für die Tochter", en:"Paediatrician: appointment for your daughter",
 sit:"Ihre Tochter hat seit gestern Fieber und Husten. Sie rufen in der Kinderarztpraxis an.",
 sitEn:"Your daughter has had a fever and a cough since yesterday. You call the paediatric practice.",
 who:{A:"Praxis", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Kinderarztpraxis Dr. Becker, Sie sprechen mit Frau Lang. Was kann ich für Sie tun?","Dr Becker's paediatric practice, you're speaking to Ms Lang. What can I do for you?"],
  ["B","Guten Morgen, mein Name ist [Ihr Name]. Ich möchte gern einen Termin für meine Tochter machen.","Good morning, my name is [your name]. I'd like to make an appointment for my daughter."],
  ["A","Wie alt ist Ihre Tochter, und was fehlt ihr denn?","How old is your daughter, and what's wrong with her?"],
  ["B","Sie ist sechs Jahre alt. Sie hat seit gestern Abend Fieber, fast 39 Grad, und einen starken Husten.","She's six. She has had a fever since last night, almost 39 degrees, and a bad cough."],
  ["A","Isst und trinkt sie noch normal?","Is she still eating and drinking normally?"],
  ["B","Sie trinkt genug, aber sie hat kaum Appetit und ist sehr müde.","She's drinking enough, but she has hardly any appetite and is very tired."],
  ["A","Gut. Waren Sie schon einmal bei uns in der Praxis?","All right. Have you been to our practice before?"],
  ["B","Ja, meine Tochter ist hier Patientin. Sie heißt [Name der Tochter].","Yes, my daughter is a patient here. Her name is [daughter's name]."],
  ["A","Einen Moment, ich schaue nach … Ja, ich habe sie gefunden. Können Sie heute um 11:30 Uhr kommen?","One moment, I'll check … Yes, I've found her. Can you come today at 11:30?"],
  ["B","Ja, das passt. Muss ich etwas mitbringen?","Yes, that works. Do I need to bring anything?"],
  ["A","Bitte bringen Sie die Versichertenkarte und das gelbe Untersuchungsheft mit.","Please bring the insurance card and the yellow check-up booklet."],
  ["B","Alles klar. Und was soll ich tun, wenn das Fieber bis dahin steigt?","All right. And what should I do if the fever goes up before then?"],
  ["A","Geben Sie ihr ein Fiebermittel für Kinder. Wenn es ihr sehr schlecht geht, rufen Sie den Notdienst unter 116 117 an.","Give her a fever medicine for children. If she gets very unwell, call the out-of-hours service on 116 117."],
  ["B","Vielen Dank für Ihre Hilfe. Bis später!","Thank you for your help. See you later!"],
  ["A","Gern geschehen. Gute Besserung für Ihre Tochter!","You're welcome. I hope your daughter gets well soon!"]],
 tips:[["Ich möchte gern einen Termin für meine Tochter machen.","I'd like to make an appointment for my daughter."],["Sie hat seit gestern Fieber.","She has had a fever since yesterday."],["Muss ich etwas mitbringen?","Do I need to bring anything?"],["Gute Besserung!","Get well soon!"]]},

{id:"kardiologe", de:"Facharzt: Brustschmerzen", en:"Specialist: chest pain",
 sit:"Sie haben seit einigen Tagen immer wieder leichte Schmerzen in der Brust. Ihr Hausarzt hat Ihnen eine Überweisung zum Kardiologen gegeben.",
 sitEn:"For a few days you've had recurring mild chest pain. Your GP has given you a referral to a cardiologist.",
 who:{A:"Praxis", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Kardiologische Praxis am Markt, guten Tag.","Cardiology practice am Markt, good afternoon."],
  ["B","Guten Tag, ich habe eine Überweisung von meinem Hausarzt und brauche einen Termin.","Hello, I have a referral from my GP and need an appointment."],
  ["A","Worum geht es denn genau?","What exactly is it about?"],
  ["B","Ich habe seit ungefähr einer Woche immer wieder Schmerzen in der Brust, vor allem beim Treppensteigen.","For about a week I've had recurring pain in my chest, especially when climbing stairs."],
  ["A","Haben Sie die Schmerzen im Moment auch?","Do you have the pain right now as well?"],
  ["B","Nein, im Moment nicht. Sie kommen und gehen.","No, not at the moment. They come and go."],
  ["A","Wichtig: Wenn Sie starke Schmerzen, Atemnot oder Schmerzen im linken Arm haben, rufen Sie sofort den Notruf 112 an.","Important: if you have severe pain, shortness of breath or pain in your left arm, call the emergency number 112 immediately."],
  ["B","Verstanden, das mache ich.","Understood, I'll do that."],
  ["A","Da Sie eine Überweisung haben, kann ich Ihnen einen dringenden Termin geben. Passt Ihnen Donnerstag um 8:15 Uhr?","As you have a referral, I can give you an urgent appointment. Does Thursday at 8:15 suit you?"],
  ["B","Ja, am Donnerstag kann ich. Muss ich nüchtern kommen?","Yes, I can on Thursday. Do I need to come with an empty stomach?"],
  ["A","Nein, das ist nicht nötig. Wir machen ein EKG und einen Ultraschall. Bringen Sie bitte die Überweisung und Ihre Medikamentenliste mit.","No, that's not necessary. We'll do an ECG and an ultrasound. Please bring the referral and your list of medicines."],
  ["B","In Ordnung. Wie lange dauert die Untersuchung ungefähr?","OK. Roughly how long does the examination take?"],
  ["A","Planen Sie etwa eine Stunde ein. Wie ist Ihr Name, bitte?","Allow about an hour. What's your name, please?"],
  ["B","[Ihr Name], ich buchstabiere: [Buchstaben].","[your name], I'll spell it: [letters]."],
  ["A","Danke, der Termin ist eingetragen. Bis Donnerstag!","Thank you, the appointment is booked. See you on Thursday!"]],
 tips:[["Ich habe eine Überweisung von meinem Hausarzt.","I have a referral from my GP."],["Die Schmerzen kommen und gehen.","The pain comes and goes."],["Muss ich nüchtern kommen?","Do I have to come with an empty stomach?"],["Bei starken Schmerzen: Notruf 112.","With severe pain: call 112."]]},

{id:"internet", de:"Internetanbieter: Beschwerde", en:"Internet provider: complaint",
 sit:"Ihr Internet funktioniert seit drei Tagen nicht. Sie arbeiten im Homeoffice und rufen beim Kundenservice an.",
 sitEn:"Your internet hasn't worked for three days. You work from home and call customer service.",
 who:{A:"Kundenservice", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Willkommen beim Kundenservice von NetFix. Mein Name ist Herr Wolf. Wie kann ich Ihnen helfen?","Welcome to NetFix customer service. My name is Mr Wolf. How can I help you?"],
  ["B","Guten Tag. Mein Internet funktioniert seit drei Tagen überhaupt nicht mehr.","Hello. My internet hasn't worked at all for three days."],
  ["A","Das tut mir leid. Nennen Sie mir bitte Ihre Kundennummer.","I'm sorry to hear that. Please give me your customer number."],
  ["B","Meine Kundennummer ist [Nummer].","My customer number is [number]."],
  ["A","Danke. Haben Sie den Router schon einmal neu gestartet?","Thank you. Have you already restarted the router?"],
  ["B","Ja, mehrmals. Die Lampe für das Internet blinkt die ganze Zeit rot.","Yes, several times. The internet light keeps flashing red."],
  ["A","Ich sehe hier, dass es in Ihrer Straße eine Störung gibt. Ein Techniker ist schon informiert.","I can see there's a fault in your street. A technician has already been informed."],
  ["B","Und wann ist das Problem gelöst? Ich arbeite von zu Hause und brauche das Internet dringend.","And when will the problem be fixed? I work from home and urgently need the internet."],
  ["A","Wir rechnen damit, dass die Störung bis morgen Abend behoben ist.","We expect the fault to be fixed by tomorrow evening."],
  ["B","Das ist ärgerlich. Ich bezahle jeden Monat, aber jetzt habe ich vier Tage kein Internet.","That's annoying. I pay every month, but now I'll have no internet for four days."],
  ["A","Das verstehe ich. Sie bekommen für die Tage ohne Internet eine Gutschrift auf Ihrer nächsten Rechnung.","I understand. You'll get a credit on your next bill for the days without internet."],
  ["B","Gut. Können Sie mir das bitte auch schriftlich per E-Mail bestätigen?","Good. Could you also confirm that in writing by email, please?"],
  ["A","Natürlich, Sie bekommen heute noch eine E-Mail. Kann ich sonst noch etwas für Sie tun?","Of course, you'll get an email today. Is there anything else I can do for you?"],
  ["B","Nein, danke. Auf Wiederhören.","No, thank you. Goodbye."]],
 tips:[["Mein Internet funktioniert seit drei Tagen nicht.","My internet hasn't worked for three days."],["Die Lampe blinkt rot.","The light is flashing red."],["Wann ist das Problem gelöst?","When will the problem be fixed?"],["Können Sie mir das schriftlich bestätigen?","Can you confirm that in writing?"]]},

{id:"supermarkt", de:"Im Supermarkt", en:"At the supermarket",
 sit:"Sie suchen im Supermarkt ein Produkt und möchten außerdem etwas umtauschen.",
 sitEn:"You're looking for a product in the supermarket and also want to exchange something.",
 who:{A:"Verkäufer", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["B","Entschuldigung, können Sie mir helfen? Ich finde die glutenfreien Nudeln nicht.","Excuse me, can you help me? I can't find the gluten-free pasta."],
  ["A","Die finden Sie in Gang vier, ganz unten im Regal neben dem Reis.","You'll find them in aisle four, on the bottom shelf next to the rice."],
  ["B","Danke. Und haben Sie auch frisches Brot ohne Weizen?","Thank you. And do you also have fresh bread without wheat?"],
  ["A","Leider nicht. Das bekommen Sie aber in der Bäckerei am Eingang.","Unfortunately not. But you can get it at the bakery by the entrance."],
  ["B","Noch eine Frage: Ich habe gestern diesen Käse gekauft, aber er ist schon abgelaufen.","One more question: I bought this cheese yesterday, but it has already expired."],
  ["A","Oh, das tut mir leid. Haben Sie den Kassenbon dabei?","Oh, I'm sorry. Do you have the receipt with you?"],
  ["B","Ja, hier ist er.","Yes, here it is."],
  ["A","Möchten Sie das Geld zurück oder lieber einen neuen Käse?","Would you like your money back or a new cheese instead?"],
  ["B","Einen neuen, bitte. Aber diesmal mit einem längeren Haltbarkeitsdatum.","A new one, please. But this time with a longer best-before date."],
  ["A","Selbstverständlich. Ich hole Ihnen einen aus dem Lager.","Of course. I'll get you one from the storeroom."],
  ["B","Vielen Dank. Sind die Erdbeeren heute im Angebot?","Thank you very much. Are the strawberries on offer today?"],
  ["A","Ja, 500 Gramm kosten heute nur 1,99 Euro.","Yes, 500 grams only cost 1.99 euros today."],
  ["B","Super, dann nehme ich zwei Schalen. Kann ich an der Kasse auch mit Karte bezahlen?","Great, then I'll take two punnets. Can I also pay by card at the checkout?"],
  ["A","Ja, mit Karte oder mit dem Handy, wie Sie möchten.","Yes, by card or with your phone, as you like."]],
 tips:[["Entschuldigung, wo finde ich …?","Excuse me, where can I find …?"],["Der Käse ist schon abgelaufen.","The cheese has already expired."],["Haben Sie den Kassenbon dabei?","Do you have the receipt with you?"],["Kann ich mit Karte bezahlen?","Can I pay by card?"]]},

{id:"arzt", de:"Beim Arzt: Rückenschmerzen und Verletzung", en:"At the doctor's: back pain and an injury",
 sit:"Sie sind beim Hausarzt. Sie haben starke Rückenschmerzen und haben sich beim Sport den Fuß verletzt.",
 sitEn:"You're at your GP's. You have bad back pain and hurt your foot doing sport.",
 who:{A:"Ärztin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Guten Tag, nehmen Sie bitte Platz. Was führt Sie zu mir?","Hello, please take a seat. What brings you to me?"],
  ["B","Ich habe seit einer Woche starke Rückenschmerzen, vor allem morgens nach dem Aufstehen.","I've had bad back pain for a week, especially in the morning after getting up."],
  ["A","Wo genau tut es weh? Zeigen Sie es mir bitte.","Where exactly does it hurt? Please show me."],
  ["B","Hier unten, im unteren Rücken. Manchmal zieht der Schmerz bis ins Bein.","Down here, in the lower back. Sometimes the pain goes down into my leg."],
  ["A","Sitzen Sie bei der Arbeit viel?","Do you sit a lot at work?"],
  ["B","Ja, acht Stunden am Tag vor dem Computer.","Yes, eight hours a day at the computer."],
  ["A","Das ist oft der Grund. Haben Sie noch andere Beschwerden?","That's often the reason. Do you have any other complaints?"],
  ["B","Ja, ich bin am Samstag beim Fußball umgeknickt. Mein Knöchel ist geschwollen.","Yes, I twisted my ankle playing football on Saturday. My ankle is swollen."],
  ["A","Lassen Sie mich mal sehen … Können Sie den Fuß bewegen?","Let me have a look … Can you move your foot?"],
  ["B","Ja, aber es tut beim Gehen weh.","Yes, but it hurts when I walk."],
  ["A","Ich glaube, er ist nur verstaucht, nicht gebrochen. Zur Sicherheit machen wir aber ein Röntgenbild.","I think it's only sprained, not broken. But to be safe we'll do an X-ray."],
  ["B","Und was kann ich gegen die Rückenschmerzen tun?","And what can I do about the back pain?"],
  ["A","Ich verschreibe Ihnen Physiotherapie und eine Salbe. Bewegen Sie sich regelmäßig und machen Sie Pausen bei der Arbeit.","I'll prescribe physiotherapy and an ointment. Move regularly and take breaks at work."],
  ["B","Brauche ich eine Krankschreibung?","Do I need a sick note?"],
  ["A","Ja, ich schreibe Sie für drei Tage krank. Die Bescheinigung bekommt Ihr Arbeitgeber elektronisch.","Yes, I'll sign you off sick for three days. Your employer gets the certificate electronically."],
  ["B","Vielen Dank, Frau Doktor.","Thank you very much, doctor."]],
 tips:[["Wo genau tut es weh?","Where exactly does it hurt?"],["Ich bin umgeknickt.","I twisted my ankle."],["Der Knöchel ist geschwollen.","The ankle is swollen."],["Brauche ich eine Krankschreibung?","Do I need a sick note?"]]},

{id:"restaurant", de:"Im Restaurant bestellen", en:"Ordering in a restaurant",
 sit:"Sie sind mit einer Freundin im Restaurant. Sie bestellen, haben eine Frage zum Essen und bezahlen.",
 sitEn:"You're in a restaurant with a friend. You order, ask about the food and pay.",
 who:{A:"Kellner", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Guten Abend! Haben Sie reserviert?","Good evening! Do you have a reservation?"],
  ["B","Ja, auf den Namen [Ihr Name], ein Tisch für zwei Personen um 19 Uhr.","Yes, under the name [your name], a table for two at 7 pm."],
  ["A","Sehr schön, folgen Sie mir bitte. Hier ist die Speisekarte. Was möchten Sie trinken?","Very good, please follow me. Here's the menu. What would you like to drink?"],
  ["B","Wir nehmen eine große Flasche Wasser und zwei Apfelschorlen, bitte.","We'll have a large bottle of water and two apple spritzers, please."],
  ["A","Haben Sie schon gewählt?","Have you already decided?"],
  ["B","Fast. Ist in der Gemüsesuppe Fleisch oder Fleischbrühe?","Almost. Is there meat or meat stock in the vegetable soup?"],
  ["A","Nein, die Suppe ist vegetarisch.","No, the soup is vegetarian."],
  ["B","Gut, dann hätte ich gern die Suppe als Vorspeise und danach das Hähnchen mit Reis.","Good, then I'd like the soup as a starter and then the chicken with rice."],
  ["A","Und für Sie?","And for you?"],
  ["B","Meine Freundin nimmt die Pasta mit Tomatensoße, aber bitte ohne Käse.","My friend will have the pasta with tomato sauce, but without cheese, please."],
  ["A","Kein Problem.","No problem."],
  ["B","Entschuldigung, das Hähnchen ist leider nicht richtig warm.","Excuse me, unfortunately the chicken isn't properly hot."],
  ["A","Oh, das tut mir leid. Ich bringe es sofort zurück in die Küche.","Oh, I'm sorry. I'll take it straight back to the kitchen."],
  ["B","Wir möchten bitte zahlen. Getrennt, bitte.","We'd like to pay, please. Separately, please."],
  ["A","Gern. Das macht bei Ihnen 24,50 Euro.","Certainly. That's 24.50 euros for you."],
  ["B","26, bitte. Stimmt so.","26, please. Keep the change."]],
 tips:[["Ein Tisch für zwei Personen, bitte.","A table for two, please."],["Ich hätte gern …","I'd like …"],["Ohne Käse, bitte.","Without cheese, please."],["Wir möchten zahlen. – Getrennt oder zusammen?","We'd like to pay. – Separately or together?"],["Stimmt so.","Keep the change."]]},

{id:"bank", de:"Bei der Bank: Konto eröffnen", en:"At the bank: opening an account",
 sit:"Sie sind neu in Deutschland und möchten ein Girokonto eröffnen.",
 sitEn:"You're new in Germany and want to open a current account.",
 who:{A:"Bankberaterin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Guten Tag, was kann ich für Sie tun?","Hello, what can I do for you?"],
  ["B","Guten Tag, ich möchte ein Girokonto eröffnen. Ich habe vor zwei Monaten eine Stelle hier angefangen.","Hello, I'd like to open a current account. I started a job here two months ago."],
  ["A","Gern. Haben Sie Ihren Pass und Ihre Meldebescheinigung dabei?","Certainly. Do you have your passport and your registration certificate with you?"],
  ["B","Ja, hier sind beide. Brauchen Sie auch meinen Aufenthaltstitel?","Yes, here are both. Do you also need my residence permit?"],
  ["A","Ja, bitte, und Ihre Steuer-Identifikationsnummer.","Yes, please, and your tax ID number."],
  ["B","Die habe ich auf diesem Brief vom Finanzamt.","I have it on this letter from the tax office."],
  ["A","Sehr gut. Wir haben zwei Kontomodelle. Das Online-Konto ist kostenlos, beim Konto mit Filialservice zahlen Sie fünf Euro im Monat.","Very good. We have two account types. The online account is free; with the branch-service account you pay five euros a month."],
  ["B","Ich nehme das Online-Konto. Bekomme ich auch eine Karte?","I'll take the online account. Do I get a card too?"],
  ["A","Ja, Sie bekommen eine Debitkarte. Die Karte und die PIN kommen in zwei getrennten Briefen.","Yes, you'll get a debit card. The card and the PIN come in two separate letters."],
  ["B","Wie lange dauert das ungefähr?","Roughly how long does that take?"],
  ["A","Etwa eine Woche. Ihre IBAN bekommen Sie aber heute schon, dann können Sie sie Ihrem Arbeitgeber geben.","About a week. But you'll get your IBAN today, so you can give it to your employer."],
  ["B","Perfekt. Kann ich auch die Miete per Dauerauftrag bezahlen?","Perfect. Can I also pay the rent by standing order?"],
  ["A","Natürlich, das können Sie im Online-Banking selbst einrichten.","Of course, you can set that up yourself in online banking."],
  ["B","Vielen Dank für die Beratung.","Thank you for the advice."]],
 tips:[["Ich möchte ein Girokonto eröffnen.","I'd like to open a current account."],["Meldebescheinigung, Aufenthaltstitel, Steuer-ID","registration certificate, residence permit, tax ID"],["Die Karte und die PIN kommen getrennt.","The card and PIN come separately."],["Kann ich einen Dauerauftrag einrichten?","Can I set up a standing order?"]]},

{id:"bahn", de:"Am DB-Schalter: Fahrkarte kaufen", en:"At the DB counter: buying a ticket",
 sit:"Sie möchten am Freitag mit dem Zug von Frankfurt nach Hamburg fahren und am Sonntag zurück.",
 sitEn:"You want to travel by train from Frankfurt to Hamburg on Friday and back on Sunday.",
 who:{A:"Bahnmitarbeiter", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Guten Tag, wohin möchten Sie fahren?","Hello, where would you like to go?"],
  ["B","Ich möchte eine Fahrkarte nach Hamburg, hin und zurück, bitte.","I'd like a return ticket to Hamburg, please."],
  ["A","Wann möchten Sie fahren?","When would you like to travel?"],
  ["B","Am Freitag, am liebsten am Nachmittag, und am Sonntagabend zurück.","On Friday, preferably in the afternoon, and back on Sunday evening."],
  ["A","Es gibt einen ICE um 14:52 Uhr. Er fährt direkt, Sie sind um 18:36 Uhr in Hamburg.","There's an ICE at 14:52. It's direct; you'll be in Hamburg at 18:36."],
  ["B","Das passt gut. Und zurück?","That works well. And back?"],
  ["A","Am Sonntag um 17:05 Uhr ab Hamburg Hauptbahnhof, mit einmal Umsteigen in Hannover.","On Sunday at 17:05 from Hamburg main station, with one change in Hanover."],
  ["B","Gibt es auch eine direkte Verbindung?","Is there a direct connection too?"],
  ["A","Ja, um 18:01 Uhr, dann sind Sie um 21:40 Uhr in Frankfurt.","Yes, at 18:01, then you'll be in Frankfurt at 21:40."],
  ["B","Die nehme ich. Was kostet das?","I'll take that one. How much is it?"],
  ["A","Mit dem Sparpreis 79,80 Euro für beide Fahrten. Haben Sie eine BahnCard?","With the saver fare 79.80 euros for both journeys. Do you have a BahnCard?"],
  ["B","Nein. Kann ich den Sparpreis stornieren, wenn ich nicht fahren kann?","No. Can I cancel the saver fare if I can't travel?"],
  ["A","Ja, bis einen Tag vorher, aber es kostet eine Gebühr von zehn Euro.","Yes, up to one day before, but there's a fee of ten euros."],
  ["B","In Ordnung. Ich möchte auch einen Sitzplatz reservieren, am Fenster, bitte.","OK. I'd also like to reserve a seat, by the window, please."],
  ["A","Gern. Wagen 7, Platz 45 hin und Wagen 5, Platz 12 zurück. Hier ist Ihre Fahrkarte.","Certainly. Coach 7, seat 45 there and coach 5, seat 12 back. Here's your ticket."]],
 tips:[["Eine Fahrkarte nach …, hin und zurück, bitte.","A return ticket to …, please."],["Muss ich umsteigen? – Gibt es eine direkte Verbindung?","Do I have to change? – Is there a direct connection?"],["Ich möchte einen Sitzplatz reservieren.","I'd like to reserve a seat."],["Kann ich die Fahrkarte stornieren?","Can I cancel the ticket?"]]},

{id:"auslaenderbehoerde", de:"Ausländerbehörde: Termin absagen", en:"Immigration office: cancelling an appointment",
 sit:"Sie haben einen Termin bei der Ausländerbehörde, können aber nicht kommen, weil Ihr Kind krank ist. Sie rufen an.",
 sitEn:"You have an appointment at the immigration office but can't come because your child is ill. You call.",
 who:{A:"Behörde", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Ausländerbehörde Frankfurt, Frau Schulz. Guten Morgen.","Frankfurt immigration office, Ms Schulz. Good morning."],
  ["B","Guten Morgen. Ich habe morgen um 9 Uhr einen Termin, aber leider kann ich nicht kommen.","Good morning. I have an appointment tomorrow at 9, but unfortunately I can't come."],
  ["A","Wie ist Ihr Name und Ihr Geburtsdatum?","What's your name and date of birth?"],
  ["B","[Ihr Name], geboren am [Datum].","[your name], born on [date]."],
  ["A","Danke. Worum geht es bei dem Termin?","Thank you. What is the appointment about?"],
  ["B","Um die Verlängerung meines Aufenthaltstitels. Mein Titel ist noch bis Ende nächsten Monats gültig.","About extending my residence permit. My permit is valid until the end of next month."],
  ["A","Darf ich fragen, warum Sie nicht kommen können?","May I ask why you can't come?"],
  ["B","Mein Sohn ist krank und ich muss zu Hause bleiben. Das tut mir sehr leid.","My son is ill and I have to stay at home. I'm very sorry."],
  ["A","Kein Problem, gut, dass Sie anrufen. Ich sage den Termin ab. Möchten Sie gleich einen neuen?","No problem, it's good that you called. I'll cancel the appointment. Would you like a new one straight away?"],
  ["B","Ja, bitte. Ist es wichtig, dass der neue Termin vor dem Ablauf meines Titels ist?","Yes, please. Is it important that the new appointment is before my permit expires?"],
  ["A","Ja. Ich gebe Ihnen einen Termin in zwei Wochen, am Dienstag, den 14., um 10:30 Uhr.","Yes. I'll give you an appointment in two weeks, on Tuesday the 14th, at 10:30."],
  ["B","Das passt. Muss ich die Unterlagen noch einmal schicken?","That works. Do I have to send the documents again?"],
  ["A","Nein, bringen Sie einfach alles zum Termin mit: Pass, biometrisches Foto, Arbeitsvertrag und Mietvertrag.","No, just bring everything to the appointment: passport, biometric photo, employment contract and rental contract."],
  ["B","Bekomme ich eine Bestätigung?","Will I get a confirmation?"],
  ["A","Ja, per E-Mail. Gute Besserung für Ihren Sohn!","Yes, by email. I hope your son gets better soon!"]],
 tips:[["Ich kann leider nicht zum Termin kommen.","Unfortunately I can't come to the appointment."],["Ich möchte den Termin absagen / verschieben.","I'd like to cancel / postpone the appointment."],["die Verlängerung meines Aufenthaltstitels","the extension of my residence permit"],["Bekomme ich eine Bestätigung?","Will I get a confirmation?"]]},

{id:"aktien", de:"Zwei Freunde: Aktien und Sparen", en:"Two friends: shares and saving",
 sit:"Zwei Freunde sprechen in der Mittagspause über Geld, Sparen und die Börse.",
 sitEn:"Two friends talk about money, saving and the stock market during their lunch break.",
 who:{A:"Daniel", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Sag mal, legst du eigentlich Geld an, oder liegt alles auf dem Sparkonto?","Tell me, do you actually invest money, or is it all in a savings account?"],
  ["B","Ich habe vor einem Jahr angefangen, jeden Monat etwas in einen ETF zu investieren.","A year ago I started investing something in an ETF every month."],
  ["A","Ein ETF? Was ist das genau?","An ETF? What exactly is that?"],
  ["B","Das ist ein Fonds, der viele Aktien auf einmal enthält, zum Beispiel von Firmen aus der ganzen Welt.","It's a fund that contains lots of shares at once, for example from companies all over the world."],
  ["A","Und ist das nicht riskant? Letzte Woche sind die Kurse ziemlich stark gefallen.","And isn't that risky? Last week prices fell quite sharply."],
  ["B","Kurzfristig schon, die Kurse steigen und fallen. Aber ich will das Geld erst in zwanzig Jahren benutzen.","In the short term, yes, prices go up and down. But I don't want to use the money for another twenty years."],
  ["A","Ich habe mal einzelne Aktien gekauft und viel verloren. Seitdem bin ich vorsichtig.","I once bought individual shares and lost a lot. Since then I've been careful."],
  ["B","Das verstehe ich. Deshalb kaufe ich keine einzelnen Aktien, sondern verteile das Risiko.","I understand. That's why I don't buy individual shares but spread the risk."],
  ["A","Wie viel legst du denn jeden Monat an, wenn ich fragen darf?","How much do you invest each month, if I may ask?"],
  ["B","Nur einen kleinen Betrag. Wichtig ist, dass man immer ein Notfallpolster auf dem Konto hat.","Only a small amount. The important thing is to always keep an emergency cushion in your account."],
  ["A","Stimmt. Und wo hast du dein Depot eröffnet?","True. And where did you open your securities account?"],
  ["B","Bei einer Online-Bank. Aber ich bin kein Experte – lass dich am besten neutral beraten.","At an online bank. But I'm no expert – it's best to get neutral advice."],
  ["A","Gute Idee. Vielleicht gehe ich mal zur Verbraucherzentrale.","Good idea. Maybe I'll go to the consumer advice centre."],
  ["B","Mach das. Und jetzt lass uns lieber essen, bevor die Pause vorbei ist!","Do that. And now let's eat before the break is over!"]],
 tips:[["Geld anlegen / investieren","to invest money"],["Die Kurse steigen / fallen.","Prices are rising / falling."],["das Risiko verteilen","to spread the risk"],["Lass dich neutral beraten.","Get neutral advice."]]},

{id:"vermieter", de:"Vermieter anrufen: Heizung kaputt", en:"Calling the landlord: heating broken",
 sit:"Es ist Januar und Ihre Heizung funktioniert nicht. Sie rufen Ihren Vermieter an.",
 sitEn:"It's January and your heating isn't working. You call your landlord.",
 who:{A:"Vermieter", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Hausverwaltung Keller, guten Tag.","Keller property management, good afternoon."],
  ["B","Guten Tag, hier ist [Ihr Name] aus der Goethestraße 12, zweiter Stock. Meine Heizung ist kaputt.","Hello, this is [your name] from Goethestraße 12, second floor. My heating is broken."],
  ["A","Seit wann funktioniert sie nicht?","Since when hasn't it been working?"],
  ["B","Seit gestern Abend. Die Heizkörper bleiben kalt, und auch das Wasser ist nur lauwarm.","Since last night. The radiators stay cold, and the water is only lukewarm too."],
  ["A","Haben Sie schon nachgesehen, ob das Ventil aufgedreht ist?","Have you checked whether the valve is turned on?"],
  ["B","Ja, alles ist auf Stufe fünf. Meine Nachbarn haben das gleiche Problem.","Yes, everything is on level five. My neighbours have the same problem."],
  ["A","Dann liegt es wahrscheinlich an der Heizungsanlage im Keller. Ich schicke heute noch einen Techniker.","Then it's probably the heating system in the basement. I'll send a technician today."],
  ["B","Wann ungefähr kommt er? Ich muss um 15 Uhr meine Kinder abholen.","Roughly when will he come? I have to pick up my children at 3 pm."],
  ["A","Er kommt zwischen 12 und 14 Uhr. Wenn Sie nicht da sind, kann er auch zuerst in den Keller gehen.","He'll come between 12 and 2. If you're not there, he can go to the basement first."],
  ["B","Gut. Und was mache ich, wenn es heute Abend immer noch nicht funktioniert?","Good. And what do I do if it still isn't working this evening?"],
  ["A","Dann rufen Sie bitte den Notdienst an, die Nummer hängt im Treppenhaus.","Then please call the emergency service; the number is on the wall in the stairwell."],
  ["B","Könnten Sie mir bitte auch ein kleines Heizgerät leihen? Meine Tochter ist erst zwei.","Could you also lend me a small heater? My daughter is only two."],
  ["A","Natürlich, der Techniker bringt eins mit.","Of course, the technician will bring one."],
  ["B","Vielen Dank für die schnelle Hilfe.","Thank you for the quick help."]],
 tips:[["Meine Heizung ist kaputt.","My heating is broken."],["Die Heizkörper bleiben kalt.","The radiators stay cold."],["Wann kommt der Techniker?","When will the technician come?"],["Die Nummer vom Notdienst","the number of the emergency service"]]},

{id:"apotheke", de:"In der Apotheke", en:"At the pharmacy",
 sit:"Sie sind erkältet und gehen in die Apotheke. Sie haben auch ein Rezept für Ihren Mann.",
 sitEn:"You have a cold and go to the pharmacy. You also have a prescription for your husband.",
 who:{A:"Apothekerin", B:"Sie"}, g:{A:"f", B:"f"},
 lines:[
  ["A","Guten Tag, was darf es sein?","Hello, what can I get you?"],
  ["B","Guten Tag, ich habe eine starke Erkältung. Haben Sie etwas gegen Halsschmerzen und Schnupfen?","Hello, I have a bad cold. Do you have something for a sore throat and a runny nose?"],
  ["A","Haben Sie auch Fieber?","Do you have a fever too?"],
  ["B","Nein, nur Halsschmerzen, Schnupfen und ein bisschen Husten.","No, just a sore throat, a runny nose and a bit of a cough."],
  ["A","Dann empfehle ich Ihnen diese Lutschtabletten und ein Nasenspray. Nehmen Sie das Spray aber höchstens eine Woche.","Then I recommend these lozenges and a nasal spray. But don't use the spray for more than a week."],
  ["B","Wie oft soll ich die Tabletten nehmen?","How often should I take the tablets?"],
  ["A","Alle drei bis vier Stunden eine, maximal sechs am Tag.","One every three to four hours, a maximum of six a day."],
  ["B","Darf ich die Tabletten auch nehmen, wenn ich stille?","May I take the tablets if I'm breastfeeding?"],
  ["A","Gut, dass Sie fragen. Dann nehmen Sie lieber diesen Tee und dieses Spray, die sind unbedenklich.","Good that you ask. Then better take this tea and this spray; they're safe."],
  ["B","Danke. Ich habe außerdem ein Rezept für meinen Mann.","Thank you. I also have a prescription for my husband."],
  ["A","Das Medikament haben wir leider nicht da. Wir können es bis heute Nachmittag bestellen.","Unfortunately we don't have that medicine in stock. We can order it for this afternoon."],
  ["B","Das ist in Ordnung. Muss ich etwas zuzahlen?","That's fine. Do I have to pay anything towards it?"],
  ["A","Ja, fünf Euro Zuzahlung. Sie können es ab 16 Uhr abholen.","Yes, a five-euro co-payment. You can collect it from 4 pm."],
  ["B","Super. Dann komme ich nach der Arbeit vorbei.","Great. Then I'll come by after work."]],
 tips:[["Haben Sie etwas gegen …?","Do you have something for …?"],["Wie oft soll ich das nehmen?","How often should I take it?"],["Ich habe ein Rezept.","I have a prescription."],["Muss ich etwas zuzahlen?","Do I have to pay a co-payment?"]]},

{id:"buergeramt", de:"Bürgeramt: Wohnung anmelden", en:"Citizens' office: registering your address",
 sit:"Sie sind in eine neue Wohnung gezogen und müssen sich innerhalb von zwei Wochen beim Bürgeramt anmelden.",
 sitEn:"You've moved into a new flat and must register at the citizens' office within two weeks.",
 who:{A:"Sachbearbeiter", B:"Sie"}, g:{A:"m", B:"m"},
 lines:[
  ["A","Guten Tag, Ihre Wartenummer war die 47? Bitte setzen Sie sich. Was ist Ihr Anliegen?","Hello, your number was 47? Please sit down. What can I do for you?"],
  ["B","Guten Tag. Ich bin umgezogen und möchte meine neue Adresse anmelden.","Hello. I've moved and would like to register my new address."],
  ["A","Haben Sie das Anmeldeformular schon ausgefüllt?","Have you already filled in the registration form?"],
  ["B","Ja, hier ist es. Und hier sind mein Pass und die Wohnungsgeberbestätigung von meinem Vermieter.","Yes, here it is. And here are my passport and the landlord's confirmation from my landlord."],
  ["A","Sehr gut. Ziehen Sie allein ein oder mit Familie?","Very good. Are you moving in alone or with family?"],
  ["B","Mit meiner Frau [Name der Ehefrau] und unserem Sohn. Meine Frau kommt nächste Woche selbst vorbei.","With my wife [wife's name] and our son. My wife will come in herself next week."],
  ["A","Das ist nicht nötig. Wenn Sie ihre Ausweise dabeihaben, kann ich alle drei gleichzeitig anmelden.","That's not necessary. If you have their ID documents with you, I can register all three at once."],
  ["B","Oh, das wusste ich nicht. Ich habe leider nur Kopien dabei.","Oh, I didn't know that. Unfortunately I only have copies with me."],
  ["A","Dann melde ich heute nur Sie an. Ihre Frau braucht die Originale, am besten mit einem Termin.","Then today I'll only register you. Your wife needs the originals, ideally with an appointment."],
  ["B","In Ordnung. Muss ich meine neue Adresse auch in den Aufenthaltstitel eintragen lassen?","OK. Do I also need to have my new address entered on my residence permit?"],
  ["A","Ja, ich schreibe Ihnen einen Aufkleber mit der neuen Adresse. Geben Sie mir bitte kurz Ihre Karte.","Yes, I'll give you a sticker with the new address. Please hand me your card for a moment."],
  ["B","Hier, bitte. Kostet die Anmeldung etwas?","Here you are. Does the registration cost anything?"],
  ["A","Nein, die Anmeldung ist kostenlos. Hier ist Ihre Meldebescheinigung – bitte gut aufbewahren.","No, registration is free. Here is your registration certificate – please keep it safe."],
  ["B","Vielen Dank. Die brauche ich bestimmt für die Bank und die Krankenkasse.","Thank you. I'm sure I'll need it for the bank and the health insurer."],
  ["A","Genau. Einen schönen Tag noch!","Exactly. Have a nice day!"]],
 tips:[["Ich möchte meine neue Adresse anmelden.","I'd like to register my new address."],["die Wohnungsgeberbestätigung","the landlord's confirmation of residence"],["die Meldebescheinigung","the registration certificate"],["Kostet das etwas? – Das ist kostenlos.","Does that cost anything? – It's free."]]},

{id:"bewerbung", de:"Vorstellungsgespräch", en:"Job interview",
 sit:"Sie haben sich als Verkäufer / Verkäuferin in einem Elektronikgeschäft beworben und sind zum Vorstellungsgespräch eingeladen.",
 sitEn:"You've applied for a job as a sales assistant in an electronics shop and have been invited to an interview.",
 who:{A:"Filialleiterin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Schön, dass Sie da sind. Erzählen Sie doch bitte kurz etwas über sich.","Nice to have you here. Please tell me a little about yourself."],
  ["B","Gern. Ich komme aus [Land] und lebe seit vier Jahren in Deutschland. Ich habe drei Jahre in einem Handygeschäft gearbeitet.","Sure. I come from [country] and have lived in Germany for four years. I worked in a mobile phone shop for three years."],
  ["A","Warum möchten Sie bei uns arbeiten?","Why would you like to work for us?"],
  ["B","Ich interessiere mich sehr für Technik und berate gern Kunden. Außerdem hat Ihre Firma einen sehr guten Ruf.","I'm very interested in technology and I enjoy advising customers. Your company also has a very good reputation."],
  ["A","Was sind Ihre Stärken?","What are your strengths?"],
  ["B","Ich bin freundlich, geduldig und arbeite gern im Team. Ich spreche außerdem Englisch und Arabisch.","I'm friendly, patient and like working in a team. I also speak English and Arabic."],
  ["A","Und Ihre Schwächen?","And your weaknesses?"],
  ["B","Manchmal bin ich zu perfektionistisch. Aber ich habe gelernt, Prioritäten zu setzen.","Sometimes I'm too much of a perfectionist. But I've learned to set priorities."],
  ["A","Bei uns arbeitet man auch samstags. Ist das ein Problem für Sie?","With us you also work on Saturdays. Is that a problem for you?"],
  ["B","Nein, das ist kein Problem. Ich bin flexibel.","No, that's not a problem. I'm flexible."],
  ["A","Haben Sie noch Fragen an uns?","Do you have any questions for us?"],
  ["B","Ja. Wie sieht die Einarbeitung aus, und gibt es Möglichkeiten zur Weiterbildung?","Yes. What does the induction look like, and are there opportunities for further training?"],
  ["A","In den ersten zwei Wochen arbeiten Sie mit einem erfahrenen Kollegen zusammen. Und wir bieten regelmäßig Schulungen an.","For the first two weeks you'll work together with an experienced colleague. And we offer training regularly."],
  ["B","Das klingt sehr gut.","That sounds very good."],
  ["A","Wir melden uns bis Ende nächster Woche bei Ihnen. Vielen Dank für das Gespräch.","We'll get back to you by the end of next week. Thank you for the interview."],
  ["B","Ich bedanke mich auch. Auf Wiedersehen!","Thank you too. Goodbye!"]],
 tips:[["Erzählen Sie etwas über sich.","Tell me about yourself."],["Meine Stärken sind …","My strengths are …"],["Ich bin flexibel.","I'm flexible."],["Wie sieht die Einarbeitung aus?","What does the induction look like?"]]},

{id:"elterngespraech", de:"Elterngespräch mit der Lehrerin", en:"Parent-teacher meeting",
 sit:"Die Lehrerin Ihres Sohnes hat Sie zu einem Gespräch eingeladen, weil er in Mathe Probleme hat.",
 sitEn:"Your son's teacher has invited you to a meeting because he's having problems in maths.",
 who:{A:"Lehrerin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Vielen Dank, dass Sie gekommen sind. Ich wollte mit Ihnen über Leon sprechen.","Thank you for coming. I wanted to talk to you about Leon."],
  ["B","Gern. Gibt es ein Problem?","Of course. Is there a problem?"],
  ["A","Leon ist ein freundlicher Junge und arbeitet im Unterricht gut mit. Aber in Mathe sind seine Noten in letzter Zeit schlechter geworden.","Leon is a friendly boy and joins in well in class. But his maths marks have got worse recently."],
  ["B","Das habe ich auch gemerkt. Zu Hause sagt er, dass er die Aufgaben nicht versteht.","I've noticed that too. At home he says he doesn't understand the exercises."],
  ["A","Vor allem das Rechnen mit Brüchen fällt ihm schwer. Macht er seine Hausaufgaben regelmäßig?","He finds calculating with fractions particularly hard. Does he do his homework regularly?"],
  ["B","Meistens ja, aber ich kann ihm in Mathe leider nicht gut helfen, weil ich es auf Deutsch anders gelernt habe.","Mostly, yes, but unfortunately I can't help him well in maths because I learned it differently."],
  ["A","Das verstehe ich. Unsere Schule bietet dienstags und donnerstags eine kostenlose Hausaufgabenhilfe an.","I understand. Our school offers free homework help on Tuesdays and Thursdays."],
  ["B","Das wusste ich nicht. Wie kann ich ihn anmelden?","I didn't know that. How can I sign him up?"],
  ["A","Ich gebe Ihnen das Formular mit. Sie können es unterschrieben wieder mitgeben.","I'll give you the form. You can send it back signed."],
  ["B","Sehr gut. Kann ich zu Hause noch etwas tun?","Very good. Is there anything else I can do at home?"],
  ["A","Es hilft, wenn er jeden Tag zehn Minuten übt. Ich empfehle Ihnen eine kostenlose Lern-App.","It helps if he practises for ten minutes every day. I recommend a free learning app."],
  ["B","Das machen wir. Wann können wir wieder sprechen?","We'll do that. When can we talk again?"],
  ["A","In sechs Wochen, dann sehen wir, ob es besser geworden ist.","In six weeks; then we'll see if it has got better."],
  ["B","Vielen Dank für Ihre Hilfe und Ihre Zeit.","Thank you for your help and your time."]],
 tips:[["Ich wollte mit Ihnen über … sprechen.","I wanted to talk to you about …"],["… fällt ihm schwer.","He finds … difficult."],["Wie kann ich ihn anmelden?","How can I sign him up?"],["Kann ich zu Hause noch etwas tun?","Is there anything else I can do at home?"]]},

{id:"friseur", de:"Beim Friseur", en:"At the hairdresser's",
 sit:"Sie haben einen Termin beim Friseur und erklären, wie Sie Ihre Haare haben möchten.",
 sitEn:"You have an appointment at the hairdresser's and explain how you'd like your hair.",
 who:{A:"Friseurin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Hallo, Sie haben um 16 Uhr einen Termin, richtig? Was darf es heute sein?","Hello, you have an appointment at 4 pm, right? What would you like today?"],
  ["B","Genau. Ich möchte die Haare schneiden lassen, aber nicht zu kurz.","That's right. I'd like a haircut, but not too short."],
  ["A","Wie viel soll ab? Ungefähr so viel?","How much should come off? About this much?"],
  ["B","Nein, etwas weniger, vielleicht drei Zentimeter. An den Seiten darf es kürzer sein.","No, a bit less, maybe three centimetres. It can be shorter at the sides."],
  ["A","Möchten Sie die Haare vorher waschen lassen?","Would you like your hair washed first?"],
  ["B","Ja, gern. Was kostet das zusammen?","Yes, please. How much is that altogether?"],
  ["A","Waschen, Schneiden und Föhnen kosten 38 Euro.","Washing, cutting and blow-drying costs 38 euros."],
  ["B","In Ordnung.","OK."],
  ["A","Ist das Wasser so angenehm?","Is the water temperature OK?"],
  ["B","Etwas wärmer, bitte.","A bit warmer, please."],
  ["A","So, schauen Sie mal in den Spiegel. Gefällt es Ihnen?","There, have a look in the mirror. Do you like it?"],
  ["B","Hinten ist es super, aber vorne ist es mir noch etwas zu lang.","It's great at the back, but at the front it's still a bit too long for me."],
  ["A","Kein Problem, ich schneide noch ein bisschen nach … Besser so?","No problem, I'll trim a bit more … Better like this?"],
  ["B","Ja, perfekt! Kann ich gleich einen neuen Termin in sechs Wochen machen?","Yes, perfect! Can I make a new appointment for six weeks' time right away?"],
  ["A","Gern, am Dienstag, den 12., wieder um 16 Uhr?","Sure – Tuesday the 12th, again at 4 pm?"],
  ["B","Ja, das passt. Danke schön!","Yes, that works. Thank you!"]],
 tips:[["Ich möchte die Haare schneiden lassen.","I'd like a haircut."],["Nicht zu kurz, bitte.","Not too short, please."],["Vorne ist es mir noch zu lang.","It's still too long at the front for me."],["Kann ich gleich einen neuen Termin machen?","Can I make a new appointment right away?"]]},

{id:"werkstatt", de:"In der Autowerkstatt", en:"At the car garage",
 sit:"Ihr Auto macht beim Bremsen komische Geräusche. Sie bringen es in die Werkstatt.",
 sitEn:"Your car makes strange noises when braking. You take it to the garage.",
 who:{A:"Mechaniker", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Guten Morgen, was kann ich für Sie tun?","Good morning, what can I do for you?"],
  ["B","Guten Morgen. Mein Auto quietscht seit ein paar Tagen, wenn ich bremse.","Good morning. My car has been squeaking for a few days when I brake."],
  ["A","Wann war der letzte Service?","When was the last service?"],
  ["B","Vor ungefähr eineinhalb Jahren. Die Inspektion ist also auch bald fällig.","About a year and a half ago. So the inspection is also due soon."],
  ["A","Dann machen wir am besten beides. Wahrscheinlich müssen die Bremsbeläge gewechselt werden.","Then it's best to do both. The brake pads probably need to be changed."],
  ["B","Was würde das ungefähr kosten?","Roughly how much would that cost?"],
  ["A","Die Inspektion kostet 190 Euro, die Bremsbeläge vorne etwa 150 Euro mit Arbeit.","The inspection costs 190 euros, the front brake pads about 150 euros including labour."],
  ["B","Können Sie mich bitte anrufen, bevor Sie noch etwas anderes reparieren?","Could you please call me before you repair anything else?"],
  ["A","Natürlich, ohne Ihr Okay machen wir nichts. Wann brauchen Sie das Auto wieder?","Of course, we won't do anything without your OK. When do you need the car back?"],
  ["B","Am liebsten heute Abend, ich brauche es morgen für die Arbeit.","Ideally this evening; I need it for work tomorrow."],
  ["A","Das schaffen wir. Sie können es ab 17 Uhr abholen.","We can manage that. You can pick it up from 5 pm."],
  ["B","Gibt es hier in der Nähe eine Bushaltestelle?","Is there a bus stop near here?"],
  ["A","Ja, gleich an der Ecke. Die Linie 30 fährt in die Stadt.","Yes, right on the corner. Line 30 goes into town."],
  ["B","Super, dann bis heute Abend.","Great, see you this evening then."]],
 tips:[["Mein Auto quietscht, wenn ich bremse.","My car squeaks when I brake."],["Die Inspektion ist fällig.","The inspection is due."],["Was würde das ungefähr kosten?","Roughly how much would that cost?"],["Bitte rufen Sie mich vorher an.","Please call me beforehand."]]},

{id:"umtausch", de:"Kleidung umtauschen", en:"Exchanging clothes",
 sit:"Sie haben letzte Woche eine Jacke gekauft. Sie ist zu klein, und ein Knopf ist lose. Sie gehen zurück in das Geschäft.",
 sitEn:"Last week you bought a jacket. It's too small and a button is loose. You go back to the shop.",
 who:{A:"Verkäuferin", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["B","Guten Tag, ich möchte diese Jacke umtauschen.","Hello, I'd like to exchange this jacket."],
  ["A","Gern. Was ist denn das Problem?","Certainly. What's the problem?"],
  ["B","Sie ist mir zu eng, und außerdem ist dieser Knopf schon lose.","It's too tight for me, and this button is already loose too."],
  ["A","Oh, das tut mir leid. Haben Sie den Kassenbon?","Oh, I'm sorry. Do you have the receipt?"],
  ["B","Ja, hier. Ich habe sie letzten Samstag gekauft.","Yes, here. I bought it last Saturday."],
  ["A","Danke. Möchten Sie dieselbe Jacke eine Nummer größer?","Thank you. Would you like the same jacket one size bigger?"],
  ["B","Ja, in Größe L, wenn Sie sie haben.","Yes, in size L, if you have it."],
  ["A","Einen Moment … In Blau haben wir sie leider nur noch in M. In Schwarz gibt es sie in L.","One moment … Unfortunately we only have it in M in blue. In black it's available in L."],
  ["B","Hm, Schwarz gefällt mir nicht so gut. Kann ich die blaue in L bestellen?","Hmm, I don't like black so much. Can I order the blue one in L?"],
  ["A","Ja, das dauert drei bis vier Tage. Oder möchten Sie lieber Ihr Geld zurück?","Yes, that takes three to four days. Or would you prefer your money back?"],
  ["B","Nein, ich bestelle sie. Muss ich dann noch einmal bezahlen?","No, I'll order it. Do I have to pay again then?"],
  ["A","Nein, der Preis ist gleich. Sie bekommen eine SMS, wenn die Jacke da ist.","No, the price is the same. You'll get a text message when the jacket arrives."],
  ["B","Perfekt, vielen Dank.","Perfect, thank you very much."]],
 tips:[["Ich möchte diese Jacke umtauschen.","I'd like to exchange this jacket."],["Sie ist mir zu eng / zu groß.","It's too tight / too big for me."],["Haben Sie sie eine Nummer größer?","Do you have it one size bigger?"],["Ich möchte lieber mein Geld zurück.","I'd prefer my money back."]]},

{id:"besichtigung", de:"Wohnungsbesichtigung", en:"Flat viewing",
 sit:"Sie besichtigen eine Drei-Zimmer-Wohnung und stellen dem Makler Fragen.",
 sitEn:"You're viewing a three-room flat and ask the estate agent questions.",
 who:{A:"Makler", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Herzlich willkommen! Kommen Sie rein. Das hier ist das Wohnzimmer, es hat 25 Quadratmeter.","Welcome! Come in. This is the living room; it's 25 square metres."],
  ["B","Oh, das ist schön hell. In welche Richtung zeigen die Fenster?","Oh, it's nice and bright. Which direction do the windows face?"],
  ["A","Nach Süden, und hier ist auch der Balkon.","South, and here's the balcony too."],
  ["B","Wie hoch ist die Miete genau?","How much exactly is the rent?"],
  ["A","Die Kaltmiete beträgt 980 Euro, dazu kommen 220 Euro Nebenkosten.","The basic rent is 980 euros, plus 220 euros in service charges."],
  ["B","Sind die Heizkosten in den Nebenkosten schon enthalten?","Are the heating costs already included in the service charges?"],
  ["A","Ja, Heizung und Wasser sind enthalten, Strom und Internet nicht.","Yes, heating and water are included; electricity and internet aren't."],
  ["B","Und wie hoch ist die Kaution?","And how much is the deposit?"],
  ["A","Drei Kaltmieten, also 2.940 Euro.","Three months' basic rent, so 2,940 euros."],
  ["B","Gibt es einen Keller oder einen Platz für Fahrräder?","Is there a cellar or a space for bikes?"],
  ["A","Ja, zur Wohnung gehört ein Kellerraum, und im Hof gibt es Fahrradständer.","Yes, a cellar room belongs to the flat, and there are bike racks in the courtyard."],
  ["B","Ab wann ist die Wohnung frei?","From when is the flat available?"],
  ["A","Ab dem 1. November. Wenn Sie Interesse haben, brauche ich eine Selbstauskunft und die letzten drei Gehaltsnachweise.","From 1 November. If you're interested, I need a tenant self-disclosure form and your last three pay slips."],
  ["B","Das schicke ich Ihnen gern bis morgen per E-Mail.","I'll gladly send you that by email by tomorrow."],
  ["A","Sehr gut. Sie hören dann bis Ende der Woche von mir.","Very good. You'll hear from me by the end of the week."]],
 tips:[["Wie hoch ist die Miete?","How much is the rent?"],["Kaltmiete / Nebenkosten / Kaution","basic rent / service charges / deposit"],["Ab wann ist die Wohnung frei?","From when is the flat available?"],["Sind die Heizkosten enthalten?","Are heating costs included?"]]},

{id:"nachbar", de:"Nachbar: Lärm und ein Paket", en:"Neighbour: noise and a parcel",
 sit:"Ihr neuer Nachbar klingelt, weil er ein Paket für Sie angenommen hat. Sie sprechen auch über den Lärm am Abend.",
 sitEn:"Your new neighbour rings the bell because he has taken in a parcel for you. You also talk about the noise in the evening.",
 who:{A:"Nachbar", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Hallo! Ich bin Herr Weber, ich wohne seit Montag über Ihnen. Ich habe heute ein Paket für Sie angenommen.","Hello! I'm Mr Weber; I've been living above you since Monday. I took in a parcel for you today."],
  ["B","Oh, wie nett, vielen Dank! Herzlich willkommen im Haus.","Oh, how kind, thank you very much! Welcome to the building."],
  ["A","Danke! Wenn Sie mal nicht da sind, kann ich gern wieder Pakete annehmen.","Thanks! If you're ever not at home, I'm happy to take in parcels again."],
  ["B","Das mache ich umgekehrt natürlich auch gern.","Of course I'm happy to do the same for you."],
  ["A","Übrigens, war es gestern Abend zu laut? Wir haben noch Möbel aufgebaut.","By the way, was it too loud last night? We were still putting furniture together."],
  ["B","Ehrlich gesagt ein bisschen. Mein kleiner Sohn schläft ab acht Uhr, und er ist zweimal aufgewacht.","To be honest, a bit. My little son sleeps from eight o'clock, and he woke up twice."],
  ["A","Oh, das tut mir wirklich leid. Das wusste ich nicht.","Oh, I'm really sorry. I didn't know that."],
  ["B","Kein Problem, beim Umzug geht das nicht anders. Die Ruhezeit ist hier im Haus ab 22 Uhr.","No problem, it can't be helped when you move. Quiet time in this building starts at 10 pm."],
  ["A","Gut zu wissen. Wir versuchen, ab 20 Uhr leiser zu sein.","Good to know. We'll try to be quieter from 8 pm."],
  ["B","Das ist sehr nett. Möchten Sie am Wochenende auf einen Kaffee vorbeikommen?","That's very kind. Would you like to come round for a coffee at the weekend?"],
  ["A","Sehr gern! Passt Ihnen Sonntagnachmittag?","I'd love to! Does Sunday afternoon suit you?"],
  ["B","Ja, gegen drei Uhr?","Yes, around three?"],
  ["A","Prima, dann bis Sonntag!","Great, see you on Sunday!"]],
 tips:[["Ich habe ein Paket für Sie angenommen.","I took in a parcel for you."],["Ehrlich gesagt …","To be honest …"],["die Ruhezeit","quiet hours"],["Möchten Sie auf einen Kaffee vorbeikommen?","Would you like to come round for a coffee?"]]},

{id:"post", de:"Auf der Post", en:"At the post office",
 sit:"Sie holen ein Paket ab und möchten ein Päckchen ins Ausland schicken.",
 sitEn:"You're collecting a parcel and want to send a small parcel abroad.",
 who:{A:"Postmitarbeiterin", B:"Sie"}, g:{A:"f", B:"f"},
 lines:[
  ["B","Guten Tag, ich möchte ein Paket abholen. Hier ist die Benachrichtigungskarte.","Hello, I'd like to collect a parcel. Here's the notification card."],
  ["A","Darf ich bitte Ihren Ausweis sehen?","May I see your ID, please?"],
  ["B","Das Paket ist für meinen Mann. Hier ist seine Vollmacht und sein Ausweis.","The parcel is for my husband. Here's his authorisation and his ID."],
  ["A","Danke, das reicht. Einen Moment, bitte … Hier ist es.","Thank you, that's fine. One moment, please … Here it is."],
  ["B","Außerdem möchte ich dieses Päckchen nach Indien schicken.","I'd also like to send this small parcel to India."],
  ["A","Was ist im Päckchen?","What's in the parcel?"],
  ["B","Nur Kleidung und Süßigkeiten, ein Geschenk für meine Familie.","Just clothes and sweets, a present for my family."],
  ["A","Dann müssen Sie bitte diese Zollerklärung ausfüllen. Wie viel ist der Inhalt ungefähr wert?","Then please fill in this customs declaration. Roughly how much is the content worth?"],
  ["B","Ungefähr 60 Euro.","About 60 euros."],
  ["A","Das Päckchen wiegt 1,8 Kilo. Mit Sendungsverfolgung kostet es 29,99 Euro.","The parcel weighs 1.8 kilos. With tracking it costs 29.99 euros."],
  ["B","Wie lange dauert es ungefähr?","How long does it take roughly?"],
  ["A","Ungefähr zwei bis drei Wochen.","Around two to three weeks."],
  ["B","Gut, dann bitte mit Sendungsverfolgung. Und ich brauche noch zehn Briefmarken für Briefe in Deutschland.","OK, with tracking then, please. And I also need ten stamps for letters within Germany."],
  ["A","Das macht zusammen 38,49 Euro. Hier ist Ihr Beleg mit der Sendungsnummer.","That comes to 38.49 euros altogether. Here's your receipt with the tracking number."]],
 tips:[["Ich möchte ein Paket abholen.","I'd like to collect a parcel."],["die Vollmacht","the authorisation"],["die Zollerklärung ausfüllen","to fill in the customs declaration"],["mit Sendungsverfolgung","with tracking"]]},

{id:"hotel", de:"Im Hotel: Einchecken und ein Problem", en:"At the hotel: checking in and a problem",
 sit:"Sie kommen im Hotel an. Später gibt es ein Problem in Ihrem Zimmer.",
 sitEn:"You arrive at the hotel. Later there's a problem in your room.",
 who:{A:"Rezeption", B:"Sie"}, g:{A:"f", B:"me"},
 lines:[
  ["A","Guten Abend und herzlich willkommen im Hotel Lindenhof.","Good evening and welcome to Hotel Lindenhof."],
  ["B","Guten Abend. Ich habe ein Doppelzimmer für drei Nächte reserviert, auf den Namen [Ihr Name].","Good evening. I've booked a double room for three nights, under the name [your name]."],
  ["A","Ja, ich habe Ihre Reservierung. Frühstück ist inklusive, von 7 bis 10 Uhr im Erdgeschoss.","Yes, I have your reservation. Breakfast is included, from 7 to 10 on the ground floor."],
  ["B","Gibt es WLAN im Zimmer?","Is there Wi-Fi in the room?"],
  ["A","Ja, das Passwort steht auf Ihrer Schlüsselkarte. Sie haben Zimmer 312 im dritten Stock.","Yes, the password is on your key card. You have room 312 on the third floor."],
  ["B","Danke. Bis wann müssen wir am Abreisetag auschecken?","Thank you. By when do we have to check out on the day of departure?"],
  ["A","Bis 11 Uhr. Das Gepäck können Sie danach gern hier lassen.","By 11 am. You're welcome to leave your luggage here afterwards."],
  ["B","Entschuldigung, ich bin's noch einmal aus Zimmer 312. Die Klimaanlage funktioniert nicht, und es ist sehr warm.","Excuse me, it's me again from room 312. The air conditioning isn't working, and it's very warm."],
  ["A","Oh, das tut mir leid. Ich schicke sofort jemanden vom Haustechnik-Team.","Oh, I'm sorry. I'll send someone from the maintenance team straight away."],
  ["B","Und das Fenster zur Straße ist ziemlich laut. Wäre ein ruhigeres Zimmer möglich?","And the window facing the street is quite noisy. Would a quieter room be possible?"],
  ["A","Ja, ich habe noch ein Zimmer zum Innenhof frei. Möchten Sie umziehen?","Yes, I still have a room facing the courtyard. Would you like to move?"],
  ["B","Ja, sehr gern, wenn es keine Umstände macht.","Yes, very much, if it's no trouble."],
  ["A","Überhaupt nicht. Hier ist die Karte für Zimmer 208. Als Entschuldigung ist das Abendessen heute für Sie kostenlos.","Not at all. Here's the card for room 208. As an apology, dinner tonight is on us."],
  ["B","Das ist sehr freundlich, vielen Dank!","That's very kind, thank you very much!"]],
 tips:[["Ich habe ein Zimmer reserviert.","I've booked a room."],["Bis wann muss ich auschecken?","By when do I have to check out?"],["Die Klimaanlage funktioniert nicht.","The air conditioning doesn't work."],["Wäre ein ruhigeres Zimmer möglich?","Would a quieter room be possible?"]]},

{id:"zahnarzt", de:"Zahnarzt: Notfalltermin", en:"Dentist: emergency appointment",
 sit:"Sie haben seit gestern starke Zahnschmerzen und rufen beim Zahnarzt an.",
 sitEn:"You've had severe toothache since yesterday and call the dentist.",
 who:{A:"Praxis", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Zahnarztpraxis Dr. Yilmaz, guten Morgen.","Dr Yilmaz's dental practice, good morning."],
  ["B","Guten Morgen, ich habe seit gestern sehr starke Zahnschmerzen und brauche dringend einen Termin.","Good morning, I've had very bad toothache since yesterday and urgently need an appointment."],
  ["A","Sind Sie schon Patient bei uns?","Are you already a patient with us?"],
  ["B","Ja, ich war im Frühling zur Kontrolle bei Ihnen.","Yes, I came for a check-up in the spring."],
  ["A","Wo genau haben Sie Schmerzen?","Where exactly do you have pain?"],
  ["B","Unten links, hinten. Die Wange ist auch ein bisschen geschwollen.","Bottom left, at the back. My cheek is a bit swollen too."],
  ["A","Haben Sie Fieber?","Do you have a fever?"],
  ["B","Nein, aber ich konnte die ganze Nacht nicht schlafen.","No, but I couldn't sleep all night."],
  ["A","Wir haben eine Schmerzsprechstunde. Können Sie heute um 11:45 Uhr kommen? Sie müssen vielleicht etwas warten.","We have an emergency pain slot. Can you come today at 11:45? You may have to wait a little."],
  ["B","Ja, das ist kein Problem. Darf ich vorher eine Schmerztablette nehmen?","Yes, that's no problem. May I take a painkiller beforehand?"],
  ["A","Ja, Ibuprofen ist in Ordnung. Aber bitte kühlen Sie die Wange nur von außen, und nicht zu lange.","Yes, ibuprofen is fine. But please only cool your cheek from the outside, and not for too long."],
  ["B","Danke. Muss ich meine Versichertenkarte mitbringen?","Thank you. Do I need to bring my insurance card?"],
  ["A","Ja, bitte, und das Bonusheft, falls Sie eins haben.","Yes, please, and your dental bonus booklet if you have one."],
  ["B","Alles klar. Bis später!","All right. See you later!"]],
 tips:[["Ich habe starke Zahnschmerzen.","I have bad toothache."],["Unten links, hinten.","Bottom left, at the back."],["Die Wange ist geschwollen.","My cheek is swollen."],["Darf ich eine Schmerztablette nehmen?","May I take a painkiller?"]]},

{id:"abschied", de:"Kollegen planen eine Abschiedsfeier", en:"Colleagues plan a leaving party",
 sit:"Ihre Kollegin Frau Weber geht in Rente. Sie planen mit einem Kollegen eine kleine Feier (wie B1 Sprechen, Teil 3).",
 sitEn:"Your colleague Ms Weber is retiring. You plan a small party with a colleague (like B1 speaking part 3).",
 who:{A:"Tom", B:"Sie"}, g:{A:"m", B:"me"},
 lines:[
  ["A","Frau Weber geht Ende des Monats in Rente. Wollen wir zusammen eine kleine Feier organisieren?","Ms Weber is retiring at the end of the month. Shall we organise a small party together?"],
  ["B","Gute Idee! Wann sollen wir feiern?","Good idea! When shall we celebrate?"],
  ["A","Ich schlage ihren letzten Arbeitstag vor, das ist der Freitag.","I suggest her last working day, that's the Friday."],
  ["B","Hm, freitags gehen viele Kollegen früher nach Hause. Was hältst du von Donnerstag?","Hmm, a lot of colleagues go home early on Fridays. What do you think about Thursday?"],
  ["A","Stimmt, Donnerstag ist besser. Um 15 Uhr?","True, Thursday is better. At 3 pm?"],
  ["B","Einverstanden. Und wo? Im Konferenzraum oder in einem Restaurant?","Agreed. And where? In the conference room or in a restaurant?"],
  ["A","Im Restaurant ist es gemütlicher, aber es wird teuer. Der Konferenzraum ist kostenlos.","It's cosier in a restaurant, but it'll be expensive. The conference room is free."],
  ["B","Dann nehmen wir den Konferenzraum und dekorieren ihn ein bisschen.","Then let's take the conference room and decorate it a bit."],
  ["A","Und das Essen? Sollen wir etwas bestellen?","And the food? Shall we order something?"],
  ["B","Ich finde, jeder bringt etwas mit, dann haben wir ein Buffet. Ich mache einen Kuchen.","I think everyone should bring something, then we'll have a buffet. I'll make a cake."],
  ["A","Super. Und als Geschenk? Sie reist doch so gern.","Great. And as a present? She loves travelling."],
  ["B","Wie wäre es mit einem Gutschein für eine Städtereise? Wir könnten Geld sammeln.","How about a voucher for a city trip? We could collect money."],
  ["A","Perfekt. Ich kümmere mich um das Geld und den Gutschein.","Perfect. I'll take care of the money and the voucher."],
  ["B","Und ich schreibe die Einladung an alle. Also: Donnerstag, 15 Uhr, Konferenzraum, Buffet und Gutschein.","And I'll write the invitation to everyone. So: Thursday, 3 pm, conference room, buffet and a voucher."],
  ["A","Genau, so machen wir es!","Exactly, that's what we'll do!"]],
 tips:[["Ich schlage … vor.","I suggest …"],["Was hältst du von …?","What do you think about …?"],["Wie wäre es mit …?","How about …?"],["Ich kümmere mich um …","I'll take care of …"],["Also, wir machen es so: …","So, this is what we'll do: …"]]}
];
