/* English for the orange labels above each Grammatik example, keyed by the
   German label. Shown only when that example's EN is tapped.
   tools/check-grammatik.mjs fails if a label has no entry here. */
window.GDEN = {
 "Präsens: jetzt / immer": "present: now / always",
 "Präteritum: geschriebene Vergangenheit": "simple past: the written past",
 "Perfekt: gesprochene Vergangenheit": "perfect: the spoken past",
 "Plusquamperfekt: noch früher in der Vergangenheit": "past perfect: even earlier in the past",
 "Futur I: Zukunft / Plan": "future I: future / plan",
 "Futur II: in der Zukunft schon fertig": "future II: already finished in the future",
 "jetzt, in diesem Moment": "now, at this moment",
 "Gewohnheit: immer, oft, jeden Tag": "habit: always, often, every day",
 "Zukunft mit Zeitangabe (sehr häufig)": "future with a time phrase (very common)",
 "mit seit: dauert bis jetzt": "with seit: still going on now",
 "allgemeine Wahrheit": "general truth",
 "Präsens + gerade (I am doing)": "present + gerade (I am doing)",
 "am + Infinitiv + sein (gesprochen)": "am + infinitive + sein (spoken)",
 "dabei sein, … zu + Infinitiv": "dabei sein, … zu + infinitive (to be busy doing)",
 "Vergangenheit: Präteritum + gerade, als …": "past: simple past + gerade, als … (was doing when …)",
 "sein und haben: im Gespräch fast immer Präteritum": "sein and haben: almost always simple past, even when speaking",
 "Modalverben: Präteritum statt Perfekt": "modal verbs: simple past instead of perfect",
 "regelmäßige Verben: -te (Erzählung, Zeitung)": "regular verbs: -te (stories, newspapers)",
 "unregelmäßige Verben: Vokalwechsel": "irregular verbs: vowel change",
 "es gab (there was / there were)": "es gab (there was / there were)",
 "haben + regelmäßiges Partizip (ge-…-t)": "haben + regular participle (ge-…-t)",
 "sein bei Bewegung (gehen, fahren, fliegen)": "sein with movement (go, drive, fly)",
 "sein bei Veränderung (einschlafen, aufwachen)": "sein with a change of state (fall asleep, wake up)",
 "trennbare Verben: ge in der Mitte": "separable verbs: ge in the middle",
 "-ieren und be-/ver-/er-: ohne ge-": "-ieren and be-/ver-/er- verbs: no ge-",
 "hatte + Partizip: vor einem anderen Ereignis": "hatte + participle: before another event",
 "war + Partizip bei Bewegung": "war + participle with movement",
 "nach nachdem": "after nachdem",
 "mit schon / vorher: Erklärung": "with schon / vorher: explanation",
 "Vorhersage (Wetter, Prognose)": "prediction (weather, forecast)",
 "Versprechen / fester Plan": "promise / firm plan",
 "Vermutung über jetzt: wird wohl": "guess about now: wird wohl (will probably be)",
 "deutliche Aufforderung": "clear request / order",
 "im Nebensatz: werde am Ende": "in a subordinate clause: werde at the end",
 "in der Zukunft schon fertig (by then)": "already finished in the future (by then)",
 "mit sein bei Bewegung": "with sein for movement",
 "Vermutung über die Vergangenheit": "guess about the past",
 "im Alltag oft Perfekt statt Futur II": "in everyday speech often perfect instead of future II",
 "Herkunft: Woher? (origin)": "origin: where from?",
 "aus einem Raum heraus (out of)": "out of a room",
 "Material: Woraus? (made of)": "material: what is it made of?",
 "Grund, ohne Artikel, am Satzanfang (out of fear, love …)": "reason, no article, at the start (out of fear, love …)",
 "in der Frage: Aus welchem …?": "in a question: from which …?",
 "Arbeitsplatz: bei einer Firma (at a company)": "workplace: at a company",
 "bei einer Person zu Hause (at someone's place)": "at someone's home",
 "beim Arzt, beim Friseur (at the doctor's)": "at the doctor's, at the hairdresser's",
 "beim + Tätigkeit, am Satzanfang (while doing)": "beim + activity, at the start (while doing)",
 "Nähe zu einem Ort (near)": "close to a place (near)",
 "Verkehrsmittel: Womit? (by)": "means of transport: by what? (by)",
 "zusammen mit einer Person (with)": "together with a person (with)",
 "Mittel in der Frage (by card, with a pen)": "means, in a question (by card, with a pen)",
 "Eigenschaft nach einem Nomen (with a balcony)": "feature after a noun (with a balcony)",
 "Alter, am Satzanfang (at the age of)": "age, at the start (at the age of)",
 "Städte und Länder ohne Artikel (to)": "cities and countries without an article (to)",
 "nach Hause, in der Frage (home)": "nach Hause (home), in a question",
 "Zeit, am Satzanfang (after)": "time, at the start (after)",
 "Richtung: nach links, nach oben (to the left)": "direction: to the left, upwards",
 "nachgestellt: meiner Meinung nach (in my opinion)": "placed after: meiner Meinung nach (in my opinion)",
 "Dauer bis jetzt, Verb im Präsens (for)": "duration until now, verb in the present (for)",
 "Zeitpunkt, am Satzanfang (since)": "point in time, at the start (since)",
 "Frage: Seit wann …? (since when / how long)": "question: Seit wann …? (since when / how long)",
 "im Nebensatz": "in a subordinate clause",
 "von einer Person (from)": "from a person",
 "Herkunft nach einem Nomen (the train from …)": "origin after a noun (the train from …)",
 "von … bis (from … to)": "von … bis (from … to)",
 "Passiv: von wem? (by)": "passive: by whom? (by)",
 "statt Genitiv, gesprochen (of, 's)": "instead of the genitive, spoken (of, 's)",
 "Richtung zu Personen: zum = zu dem (to)": "direction to people: zum = zu dem (to)",
 "Anlass, am Satzanfang (for my birthday)": "occasion, at the start (for my birthday)",
 "feste Ausdrücke: zu Fuß, zu Hause": "fixed phrases: zu Fuß (on foot), zu Hause (at home)",
 "Mahlzeit: zum Frühstück (for breakfast)": "meal: zum Frühstück (for breakfast)",
 "nach dem Weg fragen: zur = zu der": "asking the way: zur = zu der",
 "Ort, vor dem Nomen (opposite)": "place, before the noun (opposite)",
 "Ort, nach dem Nomen": "place, after the noun",
 "mit Pronomen: immer danach": "with a pronoun: always after it",
 "Verhalten zu Personen (towards)": "behaviour towards people (towards)",
 "Zeit: ab jetzt / Zukunft (from … on)": "time: from now on / the future (from … on)",
 "Ort: Startpunkt (departing from)": "place: starting point (departing from)",
 "Alter (from the age of)": "age (from the age of)",
 "Preis (from … upwards)": "price (from … upwards)",
 "für eine Person (for)": "for a person",
 "Zeitraum (for a year)": "period of time (for a year)",
 "Preis (for 200 euros)": "price (for 200 euros)",
 "Meinung, am Satzanfang (for me)": "opinion, at the start (for me)",
 "Zweck (for the application)": "purpose (for the application)",
 "Ort: von einer Seite zur anderen (through)": "place: from one side to the other (through)",
 "Mittel, am Satzanfang (through, thanks to)": "means, at the start (through, thanks to)",
 "Passiv: Ursache (by)": "passive: the cause (by)",
 "Rechnen (divided by)": "maths (divided by)",
 "gegen eine Krankheit (for, against)": "against an illness (for, against)",
 "ungefähre Uhrzeit (around)": "approximate time (around)",
 "Meinung: dagegen sein (against)": "opinion: to be against something",
 "Sport: Gegner (versus)": "sport: opponent (versus)",
 "Bewegung, Kontakt (into)": "movement, contact (into)",
 "ohne Artikel, am Satzanfang (without)": "without an article, at the start (without)",
 "mit Artikel / Personen": "with an article / with people",
 "ohne … zu + Infinitiv (without doing)": "ohne … zu + infinitive (without doing)",
 "ohne dass + Nebensatz (without someone …)": "ohne dass + subordinate clause (without someone …)",
 "Uhrzeit (at)": "clock time (at)",
 "Ort: um … herum (around)": "place: um … herum (around)",
 "ungefähr: um die … (about)": "roughly: um die … (about)",
 "Unterschied: um … gestiegen (by)": "difference: um … gestiegen (risen by)",
 "Verb mit um: sich kümmern um": "verb with um: sich kümmern um (take care of)",
 "Frist: spätestens (by)": "deadline: at the latest (by)",
 "bis zu + Dativ: Strecke (as far as)": "bis zu + dative: distance (as far as)",
 "von … bis: Arbeitszeit (from … to)": "von … bis: working hours (from … to)",
 "Abschied (see you …)": "saying goodbye (see you …)",
 "Wo? → Dativ (in)": "where? → dative (in)",
 "Wohin? → Akkusativ: ins = in das (to)": "where to? → accusative: ins = in das (to)",
 "Zeit: Monat, Jahreszeit → im (in)": "time: month, season → im (in)",
 "Zeit: in + Dauer = nach dieser Zeit (in ten minutes)": "time: in + duration = after this time (in ten minutes)",
 "Länder mit Artikel: Wohin? → Akkusativ": "countries with an article: where to? → accusative",
 "Wo? → Dativ: senkrecht, an der Wand (on)": "where? → dative: upright, on the wall (on)",
 "Wohin? → Akkusativ: hängen, stellen": "where to? → accusative: hang, put",
 "Zeit: Tage und Datum → am (on)": "time: days and dates → am (on)",
 "Wo? am Wasser (by, at)": "where? by the water (by, at)",
 "Wohin? ans Meer = an das": "where to? ans Meer = an das (to the sea)",
 "Wo? → Dativ: waagerecht, liegen (on)": "where? → dative: lying flat (on)",
 "Wohin? → Akkusativ: legen (onto)": "where to? → accusative: legen (onto)",
 "Wo? bei Ereignissen: auf einer Party (at)": "where? at events: at a party",
 "Wohin? bei Ämtern: aufs = auf das (to)": "where to? at offices: aufs = auf das (to)",
 "Sprache, in der Frage (in German)": "language, in a question (in German)",
 "Wo? → Dativ, am Satzanfang (above)": "where? → dative, at the start (above)",
 "Wohin? → Akkusativ (over, above)": "where to? → accusative (over, above)",
 "Thema: über + Akkusativ (about)": "topic: über + accusative (about)",
 "Weg: über eine Stadt (via)": "route: via a city (via)",
 "mehr als (over)": "more than (over)",
 "Wo? → Dativ (under)": "where? → dative (under)",
 "Wohin? → Akkusativ (under – movement)": "where to? → accusative (under – movement)",
 "weniger als (under, below)": "less than (under, below)",
 "zwischen vielen (among), am Satzanfang": "among many (among), at the start",
 "Telefonnummer (on, at)": "phone number (on, at)",
 "Wo? → Dativ (in front of)": "where? → dative (in front of)",
 "Wohin? → Akkusativ: stellen": "where to? → accusative: stellen (put)",
 "Zeit: vor + Dativ = ago": "time: vor + dative = ago",
 "Zeit: früher als, am Satzanfang (before)": "time: earlier than, at the start (before)",
 "Uhrzeit (to)": "clock time (to: ten to five)",
 "Wo? → Dativ (behind)": "where? → dative (behind)",
 "mit Pronomen, in der Frage": "with a pronoun, in a question",
 "übertragen: vorbei (behind me = over)": "figurative: over (behind me = it's over)",
 "Wo? → Dativ (next to)": "where? → dative (next to)",
 "Wohin? → Akkusativ: sich setzen": "where to? → accusative: sich setzen (sit down)",
 "zusätzlich, am Satzanfang (besides)": "in addition, at the start (besides)",
 "Wo? bei Personen": "where? with people",
 "Wo? → Dativ (between)": "where? → dative (between)",
 "Zeit (between … and …)": "time (between … and …)",
 "Beziehung, am Satzanfang": "relationship, at the start",
 "Grund, geschrieben mit Genitiv (because of)": "reason, written with the genitive (because of)",
 "gesprochen oft mit Dativ – im Test Genitiv": "spoken often with the dative – in the exam use the genitive",
 "im Satz, am Telefon (about, regarding)": "in the sentence, on the phone (about, regarding)",
 "mit Pronomen: wegen mir (because of me)": "with a pronoun: wegen mir (because of me)",
 "Gegengrund, am Satzanfang (despite)": "counter-reason, at the start (despite)",
 "= obwohl + Nebensatz: Obwohl die Miete hoch ist …": "= obwohl + subordinate clause: although the rent is high …",
 "im Satz, nach dem Verb": "in the sentence, after the verb",
 "trotzdem = Adverb, kein Nomen danach": "trotzdem = adverb, no noun after it",
 "Präposition + Genitiv, am Satzanfang (during)": "preposition + genitive, at the start (during)",
 "Präposition im Satz": "preposition in the sentence",
 "Konjunktion: gleichzeitig (while), Verb am Ende": "conjunction: at the same time (while), verb at the end",
 "Konjunktion: Gegensatz (whereas)": "conjunction: contrast (whereas)",
 "statt + Genitiv (instead of)": "statt + genitive (instead of)",
 "statt … zu + Infinitiv (instead of doing)": "statt … zu + infinitive (instead of doing)",
 "ohne Artikel, im Restaurant": "without an article, in a restaurant",
 "vor einer Zeitangabe (instead of today)": "before a time phrase (instead of today)",
 "Zeit: innerhalb von + Dativ (within)": "time: innerhalb von + dative (within)",
 "Zeit + Genitiv": "time + genitive",
 "Ort, am Satzanfang (inside)": "place, at the start (inside)",
 "Organisation (within the company)": "organisation (within the company)",
 "Ort + Genitiv (outside)": "place + genitive (outside)",
 "Zeit, am Satzanfang (outside of)": "time, at the start (outside of)",
 "als Adverb, ohne Nomen": "as an adverb, without a noun",
 "außerhalb von + Dativ": "außerhalb von + dative",
 "gleiches Subjekt: nicht wiederholen": "same subject: don't repeat it",
 "zwei Hauptsätze mit verschiedenen Subjekten": "two main clauses with different subjects",
 "nach und: ein anderes Wort auf Position 1": "after und: another word in position 1",
 "Aufzählung (and)": "list (and)",
 "zwei Nebensätze verbinden": "joining two subordinate clauses",
 "Gegensatz zwischen zwei Sätzen (but)": "contrast between two sentences (but)",
 "im Satz nach dem Verb (however)": "in the sentence after the verb (however)",
 "zwischen Adjektiven": "between adjectives",
 "nach einem Punkt am Satzanfang": "after a full stop, at the start of the sentence",
 "Modalpartikel: Überraschung (really)": "modal particle: surprise (really)",
 "Auswahl zwischen Wörtern (or)": "choice between words (or)",
 "Auswahl zwischen Sätzen": "choice between sentences",
 "am Ende: Bestätigung (…, right?)": "at the end: checking (…, right?)",
 "ungefähre Zahl (two or three)": "approximate number (two or three)",
 "Grund = weil, aber Hauptsatz-Wortstellung": "reason = weil, but main-clause word order",
 "mit Modalverb: Verb auf Position 2": "with a modal verb: verb in position 2",
 "mit Perfekt": "with the perfect",
 "Modalpartikel in Fragen (then, actually)": "modal particle in questions (then, actually)",
 "Korrektur nach nicht (but rather)": "correction after nicht (but rather)",
 "mit ganzem Satz": "with a whole sentence",
 "nach kein": "after kein",
 "nicht nur … sondern auch": "not only … but also",
 "Nebensatz nach dem Hauptsatz (because)": "subordinate clause after the main clause (because)",
 "Nebensatz zuerst: dann Verb, Verb": "subordinate clause first: then verb, verb",
 "Modalverb ganz am Ende": "modal verb right at the end",
 "trennbares Verb: zusammen am Ende": "separable verb: together at the end",
 "kurze Antwort auf Warum?": "short answer to Warum? (why?)",
 "Grund, oft am Satzanfang (since, as)": "reason, often at the start (since, as)",
 "typisch im formellen Brief": "typical in a formal letter",
 "Adverb: da = hier / dort (there)": "adverb: da = here / there",
 "Adverb der Zeit (then, at that moment)": "adverb of time (then, at that moment)",
 "Nebensatz nach dem Hauptsatz (although)": "subordinate clause after the main clause (although)",
 "Nebensatz zuerst, mit Perfekt": "subordinate clause first, with the perfect",
 "mit Modalverb am Ende": "with a modal verb at the end",
 "gleiche Bedeutung mit trotzdem (Hauptsatz)": "same meaning as trotzdem (main clause)",
 "nach hoffen, denken, glauben, wissen": "after hope, think, believe, know",
 "nach „Es ist wichtig / schön …“": "after „Es ist wichtig / schön …“ (it is important / nice …)",
 "dass-Satz am Satzanfang": "dass clause at the start",
 "nach einem Nomen (the news that …)": "after a noun (the news that …)",
 "indirekte Rede mit Modalverb": "reported speech with a modal verb",
 "höfliche indirekte Ja/Nein-Frage (whether)": "polite indirect yes/no question (whether)",
 "nach „Ich weiß nicht …“": "after „Ich weiß nicht …“ (I don't know …)",
 "ob … oder (whether … or)": "ob … oder (whether … or)",
 "ob-Satz am Satzanfang": "ob clause at the start",
 "Bedingung (if)": "condition (if)",
 "immer wenn: wiederholt (whenever)": "every time: repeated (whenever)",
 "Zeitpunkt in der Zukunft (when)": "point in the future (when)",
 "Hauptsatz zuerst, Imperativ": "main clause first, imperative",
 "irreal mit Konjunktiv II": "unreal, with Konjunktiv II",
 "einmal in der Vergangenheit, Nebensatz zuerst (when)": "once in the past, subordinate clause first (when)",
 "Hauptsatz zuerst, Perfekt": "main clause first, perfect",
 "Vergleich nach Komparativ (than)": "comparison after a comparative (than)",
 "Rolle / Beruf (as)": "role / job (as)",
 "Nebensatz zuerst (before)": "subordinate clause first (before)",
 "Anweisung, Nebensatz danach": "instruction, subordinate clause after it",
 "trennbares Verb am Ende": "separable verb at the end",
 "mit Nomen: vor + Dativ statt bevor": "with a noun: vor + dative instead of bevor",
 "Vergangenheit: + Plusquamperfekt, Hauptsatz Präteritum": "past: + past perfect, main clause in the simple past",
 "Gegenwart: + Perfekt, Hauptsatz Präsens": "present: + perfect, main clause in the present",
 "Hauptsatz zuerst": "main clause first",
 "mit Nomen: nach + Dativ statt nachdem": "with a noun: nach + dative instead of nachdem",
 "Konjunktion, Nebensatz zuerst (since)": "conjunction, subordinate clause first (since)",
 "Konjunktion, Hauptsatz zuerst": "conjunction, main clause first",
 "Adverb am Satzanfang: Verb sofort": "adverb at the start: verb straight after",
 "mit Nomen: seit + Dativ": "with a noun: seit + dative",
 "Nebensatz danach (until)": "subordinate clause after it (until)",
 "Nebensatz zuerst": "subordinate clause first",
 "Dauer bis zu einem Ereignis": "duration up to an event",
 "als Präposition, ohne Verb": "as a preposition, without a verb",
 "Ziel, gleiches Subjekt – auch um … zu möglich": "aim, same subject – um … zu also possible",
 "Ziel, verschiedene Subjekte → nur damit": "aim, different subjects → only damit",
 "Achtung: damit = da + mit (with it), kein Nebensatz": "careful: damit = da + mit (with it), not a subordinate clause",
 "Ziel mit Infinitiv (in order to)": "aim with the infinitive (in order to)",
 "am Satzanfang: dann Verb, Subjekt": "at the start: then verb, subject",
 "trennbares Verb: zu in der Mitte": "separable verb: zu in the middle",
 "Antwort auf Wozu?": "answer to Wozu? (what for?)",
 "Folge (so that, with the result that)": "result (so that, with the result that)",
 "so + Adjektiv, dass (so … that)": "so + adjective, dass (so … that)",
 "Folge mit Perfekt": "result with the perfect",
 "positive Folge mit Modalverb": "positive result with a modal verb",
 "höfliche Bedingung, Nebensatz zuerst (if)": "polite condition, subordinate clause first (if)",
 "für den Fall, dass (in case)": "in case",
 "formell: falls … sollten": "formal: falls … sollten (should … )",
 "Wie? Mittel (by doing)": "how? the means (by doing)",
 "Lernstrategie beschreiben": "describing a learning strategy",
 "kurze Antwort auf Wie?": "short answer to Wie? (how?)",
 "nach Komma am Satzanfang: dann Verb (therefore)": "after a comma at the start: then the verb (therefore)",
 "neuer Satz nach Punkt": "new sentence after a full stop",
 "gleiche Bedeutung: deswegen, darum": "same meaning: deswegen, darum",
 "am Satzanfang (nevertheless)": "at the start (nevertheless)",
 "am Satzende, als Antwort": "at the end of the sentence, as an answer",
 "nach und": "after und",
 "am Satzanfang: noch ein Punkt (besides)": "at the start: one more point (besides)",
 "im formellen Brief: weitere Frage": "in a formal letter: another question",
 "über sich erzählen (B1 Sprechen)": "talking about yourself (B1 speaking)",
 "sonst = wenn nicht (otherwise)": "sonst = if not (otherwise)",
 "Warnung nach Imperativ": "warning after an imperative",
 "sonst = normalerweise (usually)": "sonst = normally (usually)",
 "sonst noch = zusätzlich (anything else)": "sonst noch = in addition (anything else)",
 "Reihenfolge: zuerst …, dann … (then)": "order: first …, then …",
 "danach = nach dieser Sache (afterwards)": "danach = after that thing (afterwards)",
 "dann nach einem wenn-Satz": "dann after a wenn clause",
 "Anleitung in Schritten": "instructions in steps",
 "zwei Orte (either … or)": "two places (either … or)",
 "zwei ganze Sätze": "two whole sentences",
 "zwei Subjekte: Verb passt zum nächsten": "two subjects: the verb matches the nearer one",
 "zwei Zeitangaben": "two time phrases",
 "zwei Objekte (both … and)": "two objects (both … and)",
 "als Subjekt: Verb im Plural": "as the subject: verb in the plural",
 "zwei Adjektive": "two adjectives",
 "im Kurs / in der Schule": "in the course / at school",
 "zwei Objekte (neither … nor)": "two objects (neither … nor)",
 "Nachteile beschreiben": "describing disadvantages",
 "zwei Subjekte": "two subjects",
 "zwei Adjektive (Beschwerde)": "two adjectives (complaint)",
 "zwei Adjektive (not only … but also)": "two adjectives (not only … but also)",
 "zwei Sätze: auch im zweiten Satz": "two sentences: auch in the second one too",
 "zwei Orte": "two places",
 "zwei Adjektive (it's true … but)": "two adjectives (it's true … but)",
 "zwei Sätze, Meinung abwägen": "two sentences, weighing up an opinion",
 "zwar am Satzanfang: Verb danach": "zwar at the start: verb after it",
 "mit Perfekt, Kritik im Brief": "with the perfect, criticism in a letter",
 "je + Komparativ, Verb am Ende – desto + Komparativ, Verb": "je + comparative, verb at the end – desto + comparative, verb",
 "Tipp / Regel formulieren": "stating a tip / rule",
 "umso statt desto": "umso instead of desto",
 "mit mehr + Nomen": "with mehr + noun",
 "Nominativ Singular: -e": "nominative singular: -e",
 "Akkusativ maskulin: -en": "accusative masculine: -en",
 "Akkusativ feminin / neutral: -e": "accusative feminine / neuter: -e",
 "Dativ: immer -en": "dative: always -en",
 "Genitiv: immer -en": "genitive: always -en",
 "Nominativ maskulin: -er": "nominative masculine: -er",
 "Nominativ / Akkusativ neutral: -es": "nominative / accusative neuter: -es",
 "Akkusativ feminin -e, Dativ -en": "accusative feminine -e, dative -en",
 "kein / mein im Plural: -en": "kein / mein in the plural: -en",
 "neutral: -es (wie das)": "neuter: -es (like das)",
 "Akkusativ maskulin -en, Dativ feminin -er": "accusative masculine -en, dative feminine -er",
 "Plural Nominativ: -e": "plural nominative: -e",
 "Dativ Plural: -en (Briefschluss)": "dative plural: -en (end of a letter)",
 "nach die: -en": "after die: -en",
 "ohne Artikel, Nominativ: -e": "no article, nominative: -e",
 "ohne Artikel, Akkusativ: -e (Stellenanzeige)": "no article, accusative: -e (job advert)",
 "nach Zahl, Dativ: -en": "after a number, dative: -en",
 "nach sein: keine Endung": "after sein: no ending",
 "nach werden (to become)": "after werden (to become)",
 "nach bleiben (to stay)": "after bleiben (to stay)",
 "beim Verb (Wie?): keine Endung": "with the verb (how?): no ending",
 "nach sein: Komparativ + als": "after sein: comparative + als",
 "vor dem Nomen: Komparativ + Endung": "before the noun: comparative + ending",
 "mit Umlaut: kalt → kälter": "with an umlaut: kalt → kälter",
 "immer + Komparativ (more and more)": "immer + comparative (more and more)",
 "nach sein: am …sten": "after sein: am …sten",
 "vor dem Nomen: der/die/das …ste": "before the noun: der/die/das …ste",
 "am besten = Ratschlag (best to …)": "am besten = advice (it's best to …)",
 "mit Genitiv (… in Germany)": "with the genitive (… in Germany)",
 "gut – besser – am besten": "good – better – best",
 "gern – lieber – am liebsten": "gladly – rather – most of all",
 "viel – mehr – am meisten": "much – more – most",
 "hoch – höher – am höchsten (c fällt weg)": "high – higher – highest (the c drops)",
 "gleich: so + Adjektiv + wie (as … as)": "equal: so + adjective + wie (as … as)",
 "anders: Komparativ + als (…er than)": "different: comparative + als (…er than)",
 "nicht so … wie (not as … as)": "nicht so … wie (not as … as)",
 "doppelt so … wie (twice as …)": "doppelt so … wie (twice as …)",
 "mit Nomen": "with a noun",
 "Sache schon bekannt: darauf": "thing already known: darauf",
 "Frage nach einer Sache: worauf?": "asking about a thing: worauf?",
 "Frage nach einer Person: auf wen?": "asking about a person: auf wen?",
 "Sache schon bekannt: damit": "thing already known: damit",
 "Frage nach einer Sache: womit?": "asking about a thing: womit?",
 "verneint (Beschwerde)": "negative (complaint)",
 "im Bewerbungsbrief": "in a job application letter",
 "Frage nach einer Sache: woran?": "asking about a thing: woran?",
 "daran + zu-Infinitiv": "daran + zu-infinitive",
 "Nomen: Interesse an + Dativ": "noun: Interesse an + dative (interest in)",
 "über die Arbeit sprechen": "talking about work",
 "Frage: dafür": "question: dafür",
 "für Personen": "for people",
 "dafür + dass-Satz": "dafür + dass clause",
 "mit dass-Satz": "with a dass clause",
 "Frage: worüber?": "question: worüber?",
 "Sache schon bekannt: darüber": "thing already known: darüber",
 "vom = von dem, Adjektiv am Ende": "vom = von dem, adjective at the end",
 "von Personen abhängig": "dependent on people",
 "davon + Nebensatz": "davon + subordinate clause",
 "mit Nomen, Präsens": "with a noun, present",
 "darauf + dass-Satz": "darauf + dass clause",
 "Perfekt": "perfect",
 "denken an: mit Nomen (think of)": "denken an: with a noun (think of)",
 "daran + zu-Infinitiv (remember to)": "daran + zu-infinitive (remember to)",
 "Frage: woran?": "question: woran?",
 "Frage nach einer Person: an wen?": "asking about a person: an wen?",
 "denken über = Meinung (think about)": "denken über = opinion (think about)",
 "auf = etwas kommt noch (look forward to)": "auf = something still to come (look forward to)",
 "über = etwas ist schon da (be pleased about)": "über = something already here (be pleased about)",
 "darauf + zu-Infinitiv (Briefschluss)": "darauf + zu-infinitive (end of a letter)",
 "Frage: worauf?": "question: worauf?",
 "sich freuen, dass (be glad that)": "sich freuen, dass (be glad that)",
 "Frage: wofür?": "question: wofür?",
 "Frage nach einer Person: für wen?": "asking about a person: für wen?",
 "mit Nomen, in der Frage": "with a noun, in a question",
 "Sache schon bekannt: darum": "thing already known: darum",
 "darum + dass-Satz": "darum + dass clause",
 "darüber + dass-Satz": "darüber + dass clause",
 "Imperativ: nicht ärgern": "imperative: don't get annoyed",
 "trennbar im Präsens": "separable in the present",
 "Perfekt: teilgenommen": "perfect: teilgenommen",
 "mit Modalverb: Infinitiv am Ende": "with a modal verb: infinitive at the end",
 "im Nebensatz: zusammen am Ende": "in a subordinate clause: together at the end",
 "mit + Person (talk to)": "mit + person (talk to)",
 "über + Thema, Perfekt (talk about)": "über + topic, perfect (talk about)",
 "am Telefon (speak to)": "on the phone (speak to)",
 "von = erzählen (talk of)": "von = tell about (talk of)",
 "um + Stelle (apply for)": "um + job (apply for)",
 "bei + Firma, Perfekt (apply to)": "bei + company, perfect (apply to)",
 "im Bewerbungsbrief: hiermit": "in an application letter: hiermit (herewith)",
 "bitten um: höfliche Bitte": "bitten um: polite request",
 "darum + zu-Infinitiv (formeller Brief)": "darum + zu-infinitive (formal letter)",
 "Perfekt: gebeten": "perfect: gebeten",
 "Information → fragen nach + Dativ": "information → fragen nach + dative (ask about)",
 "mit Nomen, Frage": "with a noun, question",
 "Sache schon bekannt: daran": "thing already known: daran",
 "an eine Person, höflich": "of a person, politely",
 "jemanden erinnern an (remind)": "jemanden erinnern an (remind)",
 "Frage: wovor?": "question: wovor?",
 "davor + zu-Infinitiv": "davor + zu-infinitive",
 "ähnlich: sich fürchten vor": "similar: sich fürchten vor (be scared of)",
 "Wunsch mit Nomen": "a wish, with a noun",
 "davon + zu-Infinitiv, Perfekt": "davon + zu-infinitive, perfect",
 "Frage: wovon?": "question: wovon?",
 "im Schlaf träumen": "dreaming in your sleep",
 "Freizeit beschreiben": "describing free time",
 "Frage: womit? (Beruf)": "question: womit? (job)",
 "damit + Modalverb": "damit + modal verb",
 "mit Nomen, Perfekt": "with a noun, perfect",
 "allgemeine Aussage mit man": "general statement with man",
 "über + Problem (complain about)": "über + problem (complain about)",
 "bei + Person (complain to)": "bei + person (complain to)",
 "trennbar: hängt … ab": "separable: hängt … ab",
 "davon + ob-Satz": "davon + ob clause",
 "von einer Person": "on a person",
 "mit + Person, Perfekt": "mit + person, perfect",
 "Frage nach Personen: mit wem? (nicht womit)": "asking about people: mit wem? (not womit)",
 "Wir + uns: Ort und Zeit": "wir + uns: place and time",
 "im Nebensatz mit Modalverb": "in a subordinate clause with a modal verb",
 "Frage mit Modalverb": "question with a modal verb",
 "Perfekt: hat geholfen; er → ihm": "perfect: hat geholfen; er → ihm",
 "Imperativ, höflich": "imperative, polite",
 "Nomen im Dativ Plural: -n": "noun in the dative plural: -n",
 "Sache = Subjekt, Person = Dativ": "thing = subject, person = dative",
 "nach der Meinung fragen, Perfekt": "asking for an opinion, perfect",
 "Subjekt im Plural: Verb im Plural": "plural subject: verb in the plural",
 "Person als Nomen im Dativ": "person as a noun in the dative",
 "Frage: Wem gehört …? (whose)": "question: Wem gehört …? (whose is …?)",
 "mit Nomen im Dativ": "with a noun in the dative",
 "mit Pronomen": "with a pronoun",
 "gehören zu = ein Teil sein": "gehören zu = to be part of",
 "Essen = Subjekt": "the food = the subject",
 "im Restaurant, höflich, Perfekt": "in a restaurant, polite, perfect",
 "Frage mit wie": "question with wie",
 "schmecken nach = Geschmack (taste of)": "schmecken nach = flavour (taste of)",
 "Termin (suit)": "appointment (suit)",
 "Kleidung: Größe (fit)": "clothes: size (fit)",
 "höfliche Frage": "polite question",
 "passen zu = gut zusammen (go with)": "passen zu = go well together (go with)",
 "jemand fehlt mir (I miss)": "jemand fehlt mir (I miss someone)",
 "beim Arzt: Was fehlt Ihnen?": "at the doctor's: What's wrong?",
 "ohne Dativ: etwas ist nicht da": "without a dative: something is missing",
 "nicht da sein (be absent)": "not being there (be absent)",
 "Person im Dativ + für": "person in the dative + für",
 "Dativ Plural: Nomen + -n": "dative plural: noun + -n",
 "Perfekt, Frage": "perfect, question",
 "ähnlich: sich bedanken bei + Dativ": "similar: sich bedanken bei + dative",
 "gratulieren + Dativ + zu": "gratulieren + dative + zu (congratulate on)",
 "um … zu + Infinitiv": "um … zu + infinitive",
 "Person im Dativ": "person in the dative",
 "Sache: antworten auf + Akkusativ": "thing: antworten auf + accusative (reply to)",
 "Frage: Was hat er geantwortet?": "question: What did he answer?",
 "ohne Präposition: beantworten + Akkusativ": "without a preposition: beantworten + accusative",
 "Person im Dativ (believe someone)": "person in the dative (believe someone)",
 "Sache im Akkusativ (believe something)": "thing in the accusative (believe something)",
 "glauben an + Akkusativ (believe in)": "glauben an + accusative (believe in)",
 "Meinung: glauben, dass (think)": "opinion: glauben, dass (think that)",
 "Körperteil = Subjekt, trennbar": "body part = subject, separable",
 "andere Person im Dativ": "another person in the dative",
 "beim Arzt: Frage": "at the doctor's: question",
 "Perfekt: wehgetan": "perfect: wehgetan",
 "sich entschuldigen (I'm sorry)": "apologising (I'm sorry)",
 "Mitleid (feel sorry for)": "sympathy (feel sorry for)",
 "Präteritum: tat mir leid": "simple past: tat mir leid",
 "kurze Reaktion": "short reaction",
 "Nominativ maskulin, Relativsatz in der Mitte": "nominative masculine, relative clause in the middle",
 "Relativsatz am Ende": "relative clause at the end",
 "Achtung: der = Dativ feminin": "careful: der = dative feminine",
 "Präposition + der (Dativ feminin)": "preposition + der (dative feminine)",
 "Akkusativ maskulin, Relativsatz in der Mitte": "accusative masculine, relative clause in the middle",
 "für + den (Akkusativ)": "für + den (accusative)",
 "an + den (denken an + Akk.)": "an + den (denken an + acc.)",
 "Dativ maskulin (helfen + Dativ)": "dative masculine (helfen + dative)",
 "Dativ neutral (gehören + Dativ)": "dative neuter (gehören + dative)",
 "in dem = wo (Ort)": "in dem = wo (place)",
 "von dem (erzählen von + Dativ)": "von dem (erzählen von + dative)",
 "Nominativ feminin": "nominative feminine",
 "Akkusativ feminin": "accusative feminine",
 "Plural Nominativ": "plural nominative",
 "Plural Akkusativ": "plural accusative",
 "auf + die (sich vorbereiten auf + Akk.)": "auf + die (sich vorbereiten auf + acc.)",
 "Nominativ neutral": "nominative neuter",
 "Akkusativ neutral": "accusative neuter",
 "über + das (sprechen über + Akk.)": "über + das (sprechen über + acc.)",
 "dessen: Bezugswort maskulin (whose)": "dessen: masculine noun (whose)",
 "deren: Bezugswort feminin (whose)": "deren: feminine noun (whose)",
 "deren: Bezugswort Plural": "deren: plural noun",
 "dessen: Bezugswort neutral": "dessen: neuter noun",
 "Dativ Plural (geben + Dativ)": "dative plural (geben + dative)",
 "mit + denen": "mit + denen",
 "bei + denen (Wohnort)": "bei + denen (where someone lives)",
 "schmecken + Dativ": "schmecken + dative",
 "wo nach Städten und Ländern": "wo after cities and countries",
 "wo = in dem / in der": "wo = in dem / in der",
 "woher = Herkunft": "woher = origin",
 "wohin = Richtung": "wohin = direction",
 "nach alles (all that)": "after alles (all that)",
 "nach nichts / etwas": "after nichts / etwas",
 "nach Superlativ (the best thing that)": "after a superlative (the best thing that)",
 "bezieht sich auf den ganzen Satz": "refers to the whole sentence",
 "ganzer Satz + Präposition: wo(r)- ": "whole sentence + preposition: wo(r)-",
 "Wunsch (would like to)": "wish (would like to)",
 "höfliche Bitte, Frage": "polite request, question",
 "Ratschlag: An deiner Stelle …": "advice: An deiner Stelle … (if I were you …)",
 "vorsichtige Meinung (B1 Sprechen)": "careful opinion (B1 speaking)",
 "Wunsch": "wish",
 "höflich bestellen": "ordering politely",
 "hätte fast + Partizip (almost)": "hätte fast + participle (almost)",
 "höflicher Vorschlag": "polite suggestion",
 "irreal: in Wirklichkeit nicht": "unreal: not so in reality",
 "höfliche Frage im Brief": "polite question in a letter",
 "Vergangenheit: wäre + Partizip": "past: wäre + participle",
 "sehr höfliche Bitte": "very polite request",
 "Vorschlag (we could …)": "suggestion (we could …)",
 "Vermutung (might)": "guess (might)",
 "Vorwurf in der Vergangenheit: hätte … können": "reproach about the past: hätte … können (could have)",
 "Ratschlag unter Freunden (should)": "advice between friends (should)",
 "Ratschlag, formell": "advice, formal",
 "um Rat fragen": "asking for advice",
 "Vergangenheit: hätte … sollen (should have)": "past: hätte … sollen (should have)",
 "Wenn-Satz zuerst": "wenn clause first",
 "ohne wenn: Verb am Anfang": "without wenn: verb at the start",
 "Hauptsatz zuerst, mit Modalverb": "main clause first, with a modal verb",
 "Frage (B1 Sprechen)": "question (B1 speaking)",
 "Wenn … doch nur …! (if only)": "Wenn … doch nur …! (if only)",
 "Ich wünschte, … (I wish)": "Ich wünschte, … (I wish)",
 "mit wäre": "with wäre",
 "Vergangenheit, Verb am Anfang": "past, verb at the start",
 "irreal in der Vergangenheit": "unreal in the past",
 "Bedauern (I wish I had …)": "regret (I wish I had …)",
 "mit Grund: aber …": "with a reason: but …",
 "wäre + gewesen": "wäre + gewesen",
 "jetzt / in der Zukunft": "now / in the future",
 "allgemein, ohne Person": "general, without a person",
 "Frage": "question",
 "im Nebensatz: wird am Ende": "in a subordinate clause: wird at the end",
 "Geschichte erzählen": "telling a story",
 "mit Person: von + Dativ": "with a person: von + dative",
 "Ursache: durch + Akkusativ": "cause: durch + accusative",
 "ist + Partizip + worden": "ist + participle + worden",
 "über sich selbst berichten": "reporting about yourself",
 "im Nebensatz: worden ist am Ende": "in a subordinate clause: worden ist at the end",
 "Pflicht: müssen + Partizip + werden": "obligation: müssen + participle + werden",
 "Verbot: dürfen + nicht": "ban: dürfen + nicht",
 "Möglichkeit: können": "possibility: können",
 "im Nebensatz: Modalverb ganz am Ende": "in a subordinate clause: modal verb right at the end",
 "Zustand, nicht Handlung": "a state, not an action",
 "Ergebnis ist schon da": "the result is already there",
 "Vergangenheit: war + Partizip": "past: war + participle",
 "Unterschied: Vorgang mit werden": "difference: the process, with werden",
 "man + Aktiv = Passiv ohne Person": "man + active = passive without a person",
 "man + Modalverb (Regeln)": "man + modal verb (rules)",
 "Frage (How do you …?)": "question (How do you …?)",
 "Ratschlag mit sollte": "advice with sollte",
 "Fähigkeit (can, be able to)": "ability (can, be able to)",
 "Möglichkeit (it's possible)": "possibility (it's possible)",
 "höfliche Bitte in der Frage": "polite request as a question",
 "Präteritum: konnte": "simple past: konnte",
 "ohne Infinitiv: eine Sprache können": "without an infinitive: to know a language",
 "Pflicht (must, have to)": "obligation (must, have to)",
 "Notwendigkeit, im Nebensatz am Ende": "necessity, at the end of a subordinate clause",
 "Präteritum: musste": "simple past: musste",
 "nicht müssen = nicht nötig (don't have to)": "nicht müssen = not necessary (don't have to)",
 "sichere Vermutung (must be)": "confident guess (must be)",
 "Erlaubnis (may, be allowed to)": "permission (may, be allowed to)",
 "Verbot: nicht dürfen (mustn't)": "ban: nicht dürfen (mustn't)",
 "höfliche Frage: Darf ich …?": "polite question: Darf ich …? (May I …?)",
 "Präteritum: durfte": "simple past: durfte",
 "im Geschäft: Was darf es sein?": "in a shop: What would you like?",
 "Auftrag von einer anderen Person": "a task from another person",
 "Frage: Soll ich …? (Shall I …?)": "question: Soll ich …? (Shall I …?)",
 "Präteritum: sollte (was supposed to)": "simple past: sollte (was supposed to)",
 "Nachricht weitergeben": "passing on a message",
 "angeblich (is said to be)": "supposedly (is said to be)",
 "Plan, fester Wunsch (want to)": "plan, firm wish (want to)",
 "Präteritum: wollte": "simple past: wollte",
 "Vorschlag: Wollen wir …? (Shall we …?)": "suggestion: Wollen wir …? (Shall we …?)",
 "höflicher: möchten statt wollen": "more polite: möchten instead of wollen",
 "möchten + Infinitiv: höflicher Wunsch": "möchten + infinitive: polite wish",
 "möchten + Nomen (bestellen)": "möchten + noun (ordering)",
 "mögen + Nomen = gern haben (like)": "mögen + noun = to like",
 "möchten in der Vergangenheit: wollte": "möchten in the past: wollte",
 "im formellen Brief": "in a formal letter",
 "nicht brauchen + zu = nicht müssen": "nicht brauchen + zu = don't have to",
 "nur … zu brauchen (only need to)": "nur … zu brauchen (only need to)",
 "kein + Nomen brauchen": "kein + noun brauchen (need no …)",
 "Präteritum": "simple past",
 "Hauptsatz: Satzklammer": "main clause: sentence bracket",
 "Nebensatz: Modalverb ganz am Ende": "subordinate clause: modal verb right at the end",
 "trennbares Verb bleibt zusammen": "separable verb stays together",
 "Perfekt: doppelter Infinitiv (selten, meist Präteritum)": "perfect: double infinitive (rare, usually simple past)",
 "Präsens": "present",
 "Perfekt: mit haben": "perfect: with haben",
 "Imperativ (du / Sie)": "imperative (du / Sie)",
 "Körperteil = Akkusativ, Pronomen = Dativ": "body part = accusative, pronoun = dative",
 "sich etwas kaufen": "buying something for yourself",
 "sich etwas vorstellen (imagine)": "sich etwas vorstellen (imagine)",
 "sich Sorgen machen (worry)": "sich Sorgen machen (worry)",
 "sich etwas ansehen, Perfekt": "sich etwas ansehen (have a look at), perfect",
 "waschen: jemand anderen": "waschen: someone else",
 "sich waschen: sich selbst": "sich waschen: yourself",
 "jemanden ärgern (annoy someone)": "jemanden ärgern (annoy someone)",
 "sich ärgern (be annoyed)": "sich ärgern (be annoyed)",
 "anmelden: jemand anderen / sich selbst": "anmelden: someone else / yourself",
 "sich treffen (meet each other)": "sich treffen (meet each other)",
 "sich verstehen (get on)": "sich verstehen (get on)",
 "sich streiten (argue)": "sich streiten (argue)",
 "Frage mit ihr / euch": "question with ihr / euch",
 "nach dem konjugierten Verb": "after the conjugated verb",
 "Inversion mit Nomen: sich vor dem Subjekt": "inversion with a noun: sich before the subject",
 "Inversion mit Pronomen: sich nach dem Subjekt": "inversion with a pronoun: sich after the subject",
 "Nebensatz: sich früh im Satz": "subordinate clause: sich early in the clause",
 "sich beeilen (hurry)": "sich beeilen (hurry)",
 "sich erkälten (catch a cold)": "sich erkälten (catch a cold)",
 "sich ausruhen (rest)": "sich ausruhen (rest)",
 "sich entscheiden (decide)": "sich entscheiden (decide)",
 "sich verabschieden (say goodbye)": "sich verabschieden (say goodbye)",
 "Hauptsatz: Vorsilbe ans Ende": "main clause: prefix to the end",
 "Imperativ": "imperative",
 "Nebensatz: zusammen am Ende": "subordinate clause: together at the end",
 "mit Modalverb: zusammen am Ende": "with a modal verb: together at the end",
 "an-ge-rufen": "an-ge-rufen (phoned)",
 "ein-ge-kauft": "ein-ge-kauft (shopped)",
 "mit sein: auf-ge-standen": "with sein: auf-ge-standen (got up)",
 "unregelmäßig: mit-ge-bracht": "irregular: mit-ge-bracht (brought along)",
 "mit sein: zurück-ge-kommen": "with sein: zurück-ge-kommen (came back)",
 "an-zu-rufen": "an-zu-rufen (to phone)",
 "auf-zu-räumen": "auf-zu-räumen (to tidy up)",
 "mit um … zu": "with um … zu",
 "mit-zu-nehmen": "mit-zu-nehmen (to take along)",
 "be-: Perfekt ohne ge": "be-: perfect without ge",
 "ver-: Vorsilbe bleibt am Verb": "ver-: the prefix stays on the verb",
 "er-: Perfekt ohne ge": "er-: perfect without ge",
 "ent-: auch im Nebensatz gleich": "ent-: the same in a subordinate clause",
 "emp-: empfehlen": "emp-: empfehlen (recommend)",
 "ankommen (arrive) – trennbar": "ankommen (arrive) – separable",
 "bekommen (get, receive) – untrennbar": "bekommen (get, receive) – inseparable",
 "mitkommen (come along) – trennbar": "mitkommen (come along) – separable",
 "vorkommen (happen) – trennbar": "vorkommen (happen) – separable",
 "aufstehen (get up) – trennbar": "aufstehen (get up) – separable",
 "verstehen (understand) – untrennbar": "verstehen (understand) – inseparable",
 "bestehen (pass) – untrennbar": "bestehen (pass) – inseparable",
 "entstehen (arise) – untrennbar": "entstehen (arise) – inseparable",
 "umziehen (move house) – trennbar": "umziehen (move house) – separable",
 "umsteigen (change trains) – trennbar": "umsteigen (change trains) – separable",
 "übersetzen (translate) – untrennbar": "übersetzen (translate) – inseparable",
 "wiederholen (repeat) – untrennbar": "wiederholen (repeat) – inseparable",
 "Es ist wichtig, … zu": "It is important to …",
 "Es ist schwer / leicht, … zu": "It is hard / easy to …",
 "Es macht Spaß, … zu": "It is fun to …",
 "Es ist verboten, … zu (Regeln)": "It is forbidden to … (rules)",
 "keine Lust haben, … zu": "not feel like …ing",
 "keine Zeit haben, … zu": "have no time to …",
 "die Möglichkeit haben, … zu": "have the chance to …",
 "Angst haben, … zu": "be afraid of …ing",
 "versuchen, … zu (try)": "versuchen, … zu (try to)",
 "vergessen, … zu (forget)": "vergessen, … zu (forget to)",
 "anfangen / aufhören, … zu (start / stop)": "anfangen / aufhören, … zu (start / stop …ing)",
 "vorhaben, … zu (plan)": "vorhaben, … zu (plan to)",
 "hoffen, … zu (hope)": "hoffen, … zu (hope to)",
 "nach Modalverben": "after modal verbs",
 "nach werden (Futur)": "after werden (future)",
 "nach lassen": "after lassen",
 "nach gehen / fahren (Bewegung)": "after gehen / fahren (movement)",
 "nach sehen / hören": "after sehen / hören (see / hear)",
 "gleiches Subjekt → zu": "same subject → zu",
 "anderes Subjekt → dass": "different subject → dass",
 "beides möglich bei gleichem Subjekt": "both possible with the same subject",
 "Bitte an eine Person → zu": "request to a person → zu",
 "haben + zu = müssen (active)": "haben + zu = must (active)",
 "nichts zu … haben": "have nothing to …",
 "sein + zu = muss gemacht werden (formell)": "sein + zu = must be done (formal)",
 "sein + zu = kann gemacht werden": "sein + zu = can be done",
 "wann: Zeit": "when: time",
 "wo: Ort": "where: place",
 "wie: Art und Weise": "how: manner",
 "wie + Adjektiv: wie lange, wie oft": "wie + adjective: how long, how often",
 "warum: Grund": "why: reason",
 "was: Sache": "what: thing",
 "wer: Person (Subjekt)": "who: person (subject)",
 "mit wem / für wen: Präposition + Fragewort": "with whom / for whom: preposition + question word",
 "wie viel: Preis, Menge": "how much: price, amount",
 "welche + Nomen": "which + noun",
 "wie viele + Plural": "how many + plural",
 "woher / wohin": "where from / where to",
 "Ist der Zug pünktlich? → ob": "Is the train on time? → ob (whether)",
 "ob … oder": "ob … oder (whether … or)",
 "Können / Könnten Sie mir sagen, …?": "Can / Could you tell me …?",
 "Wissen Sie, …?": "Do you know …?",
 "Ich möchte (gern) wissen, … (Brief)": "I would like to know … (letter)",
 "Ich frage mich, … (I wonder)": "I wonder …",
 "Mich würde interessieren, … (formell)": "I would be interested to know … (formal)",
 "Wo ist der Bahnhof? →": "Where is the station? →",
 "Wann beginnt der Kurs? →": "When does the course start? →",
 "Kommt er morgen? →": "Is he coming tomorrow? →",
 "Was hat der Arzt gesagt? →": "What did the doctor say? →",
 "Nominativ: ohne -n": "nominative: without -n",
 "Akkusativ: -n": "accusative: -n",
 "Dativ: -n": "dative: -n",
 "Genitiv: -n": "genitive: -n",
 "Nominativ": "nominative",
 "Akkusativ": "accusative",
 "Dativ": "dative",
 "Plural: -n": "plural: -n",
 "Genitiv": "genitive",
 "Anrede im Brief: Nominativ, ohne -n": "greeting in a letter: nominative, without -n",
 "Akkusativ: Herrn": "accusative: Herrn",
 "Dativ: Herrn": "dative: Herrn",
 "Plural: Herren": "plural: Herren",
 "Junge, Nominativ": "Junge, nominative",
 "Junge, Dativ": "Junge, dative",
 "Mensch, Akkusativ: -en": "Mensch, accusative: -en",
 "Mensch, Plural": "Mensch, plural",
 "der Student: Akkusativ": "der Student: accusative",
 "der Praktikant: Dativ": "der Praktikant (intern): dative",
 "der Polizist: Akkusativ": "der Polizist: accusative",
 "der Patient: Genitiv": "der Patient: genitive",
 "Akkusativ: Namen": "accusative: Namen",
 "Dativ: Namen": "dative: Namen",
 "Genitiv: Namens": "genitive: Namens",
 "ein → kein": "ein → kein",
 "Akkusativ maskulin: keinen": "accusative masculine: keinen",
 "ohne Artikel → kein (Plural, Nomen ohne Artikel)": "no article → kein (plural, nouns without an article)",
 "kein … mehr (no more)": "kein … mehr (no more)",
 "Verb: am Ende": "verb: at the end",
 "vor dem Adjektiv": "before the adjective",
 "Nomen mit bestimmtem Artikel / Possessiv": "noun with a definite article / possessive",
 "Name": "name",
 "am Satzende (ganzer Satz)": "at the end of the sentence (whole sentence)",
 "vor der Präpositionalergänzung": "before the prepositional object",
 "vor dem zweiten Verbteil": "before the second part of the verb",
 "vor einem Satzteil: Teilverneinung + sondern": "before one part of the sentence: partial negation + sondern",
 "mit Modalverb: vor dem Infinitiv": "with a modal verb: before the infinitive",
 "nie = zu keiner Zeit (never)": "nie = at no time (never)",
 "niemand = keine Person (nobody)": "niemand = no person (nobody)",
 "nichts = keine Sache (nothing)": "nichts = no thing (nothing)",
 "nirgends / nirgendwo (nowhere)": "nirgends / nirgendwo (nowhere)",
 "noch nicht (not yet)": "noch nicht (not yet)",
 "nicht mehr (no longer)": "nicht mehr (no longer)",
 "noch kein (no … yet)": "noch kein (no … yet)",
 "Gegenteil: schon (already)": "opposite: schon (already)",
 "Antwort auf eine negative Frage (yes!)": "answer to a negative question (yes!)",
 "Widerspruch": "contradiction",
 "im Imperativ: freundlicher": "in the imperative: friendlier",
 "Erinnerung (you know)": "reminder (you know)",
 "werden + Nomen: Beruf": "werden + noun: job",
 "werden + Adjektiv": "werden + adjective",
 "Perfekt: ist geworden": "perfect: ist geworden",
 "Präteritum: wurde": "simple past: wurde",
 "Vollverb: werden + Nomen / Adjektiv": "main verb: werden + noun / adjective",
 "Futur: werden + Infinitiv": "future: werden + infinitive",
 "Passiv: werden + Partizip II": "passive: werden + past participle",
 "Konjunktiv II: würde + Infinitiv": "Konjunktiv II: würde + infinitive",
 "jemand anders macht es (have something done)": "someone else does it (have something done)",
 "mit Dativ: sich die Haare schneiden lassen": "with the dative: have your hair cut",
 "Perfekt: hat … lassen (doppelter Infinitiv)": "perfect: hat … lassen (double infinitive)",
 "erlauben (let, allow)": "allow (let, allow)",
 "etwas irgendwo lassen (leave)": "leave something somewhere",
 "etwas liegen lassen (leave behind)": "etwas liegen lassen (leave behind)",
 "sich lassen = man kann (can be done)": "sich lassen = one can (can be done)",
 "Lass uns …! (Let's …)": "Lass uns …! (Let's …)",
 "Subjekt auf Position 1": "subject in position 1",
 "Zeit auf Position 1: Subjekt nach dem Verb": "time in position 1: subject after the verb",
 "Objekt auf Position 1 (Betonung)": "object in position 1 (emphasis)",
 "Nebensatz auf Position 1: dann Verb": "subordinate clause in position 1: then the verb",
 "Modalverb … Infinitiv": "modal verb … infinitive",
 "Perfekt: haben/sein … Partizip": "perfect: haben/sein … participle",
 "trennbares Verb … Vorsilbe": "separable verb … prefix",
 "Futur: werden … Infinitiv": "future: werden … infinitive",
 "zwei Nomen: Dativ vor Akkusativ": "two nouns: dative before accusative",
 "zwei Pronomen: Akkusativ vor Dativ": "two pronouns: accusative before dative",
 "Pronomen vor Nomen": "pronoun before noun",
 "Akkusativ-Pronomen vor Dativ-Nomen": "accusative pronoun before dative noun",
 "Temporal vor Lokal": "time before place",
 "Temporal – Modal – Lokal": "time – manner – place",
 "Temporal – Kausal – Modal – Lokal": "time – reason – manner – place",
 "eine Angabe auf Position 1, der Rest bleibt": "one detail in position 1, the rest stays",
 "ein Verb: am Ende": "one verb: at the end",
 "Modalverb: ganz am Ende": "modal verb: right at the end",
 "Perfekt: Hilfsverb ganz am Ende": "perfect: auxiliary right at the end",
 "Nebensatz zuerst: Verb, Verb": "subordinate clause first: verb, verb",
 "W-Frage: Verb auf Position 2": "W-question: verb in position 2",
 "Ja/Nein-Frage: Verb auf Position 1": "yes/no question: verb in position 1",
 "Imperativ (du): Verb auf Position 1, kein Subjekt": "imperative (du): verb in position 1, no subject",
 "Imperativ (Sie): Verb + Sie": "imperative (Sie): verb + Sie",
 "Subjekt: wer oder was handelt": "subject: who or what does the action",
 "nach sein": "after sein",
 "nach werden (Beruf ohne Artikel)": "after werden (job without an article)",
 "nach bleiben": "after bleiben",
 "Anrede im Brief": "greeting in a letter",
 "direktes Objekt": "direct object",
 "nach Akkusativ-Präposition (für, ohne, durch …)": "after an accusative preposition (für, ohne, durch …)",
 "Zeitangabe ohne Präposition": "time phrase without a preposition",
 "Wohin? nach Wechselpräposition": "where to? after a two-way preposition",
 "es gibt + Akkusativ": "es gibt + accusative",
 "indirektes Objekt: wer etwas bekommt": "indirect object: who receives something",
 "Verb mit Dativ": "verb with the dative",
 "nach Dativ-Präposition (aus, bei, mit, nach …)": "after a dative preposition (aus, bei, mit, nach …)",
 "Wo? nach Wechselpräposition": "where? after a two-way preposition",
 "Adjektiv + Dativ (zu kalt, egal …)": "adjective + dative (too cold, all the same …)",
 "Besitz / Zugehörigkeit": "possession / belonging",
 "Name + s (ohne Apostroph)": "name + s (no apostrophe)",
 "nach Genitiv-Präposition": "after a genitive preposition",
 "feste Zeitangabe": "fixed time phrase",
 "gesprochen: von + Dativ statt Genitiv": "spoken: von + dative instead of the genitive",
 "maskulin: der – den – dem – des": "masculine: der – den – dem – des",
 "feminin: die – die – der – der": "feminine: die – die – der – der",
 "neutral: das – das – dem – des": "neuter: das – das – dem – des",
 "Plural: die – die – den (+ n) – der": "plural: die – die – den (+ n) – der",
 "Nominativ: ein – eine – ein": "nominative: ein – eine – ein",
 "Akkusativ: nur maskulin ändert sich (einen)": "accusative: only masculine changes (einen)",
 "Dativ: einem – einer – einem": "dative: einem – einer – einem",
 "Genitiv: eines – einer – eines": "genitive: eines – einer – eines",
 "kein Plural: das Nomen steht ohne Artikel": "no plural: the noun has no article",
 "kein = nicht + ein": "kein = nicht + ein (no, not a)",
 "kein hat einen Plural": "kein has a plural",
 "mein, dein, sein … Endungen wie ein": "mein, dein, sein … same endings as ein",
 "Dativ Plural: -en": "dative plural: -en",
 "sein (er / es) oder ihr (sie)?": "sein (he / it) or ihr (she)?",
 "Nominativ: Subjekt": "nominative: subject",
 "Akkusativ: direktes Objekt": "accusative: direct object",
 "Dativ: bei Dativverben": "dative: with dative verbs",
 "nach Präposition": "after a preposition",
 "wir – uns – uns": "we – us – (to) us",
 "er = der-Wort, auch für Sachen": "er = a der word, also for things",
 "ihn = Akkusativ maskulin": "ihn = accusative masculine",
 "ihm = Dativ maskulin und neutral": "ihm = dative masculine and neuter",
 "es = das-Wort": "es = a das word",
 "ihnen = Dativ Plural": "ihnen = dative plural",
 "sie (feminin): Verb mit -t": "sie (she): verb with -t",
 "sie (Plural): Verb mit -en": "sie (they): verb with -en",
 "Sie = höfliche Anrede, immer groß": "Sie = polite you, always capitalised",
 "Ihnen = höflich im Dativ": "Ihnen = polite you in the dative",
 "ihr = Dativ feminin": "ihr = dative feminine (to her)",
 "Pronomen direkt nach dem Verb": "pronoun straight after the verb",
 "Nebensatz: Pronomen direkt nach der Konjunktion": "subordinate clause: pronoun straight after the conjunction",
 "allgemeine Regel": "general rule",
 "Verbot / Erlaubnis": "ban / permission",
 "Frage nach dem Weg": "asking the way",
 "Akkusativ: einen": "accusative: einen",
 "Dativ: einem": "dative: einem",
 "jemand = eine unbekannte Person": "jemand = an unknown person",
 "niemand = keine Person": "niemand = no person",
 "Akkusativ: niemanden / jemanden": "accusative: niemanden / jemanden",
 "Dativ: jemandem": "dative: jemandem",
 "etwas = irgendeine Sache": "etwas = some thing",
 "nichts = keine Sache": "nichts = no thing",
 "alles = alle Sachen": "alles = all things",
 "etwas / nichts + Adjektiv: groß, Endung -es": "etwas / nichts + adjective: capitalised, ending -es",
 "alles + Adjektiv: Endung -e": "alles + adjective: ending -e",
 "statt er / sie / es, betont (gesprochen)": "instead of er / sie / es, stressed (spoken)",
 "Akkusativ, oft auf Position 1": "accusative, often in position 1",
 "Dativ: dem / der / denen": "dative: dem / der / denen",
 "das = die ganze Aussage": "das = the whole statement",
 "einer / eine / eins = ein + Nomen": "einer / eine / eins = ein + noun (one)",
 "keiner / keine / keins": "keiner / keine / keins (none)",
 "Akkusativ maskulin: einen / keinen": "accusative masculine: einen / keinen",
 "Plural: welche": "plural: welche (some)",
 "nur bei du und er / sie / es": "only with du and er / sie / es",
 "ich und wir: kein Wechsel": "ich and wir: no change",
 "schlafen: er schläft": "schlafen: er schläft",
 "laufen: au → äu": "laufen: au → äu",
 "tragen, waschen, lassen": "tragen, waschen, lassen",
 "geben: du gibst, er gibt": "geben: du gibst, er gibt",
 "nehmen: er nimmt (mit mm)": "nehmen: er nimmt (with mm)",
 "sprechen: sie spricht": "sprechen: sie spricht",
 "essen: du isst, er isst": "essen: du isst, er isst",
 "Imperativ mit du: auch i": "imperative with du: also i",
 "lesen: er liest": "lesen: er liest",
 "sehen: du siehst": "sehen: du siehst",
 "empfehlen: sie empfiehlt": "empfehlen: sie empfiehlt",
 "Imperativ mit du: lies! sieh!": "imperative with du: lies! sieh!",
 "bleiben – blieb – ist geblieben": "stay – stayed – has stayed",
 "schreiben – schrieb – hat geschrieben": "write – wrote – has written",
 "einsteigen – stieg ein – ist eingestiegen": "get on – got on – has got on",
 "leihen – lieh – hat geliehen": "borrow / lend – borrowed – has borrowed",
 "scheinen – schien – hat geschienen": "shine – shone – has shone",
 "schneiden – schnitt – hat geschnitten": "cut – cut – has cut",
 "streiten – stritt – hat gestritten": "argue – argued – has argued",
 "greifen – griff – hat gegriffen": "grab – grabbed – has grabbed",
 "leiden – litt – hat gelitten": "suffer – suffered – has suffered",
 "finden – fand – hat gefunden": "find – found – has found",
 "trinken – trank – hat getrunken": "drink – drank – has drunk",
 "beginnen – begann – hat begonnen (mit o!)": "begin – began – has begun (with o!)",
 "singen – sang – hat gesungen": "sing – sang – has sung",
 "gewinnen – gewann – hat gewonnen": "win – won – has won",
 "sprechen – sprach – hat gesprochen": "speak – spoke – has spoken",
 "helfen – half – hat geholfen": "help – helped – has helped",
 "treffen – traf – hat getroffen": "meet – met – has met",
 "nehmen – nahm – hat genommen": "take – took – has taken",
 "sterben – starb – ist gestorben": "die – died – has died",
 "fahren – fuhr – ist gefahren": "drive – drove – has driven",
 "tragen – trug – hat getragen": "carry – carried – has carried",
 "schlafen – schlief – hat geschlafen": "sleep – slept – has slept",
 "fallen – fiel – ist gefallen": "fall – fell – has fallen",
 "gefallen – gefiel – hat gefallen": "please – pleased – has pleased (to like)",
 "bringen – brachte – hat gebracht": "bring – brought – has brought",
 "denken – dachte – hat gedacht": "think – thought – has thought",
 "wissen – wusste – hat gewusst": "know – knew – has known (facts)",
 "kennen – kannte – hat gekannt": "know – knew – has known (people, places)",
 "rennen – rannte – ist gerannt": "run – ran – has run",
 "ersetzt auf + Sache": "replaces auf + thing",
 "sich freuen auf: etwas kommt noch": "sich freuen auf: something still to come",
 "darauf + zu-Infinitiv": "darauf + zu-infinitive",
 "örtlich: auf dieser Sache": "place: on this thing",
 "sprechen über + Sache": "sprechen über + thing (talk about)",
 "sich ärgern über": "sich ärgern über (be annoyed about)",
 "Person: über ihn / sie – nicht darüber": "person: über ihn / sie – not darüber",
 "mit + Sache": "mit + thing",
 "anfangen mit + zu-Infinitiv": "anfangen mit + zu-infinitive (start …ing)",
 "Werkzeug: womit? – damit": "tool: womit? – damit (with what? – with it)",
 "Achtung: damit als Konjunktion (Ziel)": "careful: damit as a conjunction (aim: so that)",
 "sich interessieren für": "sich interessieren für (be interested in)",
 "dafür sein = zustimmen": "dafür sein = to agree",
 "dagegen sein = ablehnen": "dagegen sein = to be against",
 "sich bedanken für": "sich bedanken für (say thank you for)",
 "dafür = als Ausgleich": "dafür = to make up for it (but on the other hand)",
 "denken an + Sache": "denken an + thing (think of)",
 "sich erinnern an": "sich erinnern an (remember)",
 "träumen von": "träumen von (dream of)",
 "abhängen von + Nebensatz": "abhängen von + subordinate clause (depend on)",
 "davon = von dieser Menge": "davon = of this amount",
 "worauf = auf + was": "worauf = auf + was",
 "woran = an + was": "woran = an + was",
 "indirekte Frage: Verb am Ende": "indirect question: verb at the end",
 "Person: an wen? auf wen?": "person: an wen? auf wen?",
 "worüber = über + was": "worüber = über + was",
 "womit = mit + was": "womit = mit + was",
 "wofür = für + was": "wofür = für + was",
 "Person: mit wem? für wen?": "person: mit wem? für wen?",
 "als Relativwort nach alles / etwas": "as a relative word after alles / etwas",
 "Nominativ: statt das + Nomen": "nominative: instead of das + noun",
 "für einen ganzen Satz": "for a whole sentence",
 "Wer ist da? – Es ist …": "Who's there? – It's …",
 "Wetterverben": "weather verbs",
 "Uhrzeit": "clock time",
 "hell / dunkel, Jahreszeit": "light / dark, season",
 "Geräusche": "sounds",
 "Temperatur im Raum": "temperature in the room",
 "vorhanden sein": "to exist, to be there",
 "Frage: Gibt es …?": "question: Gibt es …? (Is there …?)",
 "Essen: Was gibt es heute?": "food: What's for … today?",
 "verneint: es gibt kein …": "negative: es gibt kein … (there is no …)",
 "Präteritum: es gab": "simple past: es gab (there was)",
 "Wie geht es + Dativ?": "Wie geht es + dative? (How are you?)",
 "es geht um = das Thema ist": "es geht um = the topic is (it's about)",
 "es tut mir leid": "I'm sorry",
 "es kommt darauf an": "it depends",
 "es eilig haben": "to be in a hurry",
 "es + Adjektiv + zu-Infinitiv": "es + adjective + zu-infinitive",
 "es + Verb + dass-Satz": "es + verb + dass clause",
 "es + Adjektiv + dass-Satz": "es + adjective + dass clause",
 "Passiv ohne Subjekt: es auf Position 1": "passive without a subject: es in position 1",
 "es fällt weg, wenn etwas anderes auf Position 1 steht": "es drops out when something else is in position 1",
 "Bitte: klingt weniger streng": "request: sounds less strict",
 "doch mal: freundlicher Vorschlag": "doch mal: friendly suggestion",
 "= einmal (irgendwann)": "= einmal (ever, at some point)",
 "Warte mal / Moment mal": "Warte mal / Moment mal (wait a moment)",
 "Antwort auf eine negative Frage: ja": "answer to a negative question: yes",
 "Imperativ: Aufforderung, Einladung": "imperative: prompt, invitation",
 "Erinnerung: das weißt du eigentlich": "reminder: you actually know this",
 "Wunsch mit Konjunktiv II": "wish with Konjunktiv II",
 "als Konjunktion: aber": "as a conjunction: but",
 "das wissen wir beide": "we both know that",
 "Überraschung": "surprise",
 "betont im Imperativ: Warnung": "stressed in the imperative: warning",
 "Begründung: das sieht man doch": "reason: it's obvious",
 "Frage klingt interessierter, freundlicher": "question sounds more interested, friendlier",
 "Frage mit Überraschung": "question with surprise",
 "Ungeduld / Vorwurf": "impatience / reproach",
 "als Konjunktion: weil (Position 0)": "as a conjunction: because (position 0)",
 "so ist es, man kann nichts ändern": "that's how it is, nothing can be done",
 "halt = eben (vor allem im Süden)": "halt = eben (mainly in the south)",
 "eben = gerade eben (Zeit)": "eben = just now (time)",
 "Eben! = genau (Zustimmung)": "Eben! = exactly (agreeing)",
 "Frage: Themenwechsel, nebenbei": "question: change of topic, by the way",
 "im Grunde, aber …": "basically, but …",
 "genau genommen": "strictly speaking",
 "höfliche Kritik": "polite criticism",
 "schon: Beruhigung": "schon: reassurance",
 "schon: früher als gedacht": "schon: earlier than expected",
 "schon … aber: Einschränkung": "schon … aber: limitation",
 "wohl: Vermutung": "wohl: guess",
 "wohl mit Futur: starke Vermutung": "wohl with the future: strong guess",
 "Position 1: das Verb folgt sofort": "position 1: the verb follows straight away",
 "im Mittelfeld": "in the middle field",
 "mit Tageszeit: gestern Abend, morgen früh": "with a time of day: yesterday evening, tomorrow morning",
 "übermorgen / vorgestern": "the day after tomorrow / the day before yesterday",
 "heutzutage = in unserer Zeit": "heutzutage = in our time (nowadays)",
 "früher: in der Vergangenheit, Gewohnheit": "früher: in the past, habit (used to)",
 "damals: zu dieser einen Zeit": "damals: at that one time (back then)",
 "neulich: vor kurzer Zeit": "neulich: a short time ago (recently)",
 "inzwischen: seitdem hat sich etwas geändert": "inzwischen: something has changed since (by now)",
 "bald: in kurzer Zeit": "bald: in a short time (soon)",
 "immer = 100 %": "always = 100 %",
 "meistens / oft": "usually / often",
 "manchmal / ab und zu": "sometimes / now and then",
 "selten": "rarely",
 "nie = 0 %": "never = 0 %",
 "zuerst: der erste Schritt": "zuerst: the first step",
 "danach / dann: der nächste Schritt": "danach / dann: the next step",
 "anschließend: direkt danach": "anschließend: straight afterwards",
 "zum Schluss / am Ende": "zum Schluss / am Ende (finally)",
 "schon: früher als erwartet": "schon: earlier than expected",
 "noch: es dauert weiter": "noch: it is still going on",
 "erst: später als erwartet": "erst: later than expected (not until)",
 "erst: weniger als erwartet": "erst: less than expected (only)",
 "noch nicht / nicht mehr": "not yet / no longer",
 "hier = wo ich bin": "hier = where I am",
 "dort / da = an einem anderen Ort": "dort / da = in another place",
 "oben / unten": "up / down",
 "drinnen / draußen": "inside / outside",
 "überall / nirgends": "everywhere / nowhere",
 "hin = weg vom Sprecher": "hin = away from the speaker",
 "her = zum Sprecher": "her = towards the speaker",
 "woher / wohin: Fragen": "where from / where to: questions",
 "her + Präposition: herunter, herein": "her + preposition: down, in",
 "hin und her": "back and forth",
 "gern + Verb: etwas mögen": "gern + verb: to like doing something",
 "lieber: Vergleich": "lieber: comparison (rather)",
 "am liebsten: Superlativ": "am liebsten: superlative (most of all)",
 "nicht gern": "not like doing",
 "gern als Antwort": "gern as an answer (you're welcome)",
 "leider: schade": "leider: what a pity",
 "hoffentlich: ich hoffe": "hoffentlich: I hope",
 "zum Glück: glücklicherweise": "zum Glück: luckily",
 "wahrscheinlich / vielleicht": "probably / perhaps",
 "natürlich: selbstverständlich": "natürlich: of course",
 "wohnen → die Wohnung": "live → the flat",
 "erfahren → die Erfahrung": "experience (verb) → the experience",
 "bestellen → die Bestellung": "order → the order",
 "immer feminin, Plural -en": "always feminine, plural -en",
 "sich entscheiden → die Entscheidung": "decide → the decision",
 "gesund → die Gesundheit": "healthy → health",
 "frei → die Freiheit": "free → freedom",
 "-keit nach -ig, -lich, -bar": "-keit after -ig, -lich, -bar",
 "möglich → die Möglichkeit": "possible → possibility",
 "pünktlich → die Pünktlichkeit": "punctual → punctuality",
 "immer neutral und groß geschrieben": "always neuter and capitalised",
 "beim + Infinitiv: während": "beim + infinitive: while",
 "zum + Infinitiv: Zweck": "zum + infinitive: purpose (for …ing)",
 "mit Objekt: zusammengeschrieben": "with an object: written as one word",
 "Verb → der …er (Person)": "verb → der …er (person)",
 "-in: weibliche Form": "-in: female form",
 "Plural der weiblichen Form: -innen": "plural of the female form: -innen",
 "Geräte auf -er": "devices ending in -er",
 "Stadt + er: Einwohner": "city + er: inhabitant",
 "immer das: das Mädchen": "always das: das Mädchen (the girl)",
 "oft mit Umlaut": "often with an umlaut",
 "feste Wörter": "fixed words",
 "-lein: seltener, eher geschrieben": "-lein: less common, rather written",
 "ein bisschen = ein wenig": "ein bisschen = a little",
 "das letzte Wort bestimmt den Artikel: das Haus + die Tür": "the last word decides the article: das Haus + die Tür",
 "mit Fugen-s": "with a linking -s",
 "mit Fugen-n / -en": "with a linking -n / -en",
 "Verb + Nomen: warten + das Zimmer": "verb + noun: wait + the room",
 "Adjektiv + Nomen: alt + die Stadt": "adjective + noun: old + the town",
 "freundlich → unfreundlich": "friendly → unfriendly",
 "möglich → unmöglich": "possible → impossible",
 "pünktlich → unpünktlich": "punctual → unpunctual",
 "auch bei Nomen: die Unordnung": "also with nouns: die Unordnung (the mess)",
 "-bar = man kann es …": "-bar = can be …ed (-able)",
 "-los = ohne": "-los = without (-less)",
 "-ig: die Sonne → sonnig": "-ig: the sun → sunny",
 "-lich: die Person → persönlich": "-lich: the person → personal",
 "-voll = mit viel": "-voll = full of (-ful)"
};
