/* Hören (listening) for B1: exam-style scenes that play inside the app.
   Each scene: title, where it happens (amb = the background the app
   generates: station, train, sbahn, airport, shop, radio, phone, cafe,
   hotel, bank, doctor, office, street, museum), the speakers with gender, the parts
   in order – "chime" (station gong), "ring" (phone), "beep" (voicemail) or
   [speaker, German, English] – and questions:
   ["rf", statement, true/false, why] or ["mc", question, [a, b, c], index, why].
   tools/check-alltag.mjs checks the shape. */
window.HS = [
{id:"gleis", de:"Bahnhof: Gleisänderung und Verspätung", en:"Station: platform change and delay", amb:"station", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Achtung am Gleis 7. Der ICE 578 nach Hamburg-Altona, planmäßige Abfahrt 14 Uhr 32, fährt heute von Gleis 9. Ich wiederhole: Der ICE nach Hamburg-Altona fährt heute von Gleis 9.","Attention on platform 7. ICE 578 to Hamburg-Altona, scheduled departure 14:32, leaves from platform 9 today. I repeat: the ICE to Hamburg-Altona leaves from platform 9 today."],
  "chime",
  ["A","Information zum Regionalexpress nach Kassel, Abfahrt 14 Uhr 40. Der Zug hat heute circa 25 Minuten Verspätung. Grund dafür ist eine Reparatur an einem Signal. Reisende mit Anschluss in Gießen nehmen bitte die S-Bahn um 14 Uhr 45.","Information on the regional express to Kassel, departure 14:40. The train is about 25 minutes late today. The reason is a repair to a signal. Passengers with a connection in Gießen please take the S-Bahn at 14:45."]],
 q:[["rf","Der ICE nach Hamburg fährt heute von Gleis 7 ab.",false,"Er fährt heute von Gleis 9 – Gleis 7 war das alte Gleis."],
    ["mc","Wie viel Verspätung hat der Zug nach Kassel?",["etwa 15 Minuten","etwa 25 Minuten","etwa 45 Minuten"],1,"„circa 25 Minuten Verspätung“."],
    ["mc","Warum hat der Zug Verspätung?",["wegen eines Unfalls","wegen einer Reparatur an einem Signal","wegen des Wetters"],1,"„Grund dafür ist eine Reparatur an einem Signal.“"],
    ["rf","Wer nach Gießen muss, soll die S-Bahn um 14:45 Uhr nehmen.",true,"„Reisende mit Anschluss in Gießen nehmen bitte die S-Bahn um 14 Uhr 45.“"]]},

{id:"zug", de:"Im Zug: nächster Halt und Anschlüsse", en:"On the train: next stop and connections", amb:"train", kind:"Durchsage",
 who:{A:["Zugbegleiter","m"]},
 parts:["chime",
  ["A","Meine Damen und Herren, in wenigen Minuten erreichen wir Frankfurt am Main Hauptbahnhof. Wegen einer Streckensperrung haben wir leider 15 Minuten Verspätung.","Ladies and gentlemen, in a few minutes we will reach Frankfurt am Main main station. Because of a line closure we are unfortunately 15 minutes late."],
  ["A","Ihre Anschlusszüge: Der ICE nach Stuttgart wartet heute auf uns, Sie erreichen ihn am gegenüberliegenden Gleis. Die S-Bahn zum Flughafen erreichen Sie leider nicht mehr. Die nächste fährt zehn Minuten später.","Your connecting trains: the ICE to Stuttgart is waiting for us today; you'll reach it on the opposite platform. Unfortunately you won't make the S-Bahn to the airport. The next one leaves ten minutes later."],
  ["A","Bitte denken Sie beim Aussteigen an Ihr Gepäck. Das Bordbistro in Wagen 8 ist ab Frankfurt wieder geöffnet.","Please remember your luggage when getting off. The on-board bistro in coach 8 is open again from Frankfurt."]],
 q:[["mc","Warum hat der Zug Verspätung?",["wegen einer Streckensperrung","wegen eines kranken Fahrgasts","wegen eines technischen Problems am Zug"],0,"„Wegen einer Streckensperrung …“"],
    ["rf","Der ICE nach Stuttgart wartet auf den Zug.",true,"„Der ICE nach Stuttgart wartet heute auf uns.“"],
    ["rf","Die Fahrgäste erreichen die S-Bahn zum Flughafen noch.",false,"„… erreichen Sie leider nicht mehr. Die nächste fährt zehn Minuten später.“"],
    ["mc","Was ist ab Frankfurt wieder geöffnet?",["das Bordbistro in Wagen 8","die Toiletten","das Ruheabteil"],0,"„Das Bordbistro in Wagen 8 ist ab Frankfurt wieder geöffnet.“"]]},

{id:"sbahn", de:"S-Bahn: Störung und Ersatzverkehr", en:"S-Bahn: disruption and replacement buses", amb:"sbahn", kind:"Durchsage",
 who:{A:["Ansage","m"]},
 parts:["chime",
  ["A","Eine Information für Fahrgäste der Linien S3 und S4: Wegen einer Störung am Stellwerk fahren zwischen Hauptwache und Südbahnhof zurzeit keine Züge.","Information for passengers on lines S3 and S4: because of a fault at the signal box, no trains are currently running between Hauptwache and Südbahnhof."],
  ["A","Bitte benutzen Sie die U-Bahn-Linie U1 oder die Ersatzbusse. Die Busse fahren alle zehn Minuten vom Ausgang B. Ihre Fahrkarten gelten auch in den Bussen. Wir bitten um Entschuldigung.","Please use underground line U1 or the replacement buses. The buses run every ten minutes from exit B. Your tickets are also valid on the buses. We apologise."]],
 q:[["mc","Warum fahren keine S-Bahnen?",["wegen eines Streiks","wegen einer Störung am Stellwerk","wegen Bauarbeiten"],1,"„Wegen einer Störung am Stellwerk …“"],
    ["rf","Die Ersatzbusse fahren alle fünf Minuten.",false,"„Die Busse fahren alle zehn Minuten.“"],
    ["mc","Wo fahren die Busse ab?",["am Ausgang A","am Ausgang B","am Hauptbahnhof"],1,"„… vom Ausgang B.“"],
    ["rf","Man braucht für den Bus keine neue Fahrkarte.",true,"„Ihre Fahrkarten gelten auch in den Bussen.“"]]},

{id:"flughafen", de:"Flughafen: Gate-Änderung und letzter Aufruf", en:"Airport: gate change and final call", amb:"airport", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Passagiere des Fluges LH 1132 nach Lissabon, bitte beachten Sie: Ihr Flug startet heute nicht von Gate A 22, sondern von Gate B 14. Das Boarding beginnt in 20 Minuten.","Passengers on flight LH 1132 to Lisbon, please note: your flight departs today not from gate A22 but from gate B14. Boarding begins in 20 minutes."],
  "chime",
  ["A","Letzter Aufruf für den Passagier Karim Haddad, gebucht auf den Flug nach Istanbul. Bitte kommen Sie sofort zum Gate C 5. Das Gate schließt in fünf Minuten.","Final call for passenger Karim Haddad, booked on the flight to Istanbul. Please come to gate C5 immediately. The gate closes in five minutes."]],
 q:[["mc","Von welchem Gate startet der Flug nach Lissabon?",["A 22","B 14","C 5"],1,"„… nicht von Gate A 22, sondern von Gate B 14.“"],
    ["rf","Das Boarding nach Lissabon beginnt sofort.",false,"„Das Boarding beginnt in 20 Minuten.“"],
    ["rf","Herr Haddad soll schnell zum Gate kommen.",true,"„Bitte kommen Sie sofort zum Gate C 5.“"],
    ["mc","Wann schließt das Gate für den Flug nach Istanbul?",["in fünf Minuten","in 15 Minuten","in 20 Minuten"],0,"„Das Gate schließt in fünf Minuten.“"]]},

{id:"kaufhaus", de:"Kaufhaus: Angebot und Kind sucht Eltern", en:"Department store: offer and lost child", amb:"shop", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Liebe Kundinnen und Kunden, nur heute: In unserer Sportabteilung im dritten Stock sind alle Laufschuhe 30 Prozent günstiger. Das Angebot gilt bis 16 Uhr.","Dear customers, today only: in our sports department on the third floor all running shoes are 30 per cent cheaper. The offer is valid until 4 pm."],
  "chime",
  ["A","Der kleine Jonas, fünf Jahre alt, sucht seine Eltern. Er wartet an der Information im Erdgeschoss, direkt am Haupteingang.","Little Jonas, five years old, is looking for his parents. He is waiting at the information desk on the ground floor, right by the main entrance."],
  "chime",
  ["A","Wir weisen Sie darauf hin, dass unser Haus in 15 Minuten schließt. Bitte gehen Sie zu den Kassen.","Please note that our store closes in 15 minutes. Please make your way to the checkouts."]],
 q:[["mc","Wo gibt es das Angebot?",["im Erdgeschoss","im zweiten Stock","im dritten Stock"],2,"„… Sportabteilung im dritten Stock …“"],
    ["rf","Das Angebot gilt den ganzen Tag.",false,"„Das Angebot gilt bis 16 Uhr.“"],
    ["mc","Wo wartet Jonas?",["an der Kasse","an der Information im Erdgeschoss","in der Spielecke"],1,"„… an der Information im Erdgeschoss, direkt am Haupteingang.“"],
    ["rf","Das Kaufhaus schließt bald.",true,"„… dass unser Haus in 15 Minuten schließt.“"]]},

{id:"radio", de:"Radio: Verkehr und Wetter", en:"Radio: traffic and weather", amb:"radio", kind:"Radio",
 who:{A:["Moderatorin","f"],B:["Verkehrsredaktion","m"]},
 parts:[
  ["A","Und jetzt die Verkehrsmeldungen mit Tobias.","And now the traffic news with Tobias."],
  ["B","Auf der A5 Frankfurt Richtung Kassel gibt es nach einem Unfall zwischen Friedberg und Butzbach acht Kilometer Stau. Die Polizei empfiehlt, die B3 zu benutzen. In der Frankfurter Innenstadt ist die Mainzer Landstraße wegen Bauarbeiten bis Freitag gesperrt.","On the A5 from Frankfurt towards Kassel there's an eight-kilometre traffic jam between Friedberg and Butzbach after an accident. The police recommend using the B3. In Frankfurt city centre, Mainzer Landstraße is closed until Friday because of roadworks."],
  ["A","Danke, Tobias. Und das Wetter: Heute bleibt es trocken bei bis zu 18 Grad. Morgen kommen von Westen Wolken, und am Nachmittag regnet es. Am Wochenende wird es wieder sonnig.","Thanks, Tobias. And the weather: today stays dry at up to 18 degrees. Tomorrow clouds come from the west and it rains in the afternoon. At the weekend it will be sunny again."]],
 q:[["mc","Warum gibt es auf der A5 Stau?",["wegen Bauarbeiten","wegen eines Unfalls","wegen des Wetters"],1,"„… nach einem Unfall …“"],
    ["rf","Die Polizei empfiehlt, die B3 zu nehmen.",true,"„Die Polizei empfiehlt, die B3 zu benutzen.“"],
    ["mc","Wie lange ist die Mainzer Landstraße gesperrt?",["nur heute","bis Freitag","bis zum Wochenende"],1,"„… wegen Bauarbeiten bis Freitag gesperrt.“"],
    ["rf","Morgen Nachmittag regnet es.",true,"„Morgen kommen von Westen Wolken, und am Nachmittag regnet es.“"]]},

{id:"praxis", de:"Anrufbeantworter: Arztpraxis", en:"Voicemail: doctor's practice", amb:"phone", kind:"Telefon",
 who:{A:["Praxis","f"]},
 parts:["ring","beep",
  ["A","Guten Tag, Sie sind verbunden mit der Praxis Dr. Schulz. Unsere Praxis ist vom 4. bis 15. August wegen Urlaub geschlossen.","Hello, you've reached Dr Schulz's practice. Our practice is closed for holidays from 4 to 15 August."],
  ["A","In dieser Zeit vertritt uns die Praxis Dr. Lang in der Goethestraße 5, Telefon 069 23 45 67. Rezepte können Sie weiterhin online bestellen.","During this time we're covered by Dr Lang's practice at Goethestraße 5, phone 069 23 45 67. You can still order prescriptions online."],
  ["A","Außerhalb der Sprechzeiten erreichen Sie den ärztlichen Bereitschaftsdienst unter 116 117. In lebensbedrohlichen Notfällen wählen Sie bitte die 112.","Outside opening hours you can reach the out-of-hours medical service on 116 117. In life-threatening emergencies please dial 112."]],
 q:[["rf","Die Praxis ist im August zwei Wochen geschlossen.",true,"„… vom 4. bis 15. August wegen Urlaub geschlossen.“"],
    ["mc","Wer vertritt die Praxis?",["Dr. Lang","Dr. Schulz","das Krankenhaus"],0,"„In dieser Zeit vertritt uns die Praxis Dr. Lang …“"],
    ["rf","Rezepte kann man in dieser Zeit nicht bekommen.",false,"„Rezepte können Sie weiterhin online bestellen.“"],
    ["mc","Welche Nummer wählt man in einem lebensbedrohlichen Notfall?",["116 117","112","069 23 45 67"],1,"„In lebensbedrohlichen Notfällen wählen Sie bitte die 112.“"]]},

{id:"werkstatt", de:"Anrufbeantworter: Nachricht von der Werkstatt", en:"Voicemail: message from the garage", amb:"phone", kind:"Telefon",
 who:{A:["Werkstatt","m"]},
 parts:["beep",
  ["A","Guten Tag, Herr Keller, hier ist Martin Braun vom Autohaus Braun. Wir haben Ihr Auto untersucht: Die Bremsen vorne müssen gewechselt werden, das kostet ungefähr 240 Euro.","Hello Mr Keller, this is Martin Braun from Braun garage. We've examined your car: the front brakes need to be changed; that costs about 240 euros."],
  ["A","Die Inspektion ist schon fertig. Wenn Sie mit der Reparatur einverstanden sind, rufen Sie uns bitte bis heute 16 Uhr zurück. Dann ist das Auto morgen ab 10 Uhr abholbereit.","The inspection is already done. If you agree to the repair, please call us back by 4 pm today. Then the car will be ready to collect from 10 am tomorrow."],
  ["A","Unsere Nummer ist 069 88 71 20. Auf Wiederhören.","Our number is 069 88 71 20. Goodbye."]],
 q:[["mc","Was muss am Auto repariert werden?",["die Bremsen vorne","die Reifen","die Klimaanlage"],0,"„Die Bremsen vorne müssen gewechselt werden …“"],
    ["mc","Wie viel kostet die Reparatur ungefähr?",["140 Euro","240 Euro","420 Euro"],1,"„… das kostet ungefähr 240 Euro.“"],
    ["rf","Herr Keller soll bis 16 Uhr zurückrufen.",true,"„… rufen Sie uns bitte bis heute 16 Uhr zurück.“"],
    ["rf","Das Auto ist heute Abend fertig.",false,"„… morgen ab 10 Uhr abholbereit.“"]]},

{id:"restaurant", de:"Im Restaurant: bestellen, reklamieren, zahlen", en:"Restaurant: ordering, complaining, paying", amb:"cafe", kind:"Gespräch",
 who:{A:["Kellner","m"],B:["Gast","f"]},
 parts:[
  ["A","Guten Abend! Haben Sie schon gewählt?","Good evening! Have you decided?"],
  ["B","Ja. Ich hätte gern die Tomatensuppe und danach den Lachs mit Kartoffeln. Ist in der Soße Sahne? Ich vertrage keine Milchprodukte.","Yes. I'd like the tomato soup and then the salmon with potatoes. Is there cream in the sauce? I can't tolerate dairy."],
  ["A","Ja, leider. Aber wir können den Lachs auch mit Olivenöl und Zitrone machen.","Yes, unfortunately. But we can also make the salmon with olive oil and lemon."],
  ["B","Das ist perfekt. Und zu trinken ein stilles Wasser, bitte.","That's perfect. And to drink a still water, please."],
  ["B","Entschuldigung, die Suppe ist leider nur lauwarm.","Excuse me, the soup is unfortunately only lukewarm."],
  ["A","Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue. Der Nachtisch geht dann aufs Haus.","Oh, I'm sorry. I'll bring you a new one straight away. Dessert is then on the house."],
  ["B","Das ist sehr nett. Ich möchte dann bitte zahlen. Kann ich mit Karte bezahlen?","That's very kind. I'd like to pay then, please. Can I pay by card?"],
  ["A","Natürlich. Das macht 27 Euro 50.","Of course. That's 27.50 euros."],
  ["B","Machen Sie 30. Stimmt so.","Make it 30. Keep the change."]],
 q:[["mc","Was bestellt die Frau als Hauptgericht?",["Tomatensuppe","Lachs mit Kartoffeln","Nudeln mit Sahnesoße"],1,"„… danach den Lachs mit Kartoffeln.“"],
    ["rf","Die Frau darf keine Milchprodukte essen.",true,"„Ich vertrage keine Milchprodukte.“"],
    ["mc","Was ist das Problem mit der Suppe?",["Sie ist zu salzig.","Sie ist nur lauwarm.","Es ist die falsche Suppe."],1,"„… die Suppe ist leider nur lauwarm.“"],
    ["mc","Wie viel Trinkgeld gibt sie?",["50 Cent","2 Euro 50","5 Euro"],1,"27,50 € → „Machen Sie 30“ = 2,50 € Trinkgeld."]]},

{id:"hotel", de:"Im Hotel: Check-in und ein Problem", en:"Hotel: check-in and a problem", amb:"hotel", kind:"Gespräch",
 who:{A:["Rezeption","f"],B:["Gast","m"]},
 parts:[
  ["A","Guten Abend und herzlich willkommen. Haben Sie reserviert?","Good evening and welcome. Do you have a reservation?"],
  ["B","Ja, auf den Namen Okafor, ein Einzelzimmer für drei Nächte.","Yes, under the name Okafor, a single room for three nights."],
  ["A","Richtig, Herr Okafor. Frühstück ist inklusive, von 6 Uhr 30 bis 10 Uhr im ersten Stock. Das WLAN-Passwort steht auf Ihrer Karte.","That's right, Mr Okafor. Breakfast is included, from 6:30 to 10 on the first floor. The Wi-Fi password is on your card."],
  ["B","Danke. Kann ich mein Auto in der Garage parken?","Thank you. Can I park my car in the garage?"],
  ["A","Ja, das kostet 12 Euro pro Nacht.","Yes, that costs 12 euros a night."],
  ["B","Entschuldigung, ich bin's noch einmal aus Zimmer 305. Die Heizung funktioniert nicht, und im Zimmer ist es sehr kalt.","Excuse me, it's me again from room 305. The heating isn't working and it's very cold in the room."],
  ["A","Das tut mir leid. Unser Techniker ist heute nicht mehr da. Ich gebe Ihnen gern ein anderes Zimmer, die 412 im vierten Stock.","I'm sorry. Our technician has gone for the day. I'm happy to give you another room, 412 on the fourth floor."],
  ["B","Sehr gut, danke. Bis wann muss ich am Freitag auschecken?","Very good, thank you. By when do I have to check out on Friday?"],
  ["A","Bis 11 Uhr. Ihr Gepäck können Sie danach gern bei uns lassen.","By 11. You're welcome to leave your luggage with us afterwards."]],
 q:[["mc","Wie lange bleibt Herr Okafor?",["eine Nacht","drei Nächte","eine Woche"],1,"„… ein Einzelzimmer für drei Nächte.“"],
    ["rf","Das Frühstück kostet extra.",false,"„Frühstück ist inklusive …“"],
    ["mc","Was kostet die Garage?",["nichts","12 Euro pro Nacht","20 Euro pro Nacht"],1,"„… das kostet 12 Euro pro Nacht.“"],
    ["rf","Herr Okafor bekommt ein anderes Zimmer.",true,"„Ich gebe Ihnen gern ein anderes Zimmer, die 412 …“"]]},

{id:"bank", de:"Bei der Bank: Karte verloren", en:"At the bank: lost card", amb:"bank", kind:"Gespräch",
 who:{A:["Bankberater","m"],B:["Kundin","f"]},
 parts:[
  ["A","Guten Tag, was kann ich für Sie tun?","Hello, what can I do for you?"],
  ["B","Ich habe gestern Abend meine Geldbörse mit meiner Bankkarte verloren.","Last night I lost my wallet with my bank card."],
  ["A","Haben Sie die Karte schon sperren lassen?","Have you already had the card blocked?"],
  ["B","Ja, ich habe sofort beim Sperr-Notruf 116 116 angerufen.","Yes, I called the blocking hotline 116 116 straight away."],
  ["A","Sehr gut. Ich sehe, dass mit Ihrer Karte seitdem nichts bezahlt wurde. Ich bestelle Ihnen eine neue. Sie kommt in etwa fünf Werktagen per Post.","Very good. I can see that nothing has been paid with your card since then. I'll order you a new one. It will arrive by post in about five working days."],
  ["B","Und die PIN?","And the PIN?"],
  ["A","Die bekommen Sie mit einem separaten Brief. Die neue Karte kostet leider 15 Euro.","You'll get it in a separate letter. The new card unfortunately costs 15 euros."],
  ["B","Kann ich bis dahin trotzdem Geld abheben?","Can I still withdraw money until then?"],
  ["A","Ja, hier am Schalter mit Ihrem Ausweis.","Yes, here at the counter with your ID."]],
 q:[["rf","Die Frau hat die Karte noch nicht sperren lassen.",false,"„Ja, ich habe sofort beim Sperr-Notruf 116 116 angerufen.“"],
    ["mc","Wann kommt die neue Karte?",["morgen","in etwa fünf Werktagen","in zwei Wochen"],1,"„Sie kommt in etwa fünf Werktagen per Post.“"],
    ["mc","Wie viel kostet die neue Karte?",["nichts","5 Euro","15 Euro"],2,"„Die neue Karte kostet leider 15 Euro.“"],
    ["rf","Bis die Karte kommt, kann sie am Schalter Geld abheben.",true,"„Ja, hier am Schalter mit Ihrem Ausweis.“"]]},

{id:"arzt", de:"Beim Arzt: Rückenschmerzen", en:"At the doctor's: back pain", amb:"doctor", kind:"Gespräch",
 who:{A:["Ärztin","f"],B:["Patient","m"]},
 parts:[
  ["A","Guten Morgen. Was kann ich für Sie tun?","Good morning. What can I do for you?"],
  ["B","Ich habe seit zehn Tagen starke Schmerzen im unteren Rücken. Manchmal ziehen sie bis ins linke Bein.","For ten days I've had bad pain in my lower back. Sometimes it goes down into my left leg."],
  ["A","Haben Sie etwas Schweres gehoben?","Did you lift something heavy?"],
  ["B","Ja, ich bin letzte Woche umgezogen.","Yes, I moved house last week."],
  ["A","Das erklärt einiges. Ich verschreibe Ihnen ein Schmerzmittel. Nehmen Sie morgens und abends eine Tablette, immer nach dem Essen, höchstens fünf Tage lang.","That explains a lot. I'll prescribe you a painkiller. Take one tablet morning and evening, always after food, for no more than five days."],
  ["A","Außerdem bekommen Sie sechs Termine Physiotherapie. Wenn es in zwei Wochen nicht besser ist, kommen Sie bitte wieder.","You'll also get six physiotherapy sessions. If it isn't better in two weeks, please come back."],
  ["B","Brauche ich eine Krankschreibung? Ich arbeite im Lager.","Do I need a sick note? I work in a warehouse."],
  ["A","Ja, ich schreibe Sie bis Freitag krank.","Yes, I'll sign you off sick until Friday."]],
 q:[["mc","Seit wann hat der Mann Schmerzen?",["seit zwei Tagen","seit zehn Tagen","seit zwei Wochen"],1,"„Ich habe seit zehn Tagen starke Schmerzen …“"],
    ["mc","Was ist wahrscheinlich der Grund?",["ein Sportunfall","der Umzug","die Arbeit im Büro"],1,"„Ja, ich bin letzte Woche umgezogen.“ – „Das erklärt einiges.“"],
    ["rf","Er soll die Tabletten dreimal am Tag nehmen.",false,"„… morgens und abends eine Tablette …“ = zweimal am Tag."],
    ["rf","Er ist bis Freitag krankgeschrieben.",true,"„Ja, ich schreibe Sie bis Freitag krank.“"]]},

{id:"buergeramt", de:"Bürgeramt: Anmeldung", en:"Citizens' office: registration", amb:"office", kind:"Gespräch",
 who:{A:["Sachbearbeiterin","f"],B:["Sie","m"]},
 parts:[
  ["A","Guten Tag, die Nummer 128? Bitte nehmen Sie Platz. Was kann ich für Sie tun?","Hello, number 128? Please take a seat. What can I do for you?"],
  ["B","Ich möchte mich anmelden. Ich wohne seit dem 1. September in der Berger Straße.","I'd like to register. I've been living on Berger Straße since 1 September."],
  ["A","Dann haben Sie noch genau eine Woche Zeit, die Frist ist zwei Wochen. Haben Sie die Wohnungsgeberbestätigung dabei?","Then you have exactly one week left; the deadline is two weeks. Do you have the landlord's confirmation with you?"],
  ["B","Oh nein, die liegt noch zu Hause. Ich habe nur meinen Pass und den Mietvertrag.","Oh no, it's still at home. I only have my passport and the rental contract."],
  ["A","Der Mietvertrag reicht leider nicht. Sie können die Bestätigung aber auch per E-Mail schicken, dann schließe ich die Anmeldung heute ab.","Unfortunately the rental contract isn't enough. But you can also send the confirmation by email, then I'll complete the registration today."],
  ["B","Das mache ich sofort. Kostet die Anmeldung etwas?","I'll do that straight away. Does registration cost anything?"],
  ["A","Nein, sie ist kostenlos. Die Meldebescheinigung schicken wir Ihnen dann per Post.","No, it's free. We'll then send you the registration certificate by post."]],
 q:[["mc","Seit wann wohnt der Mann in der Berger Straße?",["seit dem 1. August","seit dem 1. September","seit zwei Monaten"],1,"„Ich wohne seit dem 1. September …“"],
    ["rf","Die Frist für die Anmeldung ist zwei Wochen.",true,"„… die Frist ist zwei Wochen.“"],
    ["mc","Was fehlt?",["der Pass","der Mietvertrag","die Wohnungsgeberbestätigung"],2,"„Oh nein, die liegt noch zu Hause.“ – „Der Mietvertrag reicht leider nicht.“"],
    ["rf","Die Anmeldung kostet 15 Euro.",false,"„Nein, sie ist kostenlos.“"]]},

{id:"arbeit", de:"Arbeit: Ansage der Teamleiterin", en:"Work: team leader's briefing", amb:"office", kind:"Ansage",
 who:{A:["Teamleiterin","f"]},
 parts:[
  ["A","Guten Morgen zusammen, kurz ein paar Informationen für heute. Frau Petrović ist krank, deshalb übernimmt Herr Kaya ihre Schicht an der Kasse.","Good morning everyone, a few quick pieces of information for today. Ms Petrović is ill, so Mr Kaya is taking over her shift at the checkout."],
  ["A","Um 11 Uhr kommt eine große Lieferung. Bitte helft alle beim Auspacken, damit die Regale bis 14 Uhr voll sind.","A big delivery is coming at 11. Please all help with unpacking so that the shelves are full by 2 pm."],
  ["A","Die Teambesprechung ist diese Woche nicht am Mittwoch, sondern am Donnerstag um 8 Uhr. Und denkt bitte daran, eure Urlaubswünsche bis Freitag einzutragen.","The team meeting this week is not on Wednesday but on Thursday at 8. And please remember to enter your holiday requests by Friday."]],
 q:[["rf","Herr Kaya ist heute krank.",false,"Frau Petrović ist krank; Herr Kaya übernimmt ihre Schicht."],
    ["mc","Wann kommt die Lieferung?",["um 8 Uhr","um 11 Uhr","um 14 Uhr"],1,"„Um 11 Uhr kommt eine große Lieferung.“"],
    ["mc","Wann ist die Teambesprechung?",["am Mittwoch","am Donnerstag um 8 Uhr","am Freitag"],1,"„… nicht am Mittwoch, sondern am Donnerstag um 8 Uhr.“"],
    ["rf","Die Urlaubswünsche müssen bis Freitag eingetragen werden.",true,"„… eure Urlaubswünsche bis Freitag einzutragen.“"]]},

{id:"bus", de:"Bus: Umleitung wegen einer Baustelle", en:"Bus: diversion because of roadworks", amb:"street", kind:"Durchsage",
 who:{A:["Busfahrer","m"]},
 parts:["chime",
  ["A","Liebe Fahrgäste, wegen einer Baustelle in der Friedberger Landstraße fährt die Linie 30 heute eine Umleitung. Die Haltestellen Merianplatz und Bornheim Mitte werden nicht angefahren.","Dear passengers, because of roadworks on Friedberger Landstraße, line 30 is taking a diversion today. The Merianplatz and Bornheim Mitte stops will not be served."],
  ["A","Fahrgäste nach Bornheim steigen bitte an der nächsten Haltestelle, Höhenstraße, aus und nehmen die U-Bahn-Linie U4. Die Umleitung dauert voraussichtlich bis Ende des Monats.","Passengers for Bornheim please get off at the next stop, Höhenstraße, and take underground line U4. The diversion is expected to last until the end of the month."]],
 q:[["mc","Warum fährt der Bus eine Umleitung?",["wegen eines Unfalls","wegen einer Baustelle","wegen einer Demonstration"],1,"„… wegen einer Baustelle in der Friedberger Landstraße …“"],
    ["rf","Der Bus hält heute am Merianplatz.",false,"„Die Haltestellen Merianplatz und Bornheim Mitte werden nicht angefahren.“"],
    ["mc","Was sollen Fahrgäste nach Bornheim tun?",["im Bus bleiben","an der Höhenstraße in die U4 umsteigen","ein Taxi nehmen"],1,"„… steigen bitte an der nächsten Haltestelle, Höhenstraße, aus und nehmen die U-Bahn-Linie U4.“"],
    ["rf","Die Umleitung gibt es nur heute.",false,"„Die Umleitung dauert voraussichtlich bis Ende des Monats.“"]]},

{id:"ausfall", de:"Bahnhof: Zug fällt aus – Ersatzverkehr", en:"Station: train cancelled – replacement service", amb:"station", kind:"Durchsage",
 who:{A:["Ansage","m"]},
 parts:["chime",
  ["A","Information zur Regionalbahn nach Gießen, Abfahrt 17 Uhr 12 von Gleis 4: Dieser Zug fällt heute leider aus. Grund ist ein Polizeieinsatz auf der Strecke.","Information on the regional train to Gießen, departure 17:12 from platform 4: unfortunately this train is cancelled today. The reason is a police operation on the line."],
  ["A","Zwischen Friedberg und Gießen ist ein Ersatzverkehr mit Bussen eingerichtet. Die Busse fahren vor dem Bahnhofsgebäude ab, Ausgang Nord. Reisende nach Bad Nauheim können auch den Regionalexpress um 17 Uhr 25 von Gleis 6 benutzen.","A replacement bus service has been set up between Friedberg and Gießen. The buses leave in front of the station building, north exit. Passengers to Bad Nauheim can also use the regional express at 17:25 from platform 6."],
  ["A","Ihre Fahrkarten behalten ihre Gültigkeit. Wir bitten um Ihr Verständnis.","Your tickets remain valid. We ask for your understanding."]],
 q:[["rf","Die Regionalbahn nach Gießen hat nur Verspätung.",false,"„Dieser Zug fällt heute leider aus.“"],
    ["mc","Was ist der Grund?",["ein Polizeieinsatz","ein Sturm","ein kranker Lokführer"],0,"„Grund ist ein Polizeieinsatz auf der Strecke.“"],
    ["mc","Wo fahren die Ersatzbusse ab?",["an Gleis 4","vor dem Bahnhofsgebäude, Ausgang Nord","am Ausgang Süd"],1,"„Die Busse fahren vor dem Bahnhofsgebäude ab, Ausgang Nord.“"],
    ["rf","Nach Bad Nauheim kann man auch mit dem Regionalexpress um 17:25 Uhr fahren.",true,"„Reisende nach Bad Nauheim können auch den Regionalexpress um 17 Uhr 25 … benutzen.“"]]},

{id:"museum", de:"Museum: Begrüßung bei einer Führung", en:"Museum: welcome at a guided tour", amb:"museum", kind:"Ansage",
 who:{A:["Museumsführerin","f"]},
 parts:[
  ["A","Herzlich willkommen im Historischen Museum! Mein Name ist Carla Weiß, und ich begleite Sie heute durch die Ausstellung über die Geschichte unserer Stadt. Die Führung dauert ungefähr 90 Minuten.","Welcome to the Historical Museum! My name is Carla Weiß, and today I'll guide you through the exhibition about the history of our city. The tour lasts about 90 minutes."],
  ["A","Wir beginnen im Erdgeschoss mit dem Mittelalter und gehen dann in den ersten Stock, wo Sie Fotos aus der Nachkriegszeit sehen. Nach etwa 45 Minuten machen wir eine Pause von zehn Minuten im Museumscafé.","We start on the ground floor with the Middle Ages and then go up to the first floor, where you'll see photos from the post-war period. After about 45 minutes we'll take a ten-minute break in the museum café."],
  ["A","Bitte beachten Sie: Fotografieren ist erlaubt, aber ohne Blitz. Jacken und große Taschen geben Sie bitte an der Garderobe ab. Die Garderobe ist kostenlos.","Please note: taking photos is allowed, but without flash. Please leave jackets and large bags at the cloakroom. The cloakroom is free."]],
 q:[["mc","Wie lange dauert die Führung?",["45 Minuten","90 Minuten","zwei Stunden"],1,"„Die Führung dauert ungefähr 90 Minuten.“"],
    ["rf","Im ersten Stock sieht man Fotos aus der Nachkriegszeit.",true,"„… in den ersten Stock, wo Sie Fotos aus der Nachkriegszeit sehen.“"],
    ["mc","Was ist erlaubt?",["mit Blitz fotografieren","ohne Blitz fotografieren","große Taschen mitnehmen"],1,"„Fotografieren ist erlaubt, aber ohne Blitz.“"],
    ["rf","Die Garderobe kostet zwei Euro.",false,"„Die Garderobe ist kostenlos.“"]]},

{id:"hausverwaltung", de:"Anrufbeantworter: Hausverwaltung", en:"Voicemail: property management", amb:"phone", kind:"Telefon",
 who:{A:["Hausverwaltung","f"]},
 parts:["beep",
  ["A","Guten Tag, hier ist Frau Winter von der Hausverwaltung Keller. Diese Nachricht ist für alle Mieter in der Goethestraße 12.","Hello, this is Ms Winter from Keller property management. This message is for all tenants at Goethestraße 12."],
  ["A","Am kommenden Dienstag wird zwischen 9 und 13 Uhr das Wasser abgestellt, weil die Rohre im Keller erneuert werden. Bitte stellen Sie sich vorher Wasser bereit.","Next Tuesday the water will be turned off between 9 am and 1 pm because the pipes in the basement are being replaced. Please put some water aside beforehand."],
  ["A","Außerdem kommt am Donnerstag der Schornsteinfeger. Wenn Sie an diesem Tag nicht zu Hause sind, geben Sie bitte Ihrem Nachbarn einen Schlüssel oder rufen Sie uns unter 069 45 67 89 an.","The chimney sweep is also coming on Thursday. If you're not at home that day, please give your neighbour a key or call us on 069 45 67 89."]],
 q:[["rf","Die Nachricht ist nur für einen Mieter.",false,"„Diese Nachricht ist für alle Mieter in der Goethestraße 12.“"],
    ["mc","Wann gibt es kein Wasser?",["am Dienstag von 9 bis 13 Uhr","am Donnerstag den ganzen Tag","am Dienstagabend"],0,"„Am kommenden Dienstag wird zwischen 9 und 13 Uhr das Wasser abgestellt …“"],
    ["mc","Warum wird das Wasser abgestellt?",["Die Rohre im Keller werden erneuert.","Die Heizung wird repariert.","Der Schornsteinfeger kommt."],0,"„… weil die Rohre im Keller erneuert werden.“"],
    ["rf","Wer am Donnerstag nicht da ist, kann dem Nachbarn einen Schlüssel geben.",true,"„… geben Sie bitte Ihrem Nachbarn einen Schlüssel …“"]]},

{id:"kita", de:"Anrufbeantworter: Nachricht von der Kita", en:"Voicemail: message from the nursery", amb:"phone", kind:"Telefon",
 who:{A:["Erzieherin","f"]},
 parts:["beep",
  ["A","Hallo, Frau Rossi, hier ist Sandra von der Kita Sonnenschein. Emma hat seit dem Mittagessen leichtes Fieber, ungefähr 38 Grad, und möchte gern nach Hause.","Hello Ms Rossi, this is Sandra from Sonnenschein nursery. Emma has had a slight fever since lunch, about 38 degrees, and would like to go home."],
  ["A","Könnten Sie sie bitte bis spätestens 15 Uhr abholen? Wenn Sie es nicht schaffen, darf laut Ihrem Formular auch Emmas Oma kommen.","Could you please pick her up by 3 pm at the latest? If you can't make it, according to your form Emma's grandma may also come."],
  ["A","Und noch eine Information: Der Elternabend ist nicht am Mittwoch, sondern schon am Montag um 19 Uhr. Bis später!","And one more piece of information: the parents' evening is not on Wednesday but already on Monday at 7 pm. See you later!"]],
 q:[["mc","Was hat Emma?",["Bauchschmerzen","leichtes Fieber","eine Verletzung"],1,"„Emma hat seit dem Mittagessen leichtes Fieber …“"],
    ["rf","Emma soll bis 15 Uhr abgeholt werden.",true,"„Könnten Sie sie bitte bis spätestens 15 Uhr abholen?“"],
    ["rf","Nur die Mutter darf Emma abholen.",false,"„… darf laut Ihrem Formular auch Emmas Oma kommen.“"],
    ["mc","Wann ist der Elternabend?",["am Mittwoch um 19 Uhr","am Montag um 19 Uhr","am Montag um 15 Uhr"],1,"„… nicht am Mittwoch, sondern schon am Montag um 19 Uhr.“"]]},

{id:"nachrichten", de:"Radio: Kurznachrichten", en:"Radio: short news", amb:"radio", kind:"Radio",
 who:{A:["Nachrichtensprecher","m"]},
 parts:["chime",
  ["A","Hessischer Rundfunk, die Nachrichten. Die Gewerkschaft der Lokführer hat für morgen einen Streik angekündigt. Von 4 Uhr morgens bis 18 Uhr fahren im Regionalverkehr nur wenige Züge. Die S-Bahnen in Frankfurt sind nicht betroffen.","Hessischer Rundfunk, the news. The train drivers' union has announced a strike for tomorrow. From 4 am to 6 pm only a few regional trains will run. S-Bahn trains in Frankfurt are not affected."],
  ["A","Die Stadt Frankfurt baut bis 2030 zehn neue Kitas. Damit sollen rund 900 zusätzliche Plätze für Kinder unter sechs Jahren entstehen.","The city of Frankfurt is building ten new nurseries by 2030. This is intended to create around 900 additional places for children under six."],
  ["A","Und das Wetter: Heute Nacht kommt ein Sturm aus Westen. Der Wetterdienst warnt vor umstürzenden Bäumen und bittet, nicht in den Wald zu gehen. Morgen wird es kühler, höchstens 12 Grad.","And the weather: tonight a storm is coming from the west. The weather service warns of falling trees and asks people not to go into the woods. Tomorrow will be cooler, at most 12 degrees."]],
 q:[["rf","Morgen fahren auch die S-Bahnen in Frankfurt nicht.",false,"„Die S-Bahnen in Frankfurt sind nicht betroffen.“"],
    ["mc","Wie lange dauert der Streik?",["den ganzen Tag","von 4 bis 18 Uhr","bis zum Wochenende"],1,"„Von 4 Uhr morgens bis 18 Uhr …“"],
    ["mc","Wie viele neue Kita-Plätze soll es geben?",["ungefähr 90","ungefähr 900","ungefähr 2030"],1,"„… rund 900 zusätzliche Plätze …“"],
    ["rf","Der Wetterdienst rät, heute Nacht nicht in den Wald zu gehen.",true,"„… warnt vor umstürzenden Bäumen und bittet, nicht in den Wald zu gehen.“"]]},

{id:"kasse", de:"Supermarkt: an der Kasse", en:"Supermarket: at the checkout", amb:"shop", kind:"Gespräch",
 who:{A:["Kassiererin","f"],B:["Kunde","m"]},
 parts:[
  ["A","Hallo! Sammeln Sie Punkte? Haben Sie eine Kundenkarte?","Hello! Do you collect points? Do you have a loyalty card?"],
  ["B","Nein, leider nicht. Aber ich habe hier noch einen Pfandbon über drei Euro 25.","No, unfortunately not. But I've got a deposit receipt for 3.25 euros here."],
  ["A","Danke, den ziehe ich ab. Die Milch ist heute übrigens im Angebot: Wenn Sie zwei nehmen, bekommen Sie die dritte gratis.","Thanks, I'll deduct it. By the way, the milk is on offer today: if you take two, you get the third free."],
  ["B","Ach so, dann hole ich schnell noch eine. Einen Moment bitte.","Oh, then I'll quickly get another one. One moment, please."],
  ["A","Kein Problem. So, das macht dann 23 Euro 40 minus Pfand, also 20 Euro 15.","No problem. Right, that comes to 23.40 minus the deposit, so 20.15."],
  ["B","Kann ich mit dem Handy bezahlen?","Can I pay with my phone?"],
  ["A","Ja, halten Sie es einfach hier an das Gerät. Möchten Sie den Kassenbon?","Yes, just hold it against the device here. Would you like the receipt?"],
  ["B","Ja, bitte. Und eine Tüte, bitte.","Yes, please. And a bag, please."],
  ["A","Die Tüte kostet 20 Cent. Schönen Tag noch!","The bag costs 20 cents. Have a nice day!"]],
 q:[["rf","Der Kunde hat eine Kundenkarte.",false,"„Nein, leider nicht.“"],
    ["mc","Wie viel Pfand bekommt der Kunde zurück?",["2,25 Euro","3,25 Euro","20,15 Euro"],1,"„… einen Pfandbon über drei Euro 25.“"],
    ["mc","Was ist das Angebot?",["Milch: 3 für 2","Brot: halber Preis","Obst: 20 Prozent billiger"],0,"„Wenn Sie zwei nehmen, bekommen Sie die dritte gratis.“"],
    ["rf","Die Tüte ist kostenlos.",false,"„Die Tüte kostet 20 Cent.“"]]},

{id:"apotheke", de:"In der Apotheke", en:"At the pharmacy", amb:"doctor", kind:"Gespräch",
 who:{A:["Apotheker","m"],B:["Kundin","f"]},
 parts:[
  ["A","Guten Tag, was kann ich für Sie tun?","Hello, what can I do for you?"],
  ["B","Ich habe seit drei Tagen Halsschmerzen und Husten. Haben Sie etwas dagegen?","I've had a sore throat and a cough for three days. Do you have something for it?"],
  ["A","Haben Sie auch Fieber?","Do you have a fever too?"],
  ["B","Nein, Fieber habe ich nicht.","No, I don't have a fever."],
  ["A","Dann empfehle ich Ihnen diesen Hustensaft. Nehmen Sie dreimal täglich einen Löffel, am besten nach dem Essen. Und für den Hals diese Lutschtabletten.","Then I recommend this cough syrup. Take one spoonful three times a day, ideally after meals. And for your throat these lozenges."],
  ["B","Macht der Saft müde? Ich muss heute noch Auto fahren.","Does the syrup make you tired? I still have to drive today."],
  ["A","Nein, der macht nicht müde. Wenn es in einer Woche nicht besser ist, sollten Sie aber zum Arzt gehen.","No, it doesn't make you tired. But if it's not better in a week, you should see a doctor."],
  ["B","Gut, danke. Was kostet das zusammen?","All right, thank you. How much is that together?"],
  ["A","Zusammen 14 Euro 80.","14.80 together."]],
 q:[["mc","Seit wann hat die Frau Beschwerden?",["seit gestern","seit drei Tagen","seit einer Woche"],1,"„Ich habe seit drei Tagen Halsschmerzen und Husten.“"],
    ["rf","Die Frau hat Fieber.",false,"„Nein, Fieber habe ich nicht.“"],
    ["mc","Wie oft soll sie den Hustensaft nehmen?",["einmal am Tag","zweimal am Tag","dreimal am Tag"],2,"„Nehmen Sie dreimal täglich einen Löffel …“"],
    ["rf","Mit dem Saft darf sie Auto fahren.",true,"„Nein, der macht nicht müde.“"]]},

{id:"termin", de:"Telefon: Termin beim Bürgeramt", en:"Phone: appointment at the citizens' office", amb:"phone", kind:"Gespräch",
 who:{A:["Bürgertelefon","m"],B:["Anruferin","f"]},
 parts:["ring",
  ["A","Bürgertelefon der Stadt Frankfurt, mein Name ist Hoffmann. Was kann ich für Sie tun?","City of Frankfurt citizens' line, my name is Hoffmann. What can I do for you?"],
  ["B","Guten Tag, ich brauche einen neuen Reisepass. Mein alter läuft nächsten Monat ab.","Hello, I need a new passport. My old one expires next month."],
  ["A","Dafür brauchen Sie einen Termin im Bürgeramt. Der nächste freie Termin ist am 18. Oktober um 10 Uhr 20 im Bürgeramt Nord.","You need an appointment at the citizens' office for that. The next free appointment is on 18 October at 10:20 at the Nord office."],
  ["B","Gibt es nichts früher? Ich fliege am 20. Oktober in den Urlaub.","Is there nothing earlier? I'm flying on holiday on 20 October."],
  ["A","Ein normaler Pass dauert leider drei bis vier Wochen. Für Ihre Reise brauchen Sie einen Expresspass, der ist in drei Tagen fertig, kostet aber 32 Euro mehr.","A normal passport unfortunately takes three to four weeks. For your trip you need an express passport; it's ready in three days but costs 32 euros more."],
  ["B","Dann nehme ich den Expresspass. Was muss ich mitbringen?","Then I'll take the express passport. What do I need to bring?"],
  ["A","Ihren alten Pass und ein biometrisches Foto. Sie bekommen gleich eine Bestätigung per E-Mail.","Your old passport and a biometric photo. You'll get a confirmation by email in a moment."]],
 q:[["mc","Was braucht die Frau?",["einen Personalausweis","einen neuen Reisepass","eine Meldebescheinigung"],1,"„… ich brauche einen neuen Reisepass.“"],
    ["mc","Wann ist der Termin?",["am 18. Oktober um 10:20 Uhr","am 20. Oktober","in drei Wochen"],0,"„… am 18. Oktober um 10 Uhr 20 im Bürgeramt Nord.“"],
    ["rf","Ein normaler Pass ist in drei Tagen fertig.",false,"„Ein normaler Pass dauert leider drei bis vier Wochen.“ Nur der Expresspass ist in drei Tagen fertig."],
    ["rf","Sie muss ein biometrisches Foto mitbringen.",true,"„Ihren alten Pass und ein biometrisches Foto.“"]]},

{id:"besichtigung", de:"Wohnungsbesichtigung", en:"Flat viewing", amb:"street", kind:"Gespräch",
 who:{A:["Vermieterin","f"],B:["Interessent","m"]},
 parts:[
  ["A","So, das ist die Wohnung: zwei Zimmer, Küche, Bad und ein kleiner Balkon nach Süden, insgesamt 58 Quadratmeter.","So, this is the flat: two rooms, kitchen, bathroom and a small south-facing balcony, 58 square metres in total."],
  ["B","Sehr hell! Wie hoch ist die Miete?","Very bright! How much is the rent?"],
  ["A","Die Kaltmiete ist 790 Euro, dazu kommen 180 Euro Nebenkosten. Die Kaution sind drei Kaltmieten.","The basic rent is 790 euros, plus 180 euros in service charges. The deposit is three months' basic rent."],
  ["B","Ist die Küche dabei?","Is the kitchen included?"],
  ["A","Ja, die Einbauküche bleibt in der Wohnung, die ist erst zwei Jahre alt.","Yes, the fitted kitchen stays in the flat; it's only two years old."],
  ["B","Und darf man Haustiere haben? Wir haben eine Katze.","And are pets allowed? We have a cat."],
  ["A","Eine Katze ist in Ordnung, Hunde leider nicht.","A cat is fine; dogs unfortunately not."],
  ["B","Ab wann ist die Wohnung frei?","From when is the flat available?"],
  ["A","Ab dem 1. Dezember. Wenn Sie Interesse haben, schicken Sie mir bitte bis Freitag Ihre Unterlagen.","From 1 December. If you're interested, please send me your documents by Friday."]],
 q:[["mc","Wie groß ist die Wohnung?",["48 Quadratmeter","58 Quadratmeter","85 Quadratmeter"],1,"„… insgesamt 58 Quadratmeter.“"],
    ["mc","Wie hoch sind die Nebenkosten?",["180 Euro","790 Euro","970 Euro"],0,"„… dazu kommen 180 Euro Nebenkosten.“"],
    ["rf","Die Küche gehört zur Wohnung.",true,"„Ja, die Einbauküche bleibt in der Wohnung …“"],
    ["rf","In der Wohnung sind keine Haustiere erlaubt.",false,"„Eine Katze ist in Ordnung, Hunde leider nicht.“"]]},

{id:"kantine", de:"Mittagspause in der Kantine", en:"Lunch break in the canteen", amb:"cafe", kind:"Gespräch",
 who:{A:["Jonas","m"],B:["Aylin","f"]},
 parts:[
  ["A","Hallo Aylin, ist hier noch frei?","Hi Aylin, is this seat free?"],
  ["B","Klar, setz dich! Wie war dein Urlaub?","Sure, sit down! How was your holiday?"],
  ["A","Super, wir waren zwei Wochen in Portugal. Aber jetzt ist mein Schreibtisch voller Arbeit.","Great, we were in Portugal for two weeks. But now my desk is full of work."],
  ["B","Das kenne ich. Übrigens: Hast du schon gehört, dass die Kantine ab nächsten Monat auch abends geöffnet hat?","I know that feeling. By the way: have you heard that the canteen will also be open in the evenings from next month?"],
  ["A","Nein! Bis wann denn?","No! Until when?"],
  ["B","Bis 20 Uhr, für die Kollegen in der Spätschicht. Und es gibt jeden Tag ein vegetarisches Gericht.","Until 8 pm, for the colleagues on the late shift. And there'll be a vegetarian dish every day."],
  ["A","Gute Idee. Sag mal, kommst du am Freitag zum Firmenlauf?","Good idea. Tell me, are you coming to the company run on Friday?"],
  ["B","Ich würde gern, aber ich habe mir letzte Woche den Fuß verletzt. Ich komme aber zum Zuschauen und bringe Kuchen mit.","I'd like to, but I hurt my foot last week. But I'll come to watch and bring a cake."]],
 q:[["mc","Wo war Jonas im Urlaub?",["in Spanien","in Portugal","in Italien"],1,"„… wir waren zwei Wochen in Portugal.“"],
    ["rf","Die Kantine ist bald auch abends geöffnet.",true,"„… dass die Kantine ab nächsten Monat auch abends geöffnet hat.“"],
    ["mc","Bis wann ist die Kantine dann geöffnet?",["bis 18 Uhr","bis 20 Uhr","bis 22 Uhr"],1,"„Bis 20 Uhr, für die Kollegen in der Spätschicht.“"],
    ["rf","Aylin läuft am Freitag beim Firmenlauf mit.",false,"Sie hat sich den Fuß verletzt – sie kommt nur „zum Zuschauen“."]]},

{id:"rezeption", de:"Arztpraxis: Termin verschieben", en:"Doctor's practice: moving an appointment", amb:"doctor", kind:"Gespräch",
 who:{A:["Arzthelferin","f"],B:["Patient","m"]},
 parts:[
  ["B","Guten Morgen, ich habe am Donnerstag um 9 Uhr einen Termin zur Blutabnahme. Leider muss ich an dem Tag arbeiten. Kann ich den Termin verschieben?","Good morning, I have an appointment for a blood test on Thursday at 9. Unfortunately I have to work that day. Can I move the appointment?"],
  ["A","Natürlich. Wie ist Ihr Name, bitte?","Of course. What's your name, please?"],
  ["B","Tomasz Nowak.","Tomasz Nowak."],
  ["A","Herr Nowak … Blutabnahme machen wir nur morgens zwischen 7 und 10 Uhr. Geht es am Montag um 7 Uhr 30?","Mr Nowak … we only take blood in the mornings between 7 and 10. Is Monday at 7:30 possible?"],
  ["B","Ja, das passt gut, dann komme ich vor der Arbeit.","Yes, that suits me well; then I'll come before work."],
  ["A","Denken Sie daran: Sie müssen nüchtern kommen, also vorher nichts essen. Wasser oder Tee ohne Zucker dürfen Sie trinken.","Remember: you have to come with an empty stomach, so don't eat anything beforehand. You may drink water or tea without sugar."],
  ["B","In Ordnung. Wann bekomme ich die Ergebnisse?","OK. When will I get the results?"],
  ["A","Nach etwa drei Tagen. Die Ärztin ruft Sie an, wenn etwas nicht in Ordnung ist.","After about three days. The doctor will call you if something isn't right."]],
 q:[["mc","Warum möchte der Mann den Termin verschieben?",["Er ist krank.","Er muss arbeiten.","Er ist im Urlaub."],1,"„Leider muss ich an dem Tag arbeiten.“"],
    ["mc","Wann ist der neue Termin?",["am Donnerstag um 9 Uhr","am Montag um 7:30 Uhr","am Montag um 10 Uhr"],1,"„Geht es am Montag um 7 Uhr 30?“ – „Ja, das passt gut.“"],
    ["rf","Vor der Blutabnahme darf er nichts trinken.",false,"„Wasser oder Tee ohne Zucker dürfen Sie trinken.“ Nur essen darf er nichts."],
    ["rf","Die Ärztin ruft nur an, wenn etwas nicht in Ordnung ist.",true,"„Die Ärztin ruft Sie an, wenn etwas nicht in Ordnung ist.“"]]}
];
