/* Hören (listening) for B1: exam-style scenes that play inside the app.
   Each scene: title, where it happens (amb = the background the app
   generates: station, train, sbahn, airport, shop, radio, phone, cafe,
   hotel, bank, doctor, office, street), the speakers with gender, the parts
   in order – "chime" (station gong), "ring" (phone), "beep" (voicemail) or
   [speaker, German, English] – and questions:
   ["rf", statement, true/false, why] or ["mc", question, [a, b, c], index, why].
   tools/check-alltag.mjs checks the shape. */
window.HS = [
{id:"gleis", de:"Bahnhof: Gleisänderung und Verspätung", en:"Station: platform change and delay", amb:"station", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Achtung am Gleis 7. Der ICE 578 nach Hamburg-Altona, planmäßige Abfahrt 14 Uhr 32, fährt heute von Gleis 9. Ich wiederhole: Der ICE nach Hamburg-Altona fährt heute von Gleis 9.","Attention on platform 7. ICE 578 to Hamburg-Altona, scheduled departure 14:32, leaves from platform 9 today. I repeat: the ICE to Hamburg-Altona leaves from platform 9 today."],
  "chime",
  ["A","Information zum Regionalexpress nach Kassel, Abfahrt 14 Uhr 40. Der Zug hat heute circa 25 Minuten Verspätung. Grund dafür ist eine Reparatur an einem Signal. Reisende mit Anschluss in Gießen nehmen bitte die S-Bahn um 14 Uhr 45.","Information on the regional express to Kassel, departure 14:40. The train is about 25 minutes late today. The reason is a repair to a signal. Passengers with a connection in Gießen please take the S-Bahn at 14:45."]],
 q:[["rf","Der ICE nach Hamburg fährt heute von Gleis 7 ab.",false,"Er fährt heute von Gleis 9 – Gleis 7 war das alte Gleis."],
    ["mc","Wie viel Verspätung hat der Zug nach Kassel?",["etwa 15 Minuten","etwa 25 Minuten","etwa 45 Minuten"],1,"„circa 25 Minuten Verspätung“."],
    ["mc","Warum hat der Zug Verspätung?",["wegen eines Unfalls","wegen einer Reparatur an einem Signal","wegen des Wetters"],1,"„Grund dafür ist eine Reparatur an einem Signal.“"],
    ["rf","Wer nach Gießen muss, soll die S-Bahn um 14:45 Uhr nehmen.",true,"„Reisende mit Anschluss in Gießen nehmen bitte die S-Bahn um 14 Uhr 45.“"]]},

{id:"zug", de:"Im Zug: nächster Halt und Anschlüsse", en:"On the train: next stop and connections", amb:"train", kind:"Durchsage",
 who:{A:["Zugbegleiter","m"]},
 parts:["chime",
  ["A","Meine Damen und Herren, in wenigen Minuten erreichen wir Frankfurt am Main Hauptbahnhof. Wegen einer Streckensperrung haben wir leider 15 Minuten Verspätung.","Ladies and gentlemen, in a few minutes we will reach Frankfurt am Main main station. Because of a line closure we are unfortunately 15 minutes late."],
  ["A","Ihre Anschlusszüge: Der ICE nach Stuttgart wartet heute auf uns, Sie erreichen ihn am gegenüberliegenden Gleis. Die S-Bahn zum Flughafen erreichen Sie leider nicht mehr. Die nächste fährt zehn Minuten später.","Your connecting trains: the ICE to Stuttgart is waiting for us today; you'll reach it on the opposite platform. Unfortunately you won't make the S-Bahn to the airport. The next one leaves ten minutes later."],
  ["A","Bitte denken Sie beim Aussteigen an Ihr Gepäck. Das Bordbistro in Wagen 8 ist ab Frankfurt wieder geöffnet.","Please remember your luggage when getting off. The on-board bistro in coach 8 is open again from Frankfurt."]],
 q:[["mc","Warum hat der Zug Verspätung?",["wegen einer Streckensperrung","wegen eines kranken Fahrgasts","wegen eines technischen Problems am Zug"],0,"„Wegen einer Streckensperrung …“"],
    ["rf","Der ICE nach Stuttgart wartet auf den Zug.",true,"„Der ICE nach Stuttgart wartet heute auf uns.“"],
    ["rf","Die Fahrgäste erreichen die S-Bahn zum Flughafen noch.",false,"„… erreichen Sie leider nicht mehr. Die nächste fährt zehn Minuten später.“"],
    ["mc","Was ist ab Frankfurt wieder geöffnet?",["das Bordbistro in Wagen 8","die Toiletten","das Ruheabteil"],0,"„Das Bordbistro in Wagen 8 ist ab Frankfurt wieder geöffnet.“"]]},

{id:"sbahn", de:"S-Bahn: Störung und Ersatzverkehr", en:"S-Bahn: disruption and replacement buses", amb:"sbahn", kind:"Durchsage",
 who:{A:["Ansage","m"]},
 parts:["chime",
  ["A","Eine Information für Fahrgäste der Linien S3 und S4: Wegen einer Störung am Stellwerk fahren zwischen Hauptwache und Südbahnhof zurzeit keine Züge.","Information for passengers on lines S3 and S4: because of a fault at the signal box, no trains are currently running between Hauptwache and Südbahnhof."],
  ["A","Bitte benutzen Sie die U-Bahn-Linie U1 oder die Ersatzbusse. Die Busse fahren alle zehn Minuten vom Ausgang B. Ihre Fahrkarten gelten auch in den Bussen. Wir bitten um Entschuldigung.","Please use underground line U1 or the replacement buses. The buses run every ten minutes from exit B. Your tickets are also valid on the buses. We apologise."]],
 q:[["mc","Warum fahren keine S-Bahnen?",["wegen eines Streiks","wegen einer Störung am Stellwerk","wegen Bauarbeiten"],1,"„Wegen einer Störung am Stellwerk …“"],
    ["rf","Die Ersatzbusse fahren alle fünf Minuten.",false,"„Die Busse fahren alle zehn Minuten.“"],
    ["mc","Wo fahren die Busse ab?",["am Ausgang A","am Ausgang B","am Hauptbahnhof"],1,"„… vom Ausgang B.“"],
    ["rf","Man braucht für den Bus keine neue Fahrkarte.",true,"„Ihre Fahrkarten gelten auch in den Bussen.“"]]},

{id:"flughafen", de:"Flughafen: Gate-Änderung und letzter Aufruf", en:"Airport: gate change and final call", amb:"airport", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Passagiere des Fluges LH 1132 nach Lissabon, bitte beachten Sie: Ihr Flug startet heute nicht von Gate A 22, sondern von Gate B 14. Das Boarding beginnt in 20 Minuten.","Passengers on flight LH 1132 to Lisbon, please note: your flight departs today not from gate A22 but from gate B14. Boarding begins in 20 minutes."],
  "chime",
  ["A","Letzter Aufruf für den Passagier Karim Haddad, gebucht auf den Flug nach Istanbul. Bitte kommen Sie sofort zum Gate C 5. Das Gate schließt in fünf Minuten.","Final call for passenger Karim Haddad, booked on the flight to Istanbul. Please come to gate C5 immediately. The gate closes in five minutes."]],
 q:[["mc","Von welchem Gate startet der Flug nach Lissabon?",["A 22","B 14","C 5"],1,"„… nicht von Gate A 22, sondern von Gate B 14.“"],
    ["rf","Das Boarding nach Lissabon beginnt sofort.",false,"„Das Boarding beginnt in 20 Minuten.“"],
    ["rf","Herr Haddad soll schnell zum Gate kommen.",true,"„Bitte kommen Sie sofort zum Gate C 5.“"],
    ["mc","Wann schließt das Gate für den Flug nach Istanbul?",["in fünf Minuten","in 15 Minuten","in 20 Minuten"],0,"„Das Gate schließt in fünf Minuten.“"]]},

{id:"kaufhaus", de:"Kaufhaus: Angebot und Kind sucht Eltern", en:"Department store: offer and lost child", amb:"shop", kind:"Durchsage",
 who:{A:["Ansage","f"]},
 parts:["chime",
  ["A","Liebe Kundinnen und Kunden, nur heute: In unserer Sportabteilung im dritten Stock sind alle Laufschuhe 30 Prozent günstiger. Das Angebot gilt bis 16 Uhr.","Dear customers, today only: in our sports department on the third floor all running shoes are 30 per cent cheaper. The offer is valid until 4 pm."],
  "chime",
  ["A","Der kleine Jonas, fünf Jahre alt, sucht seine Eltern. Er wartet an der Information im Erdgeschoss, direkt am Haupteingang.","Little Jonas, five years old, is looking for his parents. He is waiting at the information desk on the ground floor, right by the main entrance."],
  "chime",
  ["A","Wir weisen Sie darauf hin, dass unser Haus in 15 Minuten schließt. Bitte gehen Sie zu den Kassen.","Please note that our store closes in 15 minutes. Please make your way to the checkouts."]],
 q:[["mc","Wo gibt es das Angebot?",["im Erdgeschoss","im zweiten Stock","im dritten Stock"],2,"„… Sportabteilung im dritten Stock …“"],
    ["rf","Das Angebot gilt den ganzen Tag.",false,"„Das Angebot gilt bis 16 Uhr.“"],
    ["mc","Wo wartet Jonas?",["an der Kasse","an der Information im Erdgeschoss","in der Spielecke"],1,"„… an der Information im Erdgeschoss, direkt am Haupteingang.“"],
    ["rf","Das Kaufhaus schließt bald.",true,"„… dass unser Haus in 15 Minuten schließt.“"]]},

{id:"radio", de:"Radio: Verkehr und Wetter", en:"Radio: traffic and weather", amb:"radio", kind:"Radio",
 who:{A:["Moderatorin","f"],B:["Verkehrsredaktion","m"]},
 parts:[
  ["A","Und jetzt die Verkehrsmeldungen mit Tobias.","And now the traffic news with Tobias."],
  ["B","Auf der A5 Frankfurt Richtung Kassel gibt es nach einem Unfall zwischen Friedberg und Butzbach acht Kilometer Stau. Die Polizei empfiehlt, die B3 zu benutzen. In der Frankfurter Innenstadt ist die Mainzer Landstraße wegen Bauarbeiten bis Freitag gesperrt.","On the A5 from Frankfurt towards Kassel there's an eight-kilometre traffic jam between Friedberg and Butzbach after an accident. The police recommend using the B3. In Frankfurt city centre, Mainzer Landstraße is closed until Friday because of roadworks."],
  ["A","Danke, Tobias. Und das Wetter: Heute bleibt es trocken bei bis zu 18 Grad. Morgen kommen von Westen Wolken, und am Nachmittag regnet es. Am Wochenende wird es wieder sonnig.","Thanks, Tobias. And the weather: today stays dry at up to 18 degrees. Tomorrow clouds come from the west and it rains in the afternoon. At the weekend it will be sunny again."]],
 q:[["mc","Warum gibt es auf der A5 Stau?",["wegen Bauarbeiten","wegen eines Unfalls","wegen des Wetters"],1,"„… nach einem Unfall …“"],
    ["rf","Die Polizei empfiehlt, die B3 zu nehmen.",true,"„Die Polizei empfiehlt, die B3 zu benutzen.“"],
    ["mc","Wie lange ist die Mainzer Landstraße gesperrt?",["nur heute","bis Freitag","bis zum Wochenende"],1,"„… wegen Bauarbeiten bis Freitag gesperrt.“"],
    ["rf","Morgen Nachmittag regnet es.",true,"„Morgen kommen von Westen Wolken, und am Nachmittag regnet es.“"]]},

{id:"praxis", de:"Anrufbeantworter: Arztpraxis", en:"Voicemail: doctor's practice", amb:"phone", kind:"Telefon",
 who:{A:["Praxis","f"]},
 parts:["ring","beep",
  ["A","Guten Tag, Sie sind verbunden mit der Praxis Dr. Schulz. Unsere Praxis ist vom 4. bis 15. August wegen Urlaub geschlossen.","Hello, you've reached Dr Schulz's practice. Our practice is closed for holidays from 4 to 15 August."],
  ["A","In dieser Zeit vertritt uns die Praxis Dr. Lang in der Goethestraße 5, Telefon 069 23 45 67. Rezepte können Sie weiterhin online bestellen.","During this time we're covered by Dr Lang's practice at Goethestraße 5, phone 069 23 45 67. You can still order prescriptions online."],
  ["A","Außerhalb der Sprechzeiten erreichen Sie den ärztlichen Bereitschaftsdienst unter 116 117. In lebensbedrohlichen Notfällen wählen Sie bitte die 112.","Outside opening hours you can reach the out-of-hours medical service on 116 117. In life-threatening emergencies please dial 112."]],
 q:[["rf","Die Praxis ist im August zwei Wochen geschlossen.",true,"„… vom 4. bis 15. August wegen Urlaub geschlossen.“"],
    ["mc","Wer vertritt die Praxis?",["Dr. Lang","Dr. Schulz","das Krankenhaus"],0,"„In dieser Zeit vertritt uns die Praxis Dr. Lang …“"],
    ["rf","Rezepte kann man in dieser Zeit nicht bekommen.",false,"„Rezepte können Sie weiterhin online bestellen.“"],
    ["mc","Welche Nummer wählt man in einem lebensbedrohlichen Notfall?",["116 117","112","069 23 45 67"],1,"„In lebensbedrohlichen Notfällen wählen Sie bitte die 112.“"]]},

{id:"werkstatt", de:"Anrufbeantworter: Nachricht von der Werkstatt", en:"Voicemail: message from the garage", amb:"phone", kind:"Telefon",
 who:{A:["Werkstatt","m"]},
 parts:["beep",
  ["A","Guten Tag, Herr Keller, hier ist Martin Braun vom Autohaus Braun. Wir haben Ihr Auto untersucht: Die Bremsen vorne müssen gewechselt werden, das kostet ungefähr 240 Euro.","Hello Mr Keller, this is Martin Braun from Braun garage. We've examined your car: the front brakes need to be changed; that costs about 240 euros."],
  ["A","Die Inspektion ist schon fertig. Wenn Sie mit der Reparatur einverstanden sind, rufen Sie uns bitte bis heute 16 Uhr zurück. Dann ist das Auto morgen ab 10 Uhr abholbereit.","The inspection is already done. If you agree to the repair, please call us back by 4 pm today. Then the car will be ready to collect from 10 am tomorrow."],
  ["A","Unsere Nummer ist 069 88 71 20. Auf Wiederhören.","Our number is 069 88 71 20. Goodbye."]],
 q:[["mc","Was muss am Auto repariert werden?",["die Bremsen vorne","die Reifen","die Klimaanlage"],0,"„Die Bremsen vorne müssen gewechselt werden …“"],
    ["mc","Wie viel kostet die Reparatur ungefähr?",["140 Euro","240 Euro","420 Euro"],1,"„… das kostet ungefähr 240 Euro.“"],
    ["rf","Herr Keller soll bis 16 Uhr zurückrufen.",true,"„… rufen Sie uns bitte bis heute 16 Uhr zurück.“"],
    ["rf","Das Auto ist heute Abend fertig.",false,"„… morgen ab 10 Uhr abholbereit.“"]]},

{id:"restaurant", de:"Im Restaurant: bestellen, reklamieren, zahlen", en:"Restaurant: ordering, complaining, paying", amb:"cafe", kind:"Gespräch",
 who:{A:["Kellner","m"],B:["Gast","f"]},
 parts:[
  ["A","Guten Abend! Haben Sie schon gewählt?","Good evening! Have you decided?"],
  ["B","Ja. Ich hätte gern die Tomatensuppe und danach den Lachs mit Kartoffeln. Ist in der Soße Sahne? Ich vertrage keine Milchprodukte.","Yes. I'd like the tomato soup and then the salmon with potatoes. Is there cream in the sauce? I can't tolerate dairy."],
  ["A","Ja, leider. Aber wir können den Lachs auch mit Olivenöl und Zitrone machen.","Yes, unfortunately. But we can also make the salmon with olive oil and lemon."],
  ["B","Das ist perfekt. Und zu trinken ein stilles Wasser, bitte.","That's perfect. And to drink a still water, please."],
  ["B","Entschuldigung, die Suppe ist leider nur lauwarm.","Excuse me, the soup is unfortunately only lukewarm."],
  ["A","Oh, das tut mir leid. Ich bringe Ihnen sofort eine neue. Der Nachtisch geht dann aufs Haus.","Oh, I'm sorry. I'll bring you a new one straight away. Dessert is then on the house."],
  ["B","Das ist sehr nett. Ich möchte dann bitte zahlen. Kann ich mit Karte bezahlen?","That's very kind. I'd like to pay then, please. Can I pay by card?"],
  ["A","Natürlich. Das macht 27 Euro 50.","Of course. That's 27.50 euros."],
  ["B","Machen Sie 30. Stimmt so.","Make it 30. Keep the change."]],
 q:[["mc","Was bestellt die Frau als Hauptgericht?",["Tomatensuppe","Lachs mit Kartoffeln","Nudeln mit Sahnesoße"],1,"„… danach den Lachs mit Kartoffeln.“"],
    ["rf","Die Frau darf keine Milchprodukte essen.",true,"„Ich vertrage keine Milchprodukte.“"],
    ["mc","Was ist das Problem mit der Suppe?",["Sie ist zu salzig.","Sie ist nur lauwarm.","Es ist die falsche Suppe."],1,"„… die Suppe ist leider nur lauwarm.“"],
    ["mc","Wie viel Trinkgeld gibt sie?",["50 Cent","2 Euro 50","5 Euro"],1,"27,50 € → „Machen Sie 30“ = 2,50 € Trinkgeld."]]},

{id:"hotel", de:"Im Hotel: Check-in und ein Problem", en:"Hotel: check-in and a problem", amb:"hotel", kind:"Gespräch",
 who:{A:["Rezeption","f"],B:["Gast","m"]},
 parts:[
  ["A","Guten Abend und herzlich willkommen. Haben Sie reserviert?","Good evening and welcome. Do you have a reservation?"],
  ["B","Ja, auf den Namen Okafor, ein Einzelzimmer für drei Nächte.","Yes, under the name Okafor, a single room for three nights."],
  ["A","Richtig, Herr Okafor. Frühstück ist inklusive, von 6 Uhr 30 bis 10 Uhr im ersten Stock. Das WLAN-Passwort steht auf Ihrer Karte.","That's right, Mr Okafor. Breakfast is included, from 6:30 to 10 on the first floor. The Wi-Fi password is on your card."],
  ["B","Danke. Kann ich mein Auto in der Garage parken?","Thank you. Can I park my car in the garage?"],
  ["A","Ja, das kostet 12 Euro pro Nacht.","Yes, that costs 12 euros a night."],
  ["B","Entschuldigung, ich bin's noch einmal aus Zimmer 305. Die Heizung funktioniert nicht, und im Zimmer ist es sehr kalt.","Excuse me, it's me again from room 305. The heating isn't working and it's very cold in the room."],
  ["A","Das tut mir leid. Unser Techniker ist heute nicht mehr da. Ich gebe Ihnen gern ein anderes Zimmer, die 412 im vierten Stock.","I'm sorry. Our technician has gone for the day. I'm happy to give you another room, 412 on the fourth floor."],
  ["B","Sehr gut, danke. Bis wann muss ich am Freitag auschecken?","Very good, thank you. By when do I have to check out on Friday?"],
  ["A","Bis 11 Uhr. Ihr Gepäck können Sie danach gern bei uns lassen.","By 11. You're welcome to leave your luggage with us afterwards."]],
 q:[["mc","Wie lange bleibt Herr Okafor?",["eine Nacht","drei Nächte","eine Woche"],1,"„… ein Einzelzimmer für drei Nächte.“"],
    ["rf","Das Frühstück kostet extra.",false,"„Frühstück ist inklusive …“"],
    ["mc","Was kostet die Garage?",["nichts","12 Euro pro Nacht","20 Euro pro Nacht"],1,"„… das kostet 12 Euro pro Nacht.“"],
    ["rf","Herr Okafor bekommt ein anderes Zimmer.",true,"„Ich gebe Ihnen gern ein anderes Zimmer, die 412 …“"]]},

{id:"bank", de:"Bei der Bank: Karte verloren", en:"At the bank: lost card", amb:"bank", kind:"Gespräch",
 who:{A:["Bankberater","m"],B:["Kundin","f"]},
 parts:[
  ["A","Guten Tag, was kann ich für Sie tun?","Hello, what can I do for you?"],
  ["B","Ich habe gestern Abend meine Geldbörse mit meiner Bankkarte verloren.","Last night I lost my wallet with my bank card."],
  ["A","Haben Sie die Karte schon sperren lassen?","Have you already had the card blocked?"],
  ["B","Ja, ich habe sofort beim Sperr-Notruf 116 116 angerufen.","Yes, I called the blocking hotline 116 116 straight away."],
  ["A","Sehr gut. Ich sehe, dass mit Ihrer Karte seitdem nichts bezahlt wurde. Ich bestelle Ihnen eine neue. Sie kommt in etwa fünf Werktagen per Post.","Very good. I can see that nothing has been paid with your card since then. I'll order you a new one. It will arrive by post in about five working days."],
  ["B","Und die PIN?","And the PIN?"],
  ["A","Die bekommen Sie mit einem separaten Brief. Die neue Karte kostet leider 15 Euro.","You'll get it in a separate letter. The new card unfortunately costs 15 euros."],
  ["B","Kann ich bis dahin trotzdem Geld abheben?","Can I still withdraw money until then?"],
  ["A","Ja, hier am Schalter mit Ihrem Ausweis.","Yes, here at the counter with your ID."]],
 q:[["rf","Die Frau hat die Karte noch nicht sperren lassen.",false,"„Ja, ich habe sofort beim Sperr-Notruf 116 116 angerufen.“"],
    ["mc","Wann kommt die neue Karte?",["morgen","in etwa fünf Werktagen","in zwei Wochen"],1,"„Sie kommt in etwa fünf Werktagen per Post.“"],
    ["mc","Wie viel kostet die neue Karte?",["nichts","5 Euro","15 Euro"],2,"„Die neue Karte kostet leider 15 Euro.“"],
    ["rf","Bis die Karte kommt, kann sie am Schalter Geld abheben.",true,"„Ja, hier am Schalter mit Ihrem Ausweis.“"]]},

{id:"arzt", de:"Beim Arzt: Rückenschmerzen", en:"At the doctor's: back pain", amb:"doctor", kind:"Gespräch",
 who:{A:["Ärztin","f"],B:["Patient","m"]},
 parts:[
  ["A","Guten Morgen. Was kann ich für Sie tun?","Good morning. What can I do for you?"],
  ["B","Ich habe seit zehn Tagen starke Schmerzen im unteren Rücken. Manchmal ziehen sie bis ins linke Bein.","For ten days I've had bad pain in my lower back. Sometimes it goes down into my left leg."],
  ["A","Haben Sie etwas Schweres gehoben?","Did you lift something heavy?"],
  ["B","Ja, ich bin letzte Woche umgezogen.","Yes, I moved house last week."],
  ["A","Das erklärt einiges. Ich verschreibe Ihnen ein Schmerzmittel. Nehmen Sie morgens und abends eine Tablette, immer nach dem Essen, höchstens fünf Tage lang.","That explains a lot. I'll prescribe you a painkiller. Take one tablet morning and evening, always after food, for no more than five days."],
  ["A","Außerdem bekommen Sie sechs Termine Physiotherapie. Wenn es in zwei Wochen nicht besser ist, kommen Sie bitte wieder.","You'll also get six physiotherapy sessions. If it isn't better in two weeks, please come back."],
  ["B","Brauche ich eine Krankschreibung? Ich arbeite im Lager.","Do I need a sick note? I work in a warehouse."],
  ["A","Ja, ich schreibe Sie bis Freitag krank.","Yes, I'll sign you off sick until Friday."]],
 q:[["mc","Seit wann hat der Mann Schmerzen?",["seit zwei Tagen","seit zehn Tagen","seit zwei Wochen"],1,"„Ich habe seit zehn Tagen starke Schmerzen …“"],
    ["mc","Was ist wahrscheinlich der Grund?",["ein Sportunfall","der Umzug","die Arbeit im Büro"],1,"„Ja, ich bin letzte Woche umgezogen.“ – „Das erklärt einiges.“"],
    ["rf","Er soll die Tabletten dreimal am Tag nehmen.",false,"„… morgens und abends eine Tablette …“ = zweimal am Tag."],
    ["rf","Er ist bis Freitag krankgeschrieben.",true,"„Ja, ich schreibe Sie bis Freitag krank.“"]]},

{id:"buergeramt", de:"Bürgeramt: Anmeldung", en:"Citizens' office: registration", amb:"office", kind:"Gespräch",
 who:{A:["Sachbearbeiterin","f"],B:["Sie","m"]},
 parts:[
  ["A","Guten Tag, die Nummer 128? Bitte nehmen Sie Platz. Was kann ich für Sie tun?","Hello, number 128? Please take a seat. What can I do for you?"],
  ["B","Ich möchte mich anmelden. Ich wohne seit dem 1. September in der Berger Straße.","I'd like to register. I've been living on Berger Straße since 1 September."],
  ["A","Dann haben Sie noch genau eine Woche Zeit, die Frist ist zwei Wochen. Haben Sie die Wohnungsgeberbestätigung dabei?","Then you have exactly one week left; the deadline is two weeks. Do you have the landlord's confirmation with you?"],
  ["B","Oh nein, die liegt noch zu Hause. Ich habe nur meinen Pass und den Mietvertrag.","Oh no, it's still at home. I only have my passport and the rental contract."],
  ["A","Der Mietvertrag reicht leider nicht. Sie können die Bestätigung aber auch per E-Mail schicken, dann schließe ich die Anmeldung heute ab.","Unfortunately the rental contract isn't enough. But you can also send the confirmation by email, then I'll complete the registration today."],
  ["B","Das mache ich sofort. Kostet die Anmeldung etwas?","I'll do that straight away. Does registration cost anything?"],
  ["A","Nein, sie ist kostenlos. Die Meldebescheinigung schicken wir Ihnen dann per Post.","No, it's free. We'll then send you the registration certificate by post."]],
 q:[["mc","Seit wann wohnt der Mann in der Berger Straße?",["seit dem 1. August","seit dem 1. September","seit zwei Monaten"],1,"„Ich wohne seit dem 1. September …“"],
    ["rf","Die Frist für die Anmeldung ist zwei Wochen.",true,"„… die Frist ist zwei Wochen.“"],
    ["mc","Was fehlt?",["der Pass","der Mietvertrag","die Wohnungsgeberbestätigung"],2,"„Oh nein, die liegt noch zu Hause.“ – „Der Mietvertrag reicht leider nicht.“"],
    ["rf","Die Anmeldung kostet 15 Euro.",false,"„Nein, sie ist kostenlos.“"]]},

{id:"arbeit", de:"Arbeit: Ansage der Teamleiterin", en:"Work: team leader's briefing", amb:"office", kind:"Ansage",
 who:{A:["Teamleiterin","f"]},
 parts:[
  ["A","Guten Morgen zusammen, kurz ein paar Informationen für heute. Frau Petrović ist krank, deshalb übernimmt Herr Kaya ihre Schicht an der Kasse.","Good morning everyone, a few quick pieces of information for today. Ms Petrović is ill, so Mr Kaya is taking over her shift at the checkout."],
  ["A","Um 11 Uhr kommt eine große Lieferung. Bitte helft alle beim Auspacken, damit die Regale bis 14 Uhr voll sind.","A big delivery is coming at 11. Please all help with unpacking so that the shelves are full by 2 pm."],
  ["A","Die Teambesprechung ist diese Woche nicht am Mittwoch, sondern am Donnerstag um 8 Uhr. Und denkt bitte daran, eure Urlaubswünsche bis Freitag einzutragen.","The team meeting this week is not on Wednesday but on Thursday at 8. And please remember to enter your holiday requests by Friday."]],
 q:[["rf","Herr Kaya ist heute krank.",false,"Frau Petrović ist krank; Herr Kaya übernimmt ihre Schicht."],
    ["mc","Wann kommt die Lieferung?",["um 8 Uhr","um 11 Uhr","um 14 Uhr"],1,"„Um 11 Uhr kommt eine große Lieferung.“"],
    ["mc","Wann ist die Teambesprechung?",["am Mittwoch","am Donnerstag um 8 Uhr","am Freitag"],1,"„… nicht am Mittwoch, sondern am Donnerstag um 8 Uhr.“"],
    ["rf","Die Urlaubswünsche müssen bis Freitag eingetragen werden.",true,"„… eure Urlaubswünsche bis Freitag einzutragen.“"]]}
];
