/* Paragraphs for "Wörter erkennen", every word tagged by hand.

   One topic → an A1 and a B1 paragraph → sentences of [tokens, English].
   Tokens are separated by "~"; each is  word|POS|CASE|ROLE|lemma|English|why
   with trailing fields optional and lemma empty when it is the word itself.
   A token without "|" is punctuation and sticks to the word before it.

   POS   (with an optional .subtype where the tags cannot tell: V.hilf,
         P.refl, P.rel, P.dem — see woerter-lex.js)
         N noun · V finite verb · VT other verb part (infinitive, participle,
         separable prefix) · P pronoun · A article / determiner · J adjective ·
         ADV adverb · PR preposition · PA preposition fused with article (am,
         im, zum…) · K conjunction · Z numeral · T particle (nicht, zu, nur)
   CASE  N/A/D/G + gender m/f/n or p for plural (e.g. "Dm"); pronouns may give
         the case alone
   ROLE  S subject · P predicate · AO accusative object · DO dative object ·
         GA genitive attribute · AB adverbial · PO prepositional object ·
         PN predicative · AT attribute · K connector

   tools/check-woerter.mjs fails unless every paragraph uses every POS group
   and all four cases. */
window.WD = [
{de:"Familie", en:"Family", p:[
{lvl:"A1", s:[
[`Ich|P|N|S|ich|I ~ heiße|V||P|heißen|am called ~ Lena|N|Nf|PN||Lena (name)|After "heißen" the name is in the nominative, like after "sein". ~ und|K||K||and|Joins two main clauses; word order stays normal. ~ komme|V||P|kommen|come ~ aus|PR||AB||from|"aus" always takes the dative. ~ Spanien|N|Dn|AB||Spain|Dative after "aus". Most country names have no article. ~ .`,
 "My name is Lena and I come from Spain."],
[`Heute|ADV||AB||today|Adverb of time: Wann? When? ~ wohne|V||P|wohnen|live|The verb stays in position 2, so the subject moves behind it. ~ ich|P|N|S|ich|I|The subject comes after the verb because "Heute" takes position 1. ~ mit|PR||AB||with|"mit" always takes the dative. ~ meinem|A|Dm|AB|mein|my|Possessive article, dative masculine: mein → meinem. ~ Mann|N|Dm|AB||husband ~ in|PR||AB||in|Two-way preposition: Wo? (where) → dative. ~ Berlin|N|Dn|AB||Berlin ~ .`,
 "Today I live with my husband in Berlin."],
[`Wir|P|N|S|wir|we ~ haben|V||P||have ~ zwei|Z||AO||two ~ Kinder|N|Ap|AO|Kind|children|Was haben wir? → accusative object. das Kind → die Kinder. ~ : ~ einen|A|Am|AO|ein|a|Indefinite article, accusative masculine: ein → einen. ~ Sohn|N|Am|AO||son ~ und|K||K||and ~ eine|A|Af|AO|ein|a|Accusative feminine looks like the nominative: eine. ~ Tochter|N|Af|AO||daughter ~ .`,
 "We have two children: a son and a daughter."],
[`Am|PA|Dm|AB|an + dem|on|am = an + dem. Days of the week take "am" → dative. ~ Sonntag|N|Dm|AB||Sunday ~ besuchen|V||P||visit ~ wir|P|N|S|wir|we ~ oft|ADV||AB||often|Adverb of frequency: Wie oft? How often? ~ die|A|Ap|AO|der|the|Definite article, accusative plural: die. ~ Eltern|N|Ap|AO||parents|Wen besuchen wir? Whom do we visit? → accusative object. ~ meines|A|Gm|GA|mein|my|Wessen Eltern? Whose parents? → genitive masculine: mein → meines. ~ Mannes|N|Gm|GA|Mann|husband's|Masculine nouns add -es/-s in the genitive: der Mann → des Mannes. ~ .`,
 "On Sundays we often visit my husband's parents."],
[`Meine|A|Nf|S|mein|my ~ Schwiegermutter|N|Nf|S||mother-in-law|Wer kocht? Who cooks? → subject, always nominative. ~ kocht|V||P|kochen|cooks ~ immer|ADV||AB||always ~ ein|A|An|AO||a|Accusative neuter looks like the nominative: ein. ~ leckeres|J|An|AO|lecker|delicious|Adjective after "ein", neuter accusative: ending -es. ~ Essen|N|An|AO||meal|Was kocht sie? What does she cook? → accusative object. ~ .`,
 "My mother-in-law always cooks a delicious meal."],
[`Ich|P|N|S|ich|I ~ bringe|V||P|mitbringen|bring|Separable verb "mitbringen": bringe … mit. ~ ihr|P|Df|DO|sie|her|Wem bringe ich Blumen mit? To whom? → dative object (sie → ihr). ~ gern|ADV||AB||gladly|verb + "gern" = to like doing something. ~ Blumen|N|Ap|AO|Blume|flowers|Was bringe ich mit? → accusative object. ~ mit|VT||P|mitbringen|(along)|Prefix of the separable verb; it goes to the end of the sentence. ~ .`,
 "I like to bring her flowers."],
[`Nach|PR||AB||after|"nach" always takes the dative. ~ dem|A|Dn|AB|der|the|Dative neuter: das → dem. ~ Essen|N|Dn|AB||meal ~ spielen|V||P||play ~ die|A|Np|S|der|the ~ Kinder|N|Np|S|Kind|children|Wer spielt? → subject. It comes after the verb because "Nach dem Essen" takes position 1. ~ im|PA|Dm|AB|in + dem|in the|im = in + dem. Wo? → dative. ~ Garten|N|Dm|AB||garden ~ .`,
 "After the meal the children play in the garden."],
[`Mein|A|Nm|S|mein|my|Nominative masculine: mein, with no ending. ~ Mann|N|Nm|S||husband ~ kocht|V||P|kochen|cooks ~ nicht|T||AB||not|Negation particle: it negates "gern kochen". ~ gern|ADV||AB||gladly ~ , ~ aber|K||K||but ~ er|P|Nm|S|er|he ~ spült|V||P|spülen|washes up ~ das|A|An|AO|der|the|Accusative neuter looks like the nominative: das. ~ Geschirr|N|An|AO||dishes|Was spült er? → accusative object. ~ .`,
 "My husband doesn't like cooking, but he washes the dishes."]
]},
{lvl:"B1", s:[
[`Seit|PR||AB||since|"seit" always takes the dative. ~ meiner|A|Df|AB|mein|my|Dative feminine: meine → meiner. ~ Hochzeit|N|Df|AB||wedding ~ vor|PR||AB||ago|"vor" + a time (Wann?) → dative. ~ fünf|Z||AB||five ~ Jahren|N|Dp|AB|Jahr|years|Dative plural: the noun adds -n (die Jahre → den Jahren). ~ lebe|V||P|leben|live ~ ich|P|N|S|ich|I ~ mit|PR||AB||with|"mit" + dative. ~ meiner|A|Df|AB|mein|my ~ Familie|N|Df|AB||family ~ in|PR||AB||in|Two-way preposition: Wo? → dative. ~ einer|A|Df|AB|ein|a|Dative feminine: eine → einer. ~ ruhigen|J|Df|AB|ruhig|quiet|Adjective after "einer" in the dative: ending -en. ~ Gegend|N|Df|AB||area ~ am|PA|Dm|AT|an + dem|on the|am = an + dem. Wo? → dative. ~ Stadtrand|N|Dm|AT||edge of town ~ .`,
 "Since my wedding five years ago, I have lived with my family in a quiet area on the edge of town."],
[`Obwohl|K||K||although|Subordinating conjunction: the verb goes to the end ("sind"). ~ mein|A|Nm|S|mein|my ~ Mann|N|Nm|S||husband ~ und|K||K||and ~ ich|P|N|S|ich|I ~ beide|P|Np|S||both ~ berufstätig|J||PN||employed|Predicative adjective after "sein": no ending. ~ sind|V||P|sein|are|In a subordinate clause the conjugated verb comes last. ~ , ~ verbringen|V||P||spend|After a subordinate clause, the main clause starts with its verb. ~ wir|P|N|S|wir|we ~ die|A|Ap|AO|der|the ~ Abende|N|Ap|AO|Abend|evenings|Was verbringen wir? → accusative object. ~ meistens|ADV||AB||usually ~ zusammen|ADV||AB||together ~ .`,
 "Although my husband and I both work, we usually spend the evenings together."],
[`Die|A|Np|S|der|the ~ Großeltern|N|Np|S||grandparents|Wer wohnt nicht in der Nähe? → subject. ~ unserer|A|Gp|GA|unser|our|Wessen Großeltern? Whose? → genitive plural: unsere → unserer. ~ Kinder|N|Gp|GA|Kind|children's|Genitive plural: die Kinder → der Kinder (no ending on the noun). ~ wohnen|V||P||live ~ leider|ADV||AB||unfortunately|Comment adverb: shows the speaker's feeling. ~ nicht|T||AB||not ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the|Dative feminine: die → der. ~ Nähe|N|Df|AB||vicinity|"in der Nähe" = nearby. ~ , ~ deshalb|ADV||AB||therefore|Linking adverb: the verb follows straight after it (position 2). ~ telefonieren|V||P||phone ~ wir|P|N|S|wir|we ~ jeden|A|Am|AB|jeder|every|A time phrase without a preposition is in the accusative: jeden Sonntag. ~ Sonntag|N|Am|AB||Sunday ~ mit|PR||PO||with|"telefonieren mit" + dative. ~ ihnen|P|Dp|PO|sie|them|Pronoun in the dative plural: sie → ihnen. ~ .`,
 "Our children's grandparents unfortunately don't live nearby, so we phone them every Sunday."],
[`Meine|A|Nf|S|mein|my ~ Schwester|N|Nf|S||sister ~ hat|V.hilf||P|haben|has|Auxiliary verb for the perfect tense. ~ mir|P|D|DO|ich|me|"helfen" always takes the dative: Wem hat sie geholfen? ~ letzte|J|Af|AB|letzt|last|Time phrase in the accusative: letzte Woche (adjective without article, feminine -e). ~ Woche|N|Af|AB||week ~ geholfen|VT||P|helfen|helped|Past participle at the end (perfect: hat … geholfen). ~ , ~ einen|A|Am|AO|ein|a|Accusative masculine: ein → einen. ~ neuen|J|Am|AO|neu|new|Adjective after "einen": ending -en. ~ Kindergartenplatz|N|Am|AO||kindergarten place|Was finden? → accusative object in the infinitive clause. ~ für|PR||AB||for|"für" always takes the accusative. ~ unseren|A|Am|AB|unser|our|Accusative masculine: unser → unseren. ~ Sohn|N|Am|AB||son ~ zu|T||P||to|"zu" + infinitive (infinitive clause). ~ finden|VT||P||find|Infinitive at the end of the infinitive clause. ~ .`,
 "Last week my sister helped me find a new kindergarten place for our son."],
[`Wenn|K||K||when|Subordinating conjunction: the verb goes to the end. ~ die|A|Np|S|der|the ~ Kinder|N|Np|S|Kind|children ~ im|PA|Dn|AB|in + dem|in (the)|Wo? → dative. ~ Bett|N|Dn|AB||bed ~ sind|V||P|sein|are ~ , ~ erzählen|V||P||tell ~ wir|P|N|S|wir|we ~ uns|P.refl|D|DO|wir|each other|Reciprocal: wir erzählen uns (dative) = we tell each other. ~ von|PR||PO||about|"erzählen von" + dative. ~ unserem|A|Dm|PO|unser|our|Dative masculine: unser → unserem. ~ Tag|N|Dm|PO||day ~ .`,
 "When the children are in bed, we tell each other about our day."]
]}
]},

{de:"Wohnen", en:"Housing", p:[
{lvl:"A1", s:[
[`Meine|A|Nf|S|mein|my ~ Wohnung|N|Nf|S||flat ~ ist|V||P|sein|is ~ klein|J||PN||small|Predicative adjective after "sein": no ending. ~ , ~ aber|K||K||but ~ hell|J||PN||bright ~ .`,
 "My flat is small but bright."],
[`Sie|P|Nf|S|sie|it|"sie" = die Wohnung (feminine), so "it" in English. ~ hat|V||P|haben|has ~ zwei|Z||AO||two ~ Zimmer|N|Ap|AO||rooms|Was hat sie? → accusative. The plural is the same as the singular. ~ , ~ eine|A|Af|AO|ein|a ~ Küche|N|Af|AO||kitchen ~ und|K||K||and ~ ein|A|An|AO||a ~ Bad|N|An|AO||bathroom ~ .`,
 "It has two rooms, a kitchen and a bathroom."],
[`Im|PA|Dn|AB|in + dem|in the|Wo? → dative. ~ Wohnzimmer|N|Dn|AB||living room ~ steht|V||P|stehen|stands ~ ein|A|Nn|S||a|Nominative neuter: ein. ~ großes|J|Nn|S|groß|big|Adjective after "ein", neuter nominative: ending -es. ~ Sofa|N|Nn|S||sofa|Was steht im Wohnzimmer? → subject, even though it comes last. ~ .`,
 "There is a big sofa in the living room."],
[`Ich|P|N|S|ich|I ~ stelle|V||P|stellen|put ~ den|A|Am|AO|der|the|Accusative masculine: der → den. ~ Tisch|N|Am|AO||table|Was stelle ich? → accusative object. ~ neben|PR||AB||next to|Two-way preposition: Wohin? (where to) → accusative. ~ das|A|An|AB|der|the|Accusative neuter: das. ~ Fenster|N|An|AB||window ~ .`,
 "I put the table next to the window."],
[`Die|A|Nf|S|der|the ~ Miete|N|Nf|S||rent|Was kostet 800 Euro? → subject. ~ der|A|Gf|GA|der|of the|Wessen Miete? Whose rent? → genitive feminine: die → der. ~ Wohnung|N|Gf|GA||flat|Feminine nouns take no ending in the genitive. ~ kostet|V||P|kosten|costs ~ 800|Z||AO||800 ~ Euro|N|Ap|AO||euros|Wie viel? How much? → an amount is in the accusative. ~ im|PA|Dm|AB|in + dem|per|"im Monat" = per month. ~ Monat|N|Dm|AB||month ~ .`,
 "The rent of the flat costs 800 euros a month."],
[`Mein|A|Nm|S|mein|my ~ Vermieter|N|Nm|S||landlord ~ wohnt|V||P|wohnen|lives ~ unten|ADV||AB||downstairs|Adverb of place: Wo? ~ im|PA|Dn|AB|in + dem|on the|Wo? → dative. ~ Erdgeschoss|N|Dn|AB||ground floor ~ .`,
 "My landlord lives downstairs on the ground floor."],
[`Er|P|Nm|S|er|he ~ gibt|V||P|geben|gives ~ mir|P|D|DO|ich|me|Wem gibt er den Schlüssel? → dative object. ~ morgen|ADV||AB||tomorrow ~ den|A|Am|AO|der|the ~ Schlüssel|N|Am|AO||key|Was gibt er mir? → accusative object. ~ für|PR||AT||for|"für" always takes the accusative. ~ den|A|Am|AT|der|the ~ Keller|N|Am|AT||cellar ~ .`,
 "Tomorrow he is giving me the key for the cellar."],
[`Leider|ADV||AB||unfortunately ~ darf|V||P|dürfen|am allowed|Modal verb in position 2; the infinitive goes to the end. ~ ich|P|N|S|ich|I ~ keine|A|Af|AO|kein|no|Negative article, accusative feminine: keine. ~ Katze|N|Af|AO||cat ~ haben|VT||P||have|Infinitive at the end (after a modal verb). ~ , ~ aber|K||K||but ~ das|P.dem|Nn|S||that|Demonstrative pronoun: it refers to the whole idea before. ~ ist|V||P|sein|is ~ nicht|T||AB||not ~ schlimm|J||PN||bad ~ .`,
 "Unfortunately I'm not allowed to have a cat, but that's not so bad."]
]},
{lvl:"B1", s:[
[`Letzten|J|Am|AB|letzt|last|Time phrase in the accusative: letzten Monat (adjective without article, masculine -en). ~ Monat|N|Am|AB||month ~ bin|V.hilf||P|sein|have|Perfect with "sein" for movement: umziehen. ~ ich|P|N|S|ich|I ~ in|PR||AB||into|Two-way preposition: Wohin? → accusative. ~ eine|A|Af|AB|ein|a ~ größere|J|Af|AB|groß|bigger|Comparative (groß → größer) with ending -e (accusative feminine). ~ Wohnung|N|Af|AB||flat ~ mit|PR||AT||with|"mit" + dative. ~ drei|Z||AT||three ~ Zimmern|N|Dp|AT|Zimmer|rooms|Dative plural: the noun adds -n. ~ in|PR||AT||in|Wo? → dative. ~ der|A|Df|AT|der|the ~ Nähe|N|Df|AT||vicinity ~ des|A|Gm|GA|der|of the|Wessen Nähe? → genitive masculine: der → des. ~ Hauptbahnhofs|N|Gm|GA|Hauptbahnhof|main station|Genitive masculine: the noun adds -s. ~ umgezogen|VT||P|umziehen|moved|Participle of "umziehen": ge- goes after the prefix (um-ge-zogen). ~ .`,
 "Last month I moved into a bigger flat with three rooms near the main station."],
[`Die|A|Nf|S|der|the ~ Wohnung|N|Nf|S||flat ~ , ~ die|P.rel|Af|AO|der|that|Relative pronoun in the accusative: ich habe die Wohnung gefunden. ~ ich|P|N|S|ich|I ~ gefunden|VT||P|finden|found|Past participle (perfect). ~ habe|V.hilf||P|haben|have|In a relative clause the conjugated verb comes last. ~ , ~ hat|V||P|haben|has ~ einen|A|Am|AO|ein|a ~ Balkon|N|Am|AO||balcony|Was hat die Wohnung? → accusative object. ~ , ~ von|PR||AB||from|"von" always takes the dative. ~ dem|P.rel|Dm|AB|der|which|Relative pronoun in the dative: der Balkon → von dem. ~ man|P|N|S||you (one)|Indefinite pronoun, always nominative. ~ den|A|Am|AO|der|the ~ Fluss|N|Am|AO||river|Was sieht man? → accusative object. ~ sieht|V||P|sehen|sees ~ .`,
 "The flat that I found has a balcony from which you can see the river."],
[`Mein|A|Nm|S|mein|my ~ neuer|J|Nm|S|neu|new|After "mein" (no ending) the adjective shows the case: masculine nominative -er. ~ Vermieter|N|Nm|S||landlord ~ ist|V||P|sein|is ~ sehr|ADV||PN||very|Degree adverb: it makes the adjective stronger. ~ freundlich|J||PN||friendly|Predicative after "sein": no ending. ~ und|K||K||and ~ hat|V.hilf||P|haben|has ~ mir|P|D|DO|ich|me|"geben": Wem? → dative object. ~ sofort|ADV||AB||immediately ~ die|A|Ap|AO|der|the ~ Schlüssel|N|Ap|AO||keys|Was hat er gegeben? → accusative plural (die Schlüssel). ~ für|PR||AT||for|"für" + accusative. ~ den|A|Am|AT|der|the ~ Keller|N|Am|AT||cellar ~ gegeben|VT||P|geben|given|Past participle at the end. ~ .`,
 "My new landlord is very friendly and gave me the keys to the cellar straight away."],
[`Trotz|PR||AB||despite|"trotz" takes the genitive. ~ der|A|Gf|AB|der|the|Genitive feminine: die → der. ~ hohen|J|Gf|AB|hoch|high|hoch → hoh-; after "der" in the genitive: ending -en. ~ Miete|N|Gf|AB||rent ~ fühle|V||P|wohlfühlen|feel|Reflexive separable verb: sich wohlfühlen. ~ ich|P|N|S|ich|I ~ mich|P.refl|A|AO|ich|myself|Reflexive pronoun in the accusative. ~ hier|ADV||AB||here ~ wohl|VT||P|wohlfühlen|(comfortable)|Prefix of "sich wohlfühlen"; it goes to the end. ~ , ~ weil|K||K||because|Subordinate clause: the verb goes to the end. ~ die|A|Np|S|der|the ~ Nachbarn|N|Np|S|Nachbar|neighbours ~ nett|J||PN||nice ~ sind|V||P|sein|are ~ und|K||K||and ~ es|P|Nn|S||it ~ nicht|T||AB||not ~ laut|J||PN||loud ~ ist|V||P|sein|is ~ .`,
 "Despite the high rent I feel at home here, because the neighbours are nice and it isn't loud."],
[`Am|PA|Dn|AB|an + dem|at the|Time: am Wochenende → dative. ~ Wochenende|N|Dn|AB||weekend ~ möchte|V||P|möchten|would like|Modal verb in position 2. ~ ich|P|N|S|ich|I ~ die|A|Ap|AO|der|the ~ Wände|N|Ap|AO|Wand|walls|Was streichen? → accusative (die Wand → die Wände). ~ streichen|VT||P||paint|Infinitive at the end. ~ und|K||K||and ~ meinen|A|Dp|DO|mein|my|Dative plural: meine → meinen. ~ Freunden|N|Dp|DO|Freund|friends|Wem zeigen? → dative object. Dative plural: noun + -n. ~ die|A|Af|AO|der|the ~ Wohnung|N|Af|AO||flat|Was zeigen? → accusative object. ~ zeigen|VT||P||show ~ .`,
 "At the weekend I'd like to paint the walls and show my friends the flat."]
]}
]},

{de:"Arbeit", en:"Work", p:[
{lvl:"A1", s:[
[`Mein|A|Nm|S|mein|my ~ Bruder|N|Nm|S||brother ~ ist|V||P|sein|is ~ Koch|N|Nm|PN||cook|After "sein" the noun is in the nominative. Jobs take no article. ~ von|PR||AB||by|"von Beruf" – "von" + dative. ~ Beruf|N|Dm|AB||profession ~ .`,
 "My brother is a cook by profession."],
[`Er|P|Nm|S|er|he ~ arbeitet|V||P|arbeiten|works ~ acht|Z||AB||eight ~ Stunden|N|Ap|AB|Stunde|hours|Wie lange? A length of time without a preposition is in the accusative. ~ am|PA|Dm|AB|an + dem|a (per)|"am Tag" = per day. ~ Tag|N|Dm|AB||day ~ in|PR||AB||in|Wo? → dative. ~ einem|A|Dn|AB|ein|a|Dative neuter: ein → einem. ~ Restaurant|N|Dn|AB||restaurant ~ am|PA|Dm|AT|an + dem|at the|Wo? → dative. ~ Bahnhof|N|Dm|AT||station ~ .`,
 "He works eight hours a day in a restaurant at the station."],
[`Jeden|A|Am|AB|jeder|every|A time phrase without a preposition is in the accusative. ~ Morgen|N|Am|AB||morning ~ fährt|V||P|fahren|goes|Irregular: ich fahre, du fährst, er fährt. ~ er|P|Nm|S|er|he ~ mit|PR||AB||by|"mit" + dative: mit dem Bus = by bus. ~ dem|A|Dm|AB|der|the ~ Bus|N|Dm|AB||bus ~ zur|PA|Df|AB|zu + der|to the|zur = zu + der. "zu" always takes the dative. ~ Arbeit|N|Df|AB||work ~ .`,
 "Every morning he goes to work by bus."],
[`Er|P|Nm|S|er|he ~ kocht|V||P|kochen|cooks ~ für|PR||AB||for|"für" + accusative. ~ die|A|Ap|AB|der|the ~ Gäste|N|Ap|AB|Gast|guests|der Gast → die Gäste. ~ Suppe|N|Af|AO||soup|Was kocht er? → accusative object, here without an article. ~ , ~ Fisch|N|Am|AO||fish ~ und|K||K||and ~ Salat|N|Am|AO||salad ~ .`,
 "He cooks soup, fish and salad for the guests."],
[`Die|A|Nf|S|der|the ~ Küche|N|Nf|S||kitchen ~ des|A|Gn|GA|der|of the|Wessen Küche? → genitive neuter: das → des. ~ Restaurants|N|Gn|GA|Restaurant|restaurant's|Genitive neuter: the noun adds -s. ~ ist|V||P|sein|is ~ sehr|ADV||PN||very|Degree adverb: it makes "modern" stronger. ~ modern|J||PN||modern ~ .`,
 "The restaurant's kitchen is very modern."],
[`Sein|A|Nm|S|sein|his ~ Chef|N|Nm|S||boss ~ zeigt|V||P|zeigen|shows ~ ihm|P|Dm|DO|er|him|Wem zeigt er Rezepte? → dative object (er → ihm). ~ oft|ADV||AB||often ~ neue|J|Ap|AO|neu|new|Adjective without an article, accusative plural: ending -e. ~ Rezepte|N|Ap|AO|Rezept|recipes ~ .`,
 "His boss often shows him new recipes."],
[`Am|PA|Dm|AB|an + dem|on|Days of the week: am Montag → dative. ~ Montag|N|Dm|AB||Monday ~ muss|V||P|müssen|must|Modal verb. "nicht müssen" = not have to. ~ er|P|Nm|S|er|he ~ nicht|T||AB||not ~ arbeiten|VT||P||work|Infinitive at the end. ~ .`,
 "On Monday he doesn't have to work."],
[`Dann|ADV||AB||then ~ schläft|V||P|schlafen|sleeps ~ er|P|Nm|S|er|he ~ lange|ADV||AB||long|Adverb of time: Wie lange? How long? ~ und|K||K||and ~ trifft|V||P|treffen|meets ~ seine|A|Ap|AO|sein|his ~ Freunde|N|Ap|AO|Freund|friends|Wen trifft er? → accusative object. ~ .`,
 "Then he sleeps late and meets his friends."]
]},
{lvl:"B1", s:[
[`Seit|PR||AB||for|"seit" + dative: seit zwei Jahren = for two years. ~ zwei|Z||AB||two ~ Jahren|N|Dp|AB|Jahr|years|Dative plural: -n. ~ arbeite|V||P|arbeiten|have been working|Present tense with "seit": the action is still going on. ~ ich|P|N|S|ich|I ~ als|K||AB||as|"als" + job: same case as the word it refers to. ~ Softwareentwickler|N|Nm|AB||software developer|Nominative, because it refers to "ich" (the subject). ~ bei|PR||AB||at|"bei" always takes the dative. ~ einer|A|Df|AB|ein|a ~ internationalen|J|Df|AB|international|international|After "einer" in the dative: -en. ~ Firma|N|Df|AB||company ~ , ~ deren|P.rel|Gf|GA|die|whose|Relative pronoun in the genitive (feminine): die Firma → deren Büro. ~ Büro|N|Nn|S||office|Was liegt im Zentrum? → subject of the relative clause. ~ im|PA|Dn|AB|in + dem|in the|Wo? → dative. ~ Zentrum|N|Dn|AB||centre ~ der|A|Gf|GA|der|of the|Wessen Zentrum? → genitive feminine. ~ Stadt|N|Gf|GA||city ~ liegt|V||P|liegen|is located|Relative clause: the verb comes last. ~ .`,
 "For two years I have been working as a software developer at an international company whose office is in the city centre."],
[`Jeden|A|Am|AB|jeder|every|Time phrase → accusative. ~ Tag|N|Am|AB||day ~ entwickle|V||P|entwickeln|develop|entwickeln: ich entwickle (the -e- drops). ~ ich|P|N|S|ich|I ~ neue|J|Ap|AO|neu|new|No article, accusative plural: -e. ~ Funktionen|N|Ap|AO|Funktion|features ~ für|PR||AT||for|"für" + accusative. ~ unsere|A|Ap|AT|unser|our ~ Kunden|N|Ap|AT|Kunde|customers|n-declension: der Kunde → die Kunden. ~ und|K||K||and ~ suche|V||P|suchen|look for ~ Fehler|N|Ap|AO||errors|Was suche ich? → accusative plural. ~ im|PA|Dm|AT|in + dem|in the|Wo? → dative. ~ Code|N|Dm|AT||code ~ .`,
 "Every day I develop new features for our customers and look for errors in the code."],
[`Obwohl|K||K||although|Subordinate clause: the verb goes to the end. ~ die|A|Nf|S|der|the ~ Arbeit|N|Nf|S||work ~ manchmal|ADV||AB||sometimes ~ stressig|J||PN||stressful ~ ist|V||P|sein|is ~ , ~ gefällt|V||P|gefallen|pleases|"gefallen" + dative: etwas gefällt mir = I like something. ~ sie|P|Nf|S|sie|it|"sie" = die Arbeit. It is the subject! ~ mir|P|D|DO|ich|me|Wem gefällt sie? → dative object. ~ sehr|ADV||AB||very ~ gut|J||AB||well|Adjective used like an adverb (Wie?): no ending. ~ .`,
 "Although the work is sometimes stressful, I like it very much."],
[`Meine|A|Np|S|mein|my ~ Kollegen|N|Np|S|Kollege|colleagues|n-declension: der Kollege → die Kollegen. ~ helfen|V||P||help ~ mir|P|D|DO|ich|me|"helfen" always takes the dative. ~ , ~ wenn|K||K||when|Subordinate clause: the verb goes to the end. ~ ich|P|N|S|ich|I ~ eine|A|Af|AO|ein|a ~ Frage|N|Af|AO||question ~ habe|V||P|haben|have ~ , ~ und|K||K||and ~ wir|P|N|S|wir|we ~ essen|V||P||eat ~ oft|ADV||AB||often ~ zusammen|ADV||AB||together ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the ~ Kantine|N|Df|AB||canteen ~ .`,
 "My colleagues help me when I have a question, and we often eat together in the canteen."],
[`Nächstes|J|An|AB|nächst|next|Time phrase in the accusative: nächstes Jahr (neuter, no article: -es). ~ Jahr|N|An|AB||year ~ habe|V||P|vorhaben|plan|Separable verb "vorhaben": habe … vor. ~ ich|P|N|S|ich|I ~ vor|VT||P|vorhaben|(plan)|Prefix of "vorhaben". ~ , ~ eine|A|Af|AO|ein|a ~ Weiterbildung|N|Af|AO||further training|Was machen? → accusative object. ~ zu|T||P||to|"zu" + infinitive. ~ machen|VT||P||do ~ , ~ um|K||K||in order to|"um … zu" + infinitive: purpose. ~ bessere|J|Ap|AO|gut|better|Comparative of "gut" (besser) + ending -e. ~ Chancen|N|Ap|AO|Chance|chances ~ auf|PR||AT||of|"Chancen auf" + accusative. ~ eine|A|Af|AT|ein|a ~ Beförderung|N|Af|AT||promotion ~ zu|T||P||to ~ haben|VT||P||have ~ .`,
 "Next year I plan to do further training in order to have better chances of a promotion."]
]}
]},

{de:"Einkaufen und Essen", en:"Shopping and food", p:[
{lvl:"A1", s:[
[`Am|PA|Dm|AB|an + dem|on|am = an + dem → dative. ~ Samstag|N|Dm|AB||Saturday ~ gehe|V||P|gehen|go ~ ich|P|N|S|ich|I ~ in|PR||AB||into|Two-way preposition: Wohin? → accusative. ~ den|A|Am|AB|der|the|Accusative masculine. ~ Supermarkt|N|Am|AB||supermarket ~ .`,
 "On Saturday I go to the supermarket."],
[`Ich|P|N|S|ich|I ~ kaufe|V||P|kaufen|buy ~ Brot|N|An|AO||bread|Was kaufe ich? → accusative, without an article. ~ , ~ Milch|N|Af|AO||milk ~ , ~ Käse|N|Am|AO||cheese ~ und|K||K||and ~ fünf|Z||AO||five ~ Äpfel|N|Ap|AO|Apfel|apples|der Apfel → die Äpfel. ~ .`,
 "I buy bread, milk, cheese and five apples."],
[`Die|A|Nf|S|der|the ~ Verkäuferin|N|Nf|S||saleswoman ~ gibt|V||P|geben|gives ~ mir|P|D|DO|ich|me|Wem gibt sie eine Tüte? → dative object. ~ eine|A|Af|AO|ein|a ~ Tüte|N|Af|AO||bag|Was gibt sie mir? → accusative object. ~ .`,
 "The saleswoman gives me a bag."],
[`Der|A|Nm|S|der|the ~ Preis|N|Nm|S||price ~ des|A|Gm|GA|der|of the|Genitive masculine: der → des. ~ Käses|N|Gm|GA|Käse|cheese|Genitive masculine: the noun adds -s. ~ ist|V||P|sein|is ~ heute|ADV||AB||today ~ günstig|J||PN||cheap ~ .`,
 "The price of the cheese is cheap today."],
[`Zu|PR||AB||at|"zu Hause" = at home ("zu" + dative). ~ Hause|N|Dn|AB|Haus|home|Old dative form: das Haus → zu Hause. ~ koche|V||P|kochen|cook ~ ich|P|N|S|ich|I ~ mit|PR||AB||with|"mit" + dative. ~ meiner|A|Df|AB|mein|my|Dative feminine: meine → meiner. ~ Frau|N|Df|AB||wife ~ eine|A|Af|AO|ein|a ~ Suppe|N|Af|AO||soup ~ .`,
 "At home I cook a soup with my wife."],
[`Die|A|Nf|S|der|the ~ Suppe|N|Nf|S||soup ~ ist|V||P|sein|is ~ heiß|J||PN||hot ~ , ~ aber|K||K||but ~ sehr|ADV||PN||very ~ lecker|J||PN||delicious ~ .`,
 "The soup is hot, but very tasty."],
[`Meine|A|Nf|S|mein|my ~ Tochter|N|Nf|S||daughter ~ isst|V||P|essen|eats|Irregular: ich esse, du isst, sie isst. ~ Fisch|N|Am|AO||fish|Was isst sie? → accusative object. ~ nicht|T||AB||not ~ gern|ADV||AB||gladly ~ .`,
 "My daughter doesn't like eating fish."],
[`Nach|PR||AB||after|"nach" + dative. ~ dem|A|Dn|AB|der|the ~ Essen|N|Dn|AB||meal ~ räumen|V||P|aufräumen|tidy|Separable verb "aufräumen": räumen … auf. ~ wir|P|N|S|wir|we ~ zusammen|ADV||AB||together ~ die|A|Af|AO|der|the ~ Küche|N|Af|AO||kitchen ~ auf|VT||P|aufräumen|(up)|Prefix at the end. ~ .`,
 "After the meal we tidy up the kitchen together."]
]},
{lvl:"B1", s:[
[`Seitdem|K||K||since|Subordinate clause: the verb goes to the end. ~ ich|P|N|S|ich|I ~ mich|P.refl|A|AO|ich|myself|Reflexive pronoun: sich ernähren (accusative). ~ gesünder|J||AB|gesund|more healthily|Comparative of "gesund", used like an adverb (no ending). ~ ernähre|V||P|ernähren|eat ~ , ~ kaufe|V||P|kaufen|buy ~ ich|P|N|S|ich|I ~ mein|A|An|AO|mein|my|Accusative neuter: mein (no ending). ~ Gemüse|N|An|AO||vegetables|Was kaufe ich? → accusative object. ~ am|ADV||AB|gern|(most)|"am liebsten" = superlative of "gern" (gern – lieber – am liebsten). ~ liebsten|ADV||AB|gern|like best to ~ auf|PR||AB||at|Two-way preposition: Wo? → dative. ~ dem|A|Dm|AB|der|the ~ Wochenmarkt|N|Dm|AB||weekly market ~ .`,
 "Since I started eating more healthily, I like buying my vegetables at the weekly market best."],
[`Dort|ADV||AB||there ~ bieten|V||P|anbieten|offer|Separable: bieten … an. ~ die|A|Np|S|der|the ~ Bauern|N|Np|S|Bauer|farmers|n-declension: der Bauer → die Bauern. ~ aus|PR||AT||from|"aus" + dative. ~ der|A|Df|AT|der|the ~ Region|N|Df|AT||region ~ frisches|J|An|AO|frisch|fresh|No article, neuter accusative: -es. ~ Obst|N|An|AO||fruit|Was bieten sie an? → accusative object. ~ an|VT||P|anbieten|(offer)|Prefix at the end of the main clause. ~ , ~ das|P.rel|Nn|S|das|which|Relative pronoun in the nominative: das Obst ist billiger. ~ oft|ADV||AB||often ~ billiger|J||PN|billig|cheaper|Comparative after "sein": no ending. ~ ist|V||P|sein|is ~ als|K||K||than|Comparison: comparative + "als". ~ im|PA|Dm|AB|in + dem|in the|Wo? → dative. ~ Supermarkt|N|Dm|AB||supermarket ~ .`,
 "There the farmers from the region offer fresh fruit, which is often cheaper than in the supermarket."],
[`Der|A|Nm|S|der|the ~ Geschmack|N|Nm|S||taste ~ der|A|Gp|GA|der|of the|Genitive plural: die → der. ~ Tomaten|N|Gp|GA|Tomate|tomatoes ~ ist|V||P|sein|is ~ viel|ADV||PN||much|Makes the comparative stronger: viel intensiver. ~ intensiver|J||PN|intensiv|more intense ~ , ~ weil|K||K||because ~ sie|P|Np|S|sie|they ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the ~ Sonne|N|Df|AB||sun ~ gereift|VT||P|reifen|ripened|Past participle. Perfect with "sein" (a change of state). ~ sind|V.hilf||P|sein|have|Auxiliary verb at the end of the subordinate clause. ~ .`,
 "The taste of the tomatoes is much more intense because they have ripened in the sun."],
[`Gestern|ADV||AB||yesterday ~ habe|V.hilf||P|haben|have|Auxiliary verb (perfect). ~ ich|P|N|S|ich|I ~ meiner|A|Df|DO|mein|my|Dative feminine: Wem habe ich ihn geschenkt? ~ Nachbarin|N|Df|DO||neighbour ~ einen|A|Am|AO|ein|a ~ Korb|N|Am|AO||basket|Was habe ich geschenkt? → accusative. ~ mit|PR||AT||with|"mit" + dative. ~ zwei|Z||AT||two ~ Kilo|N|Dn|AT||kilos ~ Erdbeeren|N|Dp|AT|Erdbeere|strawberries|Dative plural (the noun already ends in -n). ~ geschenkt|VT||P|schenken|given (as a gift) ~ , ~ und|K||K||and ~ sie|P|Nf|S|sie|she ~ hat|V.hilf||P|haben|has ~ sich|P.refl|A|AO|sie|herself|Reflexive pronoun: sich freuen (accusative). ~ sehr|ADV||AB||very ~ darüber|ADV||PO||about it|Pronominal adverb: sich freuen über + etwas → darüber. ~ gefreut|VT||P|freuen|been pleased ~ .`,
 "Yesterday I gave my neighbour a basket with two kilos of strawberries, and she was very pleased about it."],
[`Beim|PA|Dn|AB|bei + dem|while|beim = bei + dem; beim + a verb used as a noun = while doing it. ~ Kochen|N|Dn|AB||cooking|A verb used as a noun: das Kochen (capital letter). ~ probiere|V||P|ausprobieren|try|Separable: probiere … aus. ~ ich|P|N|S|ich|I ~ gern|ADV||AB||gladly ~ neue|J|Ap|AO|neu|new ~ Rezepte|N|Ap|AO|Rezept|recipes ~ aus|VT||P|ausprobieren|(out) ~ , ~ aber|K||K||but ~ scharfes|J|An|AO|scharf|spicy|No article, neuter accusative: -es. ~ Essen|N|An|AO||food|The accusative object stands first here for emphasis. ~ vertrage|V||P|vertragen|tolerate ~ ich|P|N|S|ich|I ~ nicht|T||AB||not ~ .`,
 "When cooking I like to try out new recipes, but I can't tolerate spicy food."]
]}
]},

{de:"Freizeit und Reisen", en:"Free time and travel", p:[
{lvl:"A1", s:[
[`In|PR||AB||in|Wo? → dative. ~ meiner|A|Df|AB|mein|my ~ Freizeit|N|Df|AB||free time ~ mache|V||P|machen|do ~ ich|P|N|S|ich|I ~ gern|ADV||AB||gladly ~ Sport|N|Am|AO||sport|Was mache ich? → accusative, without an article. ~ .`,
 "In my free time I like doing sport."],
[`Zweimal|ADV||AB||twice|Adverb of frequency: Wie oft? ~ pro|PR||AB||per|"pro" + accusative, usually without an article. ~ Woche|N|Af|AB||week ~ gehe|V||P|gehen|go ~ ich|P|N|S|ich|I ~ ins|PA|An|AB|in + das|to the|ins = in + das. Wohin? → accusative. ~ Fitnessstudio|N|An|AB||gym ~ .`,
 "Twice a week I go to the gym."],
[`Im|PA|Dm|AB|in + dem|in|Time: im Sommer → dative. ~ Sommer|N|Dm|AB||summer ~ fahre|V||P|fahren|travel ~ ich|P|N|S|ich|I ~ mit|PR||AB||with|"mit" + dative. ~ meinen|A|Dp|AB|mein|my|Dative plural: meine → meinen. ~ Freunden|N|Dp|AB|Freund|friends|Dative plural: the noun adds -n. ~ ans|PA|An|AB|an + das|to the|ans = an + das. Wohin? → accusative. ~ Meer|N|An|AB||sea ~ .`,
 "In summer I go to the sea with my friends."],
[`Unser|A|Nn|S|unser|our ~ Hotel|N|Nn|S||hotel ~ liegt|V||P|liegen|is located ~ am|PA|Dm|AB|an + dem|on the|Wo? → dative. ~ Strand|N|Dm|AB||beach ~ .`,
 "Our hotel is on the beach."],
[`Die|A|Np|S|der|the ~ Zimmer|N|Np|S||rooms ~ des|A|Gn|GA|der|of the|Wessen Zimmer? → genitive neuter: das → des. ~ Hotels|N|Gn|GA|Hotel|hotel|Genitive neuter: the noun adds -s. ~ sind|V||P|sein|are ~ groß|J||PN||big ~ und|K||K||and ~ sauber|J||PN||clean ~ .`,
 "The hotel's rooms are big and clean."],
[`Am|PA|Dm|AB|an + dem|in the|am Abend → dative. ~ Abend|N|Dm|AB||evening ~ essen|V||P||eat ~ wir|P|N|S|wir|we ~ Pizza|N|Af|AO||pizza ~ und|K||K||and ~ trinken|V||P||drink ~ ein|A|An|AO||a ~ kaltes|J|An|AO|kalt|cold|After "ein", neuter accusative: -es. ~ Bier|N|An|AO||beer ~ .`,
 "In the evening we eat pizza and drink a cold beer."],
[`Ich|P|N|S|ich|I ~ schicke|V||P|schicken|send ~ meiner|A|Df|DO|mein|my|Wem schicke ich eine Postkarte? → dative feminine. ~ Mutter|N|Df|DO||mother ~ eine|A|Af|AO|ein|a ~ Postkarte|N|Af|AO||postcard|Was schicke ich? → accusative. ~ .`,
 "I send my mother a postcard."],
[`Leider|ADV||AB||unfortunately ~ kann|V||P|können|can ~ ich|P|N|S|ich|I ~ nur|T||AB||only|Focus particle: it limits the number. ~ zehn|Z||AB||ten ~ Tage|N|Ap|AB|Tag|days|How long? A length of time without a preposition is in the accusative. ~ bleiben|VT||P||stay|Infinitive at the end (after a modal verb). ~ .`,
 "Unfortunately I can only stay ten days."]
]},
{lvl:"B1", s:[
[`Letzten|J|Am|AB|letzt|last|Time phrase in the accusative. ~ Sommer|N|Am|AB||summer ~ habe|V.hilf||P|haben|have|Auxiliary verb (perfect). ~ ich|P|N|S|ich|I ~ mit|PR||AB||with|"mit" + dative. ~ zwei|Z||AB||two ~ Freunden|N|Dp|AB|Freund|friends|Dative plural: -n. ~ eine|A|Af|AO|ein|a ~ Rundreise|N|Af|AO||round trip|Was habe ich gemacht? → accusative. ~ durch|PR||AT||through|"durch" always takes the accusative. ~ Portugal|N|An|AT||Portugal|Country name without an article, accusative after "durch". ~ gemacht|VT||P|machen|done ~ , ~ von|PR||PO||about|"begeistert sein von" + dative. ~ der|P.rel|Df|PO|die|which|Relative pronoun in the dative feminine: die Rundreise → von der. ~ ich|P|N|S|ich|I ~ immer|ADV||AB||always ~ noch|T||AB||still|"immer noch" = still. ~ begeistert|J||PN||enthusiastic|A participle used as an adjective after "sein". ~ bin|V||P|sein|am|Relative clause: the verb comes last. ~ .`,
 "Last summer I did a round trip through Portugal with two friends, which I'm still excited about."],
[`Da|K||K||since|"da" = because. Subordinate clause: the verb goes to the end. ~ wir|P|N|S|wir|we ~ kein|A|An|AO|kein|no|Negative article, accusative neuter: kein (no ending). ~ Auto|N|An|AO||car ~ hatten|V||P|haben|had|Simple past of "haben". ~ , ~ sind|V.hilf||P|sein|have|Perfect with "sein" for movement. ~ wir|P|N|S|wir|we ~ mit|PR||AB||by|"mit" + dative. ~ dem|A|Dm|AB|der|the ~ Zug|N|Dm|AB||train ~ von|PR||AB||from|"von" + dative. ~ Lissabon|N|Dn|AB||Lisbon ~ nach|PR||AB||to|"nach" + cities or countries without an article (direction); dative. ~ Porto|N|Dn|AB||Porto ~ gefahren|VT||P|fahren|travelled ~ .`,
 "Since we didn't have a car, we travelled by train from Lisbon to Porto."],
[`Unterwegs|ADV||AB||on the way ~ haben|V.hilf||P||have ~ wir|P|N|S|wir|we ~ die|A|Af|AO|der|the ~ Schönheit|N|Af|AO||beauty|Was haben wir genossen? → accusative. ~ der|A|Gf|GA|der|of the|Genitive feminine: die → der. ~ Landschaft|N|Gf|GA||landscape ~ genossen|VT||P|genießen|enjoyed|Irregular participle: genießen → genossen. ~ und|K||K||and ~ viele|A|Ap|AO|viel|many|Determiner for an amount, accusative plural. ~ Fotos|N|Ap|AO|Foto|photos ~ gemacht|VT||P|machen|taken ~ .`,
 "On the way we enjoyed the beauty of the landscape and took lots of photos."],
[`In|PR||AB||in|Wo? → dative. ~ Porto|N|Dn|AB||Porto ~ hat|V.hilf||P|haben|has ~ uns|P|D|DO|wir|us|Wem hat er den Weg gezeigt? → dative object. ~ ein|A|Nm|S||an|Nominative masculine: ein. ~ älterer|J|Nm|S|alt|elderly|Comparative (alt → älter) after "ein", masculine nominative: -er. ~ Herr|N|Nm|S||gentleman|Wer hat uns den Weg gezeigt? → subject. It comes after the dative object here! ~ den|A|Am|AO|der|the ~ Weg|N|Am|AO||way|Was hat er gezeigt? → accusative. ~ zu|PR||AT||to|"zu" + dative. ~ einem|A|Dn|AT|ein|a ~ kleinen|J|Dn|AT|klein|small|After "einem": -en. ~ Restaurant|N|Dn|AT||restaurant ~ gezeigt|VT||P|zeigen|shown ~ , ~ in|PR||AB||in|Wo? → dative. ~ dem|P.rel|Dn|AB|das|which|Relative pronoun in the dative neuter: das Restaurant → in dem. ~ es|P|Nn|S||it|"es gibt" + accusative = there is. ~ typisches|J|An|AO|typisch|typical|No article, neuter accusative: -es. ~ Essen|N|An|AO||food|"es gibt" always takes the accusative. ~ gibt|V||P|geben|there is ~ .`,
 "In Porto an elderly gentleman showed us the way to a small restaurant where there is typical food."],
[`Nächstes|J|An|AB|nächst|next|Time phrase in the accusative (neuter -es). ~ Jahr|N|An|AB||year ~ möchten|V||P||would like ~ wir|P|N|S|wir|we ~ unbedingt|ADV||AB||definitely ~ wieder|ADV||AB||again ~ hinfahren|VT||P||go there|Infinitive after the modal verb (hin = there). ~ , ~ falls|K||K||if|Subordinate clause: the verb goes to the end. ~ wir|P|N|S|wir|we ~ genug|ADV||AO||enough|"genug" + noun = enough (no ending). ~ Geld|N|An|AO||money|Was sparen? → accusative. ~ sparen|VT||P||save ~ können|V||P||can|Modal verb at the very end of the subordinate clause. ~ .`,
 "Next year we definitely want to go there again, if we can save enough money."]
]}
]},

{de:"Gesundheit", en:"Health", p:[
{lvl:"A1", s:[
[`Ich|P|N|S|ich|I ~ bin|V||P|sein|am ~ heute|ADV||AB||today ~ krank|J||PN||ill|Predicative adjective after "sein": no ending. ~ und|K||K||and ~ habe|V||P|haben|have|The subject "ich" is not repeated after "und". ~ Kopfschmerzen|N|Ap|AO|Kopfschmerz|a headache|Was habe ich? → accusative object; usually plural: die Kopfschmerzen. ~ .`,
 "I am ill today and have a headache."],
[`Am|PA|Dm|AB|an + dem|in the|am = an + dem: "am Morgen" → dative. ~ Morgen|N|Dm|AB||morning ~ rufe|V||P|anrufen|call|Separable verb "anrufen": rufe … an. ~ ich|P|N|S|ich|I|The subject comes after the verb because "Am Morgen" takes position 1. ~ die|A|Af|AO|der|the ~ Praxis|N|Af|AO||doctor's surgery|Wen rufe ich an? → accusative object. ~ an|VT||P|anrufen|(prefix)|The prefix "an" goes to the end of the main clause. ~ .`,
 "In the morning I call the doctor's surgery."],
[`Die|A|Nf|S|der|the ~ Ärztin|N|Nf|S||doctor (woman)|Wer hat Zeit? → subject, nominative. ~ hat|V||P|haben|has ~ um|PR||AB||at|"um" + clock time; "um" always takes the accusative. ~ zehn|Z||AB||ten ~ Uhr|N|Af|AB||o'clock ~ Zeit|N|Af|AO||time|Was hat sie? → accusative object, no article. ~ für|PR||AB||for|"für" always takes the accusative. ~ mich|P|A|AB|ich|me|After "für": accusative (ich → mich). ~ .`,
 "The doctor has time for me at ten o'clock."],
[`In|PR||AB||in|Two-way preposition: Wo? (where) → dative. ~ der|A|Df|AB|der|the ~ Praxis|N|Df|AB||surgery ~ gebe|V||P|geben|give ~ ich|P|N|S|ich|I ~ der|A|Df|DO|der|the|Wem gebe ich die Karte? To whom? → dative object: die → der. ~ Frau|N|Df|DO||woman ~ am|PA|Dm|AT|an + dem|at the|Which woman? The one at the reception – Wo? → dative. ~ Empfang|N|Dm|AT||reception ~ meine|A|Af|AO|mein|my|Possessive article, accusative feminine: meine. ~ Karte|N|Af|AO||(insurance) card|Was gebe ich? → accusative object. ~ .`,
 "In the surgery I give the woman at the reception my (insurance) card."],
[`Die|A|Nf|S|der|the ~ Ärztin|N|Nf|S||doctor ~ untersucht|V||P|untersuchen|examines ~ mich|P|A|AO|ich|me|Wen untersucht sie? → accusative (ich → mich). ~ und|K||K||and ~ schreibt|V||P|krankschreiben|signs|Separable verb "krankschreiben": schreibt … krank. ~ mich|P|A|AO|ich|me ~ bis|PR||AB||until|"bis" + "zum" (zu + dem): the dative comes from "zu". ~ zum|PA|Dn|AB|zu + dem|to the ~ Ende|N|Dn|AB||end ~ der|A|Gf|GA|der|of the|Wessen Ende? The end of what? → genitive feminine: die → der. ~ Woche|N|Gf|GA||week ~ krank|VT||P|krankschreiben|off sick|The first part of "krankschreiben" goes to the end. ~ .`,
 "The doctor examines me and signs me off sick until the end of the week."],
[`Danach|ADV||AB||after that|Adverb of time in position 1: the verb follows straight away. ~ hole|V||P|holen|fetch ~ ich|P|N|S|ich|I ~ in|PR||AB||at|Wo? → dative. ~ der|A|Df|AB|der|the ~ Apotheke|N|Df|AB||pharmacy ~ zwei|Z||AO||two ~ Medikamente|N|Ap|AO|Medikament|medicines|Was hole ich? → accusative object (plural). ~ .`,
 "After that I pick up two medicines at the pharmacy."],
[`Ich|P|N|S|ich|I ~ darf|V||P|dürfen|am allowed ~ nicht|T||AB||not|"nicht" before the infinitive negates the whole action. ~ arbeiten|VT||P||work|Infinitive at the end after the modal verb. ~ , ~ aber|K||K||but|Joins two main clauses; word order stays normal. ~ ich|P|N|S|ich|I ~ trinke|V||P|trinken|drink ~ viel|ADV||AB||a lot ~ Tee|N|Am|AO||tea|Was trinke ich? → accusative object; no article for an amount. ~ und|K||K||and ~ schlafe|V||P|schlafen|sleep ~ lange|ADV||AB||long ~ .`,
 "I am not allowed to work, but I drink a lot of tea and sleep for a long time."]
]},
{lvl:"B1", s:[
[`Seit|PR||AB||for|"seit" + dative: for a time that is still going on. ~ drei|Z||AB||three ~ Tagen|N|Dp|AB|Tag|days|Dative plural: der Tag → den Tagen. ~ fühle|V||P|fühlen|feel ~ ich|P|N|S|ich|I ~ mich|P.refl|A|AO|ich|myself|Reflexive verb "sich fühlen": ich fühle mich. ~ wegen|PR||AB||because of|"wegen" takes the genitive. ~ einer|A|Gf|AB|ein|a|Genitive feminine: eine → einer. ~ starken|J|Gf|AB|stark|heavy|Adjective after "einer" in the genitive: ending -en. ~ Erkältung|N|Gf|AB||cold ~ ziemlich|ADV||AB||rather|Adverb of degree: how weak? ~ schwach|J||PN||weak|Predicative after "sich fühlen": no ending. ~ .`,
 "For three days I have been feeling rather weak because of a heavy cold."],
[`Weil|K||K||because|Subordinating conjunction: the verb goes to the end. ~ mein|A|Nm|S|mein|my ~ Hausarzt|N|Nm|S||family doctor ~ im|PA|Dm|AB|in + dem|on|Wo? → dative: im Urlaub. ~ Urlaub|N|Dm|AB||holiday ~ ist|V||P|sein|is|In the subordinate clause the verb comes last. ~ , ~ habe|V.hilf||P|haben|have|The "weil" clause is position 1, so the verb comes next, then the subject. ~ ich|P|N|S|ich|I ~ einen|A|Am|AO|ein|an ~ Termin|N|Am|AO||appointment|Was habe ich vereinbart? → accusative object. ~ in|PR||AB||at|Wo? → dative. ~ einer|A|Df|AB|ein|a|Dative feminine: eine → einer. ~ anderen|J|Df|AB|ander|different|Adjective after "einer" (dative feminine): ending -en. ~ Praxis|N|Df|AB||surgery ~ vereinbart|VT||P|vereinbaren|arranged|Past participle at the end; no ge- with the prefix ver-. ~ .`,
 "Because my family doctor is on holiday, I made an appointment at a different surgery."],
[`Die|A|Nf|S|der|the ~ Ärztin|N|Nf|S||doctor ~ , ~ die|P.rel|Nf|S|der|who|Relative pronoun: feminine (die Ärztin), nominative because it is the subject of its clause. ~ mich|P|A|AO|ich|me ~ gründlich|J||AB||thoroughly|Adjective used as an adverb (how?): no ending. ~ untersucht|VT||P|untersuchen|examined|Participle; no ge- with the prefix unter-. ~ hat|V.hilf||P|haben|has|In the relative clause the auxiliary goes last. ~ , ~ hat|V.hilf||P|haben|has ~ mir|P|D|DO|ich|me|Wem hat sie es verschrieben? → dative object. ~ ein|A|An|AO||an ~ Antibiotikum|N|An|AO||antibiotic|Was hat sie verschrieben? → accusative object. ~ verschrieben|VT||P|verschreiben|prescribed|Participle of "verschreiben": no ge-. ~ .`,
 "The doctor, who examined me thoroughly, prescribed me an antibiotic."],
[`Ich|P|N|S|ich|I ~ muss|V||P|müssen|have to ~ die|A|Ap|AO|der|the ~ Tabletten|N|Ap|AO|Tablette|tablets|Was muss ich nehmen? → accusative object. ~ zweimal|ADV||AB||twice|Adverb of frequency: Wie oft? ~ am|PA|Dm|AB|an + dem|a|"am Tag" = per day. ~ Tag|N|Dm|AB||day ~ nach|PR||AB||after|"nach" + dative; with a meal it tells the time. ~ dem|A|Dn|AB|der|the ~ Essen|N|Dn|AB||meal ~ nehmen|VT||P||take|Infinitive at the end after the modal verb. ~ .`,
 "I have to take the tablets twice a day after meals."],
[`Außerdem|ADV||AB||besides|Linking adverb in position 1: the verb follows. ~ soll|V||P|sollen|am supposed to|"sollen": what somebody else (the doctor) wants. ~ ich|P|N|S|ich|I ~ viel|ADV||AB||a lot ~ trinken|VT||P||drink|Infinitive at the end. ~ und|K||K||and ~ mich|P.refl|A|AO|ich|myself|"sich ausruhen" is reflexive: ich ruhe mich aus. ~ ausruhen|VT||P||rest|Second infinitive after "soll". ~ , ~ damit|K||K||so that|Subordinating conjunction (purpose): the verb goes to the end. ~ das|A|Nn|S|der|the ~ Fieber|N|Nn|S||fever ~ schnell|J||AB||quickly|Adjective used as an adverb: no ending. ~ sinkt|V||P|sinken|goes down|Verb at the end of the "damit" clause. ~ .`,
 "Besides, I am supposed to drink a lot and rest so that the fever goes down quickly."],
[`Falls|K||K||if|Subordinating conjunction (in case): the verb goes to the end. ~ es|P|N|S|es|it|"es geht mir gut": "es" is only a formal subject. ~ mir|P|D|DO|ich|me|"Wie geht es dir?" – the person is in the dative. ~ am|PA|Dn|AB|an + dem|at the ~ Wochenende|N|Dn|AB||weekend ~ nicht|T||AB||not ~ besser|J||AB|gut|better|Comparative of "gut", used as an adverb: no ending. ~ geht|V||P|gehen|goes|"gehen" at the end of the subordinate clause. ~ , ~ muss|V||P|müssen|must|The "falls" clause is position 1, so the verb comes next. ~ ich|P|N|S|ich|I ~ noch|T||AB||once|"noch einmal" = once more. ~ einmal|ADV||AB||more ~ zur|PA|Df|AB|zu + der|to the|zur = zu + der; "zu" always takes the dative. ~ Ärztin|N|Df|AB||doctor ~ gehen|VT||P||go|Infinitive at the end after "muss". ~ .`,
 "If I don't feel better by the weekend, I have to go to the doctor once more."]
]}
]},

{de:"Kinder und Schule", en:"Children and school", p:[
{lvl:"A1", s:[
[`Mein|A|Nm|S|mein|my ~ Sohn|N|Nm|S||son ~ Tom|N|Nm|S||Tom (name)|A name next to a noun has the same case: nominative. ~ ist|V||P|sein|is ~ sieben|Z||PN||seven ~ Jahre|N|Ap|PN|Jahr|years|Age: "… Jahre alt" – the measure is in the accusative. ~ alt|J||PN||old|Predicative adjective after "sein": no ending. ~ .`,
 "My son Tom is seven years old."],
[`Er|P|N|S|er|he ~ geht|V||P|gehen|goes ~ in|PR||AB||into|Two-way preposition: Wohin? (where to) → accusative. ~ die|A|Af|AB|der|the ~ zweite|J|Af|AB|zweit|second|Ordinal number used as an adjective; after "die": ending -e. ~ Klasse|N|Af|AB||class ~ der|A|Gf|GA|der|of the|Wessen Klasse? → genitive feminine: die → der. ~ Grundschule|N|Gf|GA||primary school ~ in|PR||AT||in|Wo? → dative. ~ Frankfurt|N|Dn|AT||Frankfurt ~ .`,
 "He is in the second class of the primary school in Frankfurt."],
[`Jeden|A|Am|AB|jeder|every|"jeder" in the accusative masculine: jeden. A time phrase without a preposition is accusative. ~ Morgen|N|Am|AB||morning ~ bringe|V||P|bringen|take ~ ich|P|N|S|ich|I ~ ihn|P|A|AO|er|him|Wen bringe ich? → accusative (er → ihn). ~ um|PR||AB||at ~ acht|Z||AB||eight ~ Uhr|N|Af|AB||o'clock ~ zur|PA|Df|AB|zu + der|to (the)|zur = zu + der. ~ Schule|N|Df|AB||school ~ .`,
 "Every morning I take him to school at eight o'clock."],
[`Tom|N|Nm|S||Tom ~ lernt|V||P|lernen|learns ~ gern|ADV||AB||gladly|verb + "gern" = to like doing something. ~ Mathe|N|Af|AO||maths|Was lernt er? → accusative object; school subjects take no article. ~ , ~ aber|K||K||but ~ Deutsch|N|An|AO||German|The object can take position 1 for emphasis; the verb stays second. ~ findet|V||P|finden|finds ~ er|P|N|S|er|he ~ nicht|T||AB||not ~ leicht|J||PN||easy|"finden" + adjective: no ending. ~ .`,
 "Tom likes learning maths, but he doesn't find German easy."],
[`Nach|PR||AB||after|"nach" + dative; with an event it tells the time. ~ der|A|Df|AB|der|the ~ Schule|N|Df|AB||school ~ isst|V||P|essen|eats ~ er|P|N|S|er|he ~ mit|PR||AB||with|"mit" always takes the dative. ~ seinen|A|Dp|AB|sein|his|Dative plural: seine → seinen. ~ Freunden|N|Dp|AB|Freund|friends|Dative plural: the noun adds -n. ~ im|PA|Dm|AB|in + dem|at the|Wo? → dative. ~ Hort|N|Dm|AB||after-school club ~ .`,
 "After school he eats with his friends at the after-school club."],
[`Um|PR||AB||at ~ vier|Z||AB||four ~ Uhr|N|Af|AB||o'clock ~ hole|V||P|abholen|pick up|Separable verb "abholen": hole … ab. ~ ich|P|N|S|ich|I ~ ihn|P|A|AO|er|him ~ ab|VT||P|abholen|(prefix)|The prefix goes to the end of the main clause. ~ und|K||K||and ~ wir|P|N|S|wir|we ~ machen|V||P||do ~ zusammen|ADV||AB||together ~ die|A|Ap|AO|der|the ~ Hausaufgaben|N|Ap|AO|Hausaufgabe|homework|Was machen wir? → accusative object (plural). ~ .`,
 "At four o'clock I pick him up and we do the homework together."],
[`Die|A|Nf|S|der|the ~ Lehrerin|N|Nf|S||teacher (woman) ~ ist|V||P|sein|is ~ sehr|ADV||AB||very ~ nett|J||PN||nice ~ und|K||K||and ~ hilft|V||P|helfen|helps ~ den|A|Dp|DO|der|the|"helfen" always takes the dative: Wem hilft sie? ~ Kindern|N|Dp|DO|Kind|children|Dative plural: die Kinder → den Kindern. ~ .`,
 "The teacher is very nice and helps the children."]
]},
{lvl:"B1", s:[
[`Am|PA|Dn|AB|an + dem|at the ~ Ende|N|Dn|AB||end ~ des|A|Gn|GA|der|of the|Wessen Ende? → genitive neuter: das → des. ~ Schuljahres|N|Gn|GA|Schuljahr|school year|Neuter nouns add -es/-s in the genitive. ~ hat|V.hilf||P|haben|has ~ unsere|A|Nf|S|unser|our ~ Tochter|N|Nf|S||daughter|The subject comes after the verb because the time phrase is in position 1. ~ ein|A|An|AO||a ~ Zeugnis|N|An|AO||school report|Was hat sie bekommen? → accusative object. ~ mit|PR||AT||with ~ sehr|ADV||AT||very ~ guten|J|Dp|AT|gut|good|Adjective without an article, dative plural: ending -en. ~ Noten|N|Dp|AT|Note|marks ~ bekommen|VT.part||P|bekommen|got|Participle of "bekommen": no ge-, the same as the infinitive. ~ .`,
 "At the end of the school year our daughter got a report with very good marks."],
[`Da|K||K||since|Subordinating conjunction (because): the verb goes to the end. ~ sie|P|N|S|sie|she ~ nach|PR||AB||after ~ den|A|Dp|AB|der|the ~ Sommerferien|N|Dp|AB||summer holidays|Dative plural after "nach"; "Ferien" only exists in the plural. ~ aufs|PA|An|AB|auf + das|to the|aufs = auf + das. Wohin? → accusative. ~ Gymnasium|N|An|AB||grammar school ~ wechselt|V||P|wechseln|moves|Verb at the end of the "da" clause. ~ , ~ müssen|V||P||have to ~ wir|P|N|S|wir|we ~ noch|T||AB||still ~ viele|A|Ap|AO|viel|many ~ Sachen|N|Ap|AO|Sache|things|Was müssen wir kaufen? → accusative object. ~ kaufen|VT||P||buy|Infinitive at the end after the modal verb. ~ .`,
 "Since she is moving to grammar school after the summer holidays, we still have to buy lots of things."],
[`Die|A|Nf|S|der|the ~ Lehrerin|N|Nf|S||teacher ~ empfiehlt|V||P|empfehlen|recommends|e → ie: ich empfehle, sie empfiehlt. ~ uns|P|D|DO|wir|us|"empfehlen" + dative for the person: Wem? → uns. ~ , ~ jeden|A|Am|AB|jeder|every|Time phrase in the accusative. ~ Tag|N|Am|AB||day ~ eine|A|Af|AB|ein|a ~ halbe|J|Af|AB|halb|half|Adjective after "eine": ending -e. ~ Stunde|N|Af|AB||hour|Wie lange? Duration in the accusative. ~ zu|T||P||to|"zu" + infinitive (infinitive clause). ~ lesen|VT||P||read|Infinitive at the end of the infinitive clause. ~ .`,
 "The teacher recommends that we read for half an hour every day."],
[`Beim|PA|Dm|AB|bei + dem|at the|beim = bei + dem. ~ Elternabend|N|Dm|AB||parents' evening ~ haben|V.hilf||P||have ~ wir|P|N|S|wir|we ~ erfahren|VT.part||P|erfahren|found out|Participle of "erfahren": no ge-, the same as the infinitive. ~ , ~ dass|K||K||that|Subordinating conjunction: the verb goes to the end. ~ die|A|Nf|S|der|the ~ Klasse|N|Nf|S||class ~ im|PA|Dm|AB|in + dem|in|Months take "im" → dative. ~ Mai|N|Dm|AB||May ~ fünf|Z||AB||five ~ Tage|N|Ap|AB|Tag|days|Wie lange? Duration in the accusative. ~ an|PR||AB||to|Two-way preposition: Wohin? → accusative. ~ die|A|Af|AB|der|the ~ Nordsee|N|Af|AB||North Sea ~ fährt|V||P|fahren|goes|The verb goes to the very end of the "dass" clause. ~ .`,
 "At the parents' evening we found out that the class is going to the North Sea for five days in May."],
[`Unser|A|Nm|S|unser|our ~ Sohn|N|Nm|S||son ~ , ~ dem|P.rel|Dm|DO|der|for whom|Relative pronoun: masculine (der Sohn), dative because "schwerfallen" needs a dative: Wem fällt es schwer? ~ das|A|Nn|S|der|the ~ Lernen|N|Nn|S||learning|A verb used as a noun: das Lernen. ~ manchmal|ADV||AB||sometimes ~ schwerfällt|V||P|schwerfallen|is hard|In the relative clause the separable verb stays together at the end. ~ , ~ bekommt|V||P|bekommen|gets ~ zweimal|ADV||AB||twice ~ pro|PR||AB||a|"pro" + accusative, usually without an article: pro Woche = per week. ~ Woche|N|Af|AB||week ~ Nachhilfe|N|Af|AO||tutoring|Was bekommt er? → accusative object. ~ .`,
 "Our son, who sometimes finds learning hard, gets tutoring twice a week."],
[`Trotzdem|ADV||AB||nevertheless|Linking adverb in position 1: the verb follows. ~ ist|V||P|sein|is ~ er|P|N|S|er|he ~ motiviert|J||PN||motivated|Predicative after "sein": no ending. ~ , ~ weil|K||K||because ~ er|P|N|S|er|he ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the ~ vierten|J|Df|AB|viert|fourth|Ordinal after "der" (dative feminine): ending -en. ~ Klasse|N|Df|AB||year ~ bessere|J|Ap|AO|gut|better|Comparative with an ending: no article, accusative plural → -e. ~ Noten|N|Ap|AO|Note|marks ~ haben|VT||P||have ~ möchte|V||P|möchten|would like|In the "weil" clause the modal verb goes to the very end. ~ .`,
 "He is still motivated, because he would like to have better marks in year four."]
]}
]},

{de:"Ämter und Behörden", en:"Offices and authorities", p:[
{lvl:"A1", s:[
[`Ich|P|N|S|ich|I ~ bin|V||P|sein|am ~ neu|J||PN||new|Predicative adjective after "sein": no ending. ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the ~ Stadt|N|Df|AB||town ~ und|K||K||and ~ muss|V||P|müssen|must ~ mich|P.refl|A|AO|ich|myself|"sich anmelden" is reflexive: ich melde mich an. ~ anmelden|VT||P||register|Infinitive at the end after "muss". ~ .`,
 "I am new in town and have to register."],
[`Das|A|Nn|S|der|the ~ Bürgeramt|N|Nn|S||citizens' office ~ ist|V||P|sein|is ~ in|PR||AB||in|Wo? → dative. ~ der|A|Df|AB|der|the ~ Nähe|N|Df|AB||vicinity ~ des|A|Gn|GA|der|of the|Wessen Nähe? → genitive neuter: das → des. ~ Rathauses|N|Gn|GA|Rathaus|town hall|Neuter nouns add -es in the genitive. ~ .`,
 "The citizens' office is near the town hall."],
[`Am|PA|Dm|AB|an + dem|on|Days of the week take "am" → dative. ~ Montag|N|Dm|AB||Monday ~ habe|V||P|haben|have ~ ich|P|N|S|ich|I ~ um|PR||AB||at ~ neun|Z||AB||nine ~ Uhr|N|Af|AB||o'clock ~ einen|A|Am|AO|ein|an|Indefinite article, accusative masculine: ein → einen. ~ Termin|N|Am|AO||appointment|Was habe ich? → accusative object. ~ .`,
 "On Monday I have an appointment at nine o'clock."],
[`Ich|P|N|S|ich|I ~ nehme|V||P|mitnehmen|take|Separable verb "mitnehmen": nehme … mit. ~ meinen|A|Am|AO|mein|my|Accusative masculine: mein → meinen. ~ Pass|N|Am|AO||passport ~ und|K||K||and ~ den|A|Am|AO|der|the ~ Mietvertrag|N|Am|AO||rental contract ~ mit|VT||P|mitnehmen|(prefix)|The prefix "mit" goes to the end. ~ .`,
 "I take my passport and the rental contract with me."],
[`Die|A|Nf|S|der|the ~ Frau|N|Nf|S||woman ~ am|PA|Dm|AT|an + dem|at the|Which woman? → attribute; Wo? → dative. ~ Schalter|N|Dm|AT||counter ~ gibt|V||P|geben|gives ~ mir|P|D|DO|ich|me|Wem gibt sie das Formular? → dative object. ~ ein|A|An|AO||a ~ Formular|N|An|AO||form|Was gibt sie mir? → accusative object. ~ .`,
 "The woman at the counter gives me a form."],
[`Ich|P|N|S|ich|I ~ fülle|V||P|ausfüllen|fill|Separable verb "ausfüllen": fülle … aus. ~ es|P|A|AO|es|it|Was fülle ich aus? → accusative (das Formular → es). ~ aus|VT||P|ausfüllen|(prefix) ~ , ~ aber|K||K||but ~ ein|A|An|AO||one ~ Wort|N|An|AO||word|The object is in position 1, so the subject follows the verb. ~ verstehe|V||P|verstehen|understand ~ ich|P|N|S|ich|I ~ nicht|T||AB||not|"nicht" at the end negates the whole sentence. ~ .`,
 "I fill it in, but there is one word I don't understand."],
[`Dann|ADV||AB||then ~ bekomme|V||P|bekommen|get ~ ich|P|N|S|ich|I ~ schnell|J||AB||quickly|Adjective used as an adverb: no ending. ~ meine|A|Af|AO|mein|my ~ Meldebescheinigung|N|Af|AO||registration certificate|Was bekomme ich? → accusative object. ~ .`,
 "Then I quickly get my registration certificate."]
]},
{lvl:"B1", s:[
[`Vor|PR||AB||ago|"vor" + a time (Wann?) → dative. ~ zwei|Z||AB||two ~ Wochen|N|Dp|AB|Woche|weeks|Dative plural. ~ habe|V.hilf||P|haben|have ~ ich|P|N|S|ich|I ~ bei|PR||AB||at|"bei" always takes the dative. ~ der|A|Df|AB|der|the ~ Ausländerbehörde|N|Df|AB||immigration office ~ die|A|Af|AO|der|the ~ Verlängerung|N|Af|AO||extension|Was habe ich beantragt? → accusative object. ~ meines|A|Gm|GA|mein|of my|Wessen Verlängerung? → genitive masculine: mein → meines. ~ Aufenthaltstitels|N|Gm|GA|Aufenthaltstitel|residence permit|Masculine genitive: the noun adds -s. ~ beantragt|VT||P|beantragen|applied for|Participle at the end; no ge- with the prefix be-. ~ .`,
 "Two weeks ago I applied to the immigration office for the extension of my residence permit."],
[`Die|A|Nf|S|der|the ~ Sachbearbeiterin|N|Nf|S||caseworker ~ , ~ mit|PR||PO||with|"telefonieren mit" + dative. ~ der|P.rel|Df|PO|der|whom|Relative pronoun after "mit": feminine (die Sachbearbeiterin), dative because of "mit". ~ ich|P|N|S|ich|I ~ telefoniert|VT||P|telefonieren|phoned|-ieren verbs have no ge- in the participle. ~ habe|V.hilf||P|haben|have|The auxiliary goes to the end of the relative clause. ~ , ~ war|V||P|sein|was|Simple past of "sein". ~ sehr|ADV||AB||very ~ freundlich|J||PN||friendly|Predicative after "sein": no ending. ~ .`,
 "The caseworker I spoke to on the phone was very friendly."],
[`Sie|P|N|S|sie|she ~ hat|V.hilf||P|haben|has ~ mir|P|D|DO|ich|me|"erklären" + dative for the person: Wem? ~ erklärt|VT||P|erklären|explained ~ , ~ dass|K||K||that ~ ich|P|N|S|ich|I ~ einen|A|Am|AO|ein|a ~ gültigen|J|Am|AO|gültig|valid|Adjective after "einen": ending -en. ~ Pass|N|Am|AO||passport ~ , ~ ein|A|An|AO||a ~ aktuelles|J|An|AO|aktuell|recent|Adjective after "ein" (neuter accusative): ending -es. ~ Foto|N|An|AO||photo ~ und|K||K||and ~ meinen|A|Am|AO|mein|my ~ Arbeitsvertrag|N|Am|AO||employment contract ~ mitbringen|VT||P||bring along|Infinitive before the modal verb at the end. ~ muss|V||P|müssen|must|In the "dass" clause the modal verb comes last. ~ .`,
 "She explained to me that I must bring a valid passport, a recent photo and my employment contract."],
[`Ohne|PR||AB||without|"ohne" always takes the accusative. ~ einen|A|Am|AB|ein|an ~ Termin|N|Am|AB||appointment ~ wird|V.hilf||P|werden|is|"werden" + participle = passive. ~ man|P|N|S|man|one|"man" = people in general; always nominative here. ~ dort|ADV||AB||there ~ leider|ADV||AB||unfortunately ~ nicht|T||AB||not ~ bedient|VT||P|bedienen|served|Participle at the end (passive). ~ .`,
 "Unfortunately you are not served there without an appointment."],
[`Deshalb|ADV||AB||that's why|Linking adverb in position 1: the verb comes next. ~ bin|V.hilf||P|sein|have|Perfect with "sein" for movement: fahren. ~ ich|P|N|S|ich|I ~ gestern|ADV||AB||yesterday ~ zum|PA|Dn|AB|zu + dem|to the|zum = zu + dem; "zu" always takes the dative. ~ Amt|N|Dn|AB||office ~ gefahren|VT||P|fahren|gone ~ , ~ um|K||K||in order|"um … zu" + infinitive = in order to. ~ meine|A|Ap|AO|mein|my ~ Unterlagen|N|Ap|AO|Unterlage|documents ~ persönlich|J||AB||in person|Adjective used as an adverb: no ending. ~ zu|T||P||to ~ übergeben|VT||P||hand over|Infinitive at the end of the "um … zu" clause. ~ .`,
 "That's why I went to the office yesterday to hand over my documents in person."],
[`In|PR||AB||in|"in" + a time (Wann?) → dative. ~ sechs|Z||AB||six ~ Wochen|N|Dp|AB|Woche|weeks|Dative plural. ~ bekomme|V||P|bekommen|get ~ ich|P|N|S|ich|I ~ den|A|Am|AO|der|the ~ neuen|J|Am|AO|neu|new|Adjective after "den": ending -en. ~ Aufenthaltstitel|N|Am|AO||residence permit ~ per|PR||AB||by|"per" + accusative, usually without an article. ~ Post|N|Af|AB||post ~ .`,
 "In six weeks I will get the new residence permit by post."]
]}
]},

{de:"Verkehr und Unterwegs", en:"Transport and getting around", p:[
{lvl:"A1", s:[
[`Ich|P|N|S|ich|I ~ fahre|V||P|fahren|go ~ jeden|A|Am|AB|jeder|every|Time phrase in the accusative: jeden Tag. ~ Tag|N|Am|AB||day ~ mit|PR||AB||by|"mit" + dative: the means of transport. ~ der|A|Df|AB|der|the ~ U-Bahn|N|Df|AB||underground ~ zur|PA|Df|AB|zu + der|to (the)|zur = zu + der. ~ Arbeit|N|Df|AB||work ~ .`,
 "Every day I go to work by underground."],
[`Die|A|Nf|S|der|the ~ Fahrt|N|Nf|S||journey ~ dauert|V||P|dauern|takes ~ zwanzig|Z||AB||twenty ~ Minuten|N|Ap|AB|Minute|minutes|Wie lange? Duration in the accusative. ~ .`,
 "The journey takes twenty minutes."],
[`Heute|ADV||AB||today ~ kommt|V||P|kommen|comes ~ die|A|Nf|S|der|the ~ Bahn|N|Nf|S||train|Wer kommt? → subject, after the verb because "Heute" is in position 1. ~ leider|ADV||AB||unfortunately ~ nicht|T||AB||not ~ pünktlich|J||AB||on time|Adjective used as an adverb: no ending. ~ .`,
 "Today the train unfortunately isn't on time."],
[`Deshalb|ADV||AB||so|Linking adverb in position 1: the verb follows. ~ nehme|V||P|nehmen|take ~ ich|P|N|S|ich|I ~ den|A|Am|AO|der|the ~ Bus|N|Am|AO||bus|Was nehme ich? → accusative object. ~ der|A|Gf|GA|der|of the|Wessen Bus? → genitive feminine: die Linie → der Linie. ~ Linie|N|Gf|GA||line ~ 30|Z||AT||30 ~ .`,
 "So I take the number 30 bus."],
[`An|PR||AB||at|Two-way preposition: Wo? → dative. ~ der|A|Df|AB|der|the ~ Haltestelle|N|Df|AB||stop ~ frage|V||P|fragen|ask ~ ich|P|N|S|ich|I ~ einen|A|Am|AO|ein|a ~ Mann|N|Am|AO||man|Wen frage ich? → accusative object. ~ nach|PR||PO||for|"fragen nach" + dative. ~ dem|A|Dm|PO|der|the ~ Weg|N|Dm|PO||way ~ .`,
 "At the stop I ask a man the way."],
[`Er|P|N|S|er|he ~ ist|V||P|sein|is ~ sehr|ADV||AB||very ~ nett|J||PN||kind ~ und|K||K||and ~ zeigt|V||P|zeigen|shows ~ mir|P|D|DO|ich|me|Wem zeigt er die Straße? → dative object. ~ die|A|Af|AO|der|the ~ richtige|J|Af|AO|richtig|right|Adjective after "die": ending -e. ~ Straße|N|Af|AO||street ~ .`,
 "He is very kind and shows me the right street."]
]},
{lvl:"B1", s:[
[`Letzte|J|Af|AB|letzt|last|Time phrase in the accusative (adjective without an article, feminine -e). ~ Woche|N|Af|AB||week ~ wollte|V||P|wollen|wanted|Simple past of the modal verb "wollen". ~ ich|P|N|S|ich|I ~ mit|PR||AB||by ~ dem|A|Dm|AB|der|the ~ Zug|N|Dm|AB||train ~ zu|PR||AB||to|"zu" + dative: to a person or an event. ~ einem|A|Dn|AB|ein|a|Dative neuter: ein → einem. ~ Vorstellungsgespräch|N|Dn|AB||job interview ~ nach|PR||AB||to|"nach" + names of cities without an article. ~ München|N|Dn|AB||Munich ~ fahren|VT||P||travel|Infinitive at the end after the modal verb. ~ .`,
 "Last week I wanted to travel by train to a job interview in Munich."],
[`Wegen|PR||AB||because of|"wegen" + genitive. ~ einer|A|Gf|AB|ein|a|Genitive feminine: eine → einer. ~ Signalstörung|N|Gf|AB||signal failure ~ hatte|V||P|haben|had ~ der|A|Nm|S|der|the ~ ICE|N|Nm|S||ICE (high-speed train) ~ schon|ADV||AB||already ~ in|PR||AB||in ~ Frankfurt|N|Dn|AB||Frankfurt ~ fast|ADV||AB||almost ~ 50|Z||AO||50 ~ Minuten|N|Ap|AO|Minute|minutes ~ Verspätung|N|Af|AO||delay|Was hatte der Zug? → accusative object: 50 minutes' delay. ~ .`,
 "Because of a signal failure the ICE was already almost 50 minutes late in Frankfurt."],
[`Weil|K||K||because|Subordinating conjunction: the verb goes to the end. ~ ich|P|N|S|ich|I ~ den|A|Am|AO|der|the ~ Anschlusszug|N|Am|AO||connecting train ~ nicht|T||AB||not ~ erreichen|VT||P||catch|Infinitive before the modal verb at the end. ~ konnte|V||P|können|could|Simple past of "können", at the end of the "weil" clause. ~ , ~ habe|V.hilf||P|haben|have ~ ich|P|N|S|ich|I ~ sofort|ADV||AB||immediately ~ den|A|Am|AO|der|the ~ Personalchef|N|Am|AO||HR manager|Wen habe ich angerufen? → accusative object. ~ der|A|Gf|GA|der|of the|Wessen Personalchef? → genitive feminine. ~ Firma|N|Gf|GA||company ~ angerufen|VT||P|anrufen|phoned|Participle of "anrufen": ge- goes after the prefix (an-ge-rufen). ~ .`,
 "Because I couldn't catch the connecting train, I immediately phoned the company's HR manager."],
[`Zum|PA|Dn|AB|zu + dem|luckily|"zum Glück" = luckily, a fixed phrase. ~ Glück|N|Dn|AB||luck ~ hat|V.hilf||P|haben|has ~ er|P|N|S|er|he ~ mir|P|D|DO|ich|me|"anbieten" + dative for the person: Wem? ~ einen|A|Am|AO|ein|a ~ neuen|J|Am|AO|neu|new|Adjective after "einen": ending -en. ~ Termin|N|Am|AO||appointment ~ angeboten|VT||P|anbieten|offered|Participle of "anbieten": ge- after the prefix. ~ .`,
 "Luckily he offered me a new appointment."],
[`Für|PR||AB||for|"für" + accusative. ~ die|A|Af|AB|der|the ~ Rückfahrt|N|Af|AB||return journey ~ habe|V.hilf||P|haben|have ~ ich|P|N|S|ich|I ~ einen|A|Am|AO|ein|a ~ Fernbus|N|Am|AO||long-distance coach ~ genommen|VT||P|nehmen|taken ~ , ~ weil|K||K||because ~ er|P|N|S|er|it|"er" = der Fernbus (masculine). ~ viel|ADV||AB||much|"viel" + comparative = much cheaper. ~ billiger|J||PN|billig|cheaper|Comparative after "sein": no ending. ~ als|K||K||than|"als" after a comparative. ~ die|A|Nf|PN|der|the|After "als" the same case as the thing compared: nominative. ~ Bahn|N|Nf|PN||train ~ war|V||P|sein|was ~ .`,
 "For the return journey I took a long-distance coach because it was much cheaper than the train."],
[`Am|PA|Dm|AB|an + dem|on the ~ nächsten|J|Dm|AB|nächst|next|Adjective after "am" (= an dem): ending -en. ~ Morgen|N|Dm|AB||morning ~ bin|V.hilf||P|sein|have|Perfect with "sein" for movement: kommen. ~ ich|P|N|S|ich|I ~ pünktlich|J||AB||on time|Adjective used as an adverb: no ending. ~ zum|PA|Dn|AB|zu + dem|to the ~ Gespräch|N|Dn|AB||interview ~ gekommen|VT||P|kommen|come ~ und|K||K||and ~ habe|V.hilf||P|haben|have ~ die|A|Af|AO|der|the ~ Stelle|N|Af|AO||job|Was habe ich bekommen? → accusative object. ~ bekommen|VT.part||P|bekommen|got|Participle of "bekommen": no ge-, the same as the infinitive. ~ !`,
 "The next morning I arrived on time for the interview and got the job!"]
]}
]},

{de:"Wetter und Jahreszeiten", en:"Weather and seasons", p:[
{lvl:"A1", s:[
[`Im|PA|Dm|AB|in + dem|in (the)|Seasons take "im" → dative. ~ Herbst|N|Dm|AB||autumn ~ ist|V||P|sein|is ~ das|A|Nn|S|der|the ~ Wetter|N|Nn|S||weather ~ in|PR||AB||in ~ Deutschland|N|Dn|AB||Germany ~ oft|ADV||AB||often ~ kühl|J||PN||cool|Predicative adjective after "sein": no ending. ~ und|K||K||and ~ nass|J||PN||wet ~ .`,
 "In autumn the weather in Germany is often cool and wet."],
[`Es|P|N|S|es|it|"es regnet": "es" is only a formal subject. ~ regnet|V||P|regnen|rains ~ viel|ADV||AB||a lot ~ und|K||K||and ~ die|A|Np|S|der|the ~ Tage|N|Np|S|Tag|days ~ sind|V||P|sein|are ~ kurz|J||PN||short ~ .`,
 "It rains a lot and the days are short."],
[`Ich|P|N|S|ich|I ~ trage|V||P|tragen|wear ~ dann|ADV||AB||then ~ einen|A|Am|AO|ein|a ~ warmen|J|Am|AO|warm|warm|Adjective after "einen": ending -en. ~ Mantel|N|Am|AO||coat|Was trage ich? → accusative object. ~ und|K||K||and ~ eine|A|Af|AO|ein|a ~ Mütze|N|Af|AO||woolly hat ~ .`,
 "Then I wear a warm coat and a woolly hat."],
[`Meine|A|Nf|S|mein|my ~ Lieblingsjahreszeit|N|Nf|S||favourite season ~ ist|V||P|sein|is ~ der|A|Nm|PN|der|the|After "sein" the noun stays in the nominative. ~ Sommer|N|Nm|PN||summer ~ .`,
 "My favourite season is summer."],
[`Im|PA|Dm|AB|in + dem|in|Months take "im" → dative. ~ Juli|N|Dm|AB||July ~ ist|V||P|sein|is ~ es|P|N|S|es|it ~ manchmal|ADV||AB||sometimes ~ dreißig|Z||PN||thirty ~ Grad|N|Ap|PN||degrees|A measure: "dreißig Grad" – no plural ending. ~ warm|J||PN||warm ~ .`,
 "In July it is sometimes thirty degrees."],
[`Am|PA|Dn|AB|an + dem|at the ~ Wochenende|N|Dn|AB||weekend ~ gehen|V||P||go ~ wir|P|N|S|wir|we ~ mit|PR||AB||with ~ den|A|Dp|AB|der|the ~ Kindern|N|Dp|AB|Kind|children|Dative plural: the noun adds -n. ~ an|PR||AB||to|Two-way preposition: Wohin? → accusative. ~ den|A|Am|AB|der|the ~ See|N|Am|AB||lake ~ .`,
 "At the weekend we go to the lake with the children."],
[`Das|A|Nn|S|der|the ~ Wasser|N|Nn|S||water ~ des|A|Gm|GA|der|of the|Wessen Wasser? → genitive masculine: der See → des Sees. ~ Sees|N|Gm|GA|See|lake's ~ ist|V||P|sein|is ~ nicht|T||AB||not ~ kalt|J||PN||cold ~ .`,
 "The water of the lake is not cold."]
]},
{lvl:"B1", s:[
[`Im|PA|Dm|AB|in + dem|in (the) ~ letzten|J|Dm|AB|letzt|last|Adjective after "im" (= in dem): ending -en. ~ Sommer|N|Dm|AB||summer ~ lagen|V||P|liegen|were|Simple past of "liegen": lag, lagen. ~ die|A|Np|S|der|the ~ Temperaturen|N|Np|S|Temperatur|temperatures ~ zwei|Z||AB||two ~ Wochen|N|Ap|AB|Woche|weeks|Wie lange? Duration in the accusative: zwei Wochen lang. ~ lang|ADV||AB||long ~ bei|PR||AB||at|"bei" always takes the dative. ~ 35|Z||AB||35 ~ Grad|N|Dp|AB||degrees|Dative plural after "bei"; "Grad" has no plural ending. ~ .`,
 "Last summer the temperatures stayed at 35 degrees for two weeks."],
[`Im|PA|Dm|AB|in + dem|in ~ Winter|N|Dm|AB||winter ~ , ~ wenn|K||K||when|"wenn" for repeated events: the verb goes to the end. ~ es|P|N|S|es|it ~ schneit|V||P|schneien|snows ~ , ~ fahren|V||P||go|"Im Winter, wenn es schneit" counts as position 1, so the verb comes next. ~ viele|A|Np|S|viel|many ~ Menschen|N|Np|S|Mensch|people ~ in|PR||AB||into|Wohin? → accusative. ~ die|A|Ap|AB|der|the ~ Berge|N|Ap|AB|Berg|mountains ~ , ~ um|K||K||in order|"um … zu" + infinitive = in order to. ~ Ski|N|An|AO||ski|"Ski fahren": the noun is used without an article. ~ zu|T||P||to ~ fahren|VT||P||go (skiing) ~ .`,
 "In winter, when it snows, lots of people go to the mountains to ski."],
[`Obwohl|K||K||although|Subordinating conjunction: the verb goes to the end. ~ ich|P|N|S|ich|I ~ den|A|Am|AO|der|the ~ Regen|N|Am|AO||rain|Was mag ich? → accusative object. ~ eigentlich|ADV||AB||actually|Comment adverb: the speaker's view. ~ mag|V||P|mögen|like|"mögen" at the end of the "obwohl" clause. ~ , ~ finde|V||P|finden|find ~ ich|P|N|S|ich|I ~ graue|J|Ap|AO|grau|grey|Adjective without an article, accusative plural: ending -e. ~ Tage|N|Ap|AO|Tag|days ~ im|PA|Dm|AT|in + dem|in ~ November|N|Dm|AT||November ~ ziemlich|ADV||AB||rather|Adverb of degree. ~ anstrengend|J||PN||tiring|"finden" + adjective: no ending. ~ .`,
 "Although I actually like the rain, I find grey days in November rather tiring."],
[`Laut|PR||AB||according to|"laut" + dative, often without an article. ~ Wettervorhersage|N|Df|AB||weather forecast ~ soll|V||P|sollen|is supposed to|"sollen" here reports what others say. ~ es|P|N|S|es|it|"es regnet": formal subject. ~ morgen|ADV||AB||tomorrow ~ im|PA|Dm|AB|in + dem|in the ~ ganzen|J|Dm|AB|ganz|whole|Adjective after "im" (= in dem): ending -en. ~ Süden|N|Dm|AB||south ~ stark|J||AB||heavily|Adjective used as an adverb: no ending. ~ regnen|VT||P||rain|Infinitive at the end after "soll". ~ .`,
 "According to the weather forecast it is supposed to rain heavily in the whole south tomorrow."],
[`Wegen|PR||AB||because of ~ der|A|Gf|AB|der|the|"wegen" + genitive feminine: die → der. ~ Unwetterwarnung|N|Gf|AB||severe weather warning ~ hat|V.hilf||P|haben|has ~ die|A|Nf|S|der|the ~ Schule|N|Nf|S||school ~ meines|A|Gm|GA|mein|of my ~ Sohnes|N|Gm|GA|Sohn|son's|Masculine genitive: der Sohn → des Sohnes. ~ den|A|Am|AO|der|the ~ Ausflug|N|Am|AO||trip|Was hat die Schule abgesagt? → accusative object. ~ abgesagt|VT||P|absagen|cancelled|Participle of "absagen": ge- after the prefix. ~ .`,
 "Because of the severe weather warning my son's school has cancelled the trip."],
[`Wir|P|N|S|wir|we ~ bleiben|V||P||stay ~ lieber|ADV||AB||rather|Comparative of "gern": lieber = would rather. ~ zu|PR||AB||at|"zu Hause" = at home (fixed phrase, dative). ~ Hause|N|Dn|AB|Haus|home|Old dative ending -e in the fixed phrase "zu Hause". ~ und|K||K||and ~ machen|V||P||make ~ es|P|A|AO|es|it|"es sich gemütlich machen" = to make yourself cosy. ~ uns|P.refl|D|DO|wir|ourselves|Reflexive pronoun in the dative. ~ mit|PR||AB||with ~ einer|A|Df|AB|ein|a ~ heißen|J|Df|AB|heiß|hot|Adjective after "einer" (dative feminine): ending -en. ~ Schokolade|N|Df|AB||chocolate ~ gemütlich|J||PN||cosy|No ending: it describes the result. ~ .`,
 "We would rather stay at home and make ourselves cosy with a hot chocolate."]
]}
]}
];
